### ISSUE TITLE
Hide Folders / Exclude folders from being shown in Gallery

### ISSUE THREAD

**Issue by motey** [owncloud/gallery#10]
Hi Folks,
Feature Request:
Most People have some Folders with Pictures they dont want to see in the Gallery (Music Cover Art, for example). 
Wouldnt it be nice to be able to hide these folders in the Gallery?
It could look similar like this:
![hidegallery](https://f.cloud.github.com/assets/1006417/2346716/2c5cc14a-a545-11e3-8088-d2ed6f5e314d.png)

**Comment by oparoz** [comment]
@jsalatiel - I like this idea... It's really simple to implement and operate. Tracked here: https://github.com/interfasys/galleryplus/issues/58
