### ISSUE TITLE
Error opening pictures from files app on external storage

### ISSUE THREAD

**Issue by smhelg** [owncloud/gallery#100]
When using files app browsing pictures on external storage the Gallery+ app only open picture if it has been open with the old Pictures app first. See screen shots:

Screenshots of old pictures app:
Before clicking on picture:
![image](https://cloud.githubusercontent.com/assets/11532933/6703329/6a9fb2c8-cd3a-11e4-86c0-fa54868eedc5.png)

After clicking on picture:
![image](https://cloud.githubusercontent.com/assets/11532933/6703327/5bf7a8f2-cd3a-11e4-8549-ec6a9888faca.png)

Screenshot of new Gallery+ app:
Before clicking on picture:
![image](https://cloud.githubusercontent.com/assets/11532933/6703345/9ed8393e-cd3a-11e4-97b9-64ccd4875464.png)

After clicking on the same picture as opened with the old picture app:
![image](https://cloud.githubusercontent.com/assets/11532933/6703371/2034be76-cd3b-11e4-806a-fe3260154785.png)

When clicking on a new image, or clicking next:
![image](https://cloud.githubusercontent.com/assets/11532933/6703375/3b3b3150-cd3b-11e4-9d39-845ea595cd54.png)

Here are output of log:
Debug   galleryplus [PreviewService] ERROR! Did not get a preview, sending mime icon    2015-03-18T05:58:21+00:00
Debug   core    OC_Image->fixOrientation() Orientation: -1  2015-03-18T05:58:21+00:00
Debug   core    OC_Image->fixOrientation() Image is not a JPEG. 2015-03-18T05:58:21+00:00
Error   PHP fopen(smb://...@192.168.79.14/Felles/Bilder\Bildealbum/m%2F2015%2F2015-03-14+-+Bella+leker+med+ein+bamse%2FFAM_7191.jpg): failed to open stream: &quot;smb_stream_wrapper::stream_open&quot; call failed at /var/www/owncloud/apps/files_external/lib/streamwrapper.php#64  2015-03-18T05:58:21+00:00
Debug   core    Generating preview for "///Bildealbum/2015/2015-03-14 - Bella leker med ein bamse/FAM_7191.jpg" with "OC\Preview\Image" 2015-03-18T05:58:21+00:00
Debug   galleryplus [PreviewService] Fetching the preview   2015-03-18T05:58:21+00:00
Debug   core    OC\Tags::__construct, tags: Array ( )   2015-03-18T05:58:20+00:00
Debug   galleryplus [PreviewService] Fetching the preview   2015-03-18T05:58:14+00:00

**Comment by oparoz** [comment]
Thanks for the report.
Just to be sure, this is on 2.0.7, correct?

**Comment by smhelg** [comment]
Yes
[cid:image001.png@01D0614D.7EA0D530]

Helsing

**Comment by oparoz** [comment]
Are you using encryption?

**Comment by smhelg** [comment]
Not that i know of. The site is at https, but notting more.

**Comment by oparoz** [comment]
Could you try turning off File Locking?

**Comment by oparoz** [comment]
Also, could you look for "Generating preview for " statements when using the original app?
I'm seeing triple slashes and I'm wondering if that's what's causing a problem.

**Comment by smhelg** [comment]
File Locking is disabled:

[cid:image001.png@01D06157.CCC42500]

Helsing

**Comment by smhelg** [comment]
Debug

core

OC_Image->fixOrientation() Orientation: 1

2015-03-18T08:09:58+00:00

Debug

core

Generating preview for "/Bildealbum/2013/2013-01-16 - June koser med hundane/DSC_8718.jpg" with "OC\Preview\Image"

2015-03-18T08:09:58+00:00

Debug

core

OC_Image->fixOrientation() Orientation: 1

2015-03-18T08:09:53+00:00

Debug

core

Generating preview for "/Bildealbum/2013/2013-01-16 - June koser med hundane/DSC_8713.jpg" with "OC\Preview\Image"

2015-03-18T08:09:53+00:00

Debug

core

OC_Image->fixOrientation() Orientation: 1

2015-03-18T08:09:53+00:00

Debug

core

OC_Image->fixOrientation() Orientation: 1

2015-03-18T08:09:53+00:00

Debug

core

Generating preview for "/Bildealbum/2013/2013-01-16 - June koser med hundane/DSC_8717.jpg" with "OC\Preview\Image"

2015-03-18T08:09:53+00:00

Debug

core

OC_Image->fixOrientation() Orientation: 1

2015-03-18T08:09:53+00:00

Debug

core

Generating preview for "/Bildealbum/2013/2013-01-16 - June koser med hundane/DSC_8714.jpg" with "OC\Preview\Image"

2015-03-18T08:09:53+00:00

Debug

core

OC_Image->fixOrientation() Orientation: 1

2015-03-18T08:09:52+00:00

Debug

core

Generating preview for "/Bildealbum/2013/2013-01-16 - June koser med hundane/DSC_8716.jpg" with "OC\Preview\Image"

2015-03-18T08:09:52+00:00

Debug

core

OC_Image->fixOrientation() Orientation: 1

2015-03-18T08:09:52+00:00

Debug

core

Generating preview for "/Bildealbum/2013/2013-01-16 - June koser med hundane/DSC_8715.jpg" with "OC\Preview\Image"

2015-03-18T08:09:52+00:00

Debug

core

Generating preview for "/Bildealbum/2013/2013-01-16 - June koser med hundane/DSC_8718.jpg" with "OC\Preview\Image"

2015-03-18T08:09:52+00:00

**Comment by oparoz** [comment]
That path
`smb://...@192.168.79.14/Felles/Bilder\Bildealbum/m%2F2015%2F2015-03-14+-+Bella+leker+med+ein+bamse%2FFAM_7191.jpg`

has a few problems:
- There is a backslash in the middle of it
- There is an extra m between Bildealbum and 2015. Giving a path which does not exists: Bildealbum/m/2015
- The end of the path seems to be encoded, but not the beginning

I have no idea how this is happening and I can't debug it locally as I don't have the same setup :| 
This should sort itself out once we can move away from using paths to request previews.

One thing you could try is to modify `preview/preview.php`

From 

```
    public function setupView($userId, $file, $imagePathFromFolder) {
        $this->userId = $userId;
        $this->file = $file;
        $this->preview = new \OC\Preview($userId, 'files', $imagePathFromFolder);
    }
```

to

```
    public function setupView($userId, $file, $imagePathFromFolder) {
        $this->userId = $userId;
        $this->file = $file;
        $imagePathFromFolder = ltrim($imagePathFromFolder, '/');
        $this->preview = new \OC\Preview($userId, 'files', $imagePathFromFolder);
    }
```

**Comment by smhelg** [comment]
Thank you very much ☺

Now it is working fine.

**Comment by oparoz** [comment]
Cool. I should use you as a guinea pig for external storage :)
I know owncloud sharing doesn't work, but maybe mounted storage does and I could re-enable that...

**Comment by jmcastellote** [comment]
Hi! Just a quick confirmation that this really makes a difference with pics from external sources.
I had exactly the same issue and had to rollback to previous gallery as there were mostly icons when previewing unless previously seen through the grid.
Now I can preview everything from local external sources and sftp external storage.
BTW, Gallery plus is waaaay better than the previous gallery. Outstanding performance after everything is indexed and thumbnails generated. Huge thank you oparoz!

**Comment by oparoz** [comment]
Thanks for the confirmation. I need to release a new version containing this fix so that more people can benefit from it.

And glad you like Gallery+ :). I just want to add that the original team did a good job with the concept of batch loading thumbnails to speed things up, but I think they underestimated the size of some of the libraries and ran out of resources before being able to fix everything.
