### ISSUE TITLE
Still spinning icon

### ISSUE THREAD

**Issue by tel2** [owncloud/gallery#102]
Upgraded to Owncloud 8.0.2 hoping that would fix the spinning icon issue when I run Gallery+, but to no avail.

Owncloud 8.0.2, lighttpd, debian 7, php 5.4 - I just get a spinning icon and nothing else.

Here's the log produced:

ar 18 14:40:52 nowlas ownCloud[3905]: {PHP} Only variables should be passed by reference at /var/www/owncloud/lib/private/cache/fileglobalgc.php#50
Mar 18 14:41:31 nowlas php-cgi[16439]: {PHP} Allowed memory size of 134217728 bytes exhausted (tried to allocate 1550081 bytes) at /var/www/owncloud/apps/gallery/ajax/getimages.php#72
Mar 18 14:42:38 nowlas php-cgi[3905]: {PHP} Allowed memory size of 134217728 bytes exhausted (tried to allocate 1550081 bytes) at /var/www/owncloud/apps/gallery/ajax/getimages.php#72
Mar 18 14:43:58 nowlas ownCloud[3905]: {index} Exception: {"Message":"","Code":0,"Trace":"#0 \/var\/www\/owncloud\/lib\/private\/files\/node\/node.php(313): OC\Files\Node\Node->getFileInfo()\n#1 \/var\/www\/owncloud\/apps\/galleryplus\/service\/infoservice.php(184): OC\Files\Node\Node->getMimeType()\n#2 \/var\/www\/owncloud\/apps\/galleryplus\/service\/infoservice.php(120): OCA\GalleryPlus\Service\InfoService->prepareImagesArray(Array, '\/todd\/files\/')\n#3 \/var\/www\/owncloud\/apps\/galleryplus\/controller\/servicecontroller.php(161): OCA\GalleryPlus\Service\InfoService->getImages(Array)\n#4 [internal function]: OCA\GalleryPlus\Controller\ServiceController->getImages()\n#5 \/var\/www\/owncloud\/lib\/private\/appframework\/http\/dispatcher.php(158): call_user_func_array(Array, Array)\n#6 \/var\/www\/owncloud\/lib\/private\/appframework\/http\/dispatcher.php(86): OC\AppFramework\Http\Dispatcher->executeController(Object(OCA\GalleryPlus\Controller\ServiceController), 'getImages')\n#7 \/var\/www\/owncloud\/lib\/private\/appframework\/app.php(97): OC\AppFramework\Http\Dispatcher->dispatch(Object(OCA\GalleryPlus\Controller\ServiceController), 'getImages')\n#8 \/var\/www\/owncloud\/lib\/private\/appframework\/routing\/routeactionhandler.php(44): OC\AppFramework\App::main('ServiceControll...', 'getImages', Object(OC\AppFramework\DependencyInjection\DIContainer), Array)\n#9 [internal function]: OC\AppFramework\routing\RouteActionHandler->__invoke(Array)\n#10 \/var\/www\/owncloud\/lib\/private\/route\/router.php(250): call_user_func(Object(OC\AppFramework\routing\RouteActionHandler), Array)\n#11 \/var\/www\/owncloud\/lib\/base.php(767): OC\Route\Router->match('\/apps\/gallerypl...')\n#12 \/var\/www\/owncloud\/index.php(36): OC::handleRequest()\n#13 {main}","File":"\/var\/www\/owncloud\/lib\/private\/files\/node\/node.php","Line":65}
Mar 18 14:44:04 nowlas ownCloud[16439]: {index} Exception: {"Message":"","Code":0,"Trace":"#0 \/var\/www\/owncloud\/lib\/private\/files\/node\/node.php(313): OC\Files\Node\Node->getFileInfo()\n#1 \/var\/www\/owncloud\/apps\/galleryplus\/service\/infoservice.php(184): OC\Files\Node\Node->getMimeType()\n#2 \/var\/www\/owncloud\/apps\/galleryplus\/service\/infoservice.php(120): OCA\GalleryPlus\Service\InfoService->prepareImagesArray(Array, '\/todd\/files\/')\n#3 \/var\/www\/owncloud\/apps\/galleryplus\/controller\/servicecontroller.php(161): OCA\GalleryPlus\Service\InfoService->getImages(Array)\n#4 [internal function]: OCA\GalleryPlus\Controller\ServiceController->getImages()\n#5 \/var\/www\/owncloud\/lib\/private\/appframework\/http\/dispatcher.php(158): call_user_func_array(Array, Array)\n#6 \/var\/www\/owncloud\/lib\/private\/appframework\/http\/dispatcher.php(86): OC\AppFramework\Http\Dispatcher->executeController(Object(OCA\GalleryPlus\Controller\ServiceController), 'getImages')\n#7 \/var\/www\/owncloud\/lib\/private\/appframework\/app.php(97): OC\AppFramework\Http\Dispatcher->dispatch(Object(OCA\GalleryPlus\Controller\ServiceController), 'getImages')\n#8 \/var\/www\/owncloud\/lib\/private\/appframework\/routing\/routeactionhandler.php(44): OC\AppFramework\App::main('ServiceControll...', 'getImages', Object(OC\AppFramework\DependencyInjection\DIContainer), Array)\n#9 [internal function]: OC\AppFramework\routing\RouteActionHandler->__invoke(Array)\n#10 \/var\/www\/owncloud\/lib\/private\/route\/router.php(250): call_user_func(Object(OC\AppFramework\routing\RouteActionHandler), Array)\n#11 \/var\/www\/owncloud\/lib\/base.php(767): OC\Route\Router->match('\/apps\/gallerypl...')\n#12 \/var\/www\/owncloud\/index.php(36): OC::handleRequest()\n#13 {main}","File":"\/var\/www\/owncloud\/lib\/private\/files\/node\/node.php","Line":65}

**Comment by oparoz** [comment]
> Mar 18 14:41:31 nowlas php-cgi[16439]: {PHP} Allowed memory size of 134217728 bytes exhausted (tried to allocate 1550081 bytes) at /var/www/owncloud/apps/gallery/ajax/getimages.php#72

Please uninstall the original Gallery before using Gallery+

And which version are you using?

**Comment by tel2** [comment]
Your suggestion has solved the problem. Thanks!
