### ISSUE TITLE
View 3D pictures in 3D in the slideshow

### ISSUE THREAD

**Issue by oparoz** [owncloud/gallery#104]
Stereo JPEGs are currently shown in 2D, but it would be interesting to be able see them in full 3D.

I'm thinking creating anaglyph 3D pictures on the fly at first since they can be viewed by anybody with a pair of red cyan glasses, but maybe there are different options to explore.

A new UI element would need to be introduced to be able to turn the effect on/off.
#### GSoC

This is a good exercise to understand how the slideshow works and a good opportunity to set up a Gallery development environment in preperation for GSoC
##

**Comment by madhug-nadig** [comment]
Hi, I found this project interesting.
SO, the idea to convert the images into an anaglyph and then upload them as any other images?

**Comment by oparoz** [comment]
Actually, it's the opposite. Currently, 3D images (jps, mpo) are sent as-is and shown as a wide image, with the image for each eye shown side-by-side.
It should be possible to use the HTML5 canvas to split the image in 2 and colourise and merge them to create a 3D picture which can be viewed with anaglyph 3D glasses.
For performance reasons, especially on mobile, it may not be the best thing to do and a PHP solution might be better. That's for potential candidates to find out.

It's quite a small project and could be some sort of warm-up proving that the candidate is capable of working on bigger gsoc projects. 
Let me know what you think.

**Comment by madhug-nadig** [comment]
Um, I believe that there are some js libraries which directly apply the dubois algorithm on the image, without using canvas. I'll find that out.

**Comment by madhug-nadig** [comment]
I found a tiny jQuery library which makes it extremely easy to convert a regular image into a 3D anaglyph. .[Basic implementation](https://github.com/madhug-nadig/3D-Anaglyph-).

Am I on the right track?

**Comment by prastut** [comment]
Are we aiming for this?
http://3dmedia.com/gallery/displayimage.php?album=toprated&cat=0&pid=7531#top_display_media

**Comment by madhug-nadig** [comment]
So, a button that can change back and fourth between 2D and 3D, yes?

**Comment by oparoz** [comment]
@madhug-nadig - I think that plugin turns any standard JPEG into a 3D anaglyph, but the idea is to only convert stereo JPEG images into 3D anaglyph. So the best thing to do would be to test with 3D jpegs.

@prastut - Yes. Currently Gallery shows 3D images side by side as it doesn't involve any processing, so that can stay as the normal mode, but then users should be able to see the anaglyph by pressing on a button.

> So, a button that can change back and fourth between 2D and 3D, yes?

Yes, also, bear in mind when thinking about the UI that not everybody has red/blue glasses, some are yellow/blue ;)

**Comment by prastut** [comment]
@oparoz I have a problem in uploading the 3D files. Since the 3D files are above 2MB, they can't be uploaded. I tried the following solutions
- Configured the .htaccess file
- Changed the default size of upload_max and post_max in /etc/php5/apache2/php.ini

Still no luck. From the admin view, it says you don't have permission to change the max file size.

**Comment by oparoz** [comment]
> From the admin view, it says you don't have permission to change the max file size

@prastut  The 2MB limit seems to be very low. For all questions related to configuring ownCloud, I invite you to look for answers on [the forum](https://forum.owncloud.org/) since this has nothing to do with Gallery or this specific task. Make sure to post all information about your setup, config.php, etc.

**Comment by oparoz** [comment]
This issue was moved to nextcloud/gallery#27
