### ISSUE TITLE
Labels

### ISSUE THREAD

**Issue by oparoz** [owncloud/gallery#106]
### Current situation
- Album label is illegible in many situations
- Picture label is missing
### Possible improvements for albums
- [x] Darker label background
- [ ] Double height on rollover with more information? (That's if and when we have something to show)
### Possible improvements for images
- [x] Revealed on hover
- [x] Darker label background than albums
- [x] Different title size and font weight
- [x] Alignment on the left, with an extra character:  `> Me_on_the_beach.DNG`.  
- [x] Titles longer than the width of the image are revealed in full when hovering over the title
- [x] Works on mobile

**Comment by oparoz** [comment]
First version is in. I'm looking for feedback...

**Comment by deMattin** [comment]
A feature I've missed a long time.
Only one could be optimzied:
If the file name is longer than the picture, there's a line wrap, if you mouse over the name. That's fine.
But the line break only depends on the ammount of characters (or length).
I thing an "intelligent" linebreak at "word separators" will look better.

Example: If there is a maximum displayable length of e.g. 50 characters and innert the last 10 characters there's a "`_`", "`-`", "`.`", "`,`" or "` `", then the break should be made there.
I don't know, how this can be easy implemented, because it is a proportional font.
But maybe you have a good idea for that.

Sometimes it looks a bit weird, if e.g. "jpg" is separated in j ...pg or in j...pg or other words in name.

**Comment by oparoz** [comment]
The main problem is that we're using the filename and so there is usually no spaces between words, so I had to force it to cut at the end of the line, other wise it would cut at a dash which makes things look really weird for filenames like at-the-Akreostynassioneky-beach-with-my-crew-and-a-case-of-champagne.jpg

**Comment by deMattin** [comment]
I know the backgrounds and also have no idea, how to realize or optimize this in a simple way without a bunch of code with probable issues on different browsers.
As it is not really a big issue, it's fine, like it is.

**Comment by bill340** [comment]
In Google Chrome 64bit beta, the filenames all appear right of the thumbnail. Once you float over the thumbnail with the mouse, it disappears.
That screws up the whole album appearance.

**Comment by oparoz** [comment]
Probably a caching issue. Try CTRL+F5 a few times or confirm that you see the same problem on the demo site:
https://oc8demo.interfacloud.com/index.php/apps/galleryplus/s/4jjwPv5E21l8Lnk

**Comment by bill340** [comment]
Cannot load the demo-site:
DNS_PROBE_FINISHED_NXDOMAIN

CTRL+F5 does not bring any change... :(

**Comment by oparoz** [comment]
Your Chrome seems to be locked up.
Open a command prompt as an administrator and type

```
> netsh winsock reset catalog
```

https://productforums.google.com/forum/#!topic/chrome/nanfBxleQpw

Might be the reason the CSS doesn't work as well. Maybe a simple computer restart will fix things.
Is it working in another browser?

**Comment by oparoz** [comment]
It could also be a problem with the ">" character I'm using, if you're using a non-latin charset maybe?

**Comment by deMattin** [comment]
No DNS error here. Demo side works.
Maybe this could help:
http://www.fixerrs.com/2015/01/Dns-Probe-Finished-NxDomain.html

**Comment by bill340** [comment]
Ok, the demo side works fine as it should. So it seems to be something on my server-configuration? Any idea, what I could try here? I'm running on an IIS 8.5

**Comment by bill340** [comment]
Ok, after installing the latest master, everything works now. DId not change anything else...

**Comment by oparoz** [comment]
:ok:

**Comment by deMattin** [comment]
With one of the last changes, the folder label doesn't fit any more
It's slightly wider than the 2x2 preview (1-2 pix on the left and bottom and 2-4 pix at the right side).:
If it is intended, the right side overlap should be as big as on the left side.
![image](https://cloud.githubusercontent.com/assets/5565503/7057824/8b99147a-de5a-11e4-8ac9-e52b3dcd0159.png)

Edit:
Have checked some more folder - the overlap differs! Some overlaps are equal, others not.
Don't know, if it is an issue on 2x2 preview changing over all size or the label changing size.

It's also on your demo page:
![image](https://cloud.githubusercontent.com/assets/5565503/7058035/f40617c2-de5c-11e4-9ef1-521ec3fb732b.png)

**Comment by oparoz** [comment]
It's been there for a while. It's a rounding problem. When it's too small, it will actually squeeze pictures out of the album. Feel free to open a separate issue for that, but it's going to be very low on my list of priorities.

**Comment by deMattin** [comment]
It's the first time, I recognized this, so I thought it is a new issue.
Opened #117 to not forget it and if someone else notices it.

**Comment by oparoz** [comment]
I'm closing this as labels are "working" and nobody has been complaining.
Users can always create enhancement requests.
