### ISSUE TITLE
Lazy Loading of files in gallery

### ISSUE THREAD

**Issue by synappsis** [owncloud/gallery#107]
In Issue https://github.com/owncloud/gallery/issues/99 lacy loading has been improved already, meaning it is faster now, but nevertheless a user will wait for the loading of the next batch of preview pictures until you can scroll again.
* Gallery app should not wait for preview creation of a pictures, instead e.g. show a frame to render the next rows immediatly and show the picture preview whenever created afterwards like in the files view.
* Gallery app should allow to jump to the end of the list (in the files view we are at least able to sort e.g. by name descending). Example, if you have 1000 pictures with 2 MB each in one folder just try to scroll down to the last and newest picture. I spent roughly 2 minutes with scrolling.

**Comment by lparmentier-quatral** [comment]
@synappsis have you update to OC8? Is it really better ? cause we have something like 21TB of data. So it is possible than we have more than 100GB of pictures, i don't wan't this kind of problem.. :/

**Comment by jospoortvliet** [comment]
@lparmentier-quatral you could try the galleryplus app but - no promises, 21TB is - well, a crazy amount of data. A nice challenge for @oparoz and @libasys ;-)

**Comment by oparoz** [comment]
@lparmentier-quatral - The first time you open an album, you'll have to wait for the thumbnails to be generated, so it should take a few seconds per row, depending on the size of images, but once that's done, Gallery should fly.

**Comment by lparmentier-quatral** [comment]
I'll try that (in next month) and give you feedback when done.

**Comment by jospoortvliet** [comment]
@oparoz whoah, you're very optimistic ;-) I hope @lparmentier-quatral will report back with results, I'm quite curious to hear if this worked or not...

**Comment by oparoz** [comment]
Well, on 8.1, if you use the Files app, you generate the max previews every time you open a folder. After that, it takes very little time to resize each PNG to the thumbnail size for Gallery.

If you open a fresh folder with Gallery, then yes, it might take a second or two per thumbnail (more with exotic or pro formats), so if you have  6 thumbnails per row, then yes, it's going to be over 10s before you see a row and more than a minute to fill the screen. That won't change until thumbnails are generated at upload time, but that process can also lead to all sorts of rendering concurrency problems...

**Comment by oparoz** [comment]
I just re-read the OP and all I can say is that the described improved process is not compatible with how we do things atm.

The OP's proposal is to build the scaffolding when we open the folder and to then send dozens of HTTP requests as we scroll down, like in the Files app. I think that approach doesn't work well for a photowall, because we'll hit some protocol bottlenecks 
What we do instead is stream pictures back and show rows as they're full. The showing part can be improved (https://github.com/owncloud/galleryplus/issues/29), but the streaming part works really well from my pov.

**Comment by oparoz** [comment]
Closing since the OP is not an issue in Gallery. Using the sorting buttons. one can quickly reach the bottom of the folder.
