### ISSUE TITLE
slideshow not themeable

### ISSUE THREAD

**Issue by woeps** [owncloud/gallery#108]
I just tried to change the gallery's template using the theme-mechanisms provided by owncloud (putting the file in `owncloud/themes/mytheme/apps/gallery/templates/slideshow.html`) without any success.

*I aim to add a div-element containing the current filename to the slideshow-template.*

- I have some other theme-modifications working, so it's not about the config.
- If I edit the original file directly I can see the changes I want to make happening, so it's the right file.

Did anybody else came across this issue?
Or did I miss something in the configs?

**Comment by oparoz** [comment]
Moved to: https://github.com/owncloud/galleryplus/issues/233
