### ISSUE TITLE
Undefined Index

### ISSUE THREAD

**Issue by autumnwalker** [owncloud/gallery#116]
Getting the following line in my log file each time I access the Gallery+ app.

```
Error    PHP    Undefined index: information at /var/www/owncloud/apps/galleryplus/service/configservice.php#176
```

Thoughts?

**Comment by oparoz** [comment]
Let me know if this is now fixed and don't hesitate to report those.

**Comment by autumnwalker** [comment]
Appears to be fixed.

Thanks!
