### ISSUE TITLE
Gallery option missing in non shared folders

### ISSUE THREAD

**Issue by HermanRonk** [owncloud/gallery#116]
### Steps to reproduce
1. Open the webinterface and go to a folder with pictures in it, no gallery option is visible (screenshot 1)

2. Share the folder and go to the shared folder URL, in top right corner an icon / button is available to change the view to gallery mode (Screenshot 2)

### Expected behaviour
It would be a welcome addition to make this button available in the default folder view in the webinterface.

### Server configuration
**Operating system**: 
Linux (Ubuntu 14.04)

**Web server:**
Apache

**Database:**
MySQL

**ownCloud version:** 
7.0.2

**Updated from an older ownCloud or fresh install:**
Updated

**List of activated apps:**
Files
Activity
Pictures
Deleted Files
Documents
External Storage Support
First Run Wizard
Full Text Search
PDF Viewer
Share Files
Updater
Versions

![owncloud 2](https://cloud.githubusercontent.com/assets/2781343/4473803/1c08c520-4958-11e4-8b45-ce4a095c207d.PNG)
![owncloud 1](https://cloud.githubusercontent.com/assets/2781343/4473804/1c0c9c04-4958-11e4-9742-3758daaa055e.PNG)

**Comment by oparoz** [comment]
I agree. Discussed in core: https://github.com/owncloud/core/issues/8268

**Comment by oparoz** [comment]
Implemented in Gallery+ for OC8.
The button is next to the other buttons in order to keep the UI consistent.

Will probably be backported to the OC7 version

**Comment by oparoz** [comment]
@HermanRonk, you can try this release to see if this implementation works for you:
https://github.com/interfasys/galleryplus/releases/tag/v1.0.2

**Comment by oparoz** [comment]
![Screenshot](https://oc7demo.interfacloud.com/public.php?service=files&t=b5a628aee0723ab20466521c8bd73eb3&download)

**Comment by oparoz** [comment]
Closing as this is fixed in Gallery
