### ISSUE TITLE
 Folder labels don't always fit any 2x2 preview

### ISSUE THREAD

**Issue by deMattin** [owncloud/gallery#117]
The folder label doesn't fit the 2x2 preview size on some previews
Sometimes the label is slightly wider than the 2x2 preview (1-2 pix on the left and bottom and 2-4 pix at the right side).:
The overlap differs! Some overlaps are equal others not, depending on content of preview.
If it is intended to overlap, it should be equal on the right side and on the left side.

![image](https://cloud.githubusercontent.com/assets/5565503/7058035/f40617c2-de5c-11e4-9ef1-521ec3fb732b.png)

**Comment by oparoz** [comment]
There is a rounding error somewhere in the resizing routine. I never managed to get rid of it with the current way of rendering rows. 
I'll gladly walk someone through the way it works if that someone wants to have a go at fixing it.

**Comment by oparoz** [comment]
That commit completely messes up things.. Will need something more subtle...
