### ISSUE TITLE
Add comments to pictures

### ISSUE THREAD

**Issue by thkin6** [owncloud/gallery#117]
Owncloud and the Pictures app are very convenient to build shared pictures albums with family and friends. However it would be nice to be able to add comments/notes to each picture, with the option of adding this text to the bottom or side of every pictures in the slideshow.

**Comment by oparoz** [comment]
I think it belongs to the Gallery app as that's what you'll probably share. First we need meta data support.

**Comment by brantje** [comment]
@oparoz But not images only images are shared. Files can be shared too.
I agree with jos, this should be a core thing.

**Comment by oparoz** [comment]
@brantje - The OP says "Add comments to pictures". I see this as something like Instagram or Pinterest, where you can read and add comments to a picture. Those comments would be available in Files view, just like the slideshow can be launched from that view.

Of course, if core want to support comments, then it would be easy to add this to the Gallery

**Comment by jospoortvliet** [comment]
I would guess that the metadata app and infrastructure developed for tags can play a role here - comments are metadata on pictures...

**Comment by oparoz** [comment]
This request is now tracked in https://github.com/owncloud/galleryplus/issues/176
