### ISSUE TITLE
Multi Monitor Problem with gallery

### ISSUE THREAD

**Issue by jsalatiel** [owncloud/gallery#118]
I have a dual monitor setup (linux mint) and i have 42 albums (subfolders); 
When i enter gallery, i got 5 rows (4 x 10   and 1 x 2 )
If i enter any of these albums to see the images, when i get back to the main gallery  , i can now only see 3 rows ( 2x10 and 1x3) but taking a a closer look the row actually contains more than 10 albums , but the horizontal scroll bar is missing.
This does not happen when using single monitor.

All tests using firefox  32

**Comment by oparoz** [comment]
Could you guys try on your setup using this gallery? 
https://oc8demo.interfacloud.com/index.php/apps/galleryplus/public?token=5M78hEM0Ci9NtAb#

I suspect you're using 0.5.x version of the gallery and a lot of progress has been made these past 6 months. There is still a tiny issue on Firefox which breaks albums sometimes.

**Comment by jsalatiel** [comment]
Hi oparoz, i have tried galleryplus a while a go, but unfortunatelly several pictures wont load on the main page. For example, instead of loading 4 pics, it would load 2 and left the other space white.

**Comment by oparoz** [comment]
Please try this release:
https://github.com/interfasys/galleryplus/releases

It's for OC7. Put your instance in debug mode and as soon as you see something which breaks, you should take a look at the log `data/owncloud.log` to try and identify what went wrong.
The number 1 reason is a file which was not correctly identified by the core providers.
In this release, if the provider fails, I replace the image with the mime icon as a stopgap measure.

You could also provide a zip with some sample pics which break stuff so that I can take a look at it.
Some issues with OC will only be fixed in OC8 unfortunately.

**Comment by jsalatiel** [comment]
Hi Oparoz, now it is working great ! Even this bug in this thread is fixed. Thanks !
Btw , I have a feature request. Would it be possible to put that circle spinning in someplace while there are still images being loaded in that folder ? It is really difficult to know if there are still images being loaded if the folder contains hundreds of pictures.

**Comment by jsalatiel** [comment]
Oparoz, is there a thread where we can discuss this version ?

**Comment by oparoz** [comment]
Ah, I'm glad to hear that it's working as expected :). I like your feature request. I think you should open a separate ticket for it, in this current gallery project as it will be easier to keep track of things.The version you've tested is a rewrite of master + all the current PR + some bugs I squashed as I went along. ‎The idea is to quickly make it the new base on which to build upon. So the logic is still the same, it has the same performance issues and keeps the same, known interface. Once and if it's made official, I'm hoping to be able to incorporate some of the work others have been doing or to find a way to make some of it available to users as options.                                                                                                                                                                                                                From: jsalatielSent: Wednesday, 14 January 2015 01:11To: gallery@noreply.github.comReply To: owncloud/galleryCc: Olivier ParozSubject: Re: [gallery] Multi Monitor Problem with gallery (#118)Hi Oparoz, now it is working great ! Even this bug in this thread is fixed. Thanks !
Btw , I have a feature request. Would it be possible to put that circle spinning in someplace while there are still images being loaded in that folder ? It is really difficult to know if there are still images being loaded if the folder contains hundreds of pictures.

—Reply to this email directly or view it on GitHub.

**Comment by jsalatiel** [comment]
I asked my girlfriend to test it and she said the pictures never loads and she only gets a circle spinning.
She has about 11000 pictures on her gallery.
There are lots of these messages in the log.

"reqId":"54b5bbe03af5e","app":"OC\\Files\\Cache\\Scanner","message":"!!! No reuse of etag for 'files\/netbook\/Musics\/Musicas\/West Coast Swing\/Contemporary_Fast' !!! \ncache: Array\n(\n    [fileid] => 100358\n    [storage] => home::dama\n    [path] => files\/netbook\/Musics\/West Coast Swing\/Contemporary_Fast\n    [parent] => 100187\n    [name] => Contemporary_Fast\n    [mimetype] => httpd\/unix-directory\n    [mimepart] => httpd\n    [size] => 906258771\n    [mtime] => 1420390358\n    [storage_mtime] => 1399478394\n    [encrypted] => \n    [unencrypted_size] => 0\n    [etag] => 54a970067c1e0\n    [permissions] => 31\n)\n \ndata: Array\n(\n    [mimetype] => httpd\/unix-directory\n    [mtime] => 1420958408\n    [size] => -1\n    [etag] => 54b5bbeac6fa4\n    [storage_mtime] => 1420958408\n    [permissions] => 31\n    [parent] => 100187\n)\n","level":0,"time":"2015-01-13T22:44:26-02:00","method":"GET","url":"\/ownclown\/index.php\/apps\/files\/ajax\/scan.php?force=false&dir=&requesttoken=eeb14c95a2fe5cd14d43"}

**Comment by oparoz** [comment]
She got hit by the performance issue that's been talked about several times on here.
The app can't cope with 11k pictures. It will generate lots and lots of thumbnails before displaying anything, if it doesn't time out before that.

What you see in the logs is OC saying it doesn't have a thumbnail, just before generating one.

What she could do is to start deep into sub folders and make her way up, instead of starting from the root folder.

1. Share the top folder
2. Go to the public files list
3. Drill down into the deepest sub-folder
4. Switch to gallery mode
5. Go up one folder

**Comment by jsalatiel** [comment]
Is there a way to build the thumbails from a command line in server ?

**Comment by oparoz** [comment]
Not yet, but several options have been talked about: using a queue manager or having a scan button in the gallery. I think the queue manager will not be part of OC8, but nothing is preventing us from coming up with something. Feel free to add your views to the existing threads.

**Comment by jsalatiel** [comment]
One cron script would already be nice :)

**Comment by oparoz** [comment]
Closing as the bug reported in the OP has been fixed in Gallery.
