### ISSUE TITLE
Unable to display photos in shared folders (Gallery+ v2.0.8)

### ISSUE THREAD

**Issue by sffax** [owncloud/gallery#120]
Since updating to Gallery+ 2.0.8, we are unable to browse each other's shared pictures. For example, I am able to see any of my own albums just fine, but any attempt to load a shared album ends immediately with: "No pictures found! If you upload pictures in the files app, they will be displayed here."

This is happening on a vanilla instance of ownCloud 8.0.2 (the latest available build) and the latest version of Firefox (I'm mentioning this here although this issue doesn't seem to have anything to do with the version of the browser used).

There is nothing in the logs that would indicate a problem. As far as I can tell, the log lines generated with this latest version are no different than the ones dropped by the previous release (v2.0.7). I restarted Apache, restarted the server, re-installed the app manually and via git... no difference. Can anyone else confirm this issue?

**Comment by deMattin** [comment]
Can confirm this!
I haven't tested this for a while and don't know, which changes may have caused this.

**Comment by sffax** [comment]
Well, looking at the changelog, this would be the number one candidate:
- Remove permission loading routine and send the information about the current folder with the files (@oparoz)

**Comment by oparoz** [comment]
Thanks for the report!
So, we're talking about local users sharing folders with one another, correct?

**Comment by deMattin** [comment]
Yes, the problem occurs with locally shared folders on same server..

**Comment by oparoz** [comment]
Thanks for confirming. I have to admit that this side has not been tested for a while :flushed:

**Comment by oparoz** [comment]
I've found the problem and a quick fix is easy, but I need to talk about the logic with the core team. I ran into a similar issue today on 8.1.
The behaviour of isLocal() is illogical. The shared folder is from the same oC instance and files are hosted in the same data folder. That's local to me.

**Comment by sffax** [comment]
Glad to hear that it was easy to pinpoint.

Is there anything we can do in the meantime as we're waiting for a resolution to this, other than reverting back to v2.0.7? I'm thinking something like a manual edit of one of the script files...

**Comment by oparoz** [comment]
In filesservice.php, remove the 2 isLocal() calls.
I'm going to release a new version tomorrow.

https://github.com/interfasys/galleryplus/commit/a444c2d245d70c0e49c54cc2ced321b35a591860

**Comment by sffax** [comment]
Done and fixed!

Thanks!

**Comment by oparoz** [comment]
Just make sure you don't add any external shares. Your gallery will slow to a crawl.

**Comment by oparoz** [comment]
Fixed in 2.0.9
