### ISSUE TITLE
no info button shown

### ISSUE THREAD

**Issue by sbr9150** [owncloud/gallery#122]
![gallreyplus](https://cloud.githubusercontent.com/assets/11934046/7128144/e02c2ba6-e280-11e4-962a-83cb3dcf8b09.jpg)

owncloud.log
[{"reqId":"9efcdfd2c102474f6ffba5782034***_","remoteAddr":"59.125.103.**_","app":"PHP","message":"Undefined index: features at \/var\/www\/html\/owncloud\/apps\/galleryplus\/controller\/filescontroller.php#105","level":3,"time":"2015-04-14T08:17:59+08:00"},

ownCloud version=8.0.2
App version=2.9
Browser version=google chrome 41.0.2272.118(64-bit)(linuxmint17)google chrome 41.0.2272.118 m (64-bit) (win7)
PHP version=5.5.9+dfsg-1ubunt

**Comment by oparoz** [comment]
Could you check a bit higher up in the log, to see if you get a parsing error?
If not, I would need your `gallery.cnf`. Just remove any sensitive information and test that the file you submit still doesn't work.

**Comment by sbr9150** [comment]
I don't find any parsing error after I started galleryplus. I'm running ubuntu server 14.04, I can't find gallery.cnf using locate/whereis command. Could you tell me where is gallery.cnf located?
This is what happend. https://youtu.be/3jhApa4w6Uw, The info button shows up a few seconds then disappears.

**Comment by oparoz** [comment]
The info button only appears if you create an album description.
The documentation is here:
https://github.com/interfasys/galleryplus/blob/master/documentation/Album%20configuration.md
