### ISSUE TITLE
Cleanup of gallery thumbs

### ISSUE THREAD

**Issue by JimLoose** [owncloud/gallery#122]
- When i deactivate the Gallery App it should clean/delete all files from the **userfolder/gallery/**
- When i delete images it should cleanup the thumbs in the gallery as well
- When i have encryption on, files and especially images should be encrypted here as well

Is it enough to simply delete files in the folder via FTP or are there any more entries in the MySQL?

**Comment by oparoz** [comment]
There is no more `userfolder/gallery` in the upcoming version of the app. I don't know if @icewind1991 had something in mind regarding the upgrade.

Afaik, nothing is stored in the DB, images are files and will be encrypted, but the thumbnails will not
```
# hexdump -C data/demo1/thumbnails/247/200-200.png | head
00000000  89 50 4e 47 0d 0a 1a 0a  00 00 00 0d 49 48 44 52  |.PNG........IHDR|
00000010  00 00 00 c8 00 00 00 c8  08 06 00 00 00 ad 58 ae  |..............X.|
00000020  9e 00 00 20 00 49 44 41  54 78 9c 54 bc 77 b8 6e  |... .IDATx.T.w.n|
```
Deleting the thumbnail is a `core`responsibility, as it should be done when an image is removed from the cloud, please report there if it has not been already implemented in OC8.

**Comment by oparoz** [comment]
Core issue regarding thumbnail encryption https://github.com/owncloud/core/issues/11790
