### ISSUE TITLE
Exif oriented pictures: not all possible values are supported

### ISSUE THREAD

**Issue by tobiasKaminsky** [owncloud/gallery#123]
Hello,

as I have included the exif rotated images in android app, I have found out, that not all possible values are supported: 2,4,5,7.
Please see http://www.daveperrett.com/articles/2012/07/28/exif-orientation-handling-is-a-ghetto/

**Comment by oparoz** [comment]
@tobiasKaminsky - You should report that in core.
https://github.com/owncloud/core/blob/master/lib/private/image.php#L324

**Comment by tobiasKaminsky** [comment]
Thank you.
I have reported it in core and therefore closing it here.
