### ISSUE TITLE
Gallery+ viewer jumps to top position after closing an image

### ISSUE THREAD

**Issue by vader2014** [owncloud/gallery#126]
When i open an image from the file app list and later close it via clicking th "X" the list view jumps back to the of the file list. This is rather annoying especially if there are lots of images in a folder. This is like issue https://github.com/owncloud/gallery/issues/96 of the old gallery app .

Can this behavior be changed/fixed?

**Comment by oparoz** [comment]
This is a problem with the Files app over which I may not have control, but I just got an idea. Let me see if this works...

**Comment by oparoz** [comment]
The quick fix didn't work, but hopefully there is a solution for this...

**Comment by oparoz** [comment]
The reason the quick fix does not work is because of a bug in core which will likely not be fixed before 8.2, once support for old IE browsers is officially dropped.

https://github.com/owncloud/core/issues/14828

**Comment by vader2014** [comment]
THX for your effort! I only want to point out it works for me in the old gallery app (v.0.6.0)

**Comment by oparoz** [comment]
I'm about to push a change which will make it work, since we only support HTML5 browsers anyway, but out of curiosity, what does the URL look like when you stop the slideshow using the old gallery app?

**Comment by vader2014** [comment]
THX! the URL does not change after i close the slideshow, so it looks like:

domain.xxx/owncloud/index.php/apps/files?dir=%2FPictures%2Ffolder1%2Fsubfolder#/Pictures/folder/subfolder/pic2.jpg

**Comment by vader2014** [comment]
Just did a short test: unfortunately it does not work, compared to the behavior of the original app the URL changes  from domain.xxx/owncloud/index.php/apps/files?dir=%2FPictures%2Ffolder1%2Fsubfolder#/Pictures/folder/subfolder/pic2.jpg

to 

domain.xxx/owncloud/index.php/apps/files?dir=%2FPictures%2Ffolder1%2Fsubfolder#

**Comment by oparoz** [comment]
Ah, thanks for that "Pictures" URL. That URL leads to another problem https://github.com/owncloud/gallery/issues/171

If you still get a hash in the URL, then you need to hit ctrl+f5 a few times until it's gone.

**Comment by vader2014** [comment]
and i have another observation: the URL of the viewed pic can be found in the browser history but if i go back i drop to the root of the file app. The old app did not place anything into the history.

**Comment by oparoz** [comment]
Thanks for testing. It's fixed in master and stable8.

**Comment by oparoz** [comment]
Just a heads up that this is likely to be reverted as it doesn't work when the browser's back button is used to close the slideshow.

So everything will be working fine on the Gallery side, but on the Files side, the list will be reloaded when you quit the slideshow, and pressing "forward" will break the Files app. Nothing can be done at this stage in fear of breaking the sacrosanct IE8 compatibility.

More discussion in https://github.com/owncloud/galleryplus/issues/160

**Comment by oparoz** [comment]
Never mind. I've found a way to restore the position. It's not as smooth as what we currently have since the content still needs to be refreshed, but that will do until the Files app is fixed.
