### ISSUE TITLE
File name listed when viewing pictures in preview/slideshow mode

### ISSUE THREAD

**Issue by mbressman** [owncloud/gallery#129]
When you browse to a folder that contains pictures, you can click on one to view it larger, and then you can also use left/right arrows, left/right button on page, or slideshow mode to view other pictures in that folder. However, there's no easy way to tell the file name of the picture you are looking at if you've opened one and then moved to others in that same folder using the above methods. This makes looking through pictures to find one and then determining the file name of that found picture very tough. It'd be great to have the file name appear at the bottom (or somewhere) as you browse through them so you can easily determine the file name of whatever picture you are viewing.

**Comment by oparoz** [comment]
Moved to https://github.com/owncloud/galleryplus/issues/237
