### ISSUE TITLE
Add a busy spinner whilst loading thumbs

### ISSUE THREAD

**Issue by arkascha** [owncloud/gallery#130]
The apps shows a busy spinner whilst initially loading an album. Great. 
The same should happen whilst still loading additional thumbs, probably centered in the row to come. 
Otherwise there is no means to tell if loading has finished.

**Comment by oparoz** [comment]
I agree. I'm adding the original Gallery ticket here for reference:
https://github.com/owncloud/gallery/issues/150

**Comment by jancborchardt** [comment]
Totally agree here. We need loading feedback, otherwise it’s not clear if it’s still loading or there’s an error (or pictures are missing which you know are there). @arkascha’s suggestion of putting it in the middle of the row to come is good.

**Comment by oparoz** [comment]
The best way to implement this would be via https://github.com/owncloud/gallery/issues/29
Otherwise we would have to create/destroy lots of divs, just to show the spinning wheel.

**Comment by jancborchardt** [comment]
@oparoz the spinner could also just be shown as the background image of the row to be rendered (via class `.icon-loading` which can then simply be removed).

**Comment by oparoz** [comment]
@jancborchardt - No, because the row is not added to the DOM until it's been filled. It already has the spinning wheel, but we just never see it. It's a regression from when the photowall was implemented.

**Comment by oparoz** [comment]
One solution to explore is to add an extra DOM element containing only the spinner and to hide it when all thumbnails have been loaded.

**Comment by jancborchardt** [comment]
@oparoz yeah, would be very good for feedback, as we talked about.

**Comment by oparoz** [comment]
Use master to test

**Comment by oparoz** [comment]
You're advised to use a custom CSS spinner if you configure the background colour of your albums as the default one doesn't look good.

**Comment by ghost** [comment]
@rperezb can you please assign

**Comment by rperezb** [comment]
@Dianafg76 did you test it on Friday?

**Comment by oparoz** [comment]
Just to be clear, it's the spinner you see at the bottom of the rows, as they're loading.
The easiest way to see it is to delete all the thumbnails and to reload an album in Gallery

**Comment by Dianafg76** [comment]
I tested this issue and it is working ok.
Server v {"installed":true,"maintenance":false,"version":"8.2.0.7","versionstring":"8.2 beta1","edition":""}
Closed
