### ISSUE TITLE
Do not rely on file name extensions

### ISSUE THREAD

**Issue by arkascha** [owncloud/gallery#131]
Not sure if this is an issue with this app or with owncloud in general: 
Apparently the file type is determined by the file name extension, like back in the 80th...
This leads to pictures not shown in this app although pictures do exist. 
The file name pattern should not be relevant any more, there are more modern and reliable ways to find out a file type.

**Comment by oparoz** [comment]
You are correct, ownCloud, picks a media type based on the file extension and I agree, it could use something like `fileinfo`.

Please report the issue in `core` if it doesn't exist already so that a possible change can be discussed.

**Comment by oparoz** [comment]
I just want to add that it's possible to add your own definitions to https://github.com/owncloud/core/blob/master/lib/private/mimetypes.list.php

And if there are some major omissions, you should submit a PR :)

**Comment by arkascha** [comment]
Adding an extension is not really an option, except for some inhouse usages with few extensions missing. 
The issue is more with file without any extension in the name or with extensions like .back and similar.

**Comment by oparoz** [comment]
I see. Definitely an interesting topic for `core`. They must have chosen to rely on a table for performance reasons.
