### ISSUE TITLE
Gallery+ won't load Pictures, destroys listing of files in "files" section

### ISSUE THREAD

**Issue by dhuuk** [owncloud/gallery#132]
This is the Error out of the OC Admin Panel

"Invalid OCS content returned for app galleryplus"

Problems occuring:
Gallery+ is avaiable in the Navigation, but it won't load any pictures.
After installing Gallery Plus the App Management won't load, it just keeps spinning both wheels on the left and right side.
After installing Gallery Plus the File Listing in the Navigation "Files" loads but does not list any of the files in the directory.

Running OC 8.0.3, latest release - clean install
php 5.4 on linux system, web hosting package of hosteurope.de

**Comment by oparoz** [comment]
Please make sure you have disabled the Pictures/Gallery app

**Comment by oparoz** [comment]
Also, I haven't tested the release version of 8.0.3 yet. It re-enables the app store and there could be issues.

**Comment by deMattin** [comment]
Updated to 8.0.3 yesterday - everything works.
Gallery+ is seen in apps and after update I had to activate it (as usual).

**Comment by oparoz** [comment]
Thanks for the feedback :). Could have been a temporary issue or a conflict. I need to implement https://github.com/interfasys/galleryplus/issues/133

**Comment by dhuuk** [comment]
That seems to be the solution. Can't find any reference in the readme to disable the integrated Gallery App. Maybe this should be part of the readme. Or maybe i was just to stupid :)

Nevertheless, thank you very much for the support and the beautiful and smooth app :+1:

**Comment by oparoz** [comment]
It's in the app store's readme (in bold), but it's been mentioned recently that this was missing from the readme included with the app. Well, it's in the bug reporting section only.

I'll update the file for the next release :)
