### ISSUE TITLE
thumbnail of lots of small pictures not all visible in gallery app

### ISSUE THREAD

**Issue by dttpy** [owncloud/gallery#133]
### Expected behaviour
Thumbnail of all pictures should be showed/listed in gallery app.

### Actual behaviour
Only some of these thumbnails are showed, not all. In my case just about 13%.

### Steps to reproduce
1. create a folder "smiley" and go into it
2. upload a lot of small pictures (at least 50). 
    (In my test, 66 .gif files were uploaded, and the average size of them are 4~5 KB. 
3. go to the gallery app and go into "smiley"

### Server configuration
Operating system: Ubuntu 13.10

Web server: apache 2.4.6 (Ubuntu)

Database: SQLite

PHP version: 5.5.3-1ubuntu2.3

ownCloud version: 7.0.3

Updated from an older ownCloud or fresh install: from 7.0.3rc

List of activated app:standard apps of owncloud 7.0.3 and encryption

The content of config/config.php: (Without the database password and passwordsalt)
$CONFIG = array (
  'instanceid' => 'oc6d9cda6e26',

  'datadirectory' => '/var/ocdata/***/owncloud/data',
  'dbtype' => 'sqlite3',
  'version' => '7.0.3.4',
  'installed' => true,
  'theme' => '',
  'maintenance' => false,
  'maxZipInputSize' => 838860800,
  'allowZipDownload' => true,
  'loglevel' => '0',
  'trusted_domains' => 
  array (
    0 => '192.168.1.80',
  ),
);

Are you using external storage, if yes which one: no

### Client configuration
Browser: firefox 33.1.1

Operating system: ubuntu 13.10

**Comment by dttpy** [comment]
tested with owncloud8-beta2 and it works

**Comment by oparoz** [comment]
Thanks!
