### ISSUE TITLE
Invalid OCS content returned for app galleryplus

### ISSUE THREAD

**Issue by binarykitchen** [owncloud/gallery#134]
```
{"reqId":"3a73b8ad17d560f74d881078c8c04c5f","remoteAddr":"203.84.135.120","app":"core","message":"Invalid OCS content returned for app galleryplus","level":4,"time":"2015-05-06T22:22:42+00:00"}
```

Happens on the stable8 branch.

**Comment by oparoz** [comment]
Thanks for the report.

Somebody else has reported an OCS error and it seems to occur on the newly pre-released 8.0.3 only.

**Comment by oparoz** [comment]
oC is contacting the app store despite the fact that the app doesn't include an ocsid.
I'll add it to the next release.

**Comment by oparoz** [comment]
8.0.11 has been released and the app now includes an ocsid. That doesn't solve the problem in core, but the info-message should disappear from the logs.
