### ISSUE TITLE
Support ownCloud 8.1

### ISSUE THREAD

**Issue by LEDfan** [owncloud/gallery#136]
Hey, awesome job with this app :)

It would be cool to support ownCloud 8.1. I tested this app (by removing the requirement in the info.xml file). Some debug information:

Browser's console:

```
TypeError: SlideShow._getSlideshowTemplate is not a function
```

There are no errors in owncloud.log

Thanks in advance :smiley:

**Comment by oparoz** [comment]
Thanks :)

Now that 8.1 has reached beta, I will add a 8.1 specific version in the appstore, but in the meantime, you can download a zip from the dev branch and it should work.

Let me know if you still get that JS error, it could be unrelated.

**Comment by oparoz** [comment]
A pre-release is now available from the app store
https://apps.owncloud.com/content/show.php/Gallery+8.1?content=169939

**Comment by TheNetStriker** [comment]
I also get this error using ownCloud 8.0.3. I'am using the latest dev version. How can I fix this problem?

**Comment by deMattin** [comment]
Install Owncloud 8.1 ... ;-)
Dev branch of gallery+ is not compatible with oC 8.0.x and needs oC 8.1.

To use gallery+ with actual oC 8.0.3 you have to use the master branch of gallery(+).

**Comment by TheNetStriker** [comment]
I've now also tested with the master branch, but I get the same error. How can I solve this problem?

**Comment by oparoz** [comment]
@TheNetStriker - I suspect you're using asset pipelining and haven't emptied the asset folder or you haven't disabled Pictures.

As you can see on master, we never call that method
https://github.com/owncloud/galleryplus/blob/master/js/slideshow.js#L307

**Comment by TheNetStriker** [comment]
Thanks for the hint. I didn't know that I have to disable the pictures app. Gallery is now working. ;)
