### ISSUE TITLE
Use same labels and milestones as core

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/gallery#140]
To align development and make it easier for other ownCloud contributors, the labels (+colors) and milestones used here should be the same as in core. Not all of them, but at least the standard ones like:
- bug
- enhancement
- design
- discussion

And for milestones the classic:
- 8.1-current
- 8.2-next
- 8.3
- etc…

Currently it’s almost all custom colors and naming which is confusing.

@oparoz can you manage that? Thanks!

**Comment by oparoz** [comment]
OK

**Comment by LukasReschke** [comment]
@craigpg Has a fancy magic script for that.

**Comment by oparoz** [comment]
Thinking about milestones, I'm not sure it makes sense to use the same milestones as core since apps are on independent cycles. I use milestones to target specific releases of the app.

**Comment by oparoz** [comment]
I've modified the labels and added two milestone labels to help categorise the bugs once 8.1 has launched

**Comment by jancborchardt** [comment]
@oparoz cool, thanks! :)

I also fixed the name from »user experience« to »design«, and the color of the »enhancement« label to green.
