### ISSUE TITLE
One image per folder to speed up the loading

### ISSUE THREAD

**Issue by etiess** [owncloud/gallery#143]
I propose to continue here the issues discussed in https://github.com/owncloud/gallery/issues/52 and https://github.com/owncloud/gallery/issues/100

Summary:
- Folders have to be distinguished from pictures
- Solution since 7.0.2 is to have four images per tile for folders

The limits of the actual solution:
 1. Design is less seamless
- there are too many small pictures on the same page. It's less seamless
- if a folder has one single picture, this solution doesn't give anything new
- if a folder has 2 or 3 pictures, it leaves a white square, which doesn't look good

 2. Other solution are possible
- we already have a transparent grey part at the bottom with the folder's name. While there's nothing for a picture. That's enough to make a difference
- pictures' thumbnail are not made square if the original picture is not square. So we see it's different from a folder
- if we want to make a bigger difference, it could be possible to include, next to the folder's name, the number of pictures which are included?
- Except in Gnome, who (on the web or on specific programs) does that in this way?

 3. Performances are poorer (https://github.com/owncloud/gallery/issues/100)
- Pictures are loaded one by one to build a tile with four pictures
- Loading is already slow (see for example https://github.com/owncloud/gallery/issues/107), this is an additional cause of slowing it down.

In my opinion, the actual solution is not satisfying, and I would prefer the previous solution. As suggested by @diederick76, it should be possible, as an admin, to go for the previous layout.

cc @jancborchardt @icewind1991 @libasys @jbtbnl who took part to the previous discussions

**Comment by oparoz** [comment]
Gallery has between 1 and 4 images per folder and it looks nice imo. That will slow down things the first time an album is visited, but I think it's acceptable. The real solution is to create thumbnails in advance.
