### ISSUE TITLE
Turn the Gallery button into a switch

### ISSUE THREAD

**Issue by oparoz** [owncloud/gallery#145]
It would be more immediately understandable if there was a switch with both the Gallery and Files button, as shown here:
![0ebbfcfc-fcdb-11e4-877c-873b19def287](https://cloud.githubusercontent.com/assets/323220/7682644/dc28dbbc-fd79-11e4-9984-2fd249e208c9.png)

**Comment by oparoz** [comment]
Change has been rejected. Will keep in Gallery+ for 8.1 and 8.0

**Comment by jancborchardt** [comment]
@oparoz sorry again for swaying back and forth on this one. Oftentimes design has to be carefully evaluated as you know. :) Especially when it’s that present in our main Files app.

**Comment by oparoz** [comment]
Yep, no hard feelings :)
Since 8.0 and 8.1 have the old design, it will work there and I'll be able to get some feedback :)
