### ISSUE TITLE
Bullet point CSS for Markdown conflicts with theme design

### ISSUE THREAD

**Issue by oparoz** [owncloud/gallery#147]
### Steps to reproduce
1. Click on the "Personal" button to access your settings
### Expected result

The menu should look the same as on the Files app
### Actual result

Menu items have a bullet point

**Comment by oparoz** [comment]
Introduced by
https://github.com/owncloud/galleryplus/commit/727a7c62d01b24dd437baf075d74ec714659e9ac

**Comment by deMattin** [comment]
Settings Button :question:

**Comment by oparoz** [comment]
"Personal" button

**Comment by deMattin** [comment]
Sorry, I don't know, what this should be.
The info button with the folder descriptions? But there's no menu with settings, it's a description ...

**Comment by oparoz** [comment]
It's a standard oC button, top right, with your name on it.
