### ISSUE TITLE
JS warning in window.onhashchange when gallery is empty

### ISSUE THREAD

**Issue by AdamWill** [owncloud/gallery#148]
When the gallery is empty, this code block in `gallery.js` `window.onhashchange` throws a warning `TypeError: album is undefined`:

		var album = Gallery.albumMap[albumPath];
		var images = album.images;
		var startImage = Gallery.imageMap[path];
		Gallery.slideShow(images, startImage);

The 'obvious' fix would be:

		var album = Gallery.albumMap[albumPath];
		if (album) {
			var images = album.images;
			var startImage = Gallery.imageMap[path];
			Gallery.slideShow(images, startImage);
		}

but I really don't know JS well at all, so I figured better report an issue than file a PR.

**Comment by karlitschek** [comment]
@PVince81 What do you think about this fix?

**Comment by PVince81** [comment]
Looks fine.

CC @icewind1991 who maintains the gallery app

**Comment by oparoz** [comment]
@AdamWill - I've fixed it a while back, see if you get the same warning in this release:
https://github.com/interfasys/galleryplus/releases/tag/v1.0-rc1

**Comment by oparoz** [comment]
Closing as this has been fixed.
