### ISSUE TITLE
please add a spinning circle while there are still pictures being lazy loaded

### ISSUE THREAD

**Issue by jsalatiel** [owncloud/gallery#150]
Please add a circle spinning while there are still pictures still being loaded.
During lazy loading, there are no real way to know if all pictures in the folder have been displayed or are still loading. I think a circle spinning would be nice. See the attached "suggestion"
![spin_while_still_loading](https://cloud.githubusercontent.com/assets/5522389/5741230/9d78c762-9be8-11e4-982c-aaf4f83cd77d.jpg)

**Comment by oparoz** [comment]
I agree, this is a big usability issue, especially is the gallery contains large images.
An alternative could be to have a ghost picture (dotted border per example) with a spinning circle in the centre.

Thoughts @jancborchardt ?

**Comment by jancborchardt** [comment]
Yeah, good call. The spinner should be at the end of the list, being the last item similar to what @oparoz suggested. @icewind1991

**Comment by devurandom** [comment]
Also applies when the image is displayed "fullscreen": If I click the "next image" arrow button on the right edge of the screen, I have no way of knowing whether I am still looking at the last image, or whether the next one is already being displayed. If you have lots of very similar images in a folder, this becomes are real problem. A simple spinner icon in the middle, overlayed over the image, would solve the issue already.

**Comment by oparoz** [comment]
AFAIK, the spinner is already there. If you're not seeing it, it's because your images are cached.
Maybe there could be a transition between images using CSS.

**Comment by devurandom** [comment]
The images take several (>15) seconds to load. They will load quicker (<1s), if I already viewed the whole album once. I doubt these are caching effects.

**Comment by oparoz** [comment]
The next picture is pre-loaded and the browser caches them, so, per example, reloading a slideshow of an album you've just viewed will show almost no loading for the first picture and nothing for the ones after that.

**Comment by devurandom** [comment]
Exactly. My point is, that the first time loading takes a while and there is no spinner. Second point is that I can clearly destinguish the two cases, because the loading time differs so drastically.

**Comment by oparoz** [comment]
@devurandom - Please open a separate issue for this so that this can be tracked properly
