### ISSUE TITLE
Plugin ideas

### ISSUE THREAD

**Issue by oparoz** [owncloud/gallery#152]
Please add and discuss your plugins idea here for now and eventually they will be moved to the wiki.

Plugins are defined here: https://github.com/owncloud/galleryplus/issues/128
### Plugins
- Advanced settings. Reveal the app's hidden settings via the app's setting menu
- Generate media links which contain the file name https://github.com/owncloud/core/issues/16470

**Comment by mrladeia** [comment]
It would be very interesting to accept the direct link.
Often I need to use images  in forums using bbcode.

Examples would be perfect:
ownlink.com/index.php/s/VVvMF3ru1AKv2PA/_direct_/**file-name**.[mp3-png-WHAT-EVER]
ownlink.com/index.php/apps/galleryplus/s/VVvMF3ru1AKv2PA/**file-name**.[mp3-png-WHAT-EVER]

**Comment by oparoz** [comment]
I think it will be possible to add this to Gallery without adding any extra plugins since we control the routes.

**Comment by oparoz** [comment]
Moved to the wiki
