### ISSUE TITLE
Gallery broken in ownCloud 8

### ISSUE THREAD

**Issue by MorrisJobke** [owncloud/gallery#152]
@fossxplorer and I noticed that the gallery is broken in master/8

@icewind1991 Can you have a look? I managed to have a listing of subfolders (by appending the path to the URL after a hash) but for the main page it's just a endless spinning spinner.

**Comment by icewind1991** [comment]
Still works for me

**Comment by mmattel** [comment]
I have the same. At some point somewhere last year end of autumn beginning winter, gallery of my dev system (master) stopped showing thumbs, stays empty and the spinner runs forever. I never gave it more notice up to I saw this issue...

I just tried it again:
- logon to my dev instance (master, updated last on saturday)
- directly go to the admin page and check logs (debug, look for the timestamp of the last entry)
- change to gallery (empty, endless spinner)
- back to admin/logs

An oC logs reports me tons of messages:
Debug,	no app in context,	Accessing the API class is deprecated! Use the appropriate services instead!

**Comment by oparoz** [comment]
There are too many things broken in the whole chain file->encryption->preview->gallery which mean than any little issue will break the gallery.

The solutions is here: https://github.com/owncloud/gallery/issues/151

**Comment by oparoz** [comment]
@mmattel - Lots of those debug messages are unrelated to the Gallery app.

**Comment by MorrisJobke** [comment]
I don't have this issue anymore with current master.

**Comment by LukasReschke** [comment]
Closing then.
