### ISSUE TITLE
Resample large images

### ISSUE THREAD

**Issue by utahbmxer** [owncloud/gallery#153]
It would be nice to see the Pictures app resize/resample images when requested during a slideshow.  In the Files app, if I click a large JPG file, such as a panorama that is 50+ MB (12240 x 2892px), it loads pretty fast and the resulting image is actually the width and/or height of the browser window.  This performs great and I often find myself using the Files app to view my photos, and stay away from the "Pictures" app.

The Pictures app on the other hand seems to download the original file, which takes quite a while and consumes a lot of bandwidth.

**Comment by oparoz** [comment]
It's actually a core issue which should be fixed in OC8.1
Patches are available for OC7 and OC8
