### ISSUE TITLE
It should be possible for the user to use various sorting filters

### ISSUE THREAD

**Issue by oparoz** [owncloud/gallery#154]
The default is to sort alphabetically, but it should be possible for the user to sort his collection by date.

Which date to use? Currently only the uploading date I imagine, but if meta data is introduced then it would be possible to sort by date-the-picture-was-taken.

**Comment by nickma82** [comment]
related to https://github.com/owncloud/gallery/issues/94

**Comment by oparoz** [comment]
There are various tickets related to sorting in Gallery. The conversation can be continued there.
