### ISSUE TITLE
Search field is not returning any results

### ISSUE THREAD

**Issue by oparoz** [owncloud/gallery#156]
### How to reproduce
Using master, go to the Gallery app and use the search field.

### Expected result
A dropdown should show up, just like when using OC7 , and it should show the result of the search

### Actual result
Nothing is happening

### Solution
It looks like results are now displayed in the main window, which means that new logic would need to be implemented so that results can be collected and displayed.
In the mean time, the search field should be hidden.

**Comment by karlitschek** [comment]
@butonic Can you have a look please?

**Comment by oparoz** [comment]
Just found out that this is linked to this:
https://github.com/owncloud/core/issues/11635#issuecomment-59767816
and
https://github.com/owncloud/core/issues/821#issuecomment-65242817

So the good news is that it will be easy for apps to add their own filters, but apparently, the search field does not hide yet

**Comment by DeepDiver1975** [comment]
summoning @jancborchardt

**Comment by jancborchardt** [comment]
@butonic @icewind1991 what’s the status on that? Search should filter just like in the files app, showing only the relevant results.

**Comment by oparoz** [comment]
Fixed in core.
