### ISSUE TITLE
Add meta data support

### ISSUE THREAD

**Issue by oparoz** [owncloud/gallery#157]
The gallery app should be able to add/edit/delete various fields linked to a media file.
Lots of the information is stored in the EXIF fields of some formats and this should be automatically imported, but a user should also be able to fill empty fields and add new ones.

This can then be used:
* for comments https://github.com/owncloud/gallery/issues/117
* for sorting https://github.com/owncloud/gallery/issues/154 https://github.com/owncloud/gallery/issues/94
* for virtual views. Date based albums, tags based albums, location based albums, etc

**Comment by Riechao** [comment]
I'm looking at this, but I can't figure out how to get exif_data from a fileinfo object. I tried making an OCP\Image from image->load() fileinfo->path or fileinfo->internalpath, but it won't load from file.

If someone can give me some directions towards how to access the files from the list of files, I can take care of the rest, the JS modifications and the getimages.php modifications.

I really don't want to touch core and add exif data to fileinfo.

**Comment by oparoz** [comment]
2 things:
1. The AppFramework needs to be used.
2. The information has to be stored permanently, so a database schema has to be created, as well as a class to access the data. I think @libasys has already worked on something like this on his fork, but it needs to fit into the AppFramework now.

http://doc.owncloud.org/server/8.0/developer_manual/app/schema.html
http://doc.owncloud.org/server/8.0/developer_manual/app/database.html

Now regarding EXIF data, if we want to avoid using core, that means accessing the file directly and extracting information via the Imagick class, using GD as a fallback, otherwise, core hacking of the Preview class would be required.
The Preview class itself is moving to the AppFramework for 8.1, so it might be worth having a chat with @georgehrke to see if extracting as much information as we can can be part of that "app".

**Comment by DeepDiver1975** [comment]
summoning @PVince81 - we are planning to get meta data handling into core as well - maybe for 8.2 ?

**Comment by Riechao** [comment]
@oparoz 
Thank you for your information.
I'm currently looking at gallery, just looking at the current code on my own playground fork. 
1. I'm not sure how to do this within the current gallery app. 
2. You are ABSOLUTELY right. Calling exif_read_data on each file when someone accesses the gallery app adds a crazy amount of time to load. I have 7700 photos on my owncloud, and it added 55 seconds... this would happen EACH time you open the gallery if you don't store it somewhere.

At this point, I've figured out how to add it to gallery, but it's not pleasant.

**Comment by oparoz** [comment]
@Riechao - You need to use the AppFramework version of the Gallery app:
https://github.com/interfasys/galleryplus

It should simplify development as the framework already provides tools to store and retrieve the information.

But maybe we have to be patient and wait 6 months for the metadata app to land in core first. It's important to be able to store more than just EXIF data.

**Comment by jospoortvliet** [comment]
@oparoz @Riechao wait? help @PVince81 make it happen faster, I'd say ;-)

(I would soooo love to have this feature... whoa)

**Comment by Riechao** [comment]
@oparoz 
Gotcha, I'll look into cloning galleryplus and starting over.

@jospoortvliet 
 Without core support for metadata though, we are still looking at at the very least one very long load for gallery that reads meta data (exif_read_data) and puts it into a schema. 
This has a lot of implications, like what do we do for files we find in the gallery directories that don't have meta data? just throw them at the end and fall back on sorting by file name? Do we attempt to parse filenames for metadata in that case? (for android I think they name them img_date.jpeg but I could be wrong)
Also, the exif-data DateTime can be modified, it doesn't always mean dateTaken...

**Comment by jospoortvliet** [comment]
@Riechao ah, yeah, I get that. hence my point of making the stuff move forward faster by helping  @PVince81  ;-)

**Comment by libasys** [comment]
@oparoz for metadata support ... I only coded editing metadata for jpg files! Because here you have the iptc feature! (https://en.wikipedia.org/wiki/IPTC_Information_Interchange_Model) I am not a fan to add new database table to have this feature, because the metadata is only on the database but not on the image. if you download this image the metadata (e.g. Title, description) gone!

**Comment by oparoz** [comment]
@libasys - Thanks for the info. What we could do is store a subset of what is stored in the DB, in the files which support storing that information.

**Comment by oparoz** [comment]
Closing as there are similar conversations going on in the new repository
