### ISSUE TITLE
request failed: URI too long

### ISSUE THREAD

**Issue by mightycoco** [owncloud/gallery#159]
I upgraded my OC7 to OC8
When opening the gallery app there is only an empty page with a spinning waiting icon.

In the apache error log, I see an entry
`[error] [client xxx.xxx.xxx.xx] request failed: URI too long (longer than 8190)`

The same request shows up in the access log with a pretty long URI:
```
"GET 
/index.php/apps/gallery/ajax/thumbnail/batch?token=&image=Audio%2Fmini.l 
ast.fm.recordings%2F0theBand%2F%270%27%2Fcover.jpg;Audio%2Fmini.last.fm. 
recordings%2F1200%20Micrograms%2FRaja%20Ram%27s%20Stash%20Bag%2C%20Volum 
e%202%2Fcover.jpg;Audio%2Fmini.last.fm.recordings%2F666%2FHellraiser%2Fc 
over.jpg;Audio%2Fmini.last.fm.recordings%2F8-Bit%20Weapon%2F8-Bit%20Oper 
ators%2Fcover.jpg;Audio%2Fmp3%2Fdatabase%2Fdiverse%2FAlbumArt_%7B13894D1 
6-4AA2-4F38-80DC-52069C1BD15C%7D_Large.jpg;Audio%2Fmp3%2Fdatabase%2Fdive 
rse%2FAlbumArt_%7B13894D16-4AA2-4F38-80DC-52069C1BD15C%7D_Small.jpg;Audi 
o%2Fmp3%2Fdatabase%2Fdiverse%2FAlbumArt_%7B181BDA4C-FBAA-4506-99DA-8A74D 
7C23C36%7D_Large.jpg;Audio%2Fmp3%2Fdatabase%2Fdiverse%2FAlbumArt_%7B181B 
DA4C-FBAA-4506-99DA-8A74D7C23C36%7D_Small.jpg;Audio%2Fmp3%2Fdatabase%2Fe 
bm%2FAlbumArt_%7B37007EB0-63AB-418F-8FC8-BAD092D3D56C%7D_Large.jpg;Audio 
%2Fmp3%2Fdatabase%2Febm%2FAlbumArt_%7B37007EB0-63AB-418F-8FC8-BAD092D3D5 
6C%7D_Small.jpg;Audio%2Fmp3%2Fdatabase%2Febm%2FAlbumArt_%7B3F7A0B90-C13A 
-4406-A6CA-B22F2705F555%7D_Large.jpg;Audio%2Fmp3%2Fdatabase%2Febm%2FAlbu 
mArt_%7B5144FBBA-9CD3-4DCD-93F8-902ECC99797D%7D_Large.jpg;Audio%2Fmp3%2F 
database%2Felectro%2FAlbumArt_%7B1527DD9C-D127-4BB4-8945-923C52E75C5D%7D 
_Large.jpg;Audio%2Fmp3%2Fdatabase%2Felectro%2FAlbumArt_%7B1527DD9C-D127- 
4BB4-8945-923C52E75C5D%7D_Small.jpg;Audio%2Fmp3%2Fdatabase%2Felectro%2FA 
lbumArt_%7B1F61226D-FDC2-479F-B3A3-AE61517CC287%7D_Large.jpg;Audio%2Fmp3 
%2Fdatabase%2Felectro%2FAlbumArt_%7B2133DD96-7AFF-453C-80DE-649F3DAC311A 
%7D_Large.jpg;Audio%2Fmp3%2Fdatabase%2FErich%20Honecker%2FRock%20Aus%20D 
eutschland%20Vol.20%2FFolder.jpg;Audio%2Fmp3%2Fincoming%20music%2FAlbumA 
rt_%7B6582292D-3D88-42B3-91FB-C6F88AD54FC4%7D_Large.jpg;Audio%2Fmp3%2Fin 
coming%20music%2FAlbumArt_%7B6582292D-3D88-42B3-91FB-C6F88AD54FC4%7D_Sma 
ll.jpg;Audio%2Fmp3%2Fincoming%20music%2FAlbumArt_%7B673B768D-A256-4CD6-8 
544-A2BC5D6156D4%7D_Large.jpg;Audio%2Fmp3%2Fincoming%20music%2FAlbumArt_ 
%7B673B768D-A256-4CD6-8544-A2BC5D6156D4%7D_Small.jpg;Audio%2Fmp3%2Fmini% 
20last.fm%20recording%2FAir%2FThe%20Virgin%20Suicides%2FAlbumArt_%7BFDEF 
8047-F53D-4469-96DF-E8CFFD57B50F%7D_Large.jpg;Audio%2Fmp3%2Fmini%20last. 
fm%20recording%2FAir%2FThe%20Virgin%20Suicides%2FAlbumArt_%7BFDEF8047-F5 
3D-4469-96DF-E8CFFD57B50F%7D_Small.jpg;Audio%2Fmp3%2Fmini%20last.fm%20re 
cording%2FAir%2FThe%20Virgin%20Suicides%2FAlbumArtSmall.jpg;Audio%2Fmp3% 
2Fmini%20last.fm%20recording%2FAir%2FThe%20Virgin%20Suicides%2FFolder.jp 
g;Audio%2Fmp3%2Fmini%20last.fm%20recording%2FAlexander%20Robotnick%2FOh% 
20No....Robotnick!%2FAlbumArt_%7B7F656786-59E8-4515-B466-0D42C7EAEDD0%7D 
_Large.jpg;Audio%2Fmp3%2Fmini%20last.fm%20recording%2FAlexander%20Robotn 
ick%2FOh%20No....Robotnick!%2FAlbumArt_%7B7F656786-59E8-4515-B466-0D42C7 
EAEDD0%7D_Small.jpg;Audio%2Fmp3%2Fmini%20last.fm%20recording%2FAlexander 
%20Robotnick%2FOh%20No....Robotnick!%2FAlbumArtSmall.jpg;Audio%2Fmp3%2Fm 
ini%20last.fm%20recording%2FAlexander%20Robotnick%2FOh%20No....Robotnick 
!%2FFolder.jpg;Audio%2Fmp3%2Fmini%20last.fm%20recording%2FBloc%20Party%2 
FI%20still%20remember%20(9-4-2007)%2FAlbumArt_%7B2DEDCF6F-61F6-4611-B363 
-407BBF39F88C%7D_Large.jpg;Audio%2Fmp3%2Fmini%20last.fm%20recording%2FBl 
oc%20Party%2FI%20still%20remember%20(9-4-2007)%2FAlbumArt_%7B2DEDCF6F-61 
F6-4611-B363-407BBF39F88C%7D_Small.jpg;Audio%2Fmp3%2Fmini%20last.fm%20re 
cording%2FBloc%20Party%2FI%20still%20remember%20(9-4-2007)%2FAlbumArt_%7 
BB9A6C6A5-470F-83E5-923E-558AA188E474%7D_Small.jpg;Audio%2Fmp3%2Fmini%20 
last.fm%20recording%2FBloc%20Party%2FI%20still%20remember%20(9-4-2007)%2 
FAlbumArtSmall.jpg;Audio%2Fmp3%2Fmini%20last.fm%20recording%2FBloc%20Par 
ty%2FSilent%20alarm%2FAlbumArt_%7B62D46EC5-701B-40A3-B7A7-D66E1E29EECA%7 
D_Large.jpg;Audio%2Fmp3%2Fmini%20last.fm%20recording%2FBloc%20Party%2FSi 
lent%20alarm%2FAlbumArt_%7B62D46EC5-701B-40A3-B7A7-D66E1E29EECA%7D_Small 
.jpg;Audio%2Fmp3%2Fmini%20last.fm%20recording%2FBloc%20Party%2FSilent%20 
alarm%2FAlbumArtSmall.jpg;Audio%2Fmp3%2Fmini%20last.fm%20recording%2FBlo 
c%20Party%2FSilent%20alarm%2Fcover.jpg;Audio%2Fmp3%2Fmini%20last.fm%20re 
cording%2FBola%2FGnayse%2FAlbumArt_%7B6509508D-AD18-4648-9438-75969772BF 
EF%7D_Large.jpg;Audio%2Fmp3%2Fmini%20last.fm%20recording%2FBola%2FGnayse 
%2FAlbumArt_%7B6509508D-AD18-4648-9438-75969772BFEF%7D_Small.jpg;Audio%2 
Fmp3%2Fmini%20last.fm%20recording%2FBola%2FGnayse%2FAlbumArtSmall.jpg;Au 
dio%2Fmp3%2Fmini%20last.fm%20recording%2FBola%2FGnayse%2Fcover.jpg;Audio 
%2Fmp3%2Fsorted%2F386%20DX%2FThe%20Best%20of%20386%20DX%2FAlbumArt_%7B90 
3C6FC3-025C-9EDA-C138-445BB75A34AE%7D_Small.jpg;Audio%2Fmp3%2Fsorted%2F3 
86%20DX%2FThe%20Best%20of%20386%20DX%2FAlbumArt_%7BBA76C387-CF76-40F6-8C 
13-857ABCD2A412%7D_Large.jpg;Audio%2Fmp3%2Fsorted%2F386%20DX%2FThe%20Bes 
t%20of%20386%20DX%2FAlbumArt_%7BBA76C387-CF76-40F6-8C13-857ABCD2A412%7D_ 
Small.jpg;Audio%2Fmp3%2Fsorted%2F386%20DX%2FThe%20Best%20of%20386%20DX%2 
FAlbumArtSmall.jpg;Audio%2Fmp3%2Fsorted%2FA%20Geh%2FWirklich%2FAlbumArt_ 
%7B5704F461-22C8-F119-5BC6-4CEAD3DA62EB%7D_Small.jpg;Audio%2Fmp3%2Fsorte 
d%2FA%20Geh%2FWirklich%2FAlbumArtSmall.jpg;Audio%2Fmp3%2Fsorted%2FA%20Ge 
h%2FWirklich%2FFolder.jpg;Audio%2Fmp3%2Fsorted%2FA%20Split-Second%2FFles 
h%20%26%20Fire%201991%20Remixes%2FAlbumArt_%7B3DC48DC0-451E-6755-5740-07 
C5A889D423%7D_Small.jpg;Audio%2Fmp3%2Fsorted%2FA%20Split-Second%2FFlesh% 
20%26%20Fire%201991%20Remixes%2FAlbumArt_%7BB9CE0F6F-45CE-45CE-B1B5-89D4 
94D38FE0%7D_Large.jpg;Audio%2Fmp3%2Fsorted%2FA%20Split-Second%2FFlesh%20 
%26%20Fire%201991%20Remixes%2FAlbumArt_%7BB9CE0F6F-45CE-45CE-B1B5-89D494 
D38FE0%7D_Small.jpg;Audio%2Fmp3%2Fsorted%2FA%20Split-Second%2FFlesh%20%2 
6%20Fire%201991%20Remixes%2FAlbumArtSmall.jpg;Audio%2Fmp3%2Fsorted%2FABB 
A%2FThe%20Definitive%20Collection%20Disc%201%2FAlbumArt_%7B45AAA19C-7749 
-4D34-A82B-01B38CE7F9DB%7D_Large.jpg;Audio%2Fmp3%2Fsorted%2FABBA%2FThe%2 
0Definitive%20Collection%20Disc%201%2FAlbumArt_%7B45AAA19C-7749-4D34-A82 
B-01B38CE7F9DB%7D_Small.jpg;Audio%2Fmp3%2Fsorted%2FABBA%2FThe%20Definiti 
ve%20Collection%20Disc%201%2FAlbumArt_%7B46BA684A-856F-E654-15C0-35F2824 
D0455%7D_Small.jpg;Audio%2Fmp3%2Fsorted%2FABBA%2FThe%20Definitive%20Coll 
ection%20Disc%201%2FAlbumArt_%7B7D6C5A9E-A289-44B5-B8A3-30FE0D9A95C5%7D_ 
Large.jpg;Audio%2Fmp3%2Fsorted%2FABBA%2FThe%20Definitive%20Collection%20 
Disc%202%2FAlbumArt_%7BA72F29CA-0B3F-4855-A276-0ED4F29F6806%7D_Large.jpg 
;Audio%2Fmp3%2Fsorted%2FABBA%2FThe%20Definitive%20Collection%20Disc%202% 
2FAlbumArt_%7BA72F29CA-0B3F-4855-A276-0ED4F29F6806%7D_Small.jpg;Audio%2F 
mp3%2Fsorted%2FABBA%2FThe%20Definitive%20Collection%20Disc%202%2FAlbumAr 
t_%7BD6160421-2FA6-D8E0-A514-E91CE62E6C7E%7D_Small.jpg;Audio%2Fmp3%2Fsor 
ted%2FABBA%2FThe%20Definitive%20Collection%20Disc%202%2FAlbumArtSmall.jp 
g;clientsync%2FTempoBox%2Fapp11_tempo_box_ios512_2x.png;clientsync%2FTem 
poBox%2Ftempo_box250_b24_Win8.png;clientsync%2FTempoBox%2Ftempo_box250_b 
24.png;clientsync%2FTempoBox%2Ftempo_box64_b24_Win8.png;Documents%2FMedi 
a%2Fbackgrounds%2F1-1.jpg;Documents%2FMedia%2Fbackgrounds%2F10-1.jpg;Doc 
uments%2FMedia%2Fbackgrounds%2F1024x768_green.jpg;Documents%2FMedia%2Fba 
ckgrounds%2F10base-t.egg.mundhenk.com.jpg;Documents%2FMedia%2FDilbert%2F 
10793.strip.print.gif;Documents%2FMedia%2FDilbert%2F10794.strip.print.gi 
f;Documents%2FMedia%2FDilbert%2F10795.strip.print.gif;Documents%2FMedia% 
2FDilbert%2F10796.strip.print.gif;Documents%2FMedia%2FMessenger%20Avatar 
s%2F1.jpg;Documents%2FMedia%2FMessenger%20Avatars%2F10.jpg;Documents%2FM 
edia%2FMessenger%20Avatars%2F11.jpg;Documents%2FMedia%2FMessenger%20Avat 
ars%2F12.jpg;Documents%2FMedia%2FMisc%20Pictures%2Fajs.jpg;Documents%2FM 
edia%2FMisc%20Pictures%2Fbug.JPG;Documents%2FMedia%2FMisc%20Pictures%2Fb 
ug2.JPG;Documents%2FMedia%2FMisc%20Pictures%2FIMAGE_362.jpg;Documents%2F 
My%20Documents%2FSignature.png;Documents%2FMy%20Documents%2FAnovio%2FAlf 
resco%2FRemote%20API%20doc%2Fresources%2Finherit.gif;Documents%2FMy%20Do 
cuments%2FCV%20and%20Profile%2F1999%20xxxxx%20xxxxx.jpg;Documents%2FMy%2 
0Documents%2FCV%20and%20Profile%2F2000%20Dienstzeitbescheinigung%20Zivie 
ldienst.JPG;Documents%2FMy%20Documents%2FCV%20and%20Profile%2F2002%20xxx 
xx%20xxxxx.JPG;Documents%2FMy%20Documents%2FCV%20and%20Profile%2FAlbumAr 
t_%7B33230BC3-95BF-460A-6132-B5BFA140F199%7D_Small.jpg;Documents%2FMy%20 
Documents%2FHaus%20G"
```

I do have a lot of photos in OC but there shouldn't be a request from a client to the server, sending all file names back to the server! 
* Actually we know server-side, what is available and what not - no need to submit server data from a webclient back to the server
* This shouldn't happen in a GET call but a POST/PUT call.

**Comment by PVince81** [comment]
@icewind1991

**Comment by abelgomez** [comment]
I have experienced the same issue.

Since this is quite annoying, a quick and dirty workaround is to increase the [LimitRequestLine Directive](http://httpd.apache.org/docs/2.2/mod/core.html#limitrequestline) of apache.

For me, that solved the problem (until a fix is released). Nevertheless... increasing this limit is not recommended, so, use at your own risk.

**Comment by oparoz** [comment]
There is definitely something wrong as the request should only be made for 20 files at a time.

Can you reproduce the issue on the next version of the app?
https://github.com/interfasys/galleryplus/releases/tag/2.0.0

Nevertheless, even with a 20 picture limit, we can quickly reach the 2000 character limit which we should try to stay below of because each picture comes with the full path. POST seems to be the solution.

**Comment by Florz** [comment]
It still doesn't work. I checked out the exact tag and forced it to run with PHP 5.6.5 (via cli, the web interface told me this is incompatible)
But this time I get an empty request string:
https://[my server]/owncloud/index.php/apps/galleryplus/images?
-> "500 Internal Server Error"

**Comment by oparoz** [comment]
Just did a couple of tests on Gallery+ with 736 files (PNG and PSD)

All in the root folder of an account: No problem loading the app
All in nested folders: No problems loading the app

So batch processing seems to work on that version.

**Comment by oparoz** [comment]
@Florz - Gallery+ has not been tested on PHP 5.6, so the requirements are PHP 5.4 or PHP 5.5 only until someone can debug it on 5.6. See if owncloud.log gives you more information on what triggered the error 500 though. It could be easy to fix.

**Comment by Florz** [comment]
@oparoz 
# cat /var/www/owncloud/data/owncloud.log | grep gallery
{"reqId":"7d7138d458516640d187d286b90c06d0","remoteAddr":"::1","app":"no app in context","message":"Accessing the API class is deprecated! Use the appropriate services instead!","level":0,"t
21+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/galleryplus\/"}
{"reqId":"51150d93758401e2760fe9c3104a4fe0","remoteAddr":"::1","app":"no app in context","message":"Accessing the API class is deprecated! Use the appropriate services instead!","level":0,"t
27+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/galleryplus\/images?"}
{"reqId":"51150d93758401e2760fe9c3104a4fe0","remoteAddr":"::1","app":"galleryplus","message":"Supported Mimes: [\"image\/png\",\"image\/jpeg\",\"image\/gif\",\"image\/x-xbitmap\",\"image\/bm
\"image\/svg+xml\"]","level":0,"time":"2015-02-12T15:59:27+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/galleryplus\/images?"}

**Comment by oparoz** [comment]
@Florz - I can't see anything wrong in that log exerpt, but since this may be PHP 5.6 related, let's keep the conversation going here: https://github.com/interfasys/galleryplus/issues/20

**Comment by mightycoco** [comment]
Just installed and enabled the galleryplus module

PHP 5.4.36-0+deb7u3 (cli) (built: Jan  9 2015 09:30:51)
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.4.0, Copyright (c) 1998-2014 Zend Technologies
    with XCache v2.0.0, Copyright (c) 2005-2012, by mOo


Opening the gallery+ app again shows the spinning icon, however, the last request to the server was this one:
```
Request URL:https://oc.pointcode.de/index.php/apps/galleryplus/images?
Request Headers
Provisional headers are shown
Accept:application/json, text/javascript, */*; q=0.01
OCS-APIREQUEST:true
Referer:https://oc.pointcode.de/index.php/apps/galleryplus/
requesttoken:wLVu9NfY9PToPEe1xiaQnJ/GilXzGP
User-Agent:Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.111 Safari/537.36
X-Requested-With:XMLHttpRequest
```

Since then my apache2 process is running at ~80% CPU usage - I'm not sure, what the /images? call does, but it's massive. It hasn't finished yet will writing this (~3 minutes and going)

I'm having a collection of 63GB Photos with ~28.000 files

I hope this initial request doesn't try to create an thumbnail on each image.

So yes: this specific problem seems to be solved by using the new app. But I can't tell for sure for now.

**Comment by mightycoco** [comment]
The Request to URL:https://xxx.de/index.php/apps/galleryplus/images? finished after ~14 minutes. Then the same issue appeard again. A request with an very long URI was sent to the server, which failed:

Request URL:https://xxx.de/index.php/apps/galleryplus/thumbnails?images=.........

Reloading the page again triggers URL:https://xxx.de/index.php/apps/galleryplus/images? - I hope it won't take another ~14 minutes again.

**Comment by oparoz** [comment]
Thanks for the feedback @mightycoco ! 
The problem with `images?` is discussed here: https://github.com/interfasys/galleryplus/issues/17
It's been talked about in a few issues. That initial request is killing servers and it's not even generating previews...
I'm still surprised that `thumbnails?` fails after that since it should only contain the link to 20 images...

**Comment by mightycoco** [comment]
In the albums.js in `Album.prototype.preload` there is some code filling the squarePaths array.
This array is a list of arrays with files.
The `squarePaths` array is correctly limited to 20 - however it's items aren't limited and in my case can have hundreds of files.

**Comment by libasys** [comment]
@mightycoco the problem is, if you batch 20 images and load the images per $_GET Parameter you can run into this issue, the $_GET Parameter length is limited, depending on apache version working with http 1.0 or http 1.1 version. The batch files load only 20 images but if you have a lot of subfolders with long names, you can run very fast into this issue. The best solution is to load the images not by folder/name, but ruther by ID of the file. The file ID is also unique!

**Comment by oparoz** [comment]
I might have a fix for the initial request, but @libasys's suggestion to use IDs like he does in his fork would solve the "URI too long" for people with long paths.

**Comment by oparoz** [comment]
The logic to implement the limit doesn't work when sub-folders are found. `limit x 4` thumbnails will be loaded.
So if your folder contains 20 subs with at least 4 pics in each, then 80 thumbnails will be requested at once. Combine that with the fact that paths are still used and you'll explode the URI limit.

**Comment by oparoz** [comment]
Just a heads up for people facing this issue. This project is unmaintained.

You need to switch to Gallery+ if you want things to get fixed. 
https://github.com/interfasys/galleryplus/releases

Not everything has been fixed yet and people who  have long folder and pictures names deeply nested will still have problems and should let us know here: https://github.com/interfasys/galleryplus/issues/27

**Comment by jospoortvliet** [comment]
As @oparoz said - Gallery is unmaintained. ownCloud 8.2 will come with GalleryPlus as default and for 8.1 and 8.0 you can install this as an app if you have so many pictures that you need it.
