### ISSUE TITLE
Addition of picture in Files does not propagate (directly) to Gallery

### ISSUE THREAD

**Issue by jbtbnl** [owncloud/gallery#16]
Refs https://github.com/owncloud/core/issues/7847

### Steps to reproduce
1. Upload picture A via Files
2. Switch to the Gallery app, notice picture A not showing up
3. Upload picture B via Files
4. Switch to the Gallery app, notice picture A now showing up and B not
5. and so on...

### Expected behaviour
Uploaded pictures should always show up in Gallery.

### Actual behaviour
Only the before-last uploaded pictures show up in Gallery.

**ownCloud version:** master

**Comment by oparoz** [comment]
I think this has been fixed a while ago. It's not reproducible on the next Gallery.
