### ISSUE TITLE
Impossible to activate the Gallery

### ISSUE THREAD

**Issue by gringo1er** [owncloud/gallery#161]
Hello! I have tried to install the last stable Gallery version (8.0.11). After an Apache restart, Gallery appears in inactive apps. But clicking on "activate" button is not efficient, the apps remains inactive (the apps seems to be active after a click, but after a refresh, the button "activate" appears again).

My configuration
MySQL 5.5.4.3
Apache 2.4.7

Do you have any idea?

Thanxx

Gringo1er

**Comment by oparoz** [comment]
On which version of ownCloud are you trying to install it?
Is there anything in data/owncloud.log which may be relevant?

The app seems to get rejected for some reason.

**Comment by gringo1er** [comment]
It's the 8.0.3 version, nothing relevant appears while activating the apps

**Comment by gringo1er** [comment]
I found the origin of the trouble: I renamed the galleryplus folder into Gallery.
Naming it galleryplus solves the problem

**Comment by oparoz** [comment]
Thanks for getting back to me.
