### ISSUE TITLE
(url-)sharing is not possible if the folder name contains an ampersand (&)

### ISSUE THREAD

**Issue by martin-rueegg** [owncloud/gallery#161]
### Steps to reproduce
1. create a folder with name e.g. `foo&bar`
2. upload at least one picture to the folder, otherwise it won't show up in the gallery
3. go to gallery, open the given folder
4. click on the `share` button on the top left corner. => the menu is grayed out with a hint that the item cannot be re-shared. (resharing is enabled, by the way)
5. go back to files, rename the folder to `foo_bar`
6. go back to gallery and retry. now sharing is possible

### Expected behaviour
* sharing should be possible in even if the folder contains `&`
* if this is technically no longer possible, an error message should be displayed telling the correct reason

### Actual behaviour
see 4th step above.

### Server configuration
**Operating system:**
Linux 3.13.0-45-generic #74-Ubuntu 14.04

**Web server:**
Apache/2.4.7 (Ubuntu) SVN/1.8.8 mod_fcgid/2.3.9 PHP/5.5.9-1ubuntu4.5 mod_python/3.3.1 Python/2.7.6 OpenSSL/1.0.1f mod_perl/2.0.8 Perl/v5.18.2

**Database:**
MySQL 5.5.41-0ubuntu0.14.04.1 - (Ubuntu)

**PHP version:**
PHP/5.5.9-1ubuntu4.5

**ownCloud version:**
8.0.0.7

**Updated from an older ownCloud or fresh install:**
updated from v0.7

**List of activated apps:**
 - activity
 - bookmarks
 - calendar
 - contacts
 - documents
 - external
 - files
 - files_external
 - files_pdfviewer
 - files_sharing
 - files_texteditor
 - files_trashbin
 - files_versions
 - files_videoviewer
 - firstrunwizard
 - gallery
 - largefileupload
 - ocsms
 - provisioning_api
 - search_lucene
 - updater

**The content of config/config.php:**
```
$CONFIG = array (
  'instanceid' => 'oc1fd83fe17d',
  'passwordsalt' => 'xxx',
  'trusted_domains' => 
  array (
    0 => 'support.metaworx.ch',
  ),
  'datadirectory' => '/var/www/owncloud/data',
  'dbtype' => 'mysql',
  'version' => '8.0.0.7',
  'installed' => true,
  'forcessl' => true,
  'apps_paths' => 
  array (
    0 => 
    array (
      'path' => '/var/www/owncloud/apps',
      'url' => '/apps',
      'writable' => false,
    ),
    1 => 
    array (
      'path' => '/var/www/owncloud/apps2',
      'url' => '/apps2',
      'writable' => true,
    ),
  ),
  'appstoreenabled' => true,
  'appstoreurl' => 'http://api.apps.owncloud.com/v1',
  'mail_from_address' => 'cloud',
  'mail_smtpmode' => 'php',
  'mail_domain' => 'metaworx.ch',
  'loglevel' => '0',
  'theme' => '',
  'maintenance' => false,
  'dbname' => 'owncloud_metaworx',
  'dbhost' => 'localhost',
  'dbuser' => 'owncloud',
  'dbpassword' => 'xxx',
  'overwrite.cli.url' => '/owncloud',
  'secret' => 'xx',
  'preview_libreoffice_path' => '/usr/bin/libreoffice',
);
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
no

**Are you using encryption:** yes/no
no

### Client configuration
**Browser:**
firefox/trusty-updates,trusty-security 35.0.1+build1-0ubuntu0.14.04.1 amd64

**Operating system:**
Linux 3.16.0-30-generic #40~14.04.1-Ubuntu SMP

#### Web server error log
nothing related here

#### ownCloud log (data/owncloud.log)
```
{"reqId":"bf1760e2c328c5bf5d2be3d732be0b58","remoteAddr":"82.192.227.33","app":"core","message":"Generating preview for \"\/photos\/foo&bar\/20110715_211114 Mond-1.jpg\" with \"OC\\Preview\\Image\"","level":0,"time":"2015-02-13T00:17:27+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/gallery\/ajax\/thumbnail\/batch?token=&image=photos%2Ffoo%26bar%2F20110715_211114%20Mond-1.jpg&scale=1.0909091234207153&square=1&requesttoken=q5nRcm7B3deChZOJsqB\/q2oagQ6a3X"}
{"reqId":"bf1760e2c328c5bf5d2be3d732be0b58","remoteAddr":"82.192.227.33","app":"core","message":"OC_Image->fixOrientation() Orientation: 1","level":0,"time":"2015-02-13T00:17:28+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/gallery\/ajax\/thumbnail\/batch?token=&image=photos%2Ffoo%26bar%2F20110715_211114%20Mond-1.jpg&scale=1.0909091234207153&square=1&requesttoken=q5nRcm7B3deChZOJsqB\/q2oagQ6a3X"}
{"reqId":"164c731d1bd50346a657188ca06e4c32","remoteAddr":"82.192.227.33","app":"core","message":"Generating preview for \"\/photos\/foo&bar\/20110715_211114 Mond-1.jpg\" with \"OC\\Preview\\Image\"","level":0,"time":"2015-02-13T00:17:37+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/gallery\/ajax\/thumbnail\/batch?token=&image=photos%2Ffoo%26bar%2F20110715_211114%20Mond-1.jpg&scale=1.0909091234207153&square=0&requesttoken=q5nRcm7B3deChZOJsqB\/q2oagQ6a3X"}
{"reqId":"164c731d1bd50346a657188ca06e4c32","remoteAddr":"82.192.227.33","app":"core","message":"OC_Image->fixOrientation() Orientation: 1","level":0,"time":"2015-02-13T00:17:37+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/gallery\/ajax\/thumbnail\/batch?token=&image=photos%2Ffoo%26bar%2F20110715_211114%20Mond-1.jpg&scale=1.0909091234207153&square=0&requesttoken=q5nRcm7B3deChZOJsqB\/q2oagQ6a3X"}
```

#### Browser log
n/a

**Comment by karlitschek** [comment]
@LukasReschke Are you in the mood for some encoding fun?

**Comment by LukasReschke** [comment]
Guess that can't be worse than https://github.com/owncloud/core/issues/10001#issuecomment-74308828 - I'll take that one.

**Comment by LukasReschke** [comment]
Another problem caused by https://github.com/owncloud/core/issues/14228… – Let me quickfix this here and for 8.1 finally make this function saner in core.

**Comment by LukasReschke** [comment]
Patch is at https://github.com/owncloud/gallery/pull/165 - please test.

**Comment by martin-rueegg** [comment]
thanks @LukasReschke for the fix.
for reference: I can confirm that while the link generation is now working (that what this burg report addreses), the generated URL does not. the formatting of `https://host/owncloud/index.php/apps/gallery/public/uNZTa2jovyGJ0zo` seems to be correct, when calling the link i get the file not found message. see https://github.com/owncloud/gallery/pull/164 which addresses that issue.
