### ISSUE TITLE
"file not found" when switching to gallery view

### ISSUE THREAD

**Issue by utack** [owncloud/gallery#162]
When clicking the icon to switch to the large picture preview in a shared folder the message
![bildschirmfoto vom 2015-02-14 14 45 09](https://cloud.githubusercontent.com/assets/8551234/6199758/1a9ac510-b458-11e4-9cbb-d811b5d9f786.png)

Link format is correct:
https://domain.tld/owncloud/index.php/apps/gallery/public/[somekey]

Owncloud log in the webinterface, apache error log and php error log show absolutely no log entry.

ls -lah /var/www/owncloud/apps/gallery/
~~~
total 64K
drwxr-xr-x  9 root     root     4.0K Feb 14 02:11 .
drwxr-xr-x 26 www-data www-data 4.0K Feb  9 18:56 ..
drwxr-xr-x  2 root     root     4.0K Feb 14 02:11 ajax
drwxr-xr-x  2 root     root     4.0K Feb 14 02:11 appinfo
drwxr-xr-x  2 root     root     4.0K Feb 14 02:11 css
drwxr-xr-x  2 root     root     4.0K Feb 14 02:11 img
-rw-r--r--  1 root     root      599 Feb  7 03:32 index.php
drwxr-xr-x  2 root     root     4.0K Feb 14 02:11 js
drwxr-xr-x  2 root     root      20K Feb 14 02:11 l10n
-rw-r--r--  1 root     root     4.3K Feb  7 03:32 public.php
drwxr-xr-x  2 root     root     4.0K Feb 14 02:11 templates

~~~

Server: Ubuntu 14.04 with Owncloud 8.0

So far reinstalling the owncloud package did not help. Neither did completely re-enabling the picture app with default settings (disabled app,dropped the gallery/pictures/app-settings in mysql, re-enabled app)

Probablly related to #158, the pictures app never loads and keeps on spinning but without generating any log at all.

Help is very welcome, no clue where the problem is coming from.

**Comment by LukasReschke** [comment]
Confirmed.

**Comment by LukasReschke** [comment]
Patch is at https://github.com/owncloud/gallery/pull/164 please test.

**Comment by utack** [comment]
Pach is working for me, issue can be closed.

**Comment by martin-rueegg** [comment]
yep, works for me as well. tnx.

**Comment by utack** [comment]
How about hte backport to stable? Will it happen soon?

**Comment by LukasReschke** [comment]
@utack https://github.com/owncloud/gallery/pull/164#issuecomment-74415484 …
