### ISSUE TITLE
Share thumbnails for shared pictures

### ISSUE THREAD

**Issue by vbouchet31** [owncloud/gallery#163]
Hi,
I'm very new to OC so sorry if this has already been discussed somewhere.
I noticed that thumbnails are not shared for shared pictures. I have two users: "Alan" and "Eric". Alan shares a directory containing 100 pictures with Eric. Alan visits the gallery, it generates all thumbnails into alan/thumbnails. Then if Eric visits his own gallery, thumbnails are generated again and stored in eric/thumbnails.

Is there any way to have these thumbnails being generated only once and then shared per user? it should reduce disk used space, memory consumption and make everything smoother.

Thanks,
#gallery #OC8 #thumbnail

**Comment by oparoz** [comment]
It's actually a `core` issue since the preview generator should be smart enough to know that a cached copy is stored in the original sharer's account. @georgehrke  should be able to confirm this.

**Comment by oparoz** [comment]
Closing as this is a core issue. The app will use what is given to it.
