### ISSUE TITLE
Picture application - Cursor just spins forever

### ISSUE THREAD

**Issue by amigliora** [owncloud/gallery#164]
I am having an owncloud 8.0.3 everything run perfect (web, sync, etc) the only caveat is when I am clicking on Picture app, screens goes white, Pictures (menu or title) in the upper left corner and spinning wheel in the center forever.

Owncloud is on ubuntu 14.04, owncloud software downloaded from OC page, I am using chrome or firefox (same issue) no third party application.

this is the error I found in the admin page log

Exception: {"Message":"Unable to generate a URL for the named route \"gallery_index\" as such route does not exist.","Code":0,"Trace":"#0 \/var\/www\/drive\/lib\/private\/route\/router.php(282): Symfony\Component\Routing\Generator\UrlGenerator->generate('gallery_index', Array, false)\n#1 \/var\/www\/drive\/lib\/private\/urlgenerator.php(42): OC\Route\Router->generate('gallery_index', Array)\n#2 \/var\/www\/drive\/lib\/private\/helper.php(112): OC\URLGenerator->linkToRoute('gallery_index', Array)\n#3 \/var\/www\/drive\/lib\/public\/util.php(219): OC_Helper::linkToRoute('gallery_index', Array)\n#4 \/var\/www\/drive\/apps\/gallery\/appinfo\/app.php(31): OCP\Util::linkToRoute('gallery_index')\n#5 \/var\/www\/drive\/lib\/private\/app.php(386): require('\/var\/www\/drive\/...')\n#6 \/var\/www\/drive\/settings\/ajax\/navigationdetect.php(9): OC_App::getAppNavigationEntries('gallery')\n#7 \/var\/www\/drive\/lib\/private\/route\/route.php(135) : runtime-created function(1): require_once('\/var\/www\/drive\/...')\n#8 [internal function]: __lambda_func(Array)\n#9 \/var\/www\/drive\/lib\/private\/route\/router.php(250): call_user_func('?lambda_317', Array)\n#10 \/var\/www\/drive\/lib\/base.php(782): OC\Route\Router->match('\/settings\/ajax\/...')\n#11 \/var\/www\/drive\/index.php(36): OC::handleRequest()\n#12 {main}","File":"\/var\/www\/drive\/3rdparty\/symfony\/routing\/Symfony\/Component\/Routing\/Generator\/UrlGenerator.php","Line":134}

I appreciate any help to fix this issue

Thanks

**Comment by oparoz** [comment]
Hello,
Please switch to the new Gallery app. Pictures is the old app.
https://apps.owncloud.com/content/show.php/Gallery+8.0?content=169116

**Comment by amigliora** [comment]
Thank you very much
Works perfect :)
:+1:
