### ISSUE TITLE
A single "*.tif" or "*.tiff" image file format brakes completely your Gallery.

### ISSUE THREAD

**Issue by Akhenaton** [owncloud/gallery#166]
[OC 8.0.0] [Gallery 0.6.0]

A single "*.tif" or "*.tiff" image file format brakes completely your Gallery and you get a spinning wheel on a blank page for ever.........

**Comment by oparoz** [comment]
With or without the TIFF provider?

**Comment by sorglos** [comment]
With oC 8.0.2 and Gallery 0.6.0 I see the spinner on a white page when I have at least one .tiff file in the folder. Preview Provider ```OC\Preview\TIFF``` is in ```config.php```. In the Files app no preview of .tiff files.

owncloud.log

    Error	PHP	imagepng() expects parameter 1 to be resource, boolean given at /home/www/lib/private/image.php#292
    Error	core	OC_Image->data. Error getting image data.

error_log

    no acceptable variant: /home/www/apps/gallery/ajax/thumbnail, referer: https://domain.tld/index.php/apps/gallery/

**Comment by oparoz** [comment]
Please switch to Gallery+ if you need to display more than JPGs and PNGs
https://github.com/interfasys/galleryplus/releases/tag/2.0.7

**Comment by sorglos** [comment]
I want to display BMP, JPG, PNG, SVG, and TIFF. It works except for TIFF, but this format is supported by the app. So I use the Gallery and hope this issue will be fixed. ;-)

**Comment by sorglos** [comment]
New label ```wontfix```?

**Comment by oparoz** [comment]
This project is unmaintained, you need to switch to Gallery+ if you want fixes.
https://apps.owncloud.com/content/show.php/Gallery%2B?action=content&content=169116

**Comment by sorglos** [comment]
:-1:

**Comment by SergioBertolinSG** [comment]
Still happening in 8.1 beta2

**Comment by oparoz** [comment]
This app does not work on 8.1, please use the new version:
https://apps.owncloud.com/content/show.php?content=169939
