### ISSUE TITLE
a hash is created in url after opening a picture

### ISSUE THREAD

**Issue by dttpy** [owncloud/gallery#171]
### Steps to reproduce
1. create a folder "pics"
2. upload a picture
3. click and open this picture
4. close this picture

### Expected behaviour
The page stays at the folder "pics", there is no # in the url, and the url should be

http://.../owncloud802/index.php/apps/files/?dir=%2Fpics

like in owncloud 7.0.4

### Actual behaviour
A "#" is created by step3, and by step4, this hash stays.

If the page is updated after step 4, it goes back to the main page with the url:

http://.../owncloud802/index.php/apps/files/?dir=%2Fpic2#/pics/P100.JPG

### Server configuration
**Operating system:** Ubuntu 13.10

**Web server:** apache 2.4.6 (Ubuntu)

**Database:** SQLite

**PHP version:** 5.5.3-1ubuntu2.3

**ownCloud version:** 8.0.2

**Updated from an older ownCloud or fresh install:** 8.0.0-beta2

**List of activated apps:** standard apps of owncloud

**The content of config/config.php:**

```
<?php
define('DEBUG',true);
$CONFIG = array (
  'instanceid' => 'oc6d9cda6e26',

  'datadirectory' => '/var/ocdata/.../owncloud/data8',
  'dbtype' => 'sqlite3',
  'version' => '8.0.2.0',
  'installed' => true,
  'theme' => '',
  'maintenance' => false,
  'maxZipInputSize' => 838860800,
  'allowZipDownload' => true,
  'loglevel' => '0',
  'trusted_domains' => 
  array (
    0 => '192.168.1.80',
  ),
  'appcodechecker' => false,


  );



```

**Are you using external storage, if yes which one:** no
**Are you using encryption:** yes

### Client configuration
**Browser:** firefox 35.0.1

**Operating system:** ubuntu 13.10

**Comment by dttpy** [comment]
also see #14828

**Comment by oparoz** [comment]
Fixed in Gallery+ https://github.com/interfasys/galleryplus/issues/50
