### ISSUE TITLE
App does not load on IE11

### ISSUE THREAD

**Issue by oparoz** [owncloud/gallery#173]
### Steps to reproduce
1. Install oC8
2. Click on the "Pictures" app **in Internet Explorer 11**

### Result
Stare at the spinning wheel forever

### Expected result
Looking at pictures

Look at the debugger. All the data is there, just never sent to where it's supposed to because the EventSource fallback is not working.

**Comment by eggithub** [comment]
Same problem, different preconditions:

upgrade from 8.0.0 to 8.0.2
firefox 36.x, ie11

gallery app shows the "pictures" directory label in the top-left beneath the menu but wheel keeps spinning. 

Seeing these kinds of errors in log but dont know if they are related:

Error 	PHP 	Call to a member function getId() on a non-object at /var/www/owncloud/apps/gallery/ajax/batch.php#59 	2015-03-14T21:02:33+01:00
Error 	core 	OC_Image->data. Error getting image data. 	2015-03-14T21:02:28+01:00
Error 	PHP 	imagepng() expects parameter 1 to be resource, boolean given at /var/www/owncloud/lib/private/image.php#292 	2015-03-14T21:02:28+01:00

if you need more info just let me know

cheers!

**Comment by oparoz** [comment]
I think the problems you're having are more generic than a IE11 problem. The PHP is killed by the script when trying to retrieve some of your files.
If you need something which works today, you should try https://github.com/interfasys/galleryplus/releases/tag/2.0.7

**Comment by libasys** [comment]
This should help you for preview of bigimages:
https://github.com/libasys/ownCloud-7.0.3/commit/08fe3725b93fdf6fb9a3c3ee7bf5c44be752d8bb
Eventsource Problem IE 11:
And this line is needed that IE11 get the images from eventsource:
https://github.com/libasys/ownCloud-7.0.3/commit/c61b27d192a7078b39cc6a0871704e14bfa6508b#diff-632df6a0ecf46b0b10462233762224eaR85

for example the files app works with the same technic, so the loading of the thumbs have to work in ie11,also!
https://github.com/owncloud/core/blob/master/apps/files/ajax/scan.php#L37

**Comment by oparoz** [comment]
Thanks for the pointers @libasys . I've actually switched EventSource in Gallery+ and everything seems to be working as expected.

**Comment by libasys** [comment]
a question with gallery+ how do you now load the images?
working with searchByMime or with getDirectoryContent or have you written your own search images?
In my new version i work with getDirectoryContent and scan for subfolder one level deep if there images found then it looks in the subfolder and get the first 4 pics for thumb preview!

**Comment by oparoz** [comment]
I've dropped the horrible searchByMime () and replaced it with getDirectoryListing()
I do the same thing. Go down until I find 4 pictures.
https://github.com/interfasys/galleryplus/blob/master/service/infoservice.php#L132

**Comment by davitol** [comment]
:+1: Gallery app 0.6.1. does not appear the spinner now. Great!!!
browser: Internet Explorer 11.0.9600.17843
OC server: version":"8.1.0.8","versionstring":"8.1.0","edition"
