### ISSUE TITLE
Pictures hangs out trying to show a deleted file shared with federated cloud share

### ISSUE THREAD

**Issue by jvillafanez** [owncloud/gallery#179]
### Steps to reproduce
1. Upload an image file (checked with a png file) and share it by link in server A
2. Add the link in server B (make sure you see the file listed, but don't open it yet)
3. Delete the image file in server A
4. Click in the file in server B (which should still be visible)

### Expected behaviour
An error is thrown telling that the file is missing, probably deleting the file in server B since the file is no longer there

### Actual behaviour
Gallery hangs out wating for the image to be loaded

### Server configuration
**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** mysql

**PHP version:** 5.5.4

**ownCloud version:** 8.0.3RC1

**Updated from an older ownCloud or fresh install:** fresh install

### Notes
If you open the file in the step 2, it seems that the app uses some kind of cache to load the image later since the app loads the image even though it isn't accessible. This seems wrong too.

**Comment by oparoz** [comment]
This won't be fixed until 8.1 is out, so if you can try the new Gallery app on 8.1 and copy/paste the issue to here https://github.com/owncloud/gallery/issues if it's still a problem.

**Comment by oparoz** [comment]
Closing since Gallery is showing an error message when it can't show the preview.
