### ISSUE TITLE
Ability to download picture from detail view

### ISSUE THREAD

**Issue by PVince81** [owncloud/gallery#18]
In OC 6.0.2:

### Steps
1. Share pic gallery with link
2. Open shared link
3. View a pic by clicking on it
4. Right click pic, copy link
5. Open in separate tab

### Actual
Link is an ajax link

### Expected
Would be better to have the download link instead

I also tried right clicking the download arrow, but it was also the wrong link for that (core issue)

Note: I tried doing this from the mobile UI of 6.0.2 so instead of right clicks I used touch and hold.
I ended up using the Android mobile app and reshared the pic I wanted to send to someone (extra link)

Just wanted to document the use case here

**Comment by jancborchardt** [comment]
Yeah, there should be a Download button for images in the detail view. Especially in the sharing view this is important.

**Comment by jancborchardt** [comment]
cc @oparoz who implemented this in the new Gallery app.

**Comment by oparoz** [comment]
@PVince81 - Let me know if the way it works in Gallery+ fills your use case. You can use 2.0.5, the master branch or just test it with this link:
https://oc8demo.interfacloud.com/index.php/apps/galleryplus/s/4jjwPv5E21l8Lnk

**Comment by jancborchardt** [comment]
@oparoz yeah it actually does. We can do further tracking in https://github.com/interfasys/galleryplus/issues/68 as well (that’s for the sharing action).
