### ISSUE TITLE
Background thumbnail generation [$25]

### ISSUE THREAD

**Issue by 8h2a** [owncloud/gallery#18]
## Feature request

**User type**: any

**User level**: any
### Description

@thedd 
Since the app is extremely slow when opening a folder for the first time I think some actions like thumbnail generation should be moved to a background/cron job.

 (I didn't review the code and have no idea if there's already some background work happening. If there is, I'd still like to discuss performance improvements)

@astroleo
I run owncloud 8.2.2 on a Raspberry Pi which works just fine (and thank you all for this!), but isn't terribly fast. When I share a link to a gallery it takes quite some time to browse through the gallery for the first visitor. opening the gallery, clicking on an image, then clicking the overlaid "next" arrow in the screen-sized image. I understand that opening one screen-sized image triggers the creation of the next one, but (for the Raspy) this isn't fast enough and the first user has to wait each time she clicks the "next" button.

My suggestion would be to add an option to create, right after uploading the album, the various required image sizes so that they are served quickly from the cache already for the first visitor.
### Benefit / value

For OC installations on low-power computers (e.g. Raspberry Pi) the first visitor would already be able  to smoothly scroll through an album.
### Risk / caveats

If uploading a large amount of pictures, creating the cached versions may create quite some server load. The pre-caching task should therefore be given a low priority.
### Sponsorship

@astroleo
I'm afraid I cannot sponsor anything yet, but I'd be happy to help developing / testing this new feature if an expert could provide me with some background on how caching works in OC. 

**Are you a developer willing to implement this feature?**: @astroleo: yes

**Can you sponsor the development of this feature or do you know somewone who can?**: no
##

**Comment by oparoz** [comment]
This will happen in 8.1, see this issue in `core`: https://github.com/owncloud/core/issues/11685

**Comment by oparoz** [comment]
Moved to 8.2...

**Comment by oparoz** [comment]
owncloud/core#11685 has been moved to 9.0 :(

**Comment by oparoz** [comment]
Depending on the timeline for the delivery of https://github.com/owncloud/gallery/issues/221, I could add a method to the service to generate the thumbnail at the same time the information is collected.

**Comment by oparoz** [comment]
@astroleo - I invite you to read owncloud/core#11685 where quite a few ideas are thrown around.

In short:
- At upload time is the best solution as the server would have the encryption key
- There may be a timing issue if it takes 5 minutes to generate a thumbnail. We can't make sync requests and we can't request the encryption key if files are encrypted
- https://github.com/owncloud/gallery/issues/550 is an app which manages images meta data. Maybe it could be modified to generate the thumbnail after analysis
- There is already code to [generate thumbnails offline](https://github.com/owncloud/gallery/pull/387). The idea is to test this on the WD Pi-drive to be able to tune it into an acceptable solution

**Comment by oparoz** [comment]
This issue was moved to nextcloud/gallery#14

**Comment by Phil1988** [comment]
Its soo sad, that this one is dead.
The images/thumbnails makes the Owncloud almost unusable on my RPi 2...

**Comment by Vraana** [comment]
Sorry to say so, but this was the reason I switched to NextCloud....

**Comment by DeepDiver1975** [comment]
> Its soo sad, that this one is dead.

yes indeed - dividing the community by forking the project left many dangling pointers - on both side

just saying - no intent to start a flame war.
