### ISSUE TITLE
Updating an image shared with federated cloud sharing in the source server doesn't show the updated image in the target one

### ISSUE THREAD

**Issue by jvillafanez** [owncloud/gallery#180]
### Steps to reproduce
1. Upload an image and share it by link in server A
2. Add the link in server B and open the image (click in the file to show it)
3. Update the image in server A
4. Open the same image in server B

### Expected behaviour
Both the preview and the file shows the new image

### Actual behaviour
It shows the old image, as it's being cached somehow

### Server configuration
**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** mysql

**PHP version:** 5.5.4

**ownCloud version:** OC 8.0.3RC1

**Updated from an older ownCloud or fresh install:** fresh install

### Notes
Clicking in the download button, you download the new file. Other apps (text editor and pdf viewer), following the same steps, show the new file.

**Comment by oparoz** [comment]
This is a `core` issue. The change is not detected in core and thus we always retrieve the cached thumbnails/previews.

**Comment by oparoz** [comment]
I will check if this is still a problem with core master and open an issue if it is.
