### ISSUE TITLE
files app content disappers when enabling gallery app

### ISSUE THREAD

**Issue by mat-mo** [owncloud/gallery#181]
### Steps to reproduce
1. install gallery app and enable it 
2. go to files, you files are not shown anymore
3. disable the gallery app - files are back
### Expected behaviour

files shouldn't disappear
### Actual behaviour

files disappear
### Server configuration

**Operating system**: 
Debian 8.1
**Web server:**
nginx 1.6.2
**Database:**
mysql 5.5.43
**PHP version:**
5.6.9
**ownCloud version:** (see ownCloud admin page)
8.0.3
**Updated from an older ownCloud or fresh install:**
update
**List of activated apps:**
files,mail,calendar,contacts,documents,pictures
**The content of config/config.php:**

```
<?php
$CONFIG = array (
  'instanceid' => '',
  'passwordsalt' => '',
  'trusted_domains' => 
  array (
    0 => 'foss.co.il',
  ),
  'datadirectory' => '/home/yunohost.app/owncloud/data',
  'dbtype' => 'mysql',
  'version' => '8.0.3.4',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'owncloud',
  'dbpassword' => '',
  'installed' => true,
  'ldapIgnoreNamingRules' => false,
  'theme' => '',
  'maintenance' => false,
  'secret' => '',
);


```

**Are you using external storage, if yes which one:** 
no
**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:** 
no
### Client configuration

**Browser:**
FF 38
**Operating system:**
Arch linux

**Comment by oparoz** [comment]
> List of activated apps:
> files,mail,calendar,contacts,documents,**pictures**

It's written several times in the instructions that you need to disable "Pictures" ;)

The next version will automatically detect this problem.

**Comment by mat-mo** [comment]
Ah, Make sure you've disabled the original Pictures app - now i understand what refers to, sorry and thanks.

**Comment by oparoz** [comment]
:+1:
