### ISSUE TITLE
Pictures App totally broken after upgrade from 7.0.4 to 8.0.3

### ISSUE THREAD

**Issue by ColinFinck** [owncloud/gallery#182]
(Reopening from https://github.com/owncloud/core/issues/16023)

ownCloud's Gallery App keeps spinning infinitely after upgrading from 7.0.4 to 8.0.3. Even after multiple tries and minutes of waiting, no pictures are shown.
Everytime when opening the Gallery App, two additional lines appear in the ownCloud error log:

Undefined index: You don’t have permission to upload or create files here at /srv/www/public/owncloud/lib/private/l10n/string.php#51
Undefined index: You don’t have permission to upload or create files here at /srv/www/public/owncloud/lib/private/l10n/string.php#69

This worked perfectly before. Permissions haven't been changed in the external data directory and are properly set for the ownCloud source files.

**Comment by RealRancor** [comment]
If no one has a clue in here you could also check out the Gallery+ at:

https://github.com/interfasys/galleryplus/
https://apps.owncloud.com/content/show.php/Gallery%2B?content=169116

which is replacing this App in the future.

**Comment by oparoz** [comment]
It's unlikely that this is going to be fixed for 8.0 or 8.1, so closing. The solution is to use Gallery+
