### ISSUE TITLE
gd-jpeg, libjpeg: recoverable error

### ISSUE THREAD

**Issue by binarykitchen** [owncloud/gallery#185]
```
{"reqId":"e50ea44e3a86c2ec883844123aaf9552","remoteAddr":"203.84.135.120","app":"PHP","message":"imagecreatefromjpeg(): gd-jpeg, libjpeg: recoverable error: \b\n at \/var\/www\/owncloud\/lib\/private\/image.php#489","level":3,"time":"2015-05-06T22:24:58+00:00"}
```

Happens on the stable8 branch.

**Comment by oparoz** [comment]
Please report this issue to the core tracker if it doesn't exist:
https://github.com/owncloud/core/issues

And make sure to use the template.

It's the first time I see this error and wonder why this is happening...

**Comment by binarykitchen** [comment]
done https://github.com/owncloud/core/issues/16135
