### ISSUE TITLE
Support the BPG image format

### ISSUE THREAD

**Issue by oparoz** [owncloud/gallery#185]
### Introduction

BPG (Better Portable Graphics) is a new image format. Its purpose is to replace the JPEG image format when quality or file size is an issue. Its main advantages are:
- High compression ratio. Files are much smaller than JPEG for similar quality.
- Supported by most Web browsers with a small Javascript decoder (gzipped size: 56 KB).
- Based on a subset of the HEVC open video compression standard.
- Supports the same chroma formats as JPEG (grayscale, YCbCr 4:2:0, 4:2:2, 4:4:4) to reduce the losses during the conversion. An alpha channel is supported. The RGB, YCgCo and CMYK color spaces are also supported.
- Native support of 8 to 14 bits per channel for a higher dynamic range.
- Lossless compression is supported.
- Various metadata (such as EXIF, ICC profile, XMP) can be included.
- Animation support.

Source: http://bellard.org/bpg/
### Converters
- Online converter: http://webencoder.libbpg.org/
- Windows batch converter http://www.romeolight.com/products/bpgconv/
### Plan

After a preliminary analysis, I concluded that it would not be too difficult to add support to ownCloud via the Gallery app, but the use cases are quite limited at the moment, since mobile browsers would not be able to show the images.

![bpg gallery](https://cloud.githubusercontent.com/assets/323220/8398468/84bd44c6-1def-11e5-989d-a590a7094784.png)
- [x] Add `image/bpg` to the list of core media types https://github.com/owncloud/core/pull/17206
- [x] Add the media type to the list of supported media types in the Gallery app
- [x] Send the raw file, like SVG
- [ ] Send to decoding queue which converts to PNG via ImageMagick so that we can serve those on mobile
- [x] Add the [decoder](https://github.com/mirrorer/libbpg) to both the Gallery and Files app
- [x] Decode images received via EventSource
- [ ] Resize canvas to the maximum size allowed via the oC config
- [ ] Load canvases in the slideshow
- [ ] Make support optional since it uses patented compression algorithms and loads an large library which needs to be compiled in real-time. This requires settings to be stored in the database if we want to avoid loading the scripts themselves 
### Avenues to explore
- Convert to PNGs and cache on server for instances which don't have access to ImageMagick
- How to catch decoding errors
### Advantages
- Saves an enormous amount of space if you're using ownCloud as a sharing tool, not as a tool to store the originals
- Once all thumbnails are loaded, they could be used as-is for the slideshow, assuming you've got enough memory to keep all the large canvases in memory
### Caveats
- No caching, means re-calculating everything at every session
- No thumbnails in the Files app until it supports the format, which probably won't happen any time soon since it doesn't support SVG today
- No support in mobile apps, but everybody can start lobbying for it to happen. https://github.com/owncloud/android/issues/1026
- Cannot be used on mobile due to the lack of asm.js and limited amount of RAM available to the browser
- Can't be used as a replacement for PNG for previews since it would introduce a dependency with a 3rd party library
##

**Comment by jospoortvliet** [comment]
aw this is really cool ;-)

**Comment by oparoz** [comment]
Except that almost nobody has collections in that format :D .
It also remains to be seen how much time the processing takes when you have photowalls with 50 BPG pictures.

I think this would be most useful as a format for thumbnails, but it won't happen before ownCloud uses PHP7 as the minimum version of PHP...

**Comment by oparoz** [comment]
Let's see what the GD team has to say about it :) 
https://github.com/libgd/libgd/issues/168

**Comment by vi** [comment]
Can it use the [JavaScript version](http://bellard.org/bpg/bpgdec.js) as a fallback when libbpg is not available?

**Comment by oparoz** [comment]
I suppose you're talking about using it for thumbnails in core, but unfortunately, it wouldn't work.
The javascript converts BPG files to an HTML5 canvas object. What we need is something which converts PSD, RAW, JPG, etc. to BPG and only ImageMagick can do that today.

I could create an app which would only work with that format, but it would only work with Gallery and would mean having 2 copies of each thumbnail, one in PNG and one in BPG.

So currently, the only thing we can do is show BPG images and let users convert their collections using their favourite tools.

**Comment by vi** [comment]
I don't want ownCloud to convert pictures, I just want to save storage and traffic by using BPGs which I provide.
Typically middle/low-quality photo in BPG already have size of a thumbnail (50-100 KB), so can be used both as a thumnail and a a full-sized photo (thumbnails being just rescaled on client instead of on server).
`bpgdec.js` should provide BPG decoding features to clients that does not have native BPG decoding.

`bpgdec.js` can turn `<img>`s with bpg to `<canvas>` with decoded data on the fly. Can't ownCloud just connect `bpgdec.js` and use plain `<img>`  for `bpgdec.js` to decode them?

**Comment by oparoz** [comment]
Since there is not a single browser supporting BGP, the app would need to always decode files.
As mentioned in the OP, it would work like for SVGs. We would be sending the raw BPG file and let the browser do the resize, but it would only work in the Gallery app and its slideshow and the resized images would look different since no cropping would take place (unless someone writes a cropping method in JS).

**Comment by oparoz** [comment]
~~Also, since there is no Javascript source code for the decoder, it might not be possible to integrate it. It's an all-or-nothing approach and we would probably need to manually call the decoder.~~
I think I've found the source code.

**Comment by vi** [comment]
Why no JavaScript source code for the decoder? It's probably this: https://github.com/mirrorer/libbpg/blob/master/post.js . It probably requires some [Emscripten](https://github.com/kripken/emscripten) and friends to complile...

[Here](http://stackoverflow.com/questions/28088036/how-to-set-bpg-on-background) is example of using `BPGDecoder` from other JavaScript...

**Comment by oparoz** [comment]
Yes, that's the one. There is no need to compile it as it provides a `load(url)` method, so the approach is the same as the one used in the SO question. Build the canvas and paste the result on it.

**Comment by oparoz** [comment]
# Preliminary analysis

I did some testing and it's a not easy to work with. We would need our own decoders since the methods available are too rigid and since we would need to add our own.
Also, it's clear that this can't be used on mobile, so shared albums would be empty... Not a great experience.

## PNGs - 16 pictures - 36.1MB - GD resizing

### 116 requests - 3.9MB - 5.5s

![originals](https://cloud.githubusercontent.com/assets/323220/8397314/ed51abee-1dc7-11e5-959c-2bb2baf7ae83.png)

## BPG - 18 pictures - 1.5MB - Browser resizing

### 116 requests - 4.5MB - 8.5s

![browser resizing](https://cloud.githubusercontent.com/assets/323220/8397347/a49e2a20-1dc8-11e5-935f-aa2c385ada11.png)

## BPG - 18 pictures - 1.5MB - Hermite algo resizing

### 116 requests - 4.5MB - 10s

![hermite resizing](https://cloud.githubusercontent.com/assets/323220/8397364/15df3e04-1dc9-11e5-9bf5-c7a1934f330e.png)

I did not enable asset pipe-lining in the tests, so you could probably shave off 4s to the loading time, which means that you get from 1.5s with PNGs to 6s with BPG with a resizing algorithm and that's with only 18 pictures... 
BUT
All the large pictures for the slideshow are already loaded, so we would probably regain the wasted time, but not everybody is using the slideshow and people will probably have a mix of pictures.
so, what you save in disk space 36.1MB vs 1.5MB, you pay in waiting time when navigating through albums.

**Comment by oparoz** [comment]
Things to test:
- [ ] Overhead when album contains just one BPG picture. Library would need to be loaded (first time we encounter a BPG picture) and the picture processed
- [ ] Overhead when 2nd album containing a BPG picture is loaded. That would be the processing time for a large image

**Comment by oparoz** [comment]
This issue was moved to nextcloud/gallery#36
