### ISSUE TITLE
ultimate dev branch some errors i get with OC8.1rc1

### ISSUE THREAD

**Issue by libasys** [owncloud/gallery#188]
```
Error   PHP     Undefined variable: etag at /is/htdocs/wp11048482_6MQ454GFGE/www/demo81/apps/galleryplus/controller/filescontroller.php#110     26.06.2015 12:30:40
Error   PHP Undefined variable: etag at /is/htdocs/wp11048482_6MQ454GFGE/www/demo81/apps/galleryplus/controller/filescontroller.php#110 26.06.2015 12:30:40
Error   PHP Missing argument 3 for OCA\GalleryPlus\Controller\FilesController::getFiles(), called in /is/htdocs/wp11048482_6MQ454GFGE/www/demo81/apps/galleryplus/controller/publicfilescontroller.php on line 33 and defined at /is/htdocs/wp11048482_6MQ454GFGE/www/demo81/apps/galleryplus/controller/filescontroller.php#99 26.06.2015 12:30:40
Error   PHP Declaration of OCA\GalleryPlus\Controller\PublicFilesController::getFiles() should be compatible with OCA\GalleryPlus\Controller\FilesController::getFiles($location, $features, $etag) at /is/htdocs/wp11048482_6MQ454GFGE/www/demo81/apps/galleryplus/controller/publicfilescontroller.php#23
```

**Comment by oparoz** [comment]
I think that's a bug which was fixed a few days ago. Could you try to update your Gallery branch?

**Comment by libasys** [comment]
ok later i update the galleryplus app! i have moved my ajax part of "gallerydeluxe" now into app framework now source optimizing ^^

**Comment by jancborchardt** [comment]
»gallerydeluxe« …? You guys are killing me. :D

**Comment by libasys** [comment]
we have to change the name prevent namespace problems ;)

**Comment by LukasReschke** [comment]
I already see "The ultimate ownCloud Gallery Bundle", featuring 5 different galleries :speak_no_evil:

**Comment by libasys** [comment]
the user will be happy! so a big bundle with different solutions ^^

**Comment by oparoz** [comment]
> I already see "The ultimate ownCloud Gallery Bundle", featuring 5 different galleries :speak_no_evil:

You know it's coming :)

**Comment by oparoz** [comment]
>  i have moved my ajax part of "gallerydeluxe" now into app framework 

That's great news :) It should make it easier to add code to both apps

**Comment by libasys** [comment]
yes but now hardcore source optimizing _hust_

**Comment by oparoz** [comment]
A good thing you can use Gallery as a model ;) and provide feedback when I did it wrong :D

**Comment by libasys** [comment]
;)

**Comment by jancborchardt** [comment]
> the user will be happy! so a big bundle with different solutions ^^

We’ll talk in half a year to a year when there’s 3 different but all mostly unmaintained apps. ;)
