### ISSUE TITLE
Use multithreading when processing batches of thumbnails

### ISSUE THREAD

**Issue by ghost** [owncloud/gallery#19]
Hi, compared to the old Gallery, this one does no longer split 1st preview generation into seperate threads/requests (~1/4 of speed or slower) and it does not load in IE11 (spinning wheel).

**Comment by oparoz** [comment]
@f-s - By old Gallery, do you mean the app which shipped with oC7 or the one which shipped with oC8? If you're a coder, do you know exactly where the code did initiate those threads?

Issue about IE11 compatibility: https://github.com/interfasys/galleryplus/issues/21

**Comment by ghost** [comment]
By old Gallery i mean the oC7. Here the gallery also loaded/displayed line by line, on the first thumb gen, but core/thread/requests (for thumb gen) are filed in parallel, so you get full CPU usage on the server on all cores: i.e. during thumb gen of a single gallery ~4x the speed on a quadcore CPU. The new oC8 does only use a single core and does sequential thumb gen. Thank you :-)

**Comment by oparoz** [comment]
#### Assessment

On oC7, each thumb was requested individually, which allowed PHP to process them in parallel.
On oC8, we send multiple batches of thumbnails to process and PHP processes these batches in parallel.

#### Solution

By fixing the way batches are prepared and by lowering the amount of thumbnails asked in each request, it's possible to trigger parallel execution on the server, at the cost of using more HTTP requests

A folder with 25 pictures is currently making 2 requests and nothing is happening until the first request for 20 thumbnail is completed.
With the proposed solution, 5 requests would be made and rendering would be blocked in groups of 5.

For maximum benefit, this has to be implemented https://github.com/interfasys/galleryplus/issues/29

## <bountysource-plugin>

Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/8511653-ie11-no-function-no-multithreading-on-first-preview-generation-in-oc8?utm_campaign=plugin&utm_content=tracker%2F9328526&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F9328526&utm_medium=issues&utm_source=github).
</bountysource-plugin>

**Comment by oparoz** [comment]
From 2.0.6, thumbnail batches are smaller, which should trigger parallel processing.
