### ISSUE TITLE
You need to disable the Pictures app before being able to use the Gallery app (500)

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/gallery#190]
Finally got time to check out the awesomely named `ultimatedev` branch :D

Why can I not use both apps side-by-side @oparoz?

**Comment by oparoz** [comment]
Mainly because both will register actions on Files and we need this slideshow to be called to preview files.
Also, there are some class collisions in Javascript and CSS since the original goal was to stay as close as possible to the original in order to be able to easily replace it.

**Comment by HLFH** [comment]
Even if I removed Pictures app, I got this issue.

**Comment by oparoz** [comment]
@HLFH - How did you remove the app?

**Comment by HLFH** [comment]
Using rm -rf I guess. I solved this issue using:

``` sql
UPDATE oc_appconfig SET configvalue = 'no' WHERE appid = 'gallery' and configkey = 'enabled';
```

I believe you can close this issue.

**Comment by oparoz** [comment]
I thought you did :). By simply deleting the folder, you did not disable it in ownCloud. This can lead to some unwanted side effects with some apps.

I'm keeping this open until I add something to the FAQ, explaining why this is required.

**Comment by oparoz** [comment]
The official app won't check for the presence of other apps.

**Comment by akeusch** [comment]
First connect to your owncloud db. In my case:

# sqlite3 /var/www/html/owncloud/data/owncloud.db
    
sqlite> UPDATE oc_appconfig SET configvalue = 'no' WHERE appid = 'gallery' and configkey = 'enabled';

**Comment by akeusch** [comment]
First connect to your owncloud db: Im my case:

sqlite3 /var/www/html/owncloud/data/owncloud.db

sqlite> UPDATE oc_appconfig SET configvalue = 'no' WHERE appid = 'gallery' and configkey = 'enabled';

**Comment by oparoz** [comment]
Updated the Gallery+ wiki: https://github.com/interfasys/galleryplus/wiki/Migrating-from-Gallery-and-vice-versa
