### ISSUE TITLE
Save the sorting order for the current session

### ISSUE THREAD

**Issue by oparoz** [owncloud/gallery#198]
If someone plays with the sorting buttons, the last used setting should be remembered for the session.

In the future, when we have a sorting section or dropdown, it should be possible to let the user save the state across sessions.

@jancborchardt - Please confirm that this would work for you.

**Comment by jancborchardt** [comment]
Yup! Remembering the last used mode is always good. :)

**Comment by oparoz** [comment]
OK. Now that caching is enabled, it shouldn't be a problem to implement.

**Comment by oparoz** [comment]
Can be tested by using `ultimate8` on core `stable8`

@setnes @demattin

**Comment by oparoz** [comment]
Now available on `ultimatedev` for core `stable8.1`
