### ISSUE TITLE
Scrollbar visible in slideshow for private link shares.

### ISSUE THREAD

**Issue by setnes** [owncloud/gallery#199]
If I open a gallery folder using a private link share, the scrollbar is still visible when I start a slideshow.  If I go to the same folder when I'm logged in, the scrollbar is hidden when I start a slideshow.  This difference can only be seen if there are enough images to need a scrollbar in the gallery view.

I'm not sure if this is from a recent change, or if it's something I just never noticed before.

This does not happen if you navigate in from the file interface.

**Comment by oparoz** [comment]
Thanks for the report. I did notice that on mobile when sharing links, but I never took the time to bisect the problem.
It's probably "just" a problem with the CSS. I did update the public.php template a couple of months back to keep it in line with files_sharing.

**Comment by oparoz** [comment]
Seems to be a Chrome only bug...

**Comment by oparoz** [comment]
Unlesss someone has a better idea, I'm going to automatically disable/enable the scrollbars when launching/quitting the slideshow.

I can "fix" body-public in the Gallery app by adding `overflow:hidden`, but I can't do the same in the core app, so the above solution is the best I could think of.

**Comment by oparoz** [comment]
@setnes - Let me know if it's fixed for you in master.

**Comment by setnes** [comment]
I am testing using ultimatedev and this scrollbar issue seems to be gone.
