### ISSUE TITLE
Exit the slideshow with one click when in fullscreen mode

### ISSUE THREAD

**Issue by oparoz** [owncloud/gallery#200]
Escape quits the fullscreen mode, when pressing the close button should leave the slideshow.

Let's see if we can find a solution for that.

**Comment by oparoz** [comment]
Fix is in https://github.com/owncloud/galleryplus/pull/207

**Comment by oparoz** [comment]
Can be tested by using `ultimate8` on core `stable8`

@setnes @demattin

**Comment by oparoz** [comment]
Now available on `ultimatedev` for core `stable8.1`

**Comment by setnes** [comment]
Sorry.  I've been very busy and haven't been able to look at any of this until now.  

I'm often confused on how to handle these requests to test things... especially when they are sitting in pull requests that I cannot clone.  Now that this is in a real branch I think I can easily use "git clone" to put this in my test environment, right?   I finally have a test server setup with OwnCloud 8.1.  So...

`git clone -b ultimatedev https://github.com/owncloud/galleryplus.git`

That got me the ultimatedev branch.  I'm happy to say that backing out of slideshows in fullscreen mode did not require a double-tap.  I used the real fullscreen mode with the "f" hotkey and also the browser's fullscreen "F11".  (F11 really bypasses the coded fullscreen mode, but thought I'd test it anyway.)

I also tried the browser's back button both on a desktop as well as my phone.  It is also working.

I am noticing that switching back to the file view is not working correctly.  Trying to get into the slideshow from the file view is also not working.  Perhaps these are issues related to other code changes inside the ultimatedev branch?  They don't seem related to exiting the slideshow.  ???

**Comment by oparoz** [comment]
Thanks for testing!

The instructions to create branches from PR are at the bottom of the PR discussion, where it say it can be merged automatically. I still find it a hassle to work with and we're missing other PRs which may be useful, but haven't been reviewed yet, so I created the ultimate branches.

I've just done this:
1. Go to a folder in Files
2. Switch to Gallery
3. Click on a thumbnail
4. Back
5. Back
6. Click on a file

Everything worked as expected.

Could you try with a different folder? Also make sure to always either clear your cache or use ctrl+F5 after a branch switch or a git pull.

**Comment by setnes** [comment]
> The instructions to create branches from PR are at the bottom of the PR discussion, where it say it can be merged automatically. 

I think this requires write access to the repository.  I shouldn't need write access to do simple code tests.  The best i can figure out on those is to generate a patch of the pull request and then figure out how to apply the patch to a local copy.  It is much easier for someone else to test code that is already merged into a branch (like this is).  Branches can be cloned locally in seconds.

**Comment by oparoz** [comment]
PRs are from branches.
You don't need to use all the commands. This should do

```
git fetch origin
git checkout -b the-branch origin/the-branch
```

And you use the username if the branch was created in a fork, like when I need to test your PRs.
