### ISSUE TITLE
CSP prevents native SVGs from being displayed in the slideshow on public pages of the Files app

### ISSUE THREAD

**Issue by oparoz** [owncloud/gallery#202]
### Steps to reproduce
1. Use the dev branch on a 8.1 instance
2. Upload a SVG in a folder
3. Add a gallery.cnf file in the folder containing

```

---
# Gallery config file
features:
  native_svg: yes
```
1. Create a public share
2. Open the share in a new tab
### Expected result

The SVG should show
### Actual result

We get an error and the console shows a Content Security Policy error

Since we don't control that app, but only send images to the slideshow, is there something we can do @LukasReschke? Is it a forgotten policy in the public controller of files_sharing?

**Comment by LukasReschke** [comment]
You would get huge plus points if master would actually be installable on master :speak_no_evil:

**Comment by LukasReschke** [comment]
Also on master: 
![2015-07-03_11-13-11](https://cloud.githubusercontent.com/assets/878997/8496311/78813202-2174-11e5-9ab4-59dd1d335948.png)

**Comment by oparoz** [comment]
That's because you need to install stable8.1 on core stable8.1.

There is a discussion on branch naming here: https://github.com/owncloud/galleryplus/pull/139

Core devs want to use master to match the name of the branch in core, but casual contributors are usually using the latest stable and I'd like to be able to get more contributors.

**Comment by LukasReschke** [comment]
Well for me it makes mostly sense to use master of core for development purposes as well which is released in a 3 month schedule. A new major app version all 3 months with new features seems fair enough to me :speak_no_evil:

**Comment by LukasReschke** [comment]
Cool. Also dev does not run on master. :speak_no_evil:

**Comment by LukasReschke** [comment]
> We get an error and the console shows a Content Security Policy error

Please post the error message. I only see unrelated error messages with regard to the font handling. In fact when accessing the public share `files.public` does _not_ contain the SVG file while in the private interface it has.

**Comment by oparoz** [comment]
> Cool. Also dev does not run on master.

Not sure if you know, but you need to disable Pictures and do a ctrl+f5 to clear its files.

Anyway, here is the error message
`Content Security Policy: The page's settings blocked the loading of a resource at data:image/svg+xml;base64,PD9...zdmc+DQo= ("img-src https://myowncloud-domain.com").`

**Comment by LukasReschke** [comment]
Which browser? Works just fine here :speak_no_evil:

**Comment by oparoz** [comment]
Both Firefox and Chrome

Chrome has a different message though:
`Refused to load the image 'data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiI…IjZmZmZmZmIj5XaW5kb3dzLCBPUyBYLCBMaW51eDwvdHNwYW4+PC90ZXh0Pg0KPC9zdmc+DQo=' because it violates the following Content Security Policy directive: "img-src 'self'".`

That's the method which loads the SVG:
https://github.com/owncloud/galleryplus/blob/master/js/slideshow.js#L215-L228

**Comment by oparoz** [comment]
Looks like the policy on the public side is much more restrictive and missing `data:` for `img-src`
`default-src 'none';script-src 'self' 'unsafe-eval';style-src 'self' 'unsafe-inline';img-src 'self';font-src 'self';connect-src 'self';media-src 'self'`
vs
`default-src 'self'; script-src 'self' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; frame-src *; img-src *; font-src 'self' data:; media-src *; connect-src *`

So, is there something we can do? I imagine not as otherwise apps could break havoc.

**Comment by oparoz** [comment]
I'm going to load SVGs directly in the img tag since this is supported by modern browsers. Older ones (<=IE9) will get an error message.

**Comment by LukasReschke** [comment]
Well. You can on 8.1 adjust the CSP policy.

On my mobile atm as in holiday, but check my website where I highlight this in the 8.1 security changes.

**Comment by oparoz** [comment]
I can control the CSP of previews per example, but I can't modify the one of the Files app, can I?

I'll wait for you to get back from your hols :)
