### ISSUE TITLE
Can't update on oc8

### ISSUE THREAD

**Issue by v1r0x** [owncloud/gallery#203]
I tried to update the app on latest oc8 (8.0.4.2), but I got an error that my version of oc is not compatible (german: Die Anwendung konnte nicht installiert werden, weil Sie nicht mit dieser Version von ownCloud kompatibel ist.).
In the appinfo/info.xml is 8.0.4 set as min-version. Maybe this is related to the .2 suffix?

**Comment by oparoz** [comment]
Hello, thanks for the report.
I've noticed the same thing when wanting to update my own instances and unfortunately there is nothing I can do. It's a problem with the app store. See here for the details: https://github.com/owncloud/core/issues/17388

The current solution is to manually update the app or upgrade ownCloud to 8.1

### Do not forget to clear your assets folder if you enable asset pipe-lining.

**Comment by godfuture** [comment]
I have the same issue for manual update to version 12 (https://github.com/owncloud/galleryplus/releases/download/v12-stable8/galleryplus-12-stable8.zip)!

I did the manual update, but when clicking on activate (I deactived it before replace) the same error message appears: "Die Anwendung konnte nicht installiert werden, weil Sie nicht mit dieser Version von ownCloud kompatibel ist.".

Is there a workaround for OCS 8.0.4?

**Comment by oparoz** [comment]
I think what happened is that you've updated the wrong app.

If you extract the app in your apps folder, it will create an entry in the "Not enabled" section and that's the one you need to activate, not the one in the multimedia section.

Let me know if that's correct. If not, I'll try to come up with a step-by-step procedure. I just hope it doesn't involve cleaning up database tables...

**Comment by godfuture** [comment]
You are right, the app in "not-activated" section did work for me.
I had more than one attempt to extract the app files to owncloud app dir. As I did not see the app in "not-activated" section first time, I have tried the targz archive, but forget the recheck the "n-a" secti
ction.

Thx!

**Comment by oparoz** [comment]
Nice :)

It takes several refreshes and logout/login sometimes before being able to see the app due to the way caching works in the app store.

**Comment by oparoz** [comment]
Currently, it seems people don't see the update button any more. That's a first step towards preventing confusion and hopefully everything will be sorted out with 8.0.5 for people who are waiting for a production ready 8.1.

**Comment by oparoz** [comment]
Works on 8.0.5. Added a note in the app store.
