### ISSUE TITLE
Real Fullscreen

### ISSUE THREAD

**Issue by stefan-niedermann** [owncloud/gallery#210]
Actual behaviour: Browser-Control- and URL-Bars are still visible
Expected behaviour:
The Image uses the javascript native fullscreen api instead of displaying the content only in the rendering-pane of the browser.
example: gallery at golem.de
http://www.golem.de/news/archos-70-xenon-7-zoll-tablet-mit-umts-fuer-140-euro-1312-103517.html
// Edit: changed example article because in the original was no gallery ;-)

```
var element = document.getElementById("#my-container");

if (element.requestFullScreen) {
element.requestFullScreen();
} else if (element.mozRequestFullScreen) {
element.mozRequestFullScreen();
} else if (element.webkitRequestFullScreen) {
element.webkitRequestFullScreen();
}
```

**Comment by oparoz** [comment]
Already implemented in galleryplus, so will be there in 8.2.

**Comment by jancborchardt** [comment]
@oparoz great stuff – then we don’t need to do it for Gallery.

**Comment by jancborchardt** [comment]
@stefan-niedermann hope that works for you. :) Backporting that stuff to 8.1 is not really possible.

**Comment by oparoz** [comment]
> Backporting that stuff to 8.1 is not really possible.

Indeed, but Gallery(+) offers the feature on both 8 and 8.1 in case someone needs it now.

**Comment by stefan-niedermann** [comment]
can anyone explain me the concept about these "plus"-apps??? i really do not understand why there are two versions of calendar, contacts, gallery,....
are the plus apps private projects or official owncloud projects? are plus apps the "future"? lika a beta version for the normal apps?

****confused****

**Comment by LukasReschke** [comment]
Complete independent rewrites by different authors. GalleryPlus will become Gallery soon though and replace the existing code.
