### ISSUE TITLE
Add possibility to delete,move picture

### ISSUE THREAD

**Issue by thenamelessthing** [owncloud/gallery#211]
Can you add the possibility to delete, move, create folders. It's more usefull to see picture in the same time we want to "manage" them..

**Comment by oparoz** [comment]
My thoughts:
- It belongs to the future thumbnail view of the Files app (https://github.com/owncloud/core/issues/17357), not really to the Gallery app
- Because we have this seamless wall of pictures. It's difficult to make adding or removing elements work smoothly as this requires re-building the entire wall

Let's see what other people think about this.

**Comment by Tramour** [comment]
I'd love to have the possibility to delete pictures within the app. The files app is of no use because I can't identify the pictures (too small). A multi select possibility to download or delete pictures would also be handy ;-)

**Comment by oparoz** [comment]
Thanks for the feedback.

Do any of you have any experience with other online tools? Do they offer these files functionalities in presentation mode or do they switch to files mode first?

**Comment by Tramour** [comment]
Hm. Unfortunately not. But I'd rather see it a little bit like Android's gallery app where I can actually identifiy the pictures and edit/delete/download them with multiselect capabilities.

**Comment by oparoz** [comment]
I was just thinking of something like Picasa. It's a specialised tool, not a file system browser and it offers basic file management features.
The way forward is probably to have a 3rd view.
Management - Photowall - Slideshow

**Comment by Tramour** [comment]
Sounds good to me!

**Comment by oparoz** [comment]
@thenamelessthing _Move_ is coming soon as drag and drop management will be in 9.1. For _delete_, we need to agree on the design. I was thinking of having a large delete area, bottom right.

**Comment by thenamelessthing** [comment]
@oparoz , sound good to me!  I'm still waiting this! ;-) If we can "move", "rename", "delete" picture in thumbnails view it will be wonderfull!

**Comment by oparoz** [comment]
Rename is not going to be easy... Maybe a pencil icon at the end of the label.

**Comment by thenamelessthing** [comment]
I'ts better than nothing!

**Comment by oparoz** [comment]
A better idea would be to try and implement the little menu which is available on each row in the Files app. Unfortunately, I think it's once again Files specific, but if it's small, it could be imported.

See #39 for details

**Comment by oparoz** [comment]
Since move has been developed and the rest is in #39, I'm closing this.
