### ISSUE TITLE
Should we highlight the thumbnail of the last slide in the slideshow

### ISSUE THREAD

**Issue by oparoz** [owncloud/gallery#212]
When you click on an image or album, it becomes semi-transparent to indicate that it was clicked on.
I think it's fine as a visual feedback, but when pressing the back button, the element is still "selected".

The CSS documentation says that it's for keyboard users, but I can't navigate through the pictures using the keyboard, so it seems useless to keep this class as-is.
Does it really help to have the last element we clicked on highlighted when we quit the slideshow? It's probably not the last slide we saw.

I vote to disable that focus when launching the slideshow.

@jancborchardt @setnes @demattin @jospoortvliet

**Comment by deMattin** [comment]
First seeing this irritated me a bit and I didn't understand, why a picture is marked "selected" sometimes, but it didn't really bother me.
From my point of view it's not needed like it works now and it would be better to remove it.

I see this selection is gone, when walking some pictures in slideshow. It does not show/mark the first or the last seen picture in slideshow.
So picture stays marked only if seeing this single picture clicked on in slideshow and then using browser back. So this way it's not really useful (for me).
If it would mark the last seen picture in slideshow, it would be useful, I think ... ;)

**Comment by oparoz** [comment]
Bug fixed here:
https://github.com/owncloud/galleryplus/commit/b7e1a33e96281c459f8e2990185817ff645cc74c

And if it's deemed useful or necessary to highlight the last image shown in the Slideshow, then we can implement something later.

**Comment by jancborchardt** [comment]
I’d also say to remove that. It was very confusing to me always, thought it was a CSS or browser bug.

**Comment by oparoz** [comment]
OK. Version 13 contains the fix and people can always open a new ticket if they need to track the last open slide.

**Comment by jancborchardt** [comment]
Great!
