### ISSUE TITLE
v13.0.0 - pictures on remote shares are not shown

### ISSUE THREAD

**Issue by j-ed** [owncloud/gallery#215]
## Expected behavior

The galleryplus app should also show pictures on remote shares, like WebDAV shares etc.
## Current behavior

Only locally stored pictures are shown in the galleryplus app. Several log messages are written but nothing seems to point to the root cause of the problem. I wonder if the app supports showing pictures on remote shares, like WebDAV shares, at all?

```
...,"app":"core","message":"DB prepare : SELECT `appid`, `configvalue` FROM `oc_appconfig` WHERE `configkey` = 'installed_version'","level":0,"time":"2015-07-17 18:31:34+02:00","method":"GET","url":"\/owncloud\/index.php\/apps\/galleryplus\/"}
...,"app":"core","message":"DB execute with arguments : array ( )","level":0,"time":"2015-07-17 18:31:34+02:00","method":"GET","url":"\/owncloud\/index.php\/apps\/galleryplus\/"}
...,"app":"core","message":"DB prepare : SELECT `gid` FROM `oc_groups` WHERE `gid` = ?","level":0,"time":"2015-07-17 18:31:34+02:00","method":"GET","url":"\/owncloud\/index.php\/apps\/galleryplus\/"}
...,"app":"core","message":"DB execute with arguments : array (   0 => 'admin', )","level":0,"time":"2015-07-17 18:31:34+02:00","method":"GET","url":"\/owncloud\/index.php\/apps\/galleryplus\/"}
...,"app":"core","message":"DB prepare : SELECT `uid`, `displayname` FROM `oc_users` WHERE LOWER(`uid`) = LOWER(?)","level":0,"time":"2015-07-17 18:31:34+02:00","method":"GET","url":"\/owncloud\/index.php\/apps\/galleryplus\/"}
....,"app":"core","message":"DB execute with arguments : array (   0 => 'juergen', )","level":0,"time":"2015-07-17 18:31:34+02:00","method":"GET","url":"\/owncloud\/index.php\/apps\/galleryplus\/"}
....,"app":"core","message":"DB prepare : SELECT `uid` FROM `oc_group_user` WHERE `gid` = ? AND `uid` = ?","level":0,"time":"2015-07-17 18:31:34+02:00","method":"GET","url":"\/owncloud\/index.php\/apps\/galleryplus\/"}
...,"app":"core","message":"DB execute with arguments : array (   0 => 'admin',   1 => 'juergen', )","level":0,"time":"2015-07-17 18:31:34+02:00","method":"GET","url":"\/owncloud\/index.php\/apps\/galleryplus\/"}
...,"app":"core","message":"DB prepare : SELECT `id` FROM `oc_jobs` WHERE `class` = ? AND `argument` = ?","level":0,"time":"2015-07-17 18:31:34+02:00","method":"GET","url":"\/owncloud\/index.php\/apps\/galleryplus\/"}
...,"app":"core","message":"DB prepare : SELECT `id` FROM `oc_jobs` WHERE `class` = ? AND `argument` = ?","level":0,"time":"2015-07-17 18:31:34+02:00","method":"GET","url":"\/owncloud\/index.php\/apps\/galleryplus\/"}
...,"app":"core","message":"DB prepare : SELECT `id` FROM `oc_jobs` WHERE `class` = ? AND `argument` = ?","level":0,"time":"2015-07-17 18:31:34+02:00","method":"GET","url":"\/owncloud\/index.php\/apps\/galleryplus\/"}
...,"app":"core","message":"DB prepare : SELECT `id`, `displayname`, `description`, `ctag` AS `lastmodified`, `userid` AS `owner`, `uri` FROM `oc_contacts_addressbooks` WHERE `userid` = ? ORDER BY `displayname`","level":0,"time":"2015-07-17 18:31:34+02:00","method":"GET","url":"\/owncloud\/index.php\/apps\/galleryplus\/"}
...,"app":"core","message":"DB execute with arguments : array (   0 => 'juergen', )","level":0,"time":"2015-07-17 18:31:34+02:00","method":"GET","url":"\/owncloud\/index.php\/apps\/galleryplus\/"}
...,"app":"core","message":"DB prepare : SELECT `gid` FROM `oc_group_user` WHERE `uid` = ?","level":0,"time":"2015-07-17 18:31:34+02:00","method":"GET","url":"\/owncloud\/index.php\/apps\/galleryplus\/"}
...,"app":"core","message":"DB execute with arguments : array (   0 => 'juergen', )","level":0,"time":"2015-07-17 18:31:34+02:00","method":"GET","url":"\/owncloud\/index.php\/apps\/galleryplus\/"}
...,"app":"core","message":"DB prepare : SELECT * FROM `oc_share`  WHERE `item_type` = ? AND ((`share_type` in (?, ?) AND `share_with` = ?)  OR (`share_type` = ? AND `share_with` IN (?,?,?)) ) AND `uid_owner` != ? ORDER BY `oc_share`.`id` ASC","level":0,"time":"2015-07-17 18:31:34+02:00","method":"GET","url":"\/owncloud\/index.php\/apps\/galleryplus\/"}
...,"app":"core","message":"DB execute with arguments : array (   0 => 'addressbook',   1 => 0,   2 => 2,   3 => 'juergen',   4 => 1,   5 => 'Eltern',   6 => 'Familie',   7 => 'admin',   8 => 'juergen', )","level":0,"time":"2015-07-17 18:31:34+02:00","method":"GET","url":"\/owncloud\/index.php\/apps\/galleryplus\/"}
...,"app":"core","message":"DB prepare : SELECT `id` FROM `oc_jobs` WHERE `class` = ? AND `argument` = ?","level":0,"time":"2015-07-17 18:31:34+02:00","method":"GET","url":"\/owncloud\/index.php\/apps\/galleryplus\/"}
...,"app":"core","message":"DB prepare : SELECT `numeric_id` FROM `oc_storages` WHERE `id` = ?","level":0,"time":"2015-07-17 18:31:34+02:00","method":"GET","url":"\/owncloud\/index.php\/apps\/galleryplus\/"}
...,"app":"core","message":"DB execute with arguments : array (   0 => 'local::\/var\/owncloud\/data\/juergen\/', )","level":0,"time":"2015-07-17 18:31:34+02:00","method":"GET","url":"\/owncloud\/index.php\/apps\/galleryplus\/"}
...,"app":"core","message":"DB prepare : SELECT `gid` FROM `oc_group_user` WHERE `uid` =?","level":0,"time":"2015-07-17 18:31:34+02:00","method":"GET","url":"\/owncloud\/index.php\/apps\/galleryplus\/"}
...,"app":"core","message":"DB execute with arguments : array (   0 => 'juergen', )","level":0,"time":"2015-07-17 18:31:34+02:00","method":"GET","url":"\/owncloud\/index.php\/apps\/galleryplus\/"}
...,"app":"core","message":"DB prepare : SELECT `oc_share`.`id`, `item_type`, `item_source`, `item_target`,`oc_share`.`parent`, `share_type`, `share_with`, `uid_owner`,`file_source`, `path`, `file_target`, `oc_share`.`permissions`,`stime`, `expiration`, `token`, `storage`, `mail_send`,`oc_storages`.`id` AS `storage_id` FROM `oc_share` INNER JOIN `oc_filecache` ON `file_source` = `oc_filecache`.`fileid`  AND `file_target` IS NOT NULL INNER JOIN `oc_storages` ON `numeric_id` = `oc_filecache`.`storage`  AND ((`share_type` in (?, ?) AND `share_with` = ?)  OR (`share_type` = ? AND `share_with` IN (?,?,?)) ) AND `uid_owner` != ? ORDER BY `oc_share`.`id` ASC","level":0,"time":"2015-07-17 18:31:34+02:00","method":"GET","url":"\/owncloud\/index.php\/apps\/galleryplus\/"}
```
## Steps to reproduce
1. Open the galleryplus app
2. check if pictures on remote shares are shown.
#### Server Configuration

OS: Linux 3.2.67
Web server: Apache2 2.4.12
Database: MySQL 5.1.73
PHP version: 5.4.42
ownCloud version: 8.0.5
GalleryPlus app version: 13.0.0
#### Client Configuration

Operating system: Windows 7
Firefox version: 39.0

**Comment by oparoz** [comment]
You need to specifically enable server-to-server sharing by placing a configuration file in the root directory of your ownCloud.

https://github.com/owncloud/galleryplus/blob/master/documentation/Album%20configuration.md#load-images-from-external-clouds

**Comment by jospoortvliet** [comment]
@oparoz seems like an option to add to the configuration of external storage, like the 'enable previews' and 'enable encryption' options we added in 8.1...

**Comment by j-ed** [comment]
@oparoz The description "`load images from external clouds`" is a little bit misleading, therefore I wouldn't have expected that this could be used to scan normal remote shares etc. Additionally I'm missing important other information, like:

Where need the configuration file to be saved, in the ownCloud root directory, in the GalleryPlus root directory?
What file name is the app looking for, `gallery.cnf`, `readme.txt`, `readme.md`, `galleryreadme.txt`, etc.?

**Comment by oparoz** [comment]
@jospoortvliet - Yes, if core could add those settings for S2S, that would be great as I wouldn't have to try to figure out if the folder is located on another cloud.

@j-ed The problem is that an "external share" can be different things in ownCloud. An FTP or S3 share uses a totally different mechanism than a share coming from another ownCloud and has different settings.

You're right, the file name seems to be missing from the documentation. You have to name it `gallery.cnf`.
Regarding the location. The documentation mention the root folder of your ownCloud. There is no galleryplus root directory. Let me know if you have better ways of describing where to put the file.

**Comment by j-ed** [comment]
@oparoz I did some research on my own before asking the question and in the file `service/configservice.php` the function `getFeaturesList` used a variable `$rootFolder` which pointed to `galleryplus/config` - that led to a 100% confusion ;-)

Nevertheless I placed a file `gallery.cnf` in the ownCloud root directory but it still seems not to work as expected. Only a picture in the users local storage is displayed, all sub-directories are not shown. Interestingly I can e.g. browse the folder `Bilder/Personen` using the Files app but as soon as I try to access the folder with the GalleryPlus app the message **No pictures found! If you upload pictures in the files app,they will be displayed here.** is displayed after a while and the following message is logged:

```
...,"app":"no app in context","message":"Album is private or unavailable (403)","level":3,"time":"2015-07-19 12:04:44+02:00","method":"GET","url":"\/owncloud\/index.php\/apps\/galleryplus\/files?location=Bilder%252FPersonen&mediatypes=image%2Fpng%3Bimage%2Fjpeg%3Bimage%2Fgif%3Bimage%2Fx-xbitmap%3Bimage%2Fbmp%3Bimage%2Fx-dcraw&features=&etag"}
```

**Comment by oparoz** [comment]
I've just tested with my setup and I was able to see all pictures

ServerA: oc8.0
ServerB: oc8.1

In serverB, I can see serverA's shared folder and all its sub-folders.

I can see from the log you've posted that the the external_shares feature has not been enabled, so maybe the config file can't be read or parsed.

Your URL `features=`
My URL `features=toggle_background%2Cexternal_shares%2Cnative_svg%2Cbpg`

**Comment by j-ed** [comment]
Good point, let's try to find the root cause of that problem.
If I understand your code correctly, the configuration should be read in function `getFeaturesList()` in `service/configservice.php`, right?
If so, it looks like that the _$rootFolder_ variable is not set in that function.
The variable should be set using the function `getVirtualRootFolder()` in `environment/environment.php`, right?

**Comment by oparoz** [comment]
That's correct, the environment object is sending back the root folder, which in your case is the user folder (/data/userB).

In the browser debug mode, look for the response you get from the URL which goes to the `config` endpoint. The response should contain an error message if the file can't be parsed.

**Comment by j-ed** [comment]
The URL `https://<my-server>/owncloud/index.php/apps/galleryplus/config/` is automatically redirected to `https://<my-server>/owncloud/index.php/apps/files/`, the files root directory of the logged-in user. An error message seems not to be logged neither in the owncloud log nor in the apache2 log files.
Should that be the ownCloud root you're speaking about? I though you meant the `../htdocs/owncloud`directory?!
Would you be available in the IRC the next time? It is difficult to analyze the behavior of the app in a timely manner if the communication latency is long and the given answers are giving to much room for interpretation.
As I wrote before, it seems that the function `getVirtualRootFolder()` is not returning a valid path so that the configuration file couldn't be found. I wonder why that happens and how it could be fixed?!

**Comment by oparoz** [comment]
If that URL gets redirected it usually means a core method is creating a redirection when encountering an error. These methods don't log anything, but the response should contain an HTML template with the error message.

The only thing which seem different between your setup and mine is that your ownCloud is in a sub-folder.

Your root would be /htdocs/owncloud/data/userB. That's the root folder you get when opening the Files app. That's where the config file needs to reside.

I'm on IRC now.

**Comment by j-ed** [comment]
So, I'm on IRC now too. The ownCloud web root on my server is `/var/www/htdocs/owncloud` and my data directory is set to `/var/owncloud/data`. The users root is `/var/owncloud/data/<user>` and the Files app base folder is `/var/owncloud/data/<user>/files`. Independently in which of these directories the _gallery.cnf_ file is saved, its content is not read nor recognized.

**Comment by oparoz** [comment]
You're correct, it's `/var/owncloud/data/<user>/files` . I need to add this to the documentation as well, but I didn't expect admins to add that file directly to the filesystem since it's a user config file. The easiest method is to use the Files app or the sync client, if the user sync the whole cloud.

**Comment by j-ed** [comment]
But, what happens if an administrator wants to get default parameters set for multiple users? At the moment each user would have to create a _gallery.cnf_ for each user. Wouldn't it be good to improve this function so, that at first a **general** configuration is read, which has been defined by the administrator and then, if it exists, load a **user specific** file where a user can modify the sort order etc.?

**Comment by oparoz** [comment]
I think an app's configuration is quite personal. If an admin enables external storage, some users will suffer from slow loading speed and might not know that they need to disable external storage in order to be able to enjoy their local content. If it's disabled then the user will know what he gets into when enabling it.

Probably something to talk about at the conference as a global level might make sense for some settings.

**Comment by oparoz** [comment]
### TODO
- [x] Add config file name
- [x] Add path to config file in the file system
- [x] Try to improve the definition of external_share
