### ISSUE TITLE
Don't show hidden files

### ISSUE THREAD

**Issue by oparoz** [owncloud/gallery#216]
We should ignore files which are hidden on Windows, Linux and OSX
### Files to blacklist
- Files starting with a dot

Please list any filename pattern which should be ignored

**Comment by j-ed** [comment]
### Files and directories on a Linux system
- Files **and directories** starting with a dot

### Files and directories to blacklist on a Synology NAS
- Files and directories starting with a dot
- `/@eaDir`
- `/@tmp`

**Comment by oparoz** [comment]
If every manufacturer adds its own patterns, then I'll probably need to add custom blacklists.

**Comment by oparoz** [comment]
This will be dealt with in `core` in 9.0

**Comment by derkostka** [comment]
Now, even if files are hidden in core, they show up in the gallery. Can we somehow link the setting to gallery ?

**Comment by oparoz** [comment]
How are you hiding files in core?

**Comment by derkostka** [comment]
I think this was introduced with OC9. The last change was some days ago here:

https://github.com/nextcloud/server/pull/965
and
https://github.com/owncloud/core/pull/25856

**Comment by oparoz** [comment]
That's for Nextcloud 11, so won't be available until later this year.
