### ISSUE TITLE
unable to enable galleryplus "ownCloud with a version lower than 8.0.9 is required"

### ISSUE THREAD

**Issue by jean-clovis** [owncloud/gallery#219]
Hi, 
just installed a fresh OC 8.1
disabled the historical galler app
git clone in my apps folder 
went to applications in OC 
can't enable V13.0.0 with red message shown "ownCloud with a version lower than 8.0.9 is required"

**Comment by jean-clovis** [comment]
![lower than 8 0 9](https://cloud.githubusercontent.com/assets/6710472/8773227/ef615882-2ed2-11e5-911d-c5a8b7e4b733.png)

**Comment by oparoz** [comment]
Hello,
You've probably cloned master which was designed for the production channel.
Switch to the dev branch and you should be good to go.

That branch won't get any updates though as we're in the process of moving the app to the official repository, so you won't miss anything if you simply use the app which is in the multimedia section of your ownCloud (after having deleted your git clone).

**Comment by jean-clovis** [comment]
that's it ! thanks ! :) 
was using stable8 version as in readme
git clone -b stable8 https://github.com/owncloud/galleryplus.git
just removed folder then : 
git clone -b dev https://github.com/owncloud/galleryplus.git
and working flawessly !
