### ISSUE TITLE
Generate thumbnails on demand

### ISSUE THREAD

**Issue by oparoz** [owncloud/gallery#22]
Background thumbnail generation might be coming in the future. We're tracking it here: https://github.com/owncloud/gallery/issues/18

In the meantime or in addition, we could offer a way to generate these thumbnails on demand in order to make the app usable from the first load.
##

**Comment by oparoz** [comment]
Closing as this needs to be dealt with in core so that we don't duplicate the effort.
Also, it won't work when encryption is enabled.

**Comment by deMattin** [comment]
:sad:

**Comment by oparoz** [comment]
I know...but it shouldn't take more than 6 months since the basic mechanism is in place in core. It's just that previews is not a priority.

It can also be a separate app which just creates a cron which goes through the whole instance, looking for missing thumbnails.

I'm sure you could even create it. It would make 2 calls: isCached() and createPreview();

**Comment by oparoz** [comment]
Solution is available as an occ command: https://github.com/owncloud/gallery/pull/387

Only available to admins, because this wouldn't work as a user callable command since it would probably time-out before the task could be completed.

**Comment by oparoz** [comment]
![smb_stats](https://cloud.githubusercontent.com/assets/323220/10209326/7bb1f568-67da-11e5-9c4f-8b8aedc6e765.png)

**Comment by oparoz** [comment]
This issue was moved to nextcloud/gallery#15

**Comment by ladiko** [comment]
as it doesnt work with owncloud 9.1, would like to point to my comment [here](https://github.com/owncloud/core/issues/11685#issuecomment-278734183), which might be helpful for one or the other.
