### ISSUE TITLE
403 error on samba share

### ISSUE THREAD

**Issue by Spekkie** [owncloud/gallery#220]
I know samba shares aren't officially supported yet, however I have this strange problem I can't seem to figure out.
I have a locally mounted samba share with all my pictures. When navigating to this share within owncloud I have full permissions. However when clicking on the Gallery button (next to the new button) to open this folder in the gallery plus app I get a 403 response, even though the share is mounted with full read/write permissions...
I don't have these issues with the "regular" image app, so the gallery app is apparently accessing the share differently?

**URL:**
https://mna.tweak.nl/owncloud/index.php/apps/galleryplus/files?location=Foto%2527s%252FAfdansen%252FAfdansen%2520(brons)&mediatypes=image%2Fpng%3Bimage%2Fjpeg%3Bimage%2Fgif%3Bimage%2Fx-xbitmap%3Bimage%2Fbmp&features=inherit&etag

**Request Header:**
Host: mna.tweak.nl
User-Agent: Mozilla/5.0 (Windows NT 6.3; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0
Accept: application/json, text/javascript, _/_; q=0.01
Accept-Language: nl,en-US;q=0.7,en;q=0.3
Accept-Encoding: gzip, deflate
OCS-APIREQUEST: true
X-Requested-With: XMLHttpRequest
Referer: https://mna.tweak.nl/owncloud/index.php/apps/galleryplus/
Cookie: ocwitfj3ni6j=rd9n4r3bobq0oieorqcu09sc50; __utma=160442040.752442790.1409911816.1418389948.1418393344.5; _ga=GA1.2.752442790.1409911816; player-5370656b6b6965=10
Connection: keep-alive

**Response Header:**
Cache-Control: no-cache, must-revalidate
Connection: Keep-Alive
Content-Length: 61
Content-Type: application/json; charset=utf-8
Date: Mon, 20 Jul 2015 15:45:49 GMT
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Keep-Alive: timeout=5, max=86
Pragma: no-cache
Server: Apache/2.4.7 (Ubuntu)
X-Content-Type-Options: nosniff
X-Frame-Options: Sameorigin
X-Powered-By: PHP/5.5.9-1ubuntu4.11
X-Robots-Tag: none
X-XSS-Protection: 1; mode=block
content-security-policy: default-src 'none';script-src 'self' 'unsafe-eval';style-src 'self' 'unsafe-inline';img-src 'self';font-src 'self';connect-src 'self';media-src 'self'
- data/owncloud.log: nothing shows in the logs...
- ownCloud version: 8.1
- App version: 13
- Browser version: Firefox 38
- PHP version: 5.5.9-1ubuntu4.11

**Comment by oparoz** [comment]
Thanks for the report.
This is a duplicate of a problem I've recently discovered
https://github.com/owncloud/galleryplus/issues/218
I'm going to rename the issue to be less focused on one type of shares

I'll make sure to notify you when I can come up with a fix.

The reason it behaves differently than Pictures is that we're respecting the new external shares settings which lets users decide if previews should be shown, but it's apparently not working.
