### ISSUE TITLE
Wrong app name in Error message about enable galleryplus

### ISSUE THREAD

**Issue by davitol** [owncloud/gallery#227]
The error message shown when Gallery and Gallery plus are active at the same time is the following:
![errorgallery](https://cloud.githubusercontent.com/assets/10596560/8869549/4e93bd62-31e5-11e5-9fe2-8e030739bee4.png)

... you need to disable the pictures app...

but it must be said ...you need not disable gallery app...

Note: Maybe it would be necessary to add in the description of the app that it is needed not disable the gallery app

**Comment by oparoz** [comment]
Pictures is what admins see in the list of apps
![pictures_app_name](https://cloud.githubusercontent.com/assets/323220/8889677/a69e9590-32e4-11e5-9f30-26fe23997b35.png)
It's just unfortunate that both the appid and the name of the folder are gallery.

But that problem will go away once `owncloud/galleryplus` is renamed to `owncloud/gallery` (as far as this repo is concerned)

**Comment by oparoz** [comment]
Closing this now since this app is now named Gallery.
Gallery+ will refer to this one as "official Gallery"
