### ISSUE TITLE
Steps required to implement IE8 support

### ISSUE THREAD

**Issue by oparoz** [owncloud/gallery#228]
I've had a look at the incompatibilities between the technologies Gallery is using and IE8's capabilities and it's possible to have IE8 compatibility if your enterprise clients need it. It will increase the technical debt and make the code harder to understand, so it's imperative to clearly mark all these changes so that they can be removed in 2017.
### Actions
- [ ] Design alternative way to fetch thumbnails since we can't use EventSource
- [x] Design alternative way to show images in the slideshow
- [ ] Find alternatives for any methods or practices which are not supported (browser throws unknown errors)
- [x] Discard SVG files in the photowall. Optional since Pictures just breaks if the users tries to load a SVG
- [x] Discard SVG files in the slideshow. Optional since Pictures will show a spinning wheel
- [ ] Fix ugly icons
- [ ] Disable some accessibility features in the slideshow. Optional since Pictures has the same problem
- [ ] Test on XP and Win7

@jancborchardt @karlitschek

**Comment by karlitschek** [comment]
@oparoz Thanks a lot for the investigation
@DeepDiver1975 @MTRichards @cmonteroluque FYI

**Comment by oparoz** [comment]
The slideshow now supports IE8 in order to not create a regression.

**Comment by MTRichards** [comment]
excellent!

**Comment by oparoz** [comment]
This can now be closed as IE8 support has been dropped for 9.0+
