### ISSUE TITLE
Actions to make Gallery official

### ISSUE THREAD

**Issue by oparoz** [owncloud/gallery#229]
### Goal
- `owncloud/galleryplus` -> `owncloud/gallery` from where official releases will be built
- `interfasys/galleryplus` from where Gallery+ releases will be built
### Plan
- [x] ~~Rename branches which are in the way. They now start with `plus-` and should not be used in the official repository.~~ Delete branches which belong to the fork
- [x] Import old "Pictures" branches from owncloud/gallery
- [x] Change namespace from GalleryPlus to Gallery
- [x] Make the master branch the new development branch
- [x] Rename repository 
#### App store

Regarding the app store and the ocsid, it seems it's been removed from the old app. I guess it's not important for official apps as they're released at the same time as oC. 
- [x] Create a new app in the app store? No
- [x] Add new ocsid or Pictures ocsid or remove it
#### Translations
- [x] Connect to Transifex. I have no idea how this works. I'm hoping the folder will automatically be updated when it sees the outdated translations and once new strings are added, they'll be made available to translate
- [x] Add missing translations to Transifex 
#### Releases
- [x] Remove Gallery+ releases

**Comment by DeepDiver1975** [comment]
@oparoz I'll take care about the transifex integration once the repos have been renamed

**Comment by oparoz** [comment]
:+1:

**Comment by DeepDiver1975** [comment]
repos have been renamed

**Comment by DeepDiver1975** [comment]
Transifex is now back in sync - translations are flowing in ....

**Comment by oparoz** [comment]
:+1:

**Comment by jancborchardt** [comment]
Nice work everyone! :)

**Comment by jancborchardt** [comment]
@oparoz should we transfer the main info (your three suggestions) from the last open issue in gallery-old over here? https://github.com/owncloud/gallery-old/issues/193 then we can close the issue tracker there.

**Comment by oparoz** [comment]
@jancborchardt - I wasn't sure since interested parties already have that issue in their email client, but creating a new one could bump things up and clarify things a bit (IE8 compat is only possible on 8.2).

**Comment by jancborchardt** [comment]
@DeepDiver1975 I assume you closed down the issue tracker in the gallery-old repo. Since the branches  & history are moved over, we might as well remove the whole repo?

**Comment by oparoz** [comment]
@jancborchardt - I think we should keep it, some issues on here are still referencing interesting discussions found in the legacy repo.

**Comment by oparoz** [comment]
So, the last step seems to be settings things up in the app store.

It doesn't seem to exist or is hidden.

@LukasReschke @karlitschek How does that work?

**Comment by karlitschek** [comment]
@oparoz Not sure I get what I understand what you want to achieve. :-) I suggest to keep the current app store entry for 8.0, 8.1 and older. For 8.2 and newer it won't me needed anymore to have it on the app store because it will be in the main release.
Not sure what the question is :-)

**Comment by oparoz** [comment]
@karlitschek - You answered my question :). I wasn't sure an ocsid was still required, because without it, that means emergency security fixes can't be pushed per example without having to push a full ownCloud release.

It was removed from Pictures stable8, but is still present in Pictures stable8.1. @LukasReschke That was intended, correct?

If yes, I'll update the ocsid in master, matching the one in stable8.1 and everything should work like before.

**Comment by LukasReschke** [comment]
> It was removed from Pictures stable8, but is still present in Pictures stable8.1. @LukasReschke That was intended, correct?

No. It should be gone there as well ;-)

**Comment by LukasReschke** [comment]
Ref https://github.com/owncloud/gallery/pull/253

**Comment by oparoz** [comment]
OK :)

**Comment by oparoz** [comment]
Closing this as all steps have been performed. Thanks for your help :)

**Comment by jancborchardt** [comment]
WOHOOOO! :) High fives all around! That’s how we properly collaborate.

**Comment by karlitschek** [comment]
Very cool! Thanks to everyone especially to @oparoz for the awesome new gallery improvements.
It's also nice to see that we have moved an independent 3rd party app from the outside into the very core of ownCloud community and enterprise. It was partly a painful process but I'm happy that we as a community and company have proven that this is possible in ownCloud. :-)
