### ISSUE TITLE
Cursor just spins when running gallery plus

### ISSUE THREAD

**Issue by tel2** [owncloud/gallery#23]
Chrome, owncloud 8 (upgraded from owncloud 7, which was working fine).

Confirmed that the app directory is called galleryplus, set permissions to www-data:www-data.
When choosing the Gallery+ icon from apps, I get an empty page with a spinning cursor that never stops.

Error in the logs:

Feb 11 18:28:53 nowlas ownCloud[12945]: {index} Exception: {"Message":"Unable to generate a URL for the named route \"galleryplus.page.index\" as such route does not exist.","Code":0,"Trace":"#0 \/var\/www\/owncloud\/lib\/private\/route\/router.php(282): Symfony\Component\Routing\Generator\UrlGenerator->generate('galleryplus.pag...', Array, false)\n#1 \/var\/www\/owncloud\/lib\/private\/urlgenerator.php(42): OC\Route\Router->generate('galleryplus.pag...', Array)\n#2 \/var\/www\/owncloud\/apps\/galleryplus\/appinfo\/app.php(36): OC\URLGenerator->linkToRoute('galleryplus.pag...')\n#3 \/var\/www\/owncloud\/lib\/private\/app.php(379): require('\/var\/www\/ownclo...')\n#4 \/var\/www\/owncloud\/settings\/ajax\/navigationdetect.php(9): OC_App::getAppNavigationEntries('galleryplus')\n#5 \/var\/www\/owncloud\/lib\/private\/route\/route.php(135) : runtime-created function(1): require_once('\/var\/www\/ownclo...')\n#6 [internal function]: __lambda_func(Array)\n#7 \/var\/www\/owncloud\/lib\/private\/route\/router.php(250): call_user_func('\x00lambda_295814', Array)\n#8 \/var\/www\/owncloud\/lib\/base.php(763): OC\Route\Router->match('\/settings\/ajax\/...')\n#9 \/var\/www\/owncloud\/index.php(36): OC::handleRequest()\n#10 {main}","File":"\/var\/www\/owncloud\/3rdparty\/symfony\/routing\/Symfony\/Component\/Routing\/Generator\/UrlGenerator.php","Line":134}

Clients: Linux (Fedora 20) with Firefox, Linux (Arch) with Chrome, Windows with Chrome
Server: Debian 7.8, lighttpd 1.4.31, php 5.4.36, OC 8.0, Gallery+ newest from git

owncloud is reachable via nowlas.org/owncloud
owncloud is installed in /var/www/owncloud

**Comment by oparoz** [comment]
Could you give me some information on your environment?
PHP version
Web server
Is oC reachable via a domain?
Is oC installed in a sub-folder?

**Comment by godfuture** [comment]
Hi folks,
I have the same issue, cursor just spins. One time switiching from files app to galery+ it happened that previews got loaded, but just the first page, no further picures lazy loaded.
Now it seems the cursor will spin forever.

Client: win7 x64, Firefox 35.0.1
Server: win7 x64 with IIS 7.5, PHP 5.5.15, OC 7.0.4, Gallery+ 1.0.3

**Comment by oparoz** [comment]
@godfuture - I suspect you're experiencing a different issue. Could you check your owncloud.log and Javascript debugger to see what's failing?

**Comment by oparoz** [comment]
This issue was moved to nextcloud/gallery#42
