### ISSUE TITLE
Panorama viewer

### ISSUE THREAD

**Issue by oparoz** [owncloud/gallery#234]
_User requested_

Some people would like to be able to view panorama or photo sphere images such as the ones taken by a mobile phone.

I know bigshot supports VR images. Not sure what it would take to implement...
##

**Comment by setnes** [comment]
I was thinking about this when we worked on the image preview size logic that was based on the monitor size.  Even without a fancy VR viewer, panoramas might be better viewed if they could simply be zoomed and scrolled.  Right now we decide the longest image edge for the preview size based on the longest monitor edge plus a normalization fudge of 100.  For a panorama, requesting a larger image (make the shortest image edge match the longest monitor edge) might have an advantage... but it could end up being a very large file served.  It seems like it should be a second download.  

The ratio between image length and width could drive this.  If it was over a certain threshold (maybe one edge has to be more than twice as long as the other), we could treat it as a panorama.  I don't think we have the image dimensions at the time we are requesting the preview though.

Just thoughts...

**Comment by oparoz** [comment]
If we automatically download the HD pictures when zooming in (https://github.com/owncloud/gallery/issues/193). We could keep things as-is and users would get the full res image as soon as they zoom-in and could then pan left-right.

Would that be good enough?

**Comment by jospoortvliet** [comment]
@oparoz for panorama's - I think it's fine... Sure, the whole parallax thing is fancy but not really crucial.

**Comment by oparoz** [comment]
This issue was moved to nextcloud/gallery#43
