### ISSUE TITLE
Embeddable galleries

### ISSUE THREAD

**Issue by oparoz** [owncloud/gallery#235]
_User requested_

**User type**: External

**User level**: Advanced
### Description

It should be possible to create a special link which just renders the photowall, including the controls, but without the header and footer.
We could also make the controls optional.

Those links would need to be loaded in an iframe and there may be some Javascript conflicts.

![embedded_galleries](https://cloud.githubusercontent.com/assets/323220/13535992/8d40fa08-e23d-11e5-959d-fe845ede9f55.jpg)
#### Competitive products
- https://api.imgur.com/
### Benefit / value

Make ownCloud hosted content available everywhere
##

**Comment by arpee** [comment]
+1

**Comment by arpee** [comment]
At the moment - it seems it is not possible to embed gallaries in an iframe - even with all controls enabled etc.

**Comment by oparoz** [comment]
@LukasReschke - Do you have some doc handy on the CSP policy which needs to be applied at the controller level for people to be able to embed the HTML template they receive?

**Comment by setnes** [comment]
I like this idea.  A smaller step might be to somehow create a special share link (using the share interface) that includes html code you could use to embed a thumbnail link to a gallery directory.  That might be a smaller hurdle.

**Comment by oparoz** [comment]
The plan is to use the new REST API (https://github.com/owncloud/gallery/issues/5) for that. Something like /api/gallery would send you the HTML and links to the JS, thumbnails and previews links.

**Comment by sagar-shah94** [comment]
i am interested to work on this project because i have worked on webservices so much whenever i read the idea i thought i could help develop this api so any other website can embed gallery into their website and use all functionality of gallery offered by our website

**Comment by oparoz** [comment]
Cool :). There is already an API, but one or two new routes should be defined. 
The biggest problem to solve from my pov is how to make sure that it's easily embeddable in various CMS without having to modify security settings there.
Luckily, we have an expert at ownCloud which will be able to assist.

**Comment by gkarugi** [comment]
The plan for embedding a gallery from ownCloud to other webpages is a great one.From my POV, the iframe idea will be much simpler  to implement because the web is heterogenous where websites are built using different languages.This also is not a very customizable way  for an end developer willing to integrate the feature to his/her webpage.
The other option is create the routes providing the endpoints for the ownCloud gallery API then develop a php package which other developers can use to integrate the feature to their websites.This will give control to the website implementers on how they want the gallery feature to appear in their websites.
This can be extended in due time to other languages as well.
I would really want to contribute to this project.

**Comment by oparoz** [comment]
Yes, using an iframe makes it very easy to quickly add a gallery without having to move files to the CMS, forum, etc., but we have to make the result flexible so that it can fit most use cases. Some people may not want the embedded slideshow per example.

There are already endpoints in Gallery for people who want to retrieve a list of images or previews: 
https://github.com/owncloud/gallery/wiki/RESTful-API

They're free then to customise any Gallery app to present the information they get.

**Comment by Karugi** [comment]
What i think we can do is create an embeddable widget which users can add just a little bit of markup,say a link then the widget can render the gallery.I think that is one option we can consider.

Your Thoughts?

**Comment by Karugi** [comment]
An embeddable widget can work perfectly for rendering the gallery to webpages.

Your thoughts?

**Comment by gkarugi** [comment]
I think an embeddable widget can work perfectly for this project. The only thing the end user will need to do is put  a code snippet containing a special code  to their webpage and a gallery will be shown in return.

Your thoughts?

**Comment by oparoz** [comment]
Yes, this could be one of the features of this project.

**Comment by gkarugi** [comment]
What other features were you thinking of?

**Comment by oparoz** [comment]
I didn't really think about all the details. There are plenty of examples of API from platforms which specialise in serving images and videos and we should at least provide a basic set which matches what they can offer.

It has to be easy to set up and flexible. Some people will want a photowall, others a slideshow, etc. It's all about empowering ownCloud users so that they can keep their data where it is without giving up on ease of share.

**Comment by oparoz** [comment]
This issue was moved to nextcloud/gallery#63
