### ISSUE TITLE
Show file name in the slideshow

### ISSUE THREAD

**Issue by oparoz** [owncloud/gallery#237]
_User requested_

Just like we can see it in the photowall, it would be great to be able to have it without having to look at the URL.

**Comment by oparoz** [comment]
@jancborchardt (and co.) - To take into consideration when re-designing the interface.

**Comment by jancborchardt** [comment]
Yeah, good call. We can and should combine this with a rename function directly in the slideshow. Should probably show the name centered below the image, along with the other actions like share, download etc.

**Comment by jancborchardt** [comment]
This has been fixed by you, @oparoz ;)
