### ISSUE TITLE
MS Edge "floods" apache server with requests, when user sorts gallery

### ISSUE THREAD

**Issue by ghost** [owncloud/gallery#242]
Hello,

loading the gallery on MS Edge&OC8.1 works fine, but sorting the gallery (alpha or date) floods the server with hundreds of requests (load goes into 100s).

Thanks!

**Comment by oparoz** [comment]
Did you use one of the releases or "master"?

**Comment by ghost** [comment]
Hi, I again cloned the master, following the instruction:

https://github.com/owncloud/gallery#installing-from-git

I cleared, the thumbnail cache and assets and now it appears to work.

Thanks.

**Comment by oparoz** [comment]
Thanks!
For reference, before I fixed the EventSource polyfill, I had to use a timer to close the connection and it meant that the browser had to re-open the connection if it had not yet received the thumbnails, leading to the kind of behaviour you experienced.
