### ISSUE TITLE
Review language used to communicate with users

### ISSUE THREAD

**Issue by oparoz** [owncloud/gallery#244]
All strings can be read there (login required)
https://www.transifex.com/projects/p/owncloud/viewstrings/#en/gallery

It would be good if someone from oC inc. could review those, to make sure the app addresses users in an appropriate manner, in line with oC's communication policy.

@carlaschroder maybe?

**Comment by ghost** [comment]
This issue will fall off 8.2 if not resolved by 6 Oct

**Comment by carlaschroder** [comment]
Hi @oparoz, I'm not sure what to do with this. Since this about app compliance, is there someone at oC who actually handles app compliance?

**Comment by oparoz** [comment]
>  is there someone at oC who actually handles app compliance?

@karlitschek @MTRichards

**Comment by MTRichards** [comment]
um. @cmonteroluque to discuss the bigger issue of reviewing text related to warnings and the like?

**Comment by ghost** [comment]
@MTRichards glad to do that

**Comment by carlaschroder** [comment]
Closing, as this doesn't seem to be a doc issue. If you want my help you know where to find me :)
