### ISSUE TITLE
Slideshow controls can be killed by a single image

### ISSUE THREAD

**Issue by oparoz** [owncloud/gallery#246]
### Steps to reproduce
1. Create a folder and put a single image in it
2. Switch to Gallery view
3. Start the slideshow
### Expected result

The picture should be shown and the play/pause controls should not appear
### Actual result

Both the play and pause icons are shown and they overlap each other
Clicking on them will make them disappear and it won't be possible to use the slideshow any more until a full refresh is performed.

**Comment by oparoz** [comment]
@jancborchardt

**Comment by jancborchardt** [comment]
Next to the play/pause being hidden, the next/previous should also not be shown, right?

Can you check if it’s the only image in that folder and then deactivate the buttons? Add a class .hidden to them, and it should be handled via CSS.

**Comment by oparoz** [comment]
The code to hide stuff is already there, but it doesn't work.
https://github.com/owncloud/gallery/blob/master/js/slideshowcontrols.js#L59-L61
