### ISSUE TITLE
Upload straight from the app [$250]

### ISSUE THREAD

**Issue by oparoz** [owncloud/gallery#25]
Being able to upload files is just one click away with the "switch to files view" button, but it could be even better if we could just ~~create folders and~~ upload files straight from the app.
## Specifications

The idea is to be able to easily drag and drop files in the current album, to be able to detect conflicts and to refresh the view once the process is complete.
- [x] Upload via drag and drop ~~only~~
- [x] Upload to current album only. The whole photowall is the drop zone
- [x] Upload as a logged in user only
- [x] Upload both files and folders (Chrome only)
- [x] Show progress bar
- [x] Reload view at end of the process
- [x] Conflict management (same as in Files)
- [x] Don't block in-app navigation. Keep uploading where the upload started (same as in Files)
- [x] Leaving the app kills the upload process (same as in Files)
- [x] Let users upload by clicking on a button in the controls bar

![conflict](https://cloud.githubusercontent.com/assets/323220/10268323/3c79c08c-6ab5-11e5-8253-3d77f4429aee.png)
### Bugs
- [x] Error 500 when uploading on an empty Gallery...
- [x] Conflict dialogue breaks when comparing images located in folders which don't appear in the album representation
##

**Comment by jancborchardt** [comment]
Yes! Please. That is very important and has come up in about every usability test I ever did on ownCloud.

**Comment by jancborchardt** [comment]
(Btw, I replaced the »feature request« with the »enhancement« label to keep it similar to core and other apps.)

**Comment by oparoz** [comment]
Link to the thread discussing the implementation in the Files app: https://github.com/owncloud/apps/issues/82

**Comment by jancborchardt** [comment]
Any progress on this here? Would really be cool to have it – this has come up already in the first usability tests of the Gallery app way back when.

**Comment by oparoz** [comment]
I'll post a roadmap soon

**Comment by oparoz** [comment]
@jospoortvliet @jancborchardt @karlitschek @LukasReschke I've posted some specs. Let me know if this meets your requirements

**Comment by jancborchardt** [comment]
Nice! The only additional requirement I have is that upload is not only posssible via drag&drop but also by a [+] button just like in the files app. That way it’s discoverable as well.

Otherwise, is there a work-in-progress pull request of this, or what do the checkmarks mean?

**Comment by oparoz** [comment]
> The only additional requirement I have is that upload is not only posssible via drag&drop but also by a [+] button just like in the files app

I was afraid you were going to say that ;). I'll explore some solutions and hopefully I'll be able to at least just add a big [ + ] which opens the dialogue.

> Otherwise, is there a work-in-progress pull request of this, or what do the checkmarks mean?

There will be. The checkmarks mean the prototype works and I'm now cleaning things up.

**Comment by jancborchardt** [comment]
Cool! :) Yeah, sorry for the request with the [ + ] button, but I consider that quite important since only having drag&drop will still not solve the problem for most people (they will just not know that the functionality exists).

**Comment by oparoz** [comment]
> will still not solve the problem for most people

That's why I'll introduce Fily, Clippy's cousin. Always floating around the screen, ready to help :)

**Comment by jancborchardt** [comment]
:D

**Comment by jospoortvliet** [comment]
![clippy](https://cloud.githubusercontent.com/assets/551757/12068004/b9c7e62e-b004-11e5-881f-b5fa12047716.png)

**Comment by oparoz** [comment]
:laughing:

**Comment by oparoz** [comment]
Upload button has been added.
