### ISSUE TITLE
Will this be namned gallery instead of galleryplus in .occ?

### ISSUE THREAD

**Issue by enoch85** [owncloud/gallery#250]
Like above question.

@oparoz

**Comment by oparoz** [comment]
Yes.
- People using Pictures today with a folder named `gallery`, will be migrated to Gallery and it will use the same folder.
- People using Gallery(+) today with a folder named `galleryplus`, will have a choice to either activate the default Gallery, which will be found in the `gallery` folder or to upgrade their installation of Gallery+, which will keep using the `galleryplus` folder

It all depends on what the user needs: `official` vs `approved`. They have different life cycles and updates policies.

**Comment by enoch85** [comment]
@oparoz Ok, thanks. I´m asking because in the install script of my pre-configured ownCloud VM I enable `galleryplus` and disable `gallery`. Just to be clear, with this change I should just enable `gallery` and nothing else to keep "`galleryplus`"?

**Comment by oparoz** [comment]
Yeah, I figured ;)
That's correct. Users can then decide to switch if they need new features sooner than every 3-4 months.

**Comment by enoch85** [comment]
Nice! Thanks.
