### ISSUE TITLE
Close lightbox with escape key

### ISSUE THREAD

**Issue by pascalBokBok** [owncloud/gallery#251]
It would be nice if the lightbox would close when the user presses escape

**Comment by oparoz** [comment]
Was a regression. Thanks for the report!

**Comment by pascalBokBok** [comment]
thanks for the fix. How/when will the change be out - through an update in the Apps app?

**Comment by oparoz** [comment]
You can use master, wait for ownCloud 8.2 to come out in October or you can use Gallery+ which gets updated more frequently (1-2 releases a month): https://apps.owncloud.com/content/show.php/Gallery?content=169116

The next version, which contains the fix, should get released in the coming days.
