### ISSUE TITLE
Some issues when trying to open the app

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/gallery#254]
I see the spinner, but nothing shows up. The JS console says:

```

js.js?v=45360383019c34fc1b722568d8ed4110:1846 Deprecation warning: tipsy is deprecated. Use tooltip instead.
localhorst/:1 Refused to load the font 'data:font/woff;charset=utf-8;base64,d09GRgABAAAAAAYcAA0AAAAACjQAAQAAAAAAAAA…cP3P8MNIWLyYOBuxL6DRylJ4cAAAB4nGNgYoAALjDJyIAOWMCiTIxMLDmZedkABtIBygAAAA==' because it violates the following Content Security Policy directive: "font-src 'self'".
```

owncloud.log

```
{"reqId":"pcDqU7EJOFtDBRFhpFL6","remoteAddr":"127.0.0.1","app":"PHP","message":"Cannot modify header information - headers already sent at \/home\/jan\/owncloud\/lib\/private\/response.php#103","level":0,"time":"2015-07-29T14:48:55+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/gallery\/thumbnails?ids=1862%3B1861%3B1103%3B1049%3B755%3B762%3B759%3B756&scale=1.5&square=1&requesttoken=TKvKo7whYu4olM%2F9Mftduk4QKF%2BjNq"}
{"reqId":"7ou\/crqvr30DfBo660WD","remoteAddr":"127.0.0.1","app":"PHP","message":"Cannot modify header information - headers already sent at \/home\/jan\/owncloud\/lib\/private\/response.php#103","level":0,"time":"2015-07-29T14:48:59+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/gallery\/thumbnails?ids=1862%3B1861%3B1103%3B1049%3B755%3B762%3B759%3B756&scale=1.5&square=1&requesttoken=TKvKo7whYu4olM%2F9Mftduk4QKF%2BjNq"}
```

Anything I’m missing? @oparoz

**Comment by oparoz** [comment]
I've moved from tipsy to tooltip since it's deprecated, but I'm not really happy about that change in core as it doesn't work well for the breadcrumb.

For the rest, I need more info. It could be that you simply need a ctrl+f5.
I'm not using any fonts in Gallery and I cant reproduce.

This is on master, using master?

This is a private gallery?

**Comment by jancborchardt** [comment]
> but I'm not really happy about that change in core as it doesn't work well for the breadcrumb.

What do you exactly mean by that?

Not sure about the font stuff, reload does not fix it, neither does incognito window … says something about content-security-policy – cc @LukasReschke 

(And yeah, this is master on master. No private gallery [what is that?], just the regular gallery app over all files.)

**Comment by oparoz** [comment]
> What do you exactly mean by that?

Ah no, I spoke too soon. I added another level and the tooltip gets wrapped. At the previous one, it was glued to the left of the window and I was afraid it would slide under if it got any longer

Regarding the font error, it's a Chrome only problem...

**Comment by oparoz** [comment]
Not sure where that font is used in the template, but the issue is gone now.
