### ISSUE TITLE
Call to undefined method OCA\\GalleryPlus\\Service\\ConfigService::isAllowed()

### ISSUE THREAD

**Issue by j-ed** [owncloud/gallery#261]
## Expected behavior

No PHP errors should be caused by the Gallery(Plus) app.
## Current behavior

The following error is logged on a regular base when the Gallery(Plus) app has been activazted:

```
...,"app":"PHP","message":"Call to undefined method OCA\\GalleryPlus\\Service\\ConfigService::isAllowed() at \/var\/www\/htdocs\/owncloud\/apps2\/galleryplus\/service\/filesservice.php#120","level":3,"time":"2015-08-04 11:16:03+02:00","method":"GET","url":"\/owncloud\/index.php\/apps\/galleryplus\/config?slideshow=1"}

```
## Steps to reproduce
1. Activate the Gallery(Plus) app
2. check ithe log file
#### Server Configuration

OS: Linux 3.2.67
Web server: Apache2 2.4.12
Database: MySQL 5.1.73
PHP version: 5.4.42
ownCloud version: 8.0.5
GalleryPlus app version: 13.0.0
#### Client Configuration

Operating system: Windows 7
Firefox version: 39.0

**Comment by oparoz** [comment]
This method call doesn't exist in the file mentioned, in release 13 for stable8, so you may have mixed some files together.

https://github.com/interfasys/galleryplus/blob/v13-stable8/service/filesservice.php#L120

**Comment by j-ed** [comment]
I think I know what has happened. You recommended to apply a patch to fix a problem with external shares https://github.com/owncloud/gallery/issues/218#issuecomment-123280558 which included the method that is now reported as "missing".

**Comment by oparoz** [comment]
Indeed, but at the bottom of that post, it is specified in bold that it is for 8.1 only ;)

I did write about what you should do in 8.0 here: https://github.com/owncloud/gallery/issues/218#issuecomment-123781356
