### ISSUE TITLE
zoom not possible on all mobile devices

### ISSUE THREAD

**Issue by Flexmaen** [owncloud/gallery#263]
The gallery is doing a great job on mobile devices too (tested with Blackberry and Android Browser).

However, if you want to zoom a picture, this is only possible if you download it to your local folder and open it from there. I think it would be great if you also could zoom pictures somehow.
##

**Comment by oparoz** [comment]
I agree. Unfortunately, the BigShot library we're using only captures iOS events.

That one of the reason I'm considering [changing Slideshow engine](https://github.com/owncloud/gallery/issues/158) or maybe offering a choice

**Comment by oparoz** [comment]
I've had a look at the Bigshot code and for it to work, someone would have to write new code converting the pinch distance into a scale factor. Not too difficult, but I'm not sure it's worth it given the fact that the Bigshot project has silently died.

**Comment by oparoz** [comment]
This issue was moved to nextcloud/gallery#66
