### ISSUE TITLE
Firefox 40 seems to have problems with the CSP rules.

### ISSUE THREAD

**Issue by sezuan** [owncloud/gallery#272]
### Steps to reproduce
1. Put some pictures into the picture folder
2. Open gallery
### Expected behaviour

It should show the pictures
### Actual behaviour

Loading forever
### Server configuration

**Operating system**: Ubuntu 14.04

**Web server:** Apache 2.4

**Database:** MySQL 5.5

**PHP version:** 5.5.28

**ownCloud version:** 8.1.1(stable)

**Updated from an older ownCloud or fresh install:** Update form 7.0.4

**List of activated apps:** 
- calendar: 0.7.3
- contacts: 0.4.0.0
- direct_menu: 0.3
- files: 1.1.10
- files_external: 0.2.3
- files_markdown: 0.1
- files_mv: 0.8.1a
- files_pdfviewer: 0.7
- files_sharing: 0.6.2
- files_texteditor: 0.4
- files_trashbin: 0.6.3
- files_versions: 1.0.6
- files_videoviewer: 0.1.3
- firstrunwizard: 1.1
- gallery: 0.6.1
- music: 0.3.7
- news: 6.0.1
- ownnote: 1.05
- search_lucene: 0.6.0
- updater: 0.6
- user_ldap: 0.6.1

also tried to disable all 3rd Party and 'Approved' apps.

**The content of config/config.php:**

```
<?php
$CONFIG = array (
  'instanceid' => '',
  'passwordsalt' => '',
  'datadirectory' => '/var/lib/owncloud/data',
  'dbtype' => 'mysql',
  'version' => '8.1.1.3',
  'session_lifetime' => 28800,
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => '',
  'dbpassword' => '',
  'installed' => true,
  'overwriteprotocol' => 'https',
  'overwritewebroot' => '',
  'forcessl' => true,
  'loglevel' => 0,
 'ldapIgnoreNamingRules' => false,
 'maintenance' => false,
 'theme' => '',
 'appstoreenabled' => true,
 'trusted_domains' => 
 array (
   0 => '<domain>',
 ),
 'singleuser' => false,
  'share_folder' => '/Shared',
  'mail_smtpmode' => 'smtp',
  'mail_from_address' => 'oc',
  'mail_domain' => '',
  'mail_smtphost' => '10.42.0.2',
  'mail_smtpport' => '465',
  'mail_smtpsecure' => 'ssl',
  'secret' => '',
  'asset-pipeline.enabled' => false,
  'memcache.local' => '\OC\Memcache\APCu',
);
```

**Are you using an external user-backend, if yes which one:** LDAP

Insert your browser log here, this could for example include:

Content Security Policy: The page's settings blocked the loading of a resource at self ("script-src https://<domain> 'unsafe-eval'").
onsubmit attribute on DIV element

and later:

Content Security Policy: The page's settings blocked the loading of a resource at data:image/jpg;base64,/9j/4AAQSkZJRg...RRRQAylpBRQAtLSUUALS0lLQIKWkooGOopKKBC5ozSUUAOzRSUUDFzSUUUAFFFFABRRSUAFFFFABSUUUAFFFFAEYpaKKAFooooAWiiigBaM0UUCFooooAKKKKACloooGhKWiigAooooASiiigBKKKKACiiigAzRRRQB//9k= ("img-src *").

It works with Firefox 39 and with Firefox 40 when I disable `security.csp.enable`.

**Comment by dsteinborn** [comment]
I can confirm this problem with my installation of Owncloud 8.1.1 and Firefox 40.0.2 under Archlinux and Windows. Opera 31 instead works just fine.

Problem can also be reproduced when opening a share link (folder with images) and switching to the gallery view.

**Comment by oparoz** [comment]
Thank you for the report.
Do you experience the same problem when using Gallery+ from the multimedia section in settings/app?

**Comment by sezuan** [comment]
@oparoz I did a very quick test. Gallery+ seems to work correctly. I still get the first error:

```
Content Security Policy:
The page's settings blocked the loading of a resource at self ("script-src https:// 'unsafe-eval'").
onsubmit attribute on DIV element
```

**Comment by oparoz** [comment]
@sezuan - Thanks. That CSP error has to do with translations (https://github.com/owncloud/core/issues/17758). Not sure if `core` is going to be able to solve it: https://github.com/owncloud/core/issues/11925

Regarding the CSP policy for "Pictures", I have no idea where to look. Maybe @icewind1991 or @LukasReschke know?

**Comment by ilsi** [comment]
I have the same issue with  ownCloud 8.0.5 (stable) and Firefox 40.
Both server and client are Fedora 22 x86_64.

WebServer: nginx 1.8.0
DB: PostgreSQL 9.4.4

**Comment by d-tamm** [comment]
Same here: Firefox 40.0 keeps loading infinitely in Gallery view, both in the Pictures app and in shared folders when clicking on the 4 squares. Latest ownCloud on Synology server and Ubuntu server.

**Comment by ToonvdPas** [comment]
I have the same problem on ownCloud 8.1.1 stable.
The picture gallery works on Firefox 38.1.1 (on Linux)
The picture gallery works on Android 4.1.2
The picture gallery does NOT work on Firefox 40.0.3 (on Windows 10)
The picture gallery does NOT work on Edge 20.10240.16384.0 (on Windows 10)
The picture gallery works on Internet Explorer 11.0.10240.16431 (on Windows 10)
So only archaic browsers seem to work.  My users are complaining.

**Comment by icewind1991** [comment]
Works fine for me on FF40, even though I get the csrf error message in the console

(gallery and core both on master)

**Comment by ToonvdPas** [comment]
Oops, you're right.  I goofed.  My apologies.
So my remark at the bottom (regarding archaic browsers) is not correct too.
Thanks for putting me straight.
[...scratching head, testing again and updating comment...]
No, my previous posting was corrrect, FF40 on Windows 10 does NOT work.
Did you by any chance test FF40 on a different platform?  Does that make a difference?

**Comment by oparoz** [comment]
@ToonOwncloud - You mentioned 8.1.1 earlier though. If your users are on 8.1, they do not get the same experience you get on master.

**Comment by icewind1991** [comment]
FF40 on Arch Linux

**Comment by ToonvdPas** [comment]
@aparoz -  I just follow the stable releases.
At the bottom of the Administrator screen it advertises itself as "ownCloud 8.1.1 (stable)".
I follow the releases by doing a 'yum update' on a regular basis.  The current rpm version is:

# yum list owncloud-server
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: centos.mirror.transip.nl
 * epel: ftp.nluug.nl
 * extras: mirror.sitbv.nl
 * updates: mirrors.supportex.net
Installed Packages
owncloud-server.noarch            8.1.1-12.1            @isv_ownCloud_community

**Comment by e-alfred** [comment]
I can reproduce this problem on Firefox 40 on Ubuntu 12.04. PC-BSD and Arch Linux. The circle is showing indefinitely. If I disable security.csp.enable in about:config, it loads like normal.

This happens on latest 8.0 as well as 8.1.

**Comment by Tronde** [comment]
I could reproduce this issue on Ubuntu 14.04.3 with Firefox 40.0.3. With Firefox ESR 38.2.1 on Windows 7 it works. This happens on ownCloud 8.1.2.

**Comment by Wikinaut** [comment]
Same problem for me here with latest Firefox 40.0.3
- OC server 8.1.1
- Client: Firefox 40.0.3 on openSUSE Tumbleweed (this FF plays mp3 files, I double-checked this).

javascript log full of errors when trying to open an owncloud/document https://github.com/owncloud/documents/issues/526

inter alia:

```
Fehler: Content Security Policy: 
Die Einstellungen der Seite haben das Laden einer Ressource auf self blockiert
("script-src https://myserver 'unsafe-eval'").

Quelldatei: https://myserver/owncloud/index.php/apps/documents/
Zeile: 0
Quelltext:
ondragstart attribute on IMG element
```

**Comment by enricotagliavini** [comment]
Current Content-Security-Policy response header for the gallery main page is:

<code>
default-src 'self'; script-src 'self' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; frame-src *; img-src *; font-src 'self' data:; media-src *; connect-src *
</code>

Since the images are loaded with base64 data scheme data: must be added to image-src *. Adding this header to the response (for example by mangling the header in apache httpd config or in .htaccess file) solves the problem

**Comment by oparoz** [comment]
That's correct. One needs to attach that policy to the controllers of the legacy app.

**Comment by jelofson** [comment]
You could, if you really want to, add  . 'img-src \* data:; ' to the 'lib/private/response.php' file at about line 250. That will make it work, but I am not really into that as a solution. I have yet to figure out how to override that via the \OCP\AppFramework\Http\ContentSecurityPolicy along with the OCP\AppFramework\Http\Reponse::setContentSecurityPolicy(). At least I can't figure out how from the **Pictures** app. 

```
 public static function addSecurityHeaders() {
                /**
                 * FIXME: Content Security Policy for legacy ownCloud components. This
                 * can be removed once \OCP\AppFramework\Http\Response from the AppFramework
                 * is used everywhere.
                 * @see \OCP\AppFramework\Http\Response::getHeaders
                 */
                $policy = 'default-src \'self\'; '
                        . 'script-src \'self\' \'unsafe-eval\'; '
                        . 'style-src \'self\' \'unsafe-inline\'; '
                        . 'frame-src *; '
                        . 'img-src * data:; '
                        . 'font-src \'self\' data:; '
                        . 'media-src *; '
                        . 'connect-src *';
                header('Content-Security-Policy:' . $policy);

                // Send fallback headers for installations that don't have the possibility to send
                // custom headers on the webserver side
                if(getenv('modHeadersAvailable') !== 'true') {
                        header('X-XSS-Protection: 1; mode=block'); // Enforce browser based XSS filters
                        header('X-Content-Type-Options: nosniff'); // Disable sniffing the content type for IE
                        header('X-Frame-Options: Sameorigin'); // Disallow iFraming from other domains
                        header('X-Robots-Tag: none'); // https://developers.google.com/webmasters/control-crawl-index/docs/robots_meta_tag
                }
        }
```

**Comment by xylo** [comment]
Some for owncloud 8.1.3 on centos 6.7 with php 5.6 using fastcgi and apache 2.2.

**Comment by oparoz** [comment]
@jelofson - I've modified the policy in addSecurityHeaders() for 8.1.4, so hopefully this will get Pictures to work for those who cannot move to Gallery+.

**Comment by cdamken** [comment]
@oparoz I tried to find the fix, but could find it. where is the fix?

**Comment by oparoz** [comment]
https://github.com/owncloud/core/pull/19450

**Comment by cdamken** [comment]
Thanks @oparoz
