### ISSUE TITLE
Ipad 1 can't show the gridview ("thumbnailpage")

### ISSUE THREAD

**Issue by gibbiceps** [owncloud/gallery#277]
On my Ipad (first gen) there's a problem with the gridview, once there are more than 30 Pictures. It's persistent since Owncloud 3 at least.  It's loading about 10 Pictures, then it reloads the page...forever.
Also the slideshowmode is now working. I'm using relatively big pictures up to 14mp, all jpg.
I'm running the latest version of owncloud, ios and safari. On my Notebook everything is running fine. That Ipad is one of very view windows to the world for my grandma ;). Thanks in advance!

**Comment by oparoz** [comment]
@gibbiceps - Could you try to disable "Pictures" in the app manager and install "Gallery+" ?
Also, on which OS is that iPad1? It could be that it doesn't support some of the technologies we're using.

And which ownCloud version are you using?
