### ISSUE TITLE
Error PHP Call to a member function getMimetype() on a non-object at /var/www/owncloud/lib/private/files/node/node.php#276

### ISSUE THREAD

**Issue by vader2014** [owncloud/gallery#28]
Hi!
When i want to open gallery+ i see the following error in the log: "Error   PHP Call to a member function getMimetype() on a non-object at /var/www/owncloud/lib/private/files/node/node.php#276"

I do not experience this error with all users but only with some (the users have an extensive number of images in their accounts)

BR

**Comment by oparoz** [comment]
Hello BR,
Would it be possible to get some of the error messages which happen just before that?
You'll need to [enable debugging](http://doc.owncloud.org/server/8.0/developer_manual/general/debugging.html) and set error logging to `0`.

This might be a core issue as the app always checks if we have a valid file before doing anything.

**Comment by vader2014** [comment]
Hi!

{"reqId":"c4c3213828211afcbe6193fb814b897f","remoteAddr":"192.168.1.123","app":"no app in context","message":"Accessing the API class is deprecated! Use the appropriate services instead!","level":0,"time":"2015-02-17T22:55:54+01:00","method":"GET","url":"\/owncloud\/index.php\/apps\/galleryplus\/"}
{"reqId":"31333d8ed7fd5a53f44666ae253397e8","remoteAddr":"192.168.1.123","app":"no app in context","message":"Accessing the API class is deprecated! Use the appropriate services instead!","level":0,"time":"2015-02-17T22:55:54+01:00","method":"GET","url":"\/owncloud\/index.php\/core\/js\/oc.js?v=f7128bfd2edf7c105ecd9b7287b97b50"}
{"reqId":"6eaac82afebe34e479d253e6152f17cc","remoteAddr":"192.168.1.123","app":"no app in context","message":"Accessing the API class is deprecated! Use the appropriate services instead!","level":0,"time":"2015-02-17T22:55:55+01:00","method":"GET","url":"\/owncloud\/index.php\/avatar\/vader\/128?requesttoken=fzKBYt6CqFNrt4G1y0swfzco592wLx"}
{"reqId":"9f2c5f2d1a5c8fcdc119e5ea738daa2c","remoteAddr":"192.168.1.123","app":"no app in context","message":"Accessing the API class is deprecated! Use the appropriate services instead!","level":0,"time":"2015-02-17T22:55:56+01:00","method":"GET","url":"\/owncloud\/index.php\/apps\/galleryplus\/images?"}
{"reqId":"9f2c5f2d1a5c8fcdc119e5ea738daa2c","remoteAddr":"192.168.1.123","app":"galleryplus","message":"Supported Mimes: [\"image\/png\",\"image\/jpeg\",\"image\/gif\",\"image\/x-xbitmap\",\"image\/bmp\",\"image\/tiff\",\"image\/x-dcraw\",\"application\/x-photoshop\",\"application\/postscript\",\"image\/svg+xml\"]","level":0,"time":"2015-02-17T22:55:56+01:00","method":"GET","url":"\/owncloud\/index.php\/apps\/galleryplus\/images?"}
{"reqId":"9f2c5f2d1a5c8fcdc119e5ea738daa2c","remoteAddr":"192.168.1.123","app":"PHP","message":"Call to a member function getMimetype() on a non-object at \/var\/www\/owncloud\/lib\/private\/files\/node\/node.php#276","level":3,"time":"2015-02-17T22:57:15+01:00","method":"GET","url":"\/owncloud\/index.php\/apps\/galleryplus\/images?"}

**Comment by oparoz** [comment]
Thanks.

This seems to be created by searchByMime(), which is a `core` method and would need to get fixed there, but I need to find a way to replicate the problem first...

Are you using the released version or are you tracking Github?
Did you use the provided patches?

And do you have any Raw files in your collection?
I'm asking because I'm seeing Raw support and the patch in the 2.0 release did not include the migration script to update existing files.

**Comment by vader2014** [comment]
I was using the released version.

I did a little bit of testing:
*) clean install without patches
*) only the raw patch (with and without the changes to config.php)
*) all patches

today alsoi tried the github version as there are some raw files (although not in the folder i tried the gallery+ function on)

all resulted in the same result error :-(

if you could provide me with a way to log the files passed to the core function, i could locate the guilty file (or path) and have a look whether its broken.

**Comment by oparoz** [comment]
Thanks!
So, if you've tried the github version and applied the Raw patch on a **clean** oC installation, you should be good to go. (Also works if you know you way around patches and ignore the ones which were already applied.)

What you could do is add
`$this->logger->debug("Scanning for: {mime}", ['mime' => $mime]);`
before this
https://github.com/interfasys/galleryplus/blob/master/service/infoservice.php#L145

That way we would get the media type, just before it fails.

`core`is responsible to go through all files and send back a list of the ones which can be displayed, so we can't know which file is responsible without hacking core directly.

One thing you could do is clone the performance-fixes branch as this only looks for files in the current folder and should help identify where the problem is located.

```
# git clone -b performance-fixes https://github.com/interfasys/galleryplus.git
```

**Comment by vader2014** [comment]
The last media type before the error is image/svg+xml
I will try the performance branch later.

**Comment by oparoz** [comment]
Ah, thanks that's useful as there are quite a few workarounds for that media type.
Have you turned on the SVG provider in your config? If yes, could you try to comment it out to see if it makes a difference? And vice-versa.

In my tests, I get the mime icon with the SVG provider as it's very restrictive, but something else might be wrong.

**Comment by oparoz** [comment]
I've filed this
https://github.com/owncloud/core/issues/14390

**Comment by oparoz** [comment]
@vader2014 - Could you try this fix https://github.com/owncloud/core/pull/14437 ?

**Comment by vader2014** [comment]
after the fix i get:

Fatal error: Call to a member function getId() on a non-object in /var/www/owncloud/lib/private/files/node/node.php on line 156

**Comment by oparoz** [comment]
@vader2014 - Could you check that your getFileInfo() looks like this?

```
public function getFileInfo() {
    if (!Filesystem::isValidPath($this->path)) {
        throw new InvalidPathException();
    }
    if (!$this->fileInfo) {
        $fileInfo = $this->view->getFileInfo($this->path);
        if ($fileInfo instanceof FileInfo) {
            $this->fileInfo = $fileInfo;
        } else {
            throw new NotFoundException();
        }
    }
    return $this->fileInfo;
}
```

**Comment by vader2014** [comment]
with owncloud 8.0.1 and gallery+ 2.0.5 it works now. thx!

**Comment by oparoz** [comment]
That's good to hear :)
