### ISSUE TITLE
Shared picture album | No preview slideshow

### ISSUE THREAD

**Issue by ghost** [owncloud/gallery#280]
sharing a picture album with link, then access that link brings up the shared pictures in a list, using the preview slideshow button in upper left corner results in a slideshow where no pictures is found.

its no possible to see slideshow for the the shared pictures folder. files no found

**Comment by oparoz** [comment]
Please fill in this template so that we have more information about your setup: https://raw.githubusercontent.com/owncloud/core/master/issue_template.md

Thank you.

**Comment by ghost** [comment]
### Steps to reproduce

sharing a picture album with link, then access that link brings up the shared pictures in a list, using the preview slideshow button in upper left corner results in a slideshow where no pictures is found.

its no possible to see slideshow for the the shared pictures folder. files no found

### Expected behaviour

Slideshow should be enabled for public shared picture folders

### Actual behaviour

No files/pictures found

Look in this test album and see if you can preview the pictures shared by this link.
https://cloud.hisp.no/index.php/s/17cT1sF3xFCTv2h

### Server configuration

Debian 8 jessie

**Web server:**
apache 2.4

**Database:**
Mariadb

**PHP version:**
5.6

**ownCloud version:** (see ownCloud admin page)
8.1.1(stable)

**Updated from an older ownCloud or fresh install:**
Fresh install

**List of activated apps:**
Files
Activity
gallery+
news
email
notes
contacts
sms
calendar

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder
```

**The content of config/config.php:**

<?php
$CONFIG = array (
  'version' => '8.1.1.3',
  'instanceid' => 'N/A',
  'passwordsalt' => 'N/A',
  'secret' => 'N/A',
  'trusted_domains' => 
  array (
    0 => 'subdomain.domain.com (replaced)',
  ),
  'datadirectory' => '/data',
  'overwritehost' => 'subdomain.domain.com (replaced)',
  'overwriteprotocol' => 'https',
  'overwrite.cli.url' => 'https://subdomain.domain.com (replaced)',
  'dbtype' => 'mysql',
  'dbname' => 'owncloud',
  'dbhost' => 'IP',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'owncloud',
  'dbpassword' => 'Password',
  'installed' => true,
  'mail_smtpmode' => 'smtp',
  'mail_from_address' => 'no-replay',
  'mail_domain' => 'domain.com',
  'mail_smtphost' => 'mx1.domain.com',
  'mail_smtpport' => '25',
  'mail_smtpsecure' => 'tls',
  'loglevel' => 2,
  'logtimezone' => 'Europe/Oslo',
  'activity_expire_days' => 100,
  'trashbin_retention_obligation' => 60,
  'trashbin_auto_expire' => true,
  'check_for_working_webdav' => true,
  'check_for_working_htaccess' => true,
  'appcodechecker' => false,
  'updatechecker' => true,
  'has_internet_connection' => true,
  'default_language' => 'no',
  'maintenance' => false,
  'theme' => '',
  'appstore.experimental.enabled' => true,
  'asset-pipeline.enabled' => true,
  'memcache.local' => '\OC\Memcache\APCu',
  'trusted_proxies' => 
  array (
    0 => 'IP',
  ),
  'forwarded_for_headers' => 
  array (
    0 => 'HTTP_X_FORWARDED',
    1 => 'HTTP_FORWARDED_FOR',
  ),
  'preview_max_scale_factor' => 10,
  'enabledPreviewProviders' =>
  array (
    0 => 'OC\Preview\PNG',
    1 => 'OC\Preview\JPEG',
    2 => 'OC\Preview\GIF',
    11 => 'OC\Preview\Illustrator',
    12 => 'OC\Preview\Postscript',
    13 => 'OC\Preview\Photoshop',
    14 => 'OC\Preview\TIFF'
  ),
);

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system --public
from within your ownCloud installation folder

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** yes/no
No

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No

### Client configuration

firefox 40

**Operating system:**
win 7 ult

### Logs

#### Web server error log

No error log entrys regarding this issue

#### ownCloud log (data/owncloud.log)

No error Logs regarding this issue

#### Browser log

No error log regarding this issue

**Comment by oparoz** [comment]
Many thanks.

Are you using Gallery+ from the app store or are you using git?

**Comment by ghost** [comment]
gallery+ from appstore

**Comment by oparoz** [comment]
Thanks!

**Comment by oparoz** [comment]
Should be fixed in the next release.
