### ISSUE TITLE
need limit for gallery/ajax/thumbnail/batch 

### ISSUE THREAD

**Issue by askovpen** [owncloud/gallery#282]
my current photo gallery have get string for `index.php/apps/gallery/ajax/thumbnail/batch` 14Kb (?image=...;...;...&scale=1&square=1&requesttoken=...) but my server not support to long. i can increase `large_client_header_buffers`, but m.b. split this request to several  requests?

**Comment by oparoz** [comment]
It's been fixed already, see ticket https://github.com/owncloud/gallery/issues/27

You can use [Gallery+](https://github.com/interfasys/galleryplus) today or wait for ownCloud 8.2.
