### ISSUE TITLE
Blank Pictures page with infinite load (related to long request uri)

### ISSUE THREAD

**Issue by PaulAnnekov** [owncloud/gallery#284]
### Steps to reproduce
1. You must have a large amount of photos with deep hierarchy and non-latin names (url encoding will apply and it will increase the length of url).
2. Open Developer Tools and Network tab.
3. Open Pictures page.
4. You will see infinite load.
5. You will see https://example.com/index.php/apps/gallery/ajax/thumbnail/batch?token=&image=[string_with_over_18k_characters_with_urls_to_photos_all_over_the_storage]&scale=1&square=1&requesttoken=[token] with status `cancelled`.
6. Open url above in separate tab and you will see `414 (Request-URI Too Large)` error from nginx.
### Expected behaviour

I should see a gallery.
### Server configuration

**Operating system**: Debian

**Web server:** nginx

**ownCloud version:** (see ownCloud admin page) 8.1.1
### Client configuration

**Browser:** Google Chrome 44.0.2403.157 (64-bit)

**Operating system:** Xubuntu 15.04
### How to solve

Don't request this url. Why do we need it? Let PHP do this for you.
or
Add `large_client_header_buffers 4 24k;` (http://nginx.org/en/docs/http/ngx_http_core_module.html#large_client_header_buffers) header to http/server section. You can replace `24k` with the most small value that makes this page work.

**Comment by oparoz** [comment]
It's already fixed in Gallery (8.2) and Gallery+ (8.0 & 8.1).

**Comment by PaulAnnekov** [comment]
@oparoz please, send a link to commit/pr.

**Comment by oparoz** [comment]
Here you go:
https://github.com/owncloud/gallery/commit/80c1016d8cd9bf2ab0e7e516f3074aea5c6a96a5

**Comment by PaulAnnekov** [comment]
@oparoz that's just what I wanted, good job :+1:
