### ISSUE TITLE
Remove the scrollbar when it's not required to have one

### ISSUE THREAD

**Issue by oparoz** [owncloud/gallery#289]
A scrollbar is showing up on the right, even if there are only a couple of pictures in the album. We need to figure out what triggers it and eliminate it.

**Comment by oparoz** [comment]
Use master to test

**Comment by ghost** [comment]
@rperezb test please?

**Comment by Dianafg76** [comment]
I tested this Issue, I Have used:
1. Firefox, it is working OK. The scroollbar you can see when have more than 25 Photos, it does not appear before.
2. Chrome, it is working OK. The scroollbar can see when they have more than 25 photos , it does not appear before.
3. Safary, it is working OK. The scroollbar can see when they have more than 25 photos , it does not appear before.
4. IE8, is an incompatible browser for gallery

Closed

**Comment by oparoz** [comment]
Many thanks.
