### ISSUE TITLE
link to gallery for folders

### ISSUE THREAD

**Issue by tessus** [owncloud/gallery#29]
Opening a new issue by request of @PVince81 in [owncloud/core #8268](https://github.com/owncloud/core/issues/8268)

When you share a folder, the link that is shown is always in the format:
`//example.com/public.php?service=files&t=49e186e1cfe7afd7f0bfe638aa5ff16d`

If you share a folder that holds pictures, you might want to share the link to the gallery instead.

What do you think of an additional checkbox (only for folders) that allows you to share the link as:
`//example.com/public.php?service=gallery&t=49e186e1cfe7afd7f0bfe638aa5ff16d`

PVince81: *This is a known issue but not sure how to solve it as it might involve knowing the contents of the folder/subfolder to decide what service to use.*

Not sure, if I understand the problem here. I'm not talking about changing the link automatically, just giving a user the option to use a checkmark when sharing a folder.
e.g. above the *Password protect* option.

![screen shot 2014-05-01 at 17 40 58](https://cloud.githubusercontent.com/assets/223439/2857552/600e7320-d179-11e3-92a8-f54d708a1f4e.png)

**Comment by oparoz** [comment]
This has been implemented via ShareLinks
https://apps.owncloud.com/content/show.php/ShareLinks?content=170527
