### ISSUE TITLE
Update the "no pictures found" landing page to be in line with Files

### ISSUE THREAD

**Issue by oparoz** [owncloud/gallery#290]
The default design includes a large icon and a friendly text and we should imitate that.

**Comment by jancborchardt** [comment]
Aaand ready to review https://github.com/owncloud/gallery/pull/372

**Comment by oparoz** [comment]
Not complete yet.

**Comment by jancborchardt** [comment]
Replaced by https://github.com/owncloud/gallery/issues/374 though?

**Comment by oparoz** [comment]
Absolutely. I later realised it was unrelated.
