### ISSUE TITLE
Gallery keeps loading with a spinner

### ISSUE THREAD

**Issue by davitol** [owncloud/gallery#292]
### Steps to reproduce
1. Go to the gallery app
### Expected behaviour

The pictures should be shown
### Actual behaviour

The spinner keep loading forever
### Server configuration

**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** mysql

**PHP version:** 5.5.9

**ownCloud version:"8.1.2.0","versionstring":"8.1.2RC1"

**Updated from an older ownCloud or fresh install:** Fresh install

**List of activated apps:**
nabled:
- activity: 2.0.2
- admin_audit: 0.6
- enterprise_key: 0.1.0
- files: 1.1.10
- files_locking: 
- files_pdfviewer: 0.7
- files_sharing: 0.6.2
- files_sharing_log: 0.5
- files_texteditor: 0.4
- files_trashbin: 0.6.3
- files_versions: 1.0.6
- files_videoviewer: 0.1.3
- firewall: 0.91.2
- firstrunwizard: 1.1
- gallery: 0.6.0
- provisioning_api: 0.2
- templateeditor: 0.1
- updater: 0.6
- windows_network_drive: 0.1.1

**Are you using external storage, if yes which one:** no;
**Are you using encryption:** no
**Are you using an external user-backend, if yes which one:** no
### Client configuration

**Browser:** Firefox

![captura de pantalla 2015-09-01 a las 17 43 36](https://cloud.githubusercontent.com/assets/10596560/9608915/0ef8d24a-50d1-11e5-9c9b-ff6874289003.png)

**Comment by ghost** [comment]
@oparoz could you please have a look?

**Comment by oparoz** [comment]
The problem is that there are too many ways the old "Pictures" can break. It could be because there is a SVG somewhere or a TIFF or too many files, etc. Gallery+ contains all the fixes, but it can't officially replace Pictures on older versions of ownCloud unless someone decides it's a good idea to make an exception.

So, the solution is to advise users to use Gallery+ on <8.2.

**Comment by SergioBertolinSG** [comment]
I'm facing same problem in 8.0.7.

**Comment by oparoz** [comment]
Yes, all version of ownCloud 8.x and 8.1.x have the same Pictures app which has been left mostly untouched for 9 months.

**Comment by Wikinaut** [comment]
I think, it's related to https://github.com/owncloud/gallery/issues/272  (Content security policy issues)

Javacript error console:

```
Zeitstempel: 07.09.2015 00:20:23
Fehler: Content Security Policy:
Die Einstellungen der Seite haben das Laden einer Ressource auf self blockiert
("script-src https://myserver 'unsafe-eval'").
Quelldatei: https://myserver/owncloud/index.php/apps/gallery/
Zeile: 0
Quelltext:
onchange attribute on DIV element
```

and more.

Perhaps important to know: The **galleryplus** app available via the owncloud app+ button works for me. See https://github.com/interfasys/galleryplus
