### ISSUE TITLE
Routes must not be used before app.php is fully loaded

### ISSUE THREAD

**Issue by RobinMcCorkell** [owncloud/gallery#293]
After some routing changes in ownCloud 8.2, apps must be loaded before app routes are loaded. This means that app.php cannot directly use any self-referencing routes, for example with the URLGenerator. This is an issue with the navigation entry registration, which tries to create a URL pointing to the gallery app.

The solution is to move the navigation entry generation to a closure that returns the array, so that loading the routes is delayed until the navigation entries are actually used. This will also increase performance.

**Comment by oparoz** [comment]
OK. Is there some reference implementation?

**Comment by RobinMcCorkell** [comment]
@oparoz It is literally just wrapping the array in a `function() { return [...];}`, then passing that to `->add()` instead of the raw array.

**Comment by oparoz** [comment]
Got it, thanks @Xenopathic :)
