### ISSUE TITLE
Add spinner to view change button

### ISSUE THREAD

**Issue by oparoz** [owncloud/gallery#309]
Extract the code from https://github.com/owncloud/gallery/commit/b9f7e91919832bf045100c2bd1706307fb9e984b

**Comment by oparoz** [comment]
Use the SVG spinner on the Gallery side as we don't care about IE8

**Comment by oparoz** [comment]
~~Use https://github.com/owncloud/gallery/pull/148 to test.~~ Available in master

**Comment by oparoz** [comment]
You're advised to use a custom CSS spinner if you want the effect to work on all modern browsers. Firefox stops GIF animations.

**Comment by jancborchardt** [comment]
Can you make it use `.icon-loading-small` instead, and replace the existing icon while loading? Currently it’s too big and looks strange when overlapping.

**Comment by oparoz** [comment]
16px is too small and without the original icon, it looks really weird. I picked 24px because it's just in between and fits nicely in the button. At the size, I don't find the overlay that strange, especially since it's only for less than a second. Again, without the original icon I feel like there is something missing.

**Comment by oparoz** [comment]
Try in F12 mode, you can easily hide and resize to see the difference.

**Comment by oparoz** [comment]
Maybe I could dim the original icon
