### ISSUE TITLE
Add flip effect to sorting buttons

### ISSUE THREAD

**Issue by oparoz** [owncloud/gallery#310]
Implement changes from https://github.com/owncloud/gallery/commit/a81f3bde49249c3fdedf77eab64c7ba165ea17c1

**Comment by oparoz** [comment]
~~Use https://github.com/owncloud/gallery/pull/148 to test.~~ Available in master

**Comment by jancborchardt** [comment]
Not sure how I feel about this. :D Just discovered it and it seems quite gaudy.

**Comment by oparoz** [comment]
I haven't had much feedback yet. It doesn't get in the way. It's just a hint.
I'd say let it sink in and we'll see in a few weeks.
