### ISSUE TITLE
File list refreshes after closing Gallery slideshow

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/gallery#313]
1. Open an image with the Gallery slideshow / detail view
2. Close it again

Expected:
You are able to seamlessly browse your pics again.

What actually happens:
The whole file list is very visibly reloaded. That’s confusing and rips you out of the flow.

@oparoz @schiesbn @PVince81 @MorrisJobke what can we do here? Same is true for the text editor cc @tomneedham 
##

**Comment by oparoz** [comment]
It's by design (https://github.com/owncloud/gallery/issues/160). Nothing can be done until core drops supports for IE8 and fixes the FilesList navigation.

**Comment by oparoz** [comment]
See https://github.com/owncloud/core/issues/14828

**Comment by jancborchardt** [comment]
Ugh, another reason to drop IE8 – it impacts the UX of everyone else. cc @MTRichards @karlitschek.

**Comment by karlitschek** [comment]
@jancborchardt Don't mention @MTRichards and me. It's not our fault. :-) Mention the 10% of all the people on the internet who still use IE8 ;-)

**Comment by jancborchardt** [comment]
I know – just mentioning to provide food for thought regarding when we drop support. 10% is not correct btw, it’s more like less than 3%: http://gs.statcounter.com/#browser_version-ww-monthly-201503-201508-bar ;)

**Comment by oparoz** [comment]
It's 10% of enterprise users ;). Given the fact that these corporations are 3-5 years behind consumer environments and have completely different needs, ownCloud will always be behind other consumer oriented products, unless there is a cheap way to keep all the patches required for the enterprise (IE8, IE9, etc.) in a separate branch. It kills the experience for the rest of us, but then without those enterprises supporting ownCloud, we wouldn't have a product to hack... Hopefully one day, oC will be big enough to be able to maintain 2 separate trees.

**Comment by oparoz** [comment]
The other option, of course, is to always give enterprises a 3-5 year old ownCloud version and to backport security fixes ;)

**Comment by karlitschek** [comment]
Guys. Can we stop this discussion please? This is the real world: https://www.netmarketshare.com/browser-market-share.aspx?qprid=2&qpcustomd=0
And if ownCloud wants to care about real users then we have to care about IE8. This is just how it is.
We have to and will support is until the marketshare has dropped significantly. And no, we can't do this in a separate branch. This would mean that we have to release a different app in parallel which would mean that we have effectively two apps. One which is in our server release and supports IE8 and a different one which is your cool gallery but is not the default. 
We all want to avoid this because this would be the old situation with gallery plus.
So the only option is to support IE8.
Can we all please accept this reality now? Thanks!

**Comment by MorrisJobke** [comment]
I adjusted the milestone to the core ticket milestone. - cc @cmonteroluque

**Comment by jancborchardt** [comment]
Also tagging as bug rather than enhancement since it also closes the sidebar if one was open.

**Comment by ghost** [comment]
@MorrisJobke thanks

**Comment by oparoz** [comment]
I've taken a look and I don't know how to fix it.
There is a secret handshake hidden in Files which prevents that behaviour, but it would be better if apps didn't need to do anything.

How to verify it's not a bug in Gallery:
1. install files_texteditor
2. click on a text file
3. click on the back button in the browser
4. click on an image
5. click on the back button in the browser

No reloading happened this time. You can even change folder and open as many images as you want. Files will never reload again. It's the same on 8.2.

@PVince81 @MorrisJobke What's the secret password? :)

**Comment by oparoz** [comment]
And if you upload a file, it breaks again.

**Comment by jancborchardt** [comment]
@owncloud/javascript can you check this out? It's disrupting the UX.

**Comment by oparoz** [comment]
This issue was moved to nextcloud/gallery#72
