### ISSUE TITLE
Images and folders doesn't load

### ISSUE THREAD

**Issue by LEDfan** [owncloud/gallery#322]
### Steps to reproduce
1. Install the latest git version of gallery
2. Load the gallery app
### Expected behaviour

All directories with images are shown. All images are loaded
### Actual behaviour

Not all directories are listed and no images are loaded (the spinner keeps spinning).
![selectie_115](https://cloud.githubusercontent.com/assets/2996275/9830058/8f1f47a4-5920-11e5-9e77-8745648abdde.png)
### Server configuration

**Operating system**: Centos 7

**Web server:**  

```
Server version: Apache/2.4.6 (CentOS)
Server built:   Aug 24 2015 18:11:25
```

**Database:**

```
mysql  Ver 15.1 Distrib 5.5.44-MariaDB, for Linux (x86_64) using readline 5.1
```

**PHP version:** PHP-FPM

```
PHP 5.6.12 (fpm-fcgi) (built: Aug  9 2015 08:48:29)
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2015 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2015, by Zend Technologies
```

**ownCloud version:** 8.1.1

**Updated from an older ownCloud or fresh install:** Several updates 

**List of activated apps:**
Enabled:
- calendar: 0.7.3
- contacts: 0.4.0.0
- files: 1.1.10
- files_pdfviewer: 0.7
- files_sharing: 0.6.2
- files_texteditor: 0.4
- files_trashbin: 0.6.3
- files_versions: 1.0.6
- files_videoviewer: 0.1.3
- gallery: 14.0.0
- mail: 0.3-alpha
- news: 6.0.1
- updater: 0.6
  Disabled:
- activity
- encryption
- external
- files_external
- files_locking
- firstrunwizard
- provisioning_api
- templateeditor
- user_external
- user_ldap
- user_webdavauth

**The content of config/config.php:**

```
$CONFIG = array (
  'instanceid' => '',
  'passwordsalt' => '',
  'trusted_domains' =>
  array (
    0 => 'xx',
  ),
  'datadirectory' => '/srv/xxx/data',
  'dbtype' => 'mysql',
  'version' => '8.1.1.3',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'owncloud',
  'dbpassword' => '',
  'installed' => true,
  'theme' => '',
  'maintenance' => false,
  'maxZipInputSize' => 0,
  'allowZipDownload' => true,
  'secret' => '',
  'forcessl' => true,
  'asset-pipeline.enabled' => true,
  'appstore.experimental.enabled' => true,
  'app.mail.imaplog.enabled' => false,
  'app.mail.server-side-cache.enabled' => true,
);

```

**Are you using external storage, if yes which one:** No

**Are you using encryption:** No

**Are you using an external user-backend, if yes which one:** No
### Client configuration

**Browser:** Firefox 40.0.3 and chrome

**Operating system:** OpenSUSE 13.2
#### Web server error log

```
Nothing in here
```
#### ownCloud log (data/owncloud.log)

```
Nothing relevant
```
#### Browser log

```
Content Security Policy: De instellingen van de pagina blokkeerden het laden van een bron op data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAMgAAADICAYAAACtWK6eAAAgAElEQVR4nOydd1xUR9f4v3cru5SFZekdAQULNsTeY42Jpqgx0cT0njc+T3o1/cmT+qSYakkxaixRo8ZeUGPHClhAQUFAel+2/f5YyrLcu0Bikvf9PTmfD+y9M2fOOXNmzpyZM3PvFWIW5NhsNhuCIGCzggDYsNkv7P8QBLDZaAE2hwRBEGikATawNuA0k2iBi9XWwKOBsNAS0WazNcjhVLYpv+GugW8zWBvwZGADm4CDXI0SNfBsyG9ZqeZsGv4ay9qapLFhszXKLTTLabOJK6qRrODA14GxINilFhrrJVK+qfIOWU1t1lDQTlHWoI+GPFtzpWw2WsrnWHebnV6jLpv11dDOLURy1nkTYqv2apndTLup/aTK2mwIje3npAJsNmw2WcviTXW0IbM187OzERBwrkMzjl2tQtN1yz4loHi0dpOLav13QoOdNN1INrxzhsse0vArgPOg0QRS6X8KtKi1Q1ojuMr7XwSN1XDU9+8QVdhx5Nz/0pr+DX/DXw8KhL902Pob/obfBTarleKiMurrTR0uq1Yr0fv6YLNZqCgrw2q1tsJRyP42kL/h/zAUXilD56VB7ebd4bK1NXWUFJchE0wEBAQgyGStcBSXL+cSFhYBxlLyamxUnj9HlVVOp249UVTlUmLRER6go7o0H6PCB72nmvqqIk6fycQ7LIEwP0+wGDl3Jo0qk5zY+B64KwGbmeyzJykzedCtawxyAFs9Z46noglOQFF1gbxyOd0T47h0KhWLVwQx4f6UXMoEnzB83VV2Cc3VpKdnYFP70Tku3E7nb/gbGsAGqNRqzK0H/zZBpVYh1NQjk8lQqtTUmyxNe
TypeError: img is null
```

![selectie_116](https://cloud.githubusercontent.com/assets/2996275/9830093/748a7660-5921-11e5-8361-cdf715f59489.png)

**Comment by oparoz** [comment]
Thanks for the report.
This should be fixed if you're using master at interfasys/galleryplus.
