### ISSUE TITLE
Download button may need some love

### ISSUE THREAD

**Issue by oparoz** [owncloud/gallery#328]
![slideshow_ui](https://cloud.githubusercontent.com/assets/323220/9833458/eab0e010-5997-11e5-9a8b-61c92fbfb7db.png)

So the slideshow UI is using the standard download icon, but maybe something needs to be done to make its role more obvious.

I would change it in core if I were in charge of the design, adding a line underneath, like we see in many places.
If it doesn't matter if the icon is different in Gallery, then maybe we can fix this quickly.

@jancborchardt

**Comment by jancborchardt** [comment]
Closing this in favor of https://github.com/owncloud/gallery/issues/349 (move actions to bottom, next to filename) cause it has a specific solution. :)
