### ISSUE TITLE
Override core's css which makes the share dropdown jump to the left

### ISSUE THREAD

**Issue by oparoz** [owncloud/gallery#329]
This is making the share dropdown jump to the left
https://github.com/owncloud/core/commit/8b2e09a77e22d234b48ee572b13e69001f1a3e54

We need to override it.

**Comment by oparoz** [comment]
Available in master.
1. Open the share dialogue 
2. Resize the window so that it's less than 990px wide

The dialogue should stay on the right

@jancborchardt @setnes @demattin

**Comment by oparoz** [comment]
It's impossible to test this right now and the share button will probably have to be removed as the logic we use has been removed from core.

**Comment by oparoz** [comment]
@cmonteroluque - This will be automatically fixed as soon as #359 is fixed, which is targeted for 8.2, so I'm putting it back on 8.2

**Comment by ghost** [comment]
@oparoz ok, reviewed
