### ISSUE TITLE
Load SVG media type icons

### ISSUE THREAD

**Issue by oparoz** [owncloud/gallery#331]
The PNGs look horrible because they're too pixelated, so we need to load the SVGs.

These will be swapped with the ugly ones on Internet Explorer.

**Comment by oparoz** [comment]
Available in master.
Upload a corrupt JPG and you should get a nice SVG icon instead of the preview.
@jancborchardt @setnes @demattin

**Comment by jancborchardt** [comment]
So, we can close this @oparoz? :)

**Comment by oparoz** [comment]
Yes, you can follow up here: https://github.com/owncloud/gallery/issues/334
