### ISSUE TITLE
SVG icons are not resized on IE

### ISSUE THREAD

**Issue by oparoz** [owncloud/gallery#334]
![tiny](https://cloud.githubusercontent.com/assets/323220/9836787/c0726e38-5a26-11e5-9e60-66ab04a086d1.png)
##

**Comment by oparoz** [comment]
The solution is to use the PNGs on IE.

**Comment by karlitschek** [comment]
@jancborchardt any idea?

**Comment by oparoz** [comment]
It's a known issue
http://caniuse.com/#search=svg

> IE9-11 desktop & mobile don't properly scale SVG files. Adding height, width, viewBox, and CSS rules seem to be the best workaround.

One solution in order to keep SVGs for IE is to fix all the media type icons in core.

**Comment by oparoz** [comment]
Keeping open, in case someone wants to play with SVG and IE.

**Comment by oparoz** [comment]
In order to see the difference, you need to upload a broken JPG to a folder and to load that folder in Gallery in both Firefox and IE. One will use the SVG icon, the other the fallback.

**Comment by oparoz** [comment]
This issue was moved to nextcloud/gallery#74
