### ISSUE TITLE
Align the controls' colours with the photowall background

### ISSUE THREAD

**Issue by oparoz** [owncloud/gallery#335]
### Solution 1
- All the elements in the controls have to be made transparent
- We need 2 sets of icons, one for light, one for dark backgrounds
- We need an auto-luminance algorithm, just like for #84 in oder to be able to pick the right set of icons

This needs to be merged first: 
- [x] https://github.com/owncloud/gallery/pull/148
##

**Comment by jospoortvliet** [comment]
Instead of auto-luminance, can't you pick white and use a shadow around the icons? That should work in 99% of the situations...

**Comment by oparoz** [comment]
Except that shadows don't exist any more in ownCloud. Everything is now super flat.

**Comment by jospoortvliet** [comment]
Dark outline then... I mean, there's no decent other way. @jancborchardt other ideas?

**Comment by oparoz** [comment]
This issue was moved to nextcloud/gallery#75
