### ISSUE TITLE
Use a higher quality spinner

### ISSUE THREAD

**Issue by oparoz** [owncloud/gallery#336]
The one we use from core simply doesn't cut it. It's very pixelated and has jagged edges.

**Comment by oparoz** [comment]
Available in master. You'll notice it in the photowall, slideshow and infobox
@jancborchardt @setnes @demattin

**Comment by jancborchardt** [comment]
@oparoz sorry what, did you change the spinner in the Gallery app? We should keep in line with core. We can change it to a better spinner with 9.0.

**Comment by oparoz** [comment]
It looks the same, but with less problems. It can be altered slightly maybe if you think it's too big, etc.

**Comment by jancborchardt** [comment]
@oparoz ah ok! Can you also change it in core then? And can you link to the change so I can check it? :)

**Comment by oparoz** [comment]
Here you go: https://github.com/owncloud/gallery/commit/4ae75cb14ca8078b240c387a45b0b9ccc67169be

Fairly easy to implement once you understand how it works, but it's not as simple as adding the GIF as a background-image.

**Comment by oparoz** [comment]
One think I like is that you can decide if you want to hide or remove the element. There may be advantages to each situation.

**Comment by jancborchardt** [comment]
@oparoz hmm … sorry but that spinner doesn’t look good or similar to the current one – it’s too bulky.

Can you revert that change please? My plan for 9.0 is to move to a more modern and high-res spinner anyway. But for 8.2 we shouldn’t do such a strange cosmetic change only in the Gallery app.

**Comment by oparoz** [comment]
No need to revert, you can make it look exactly like the old one:

https://fgnass.github.io/spin.js/

**Comment by oparoz** [comment]
Default values

```
  var defaults = {
    lines: 12             // The number of lines to draw
  , length: 7             // The length of each line
  , width: 5              // The line thickness
  , radius: 10            // The radius of the inner circle
  , scale: 1.0            // Scales overall size of the spinner
  , corners: 1            // Roundness (0..1)
  , color: '#000'         // #rgb or #rrggbb
  , opacity: 1/4          // Opacity of the lines
  , rotate: 0             // Rotation offset
  , direction: 1          // 1: clockwise, -1: counterclockwise
  , speed: 1              // Rounds per second
  , trail: 100            // Afterglow percentage
  , fps: 20               // Frames per second when using setTimeout()
  , zIndex: 2e9           // Use a high z-index by default
  , className: 'spinner'  // CSS class to assign to the element
  , top: '50%'            // center vertically
  , left: '50%'           // center horizontally
  , shadow: false         // Whether to render a shadow
  , hwaccel: false        // Whether to use hardware acceleration (might be buggy)
  , position: 'absolute'  // Element positioning
  }
```

**Comment by oparoz** [comment]
This looks pretty similar:
https://fgnass.github.io/spin.js/#?lines=13&length=5&width=3&radius=8&scale=1.00&corners=1.0&opacity=0.25&rotate=0&direction=1&speed=0.8&trail=60&top=50&left=50&hwaccel=on

The main difference being that the GIFs has pointier ends

![new_spinner](https://cloud.githubusercontent.com/assets/323220/9885401/476887e6-5be5-11e5-8b5d-f2a2a9f78b66.png)

**Comment by jancborchardt** [comment]
@oparoz sorry, but as I said, this is not a time for a core shipped app to just decide and digress in this fashion.

We will switch to a better (and way simpler, entirely different spinner) with 9.0, similar to this maybe (of course better quality and scalable etc.):
![](http://www.designbrooklyn.com/images/loading_icon1.gif)

But for the nearing 8.2 release I ask you to switch back to the spinner like we use in core. Thank you.

**Comment by oparoz** [comment]
I don't get it because there is virtually no visual difference with the GIF and it has zero impact on core. Nobody will see the difference, so why is it so important?

**Comment by oparoz** [comment]
And I did get a thumb up:
https://github.com/owncloud/gallery/pull/337#issuecomment-139896247

**Comment by jancborchardt** [comment]
Something like a spinner change should be done in core instead of in an app. Sorry but especially shipped apps should not go rogue with changes like these, especially when it’s introducing a whole JS library for something as simple as a spinner.

cc @karlitschek @DeepDiver1975

**Comment by oparoz** [comment]
Yes, but it's not a change as far as the user is concerned, that's the reason I don't see how this is so important

![](https://cloud.githubusercontent.com/assets/323220/9885401/476887e6-5be5-11e5-8b5d-f2a2a9f78b66.png)

I've used a library to make sure I could get it to work in all browsers. The GIF was probably originally picked so as to not have to deal with that, but it's got all the limitations of a GIF.

**Comment by jancborchardt** [comment]
Yes, but as said there are several problems:
- digression from core – changes like these should be done in core, not in apps, because the spinner is used _everywhere_
- usage of a JS library where one simple gif is enough
- the fact that we will move to a better spinner for 9.0 anyway

Hope that clears it up. Yes, the existing gif might not be perfect, but this is something to fix in core, not in Gallery alone and still have core look imperfect.

**Comment by jancborchardt** [comment]
Core issue opened at https://github.com/owncloud/core/issues/19091

**Comment by oparoz** [comment]
OK, so it's more about politics then. GIFs don't work, so a JS lib is necessary if you want IE8 compat.
Core doesn't look that bad with the current one, but it's because you control the environment and it's white or black. Apps use different colours, users theme their ownCloud, etc. and it's in those circumstances that the GIF shows its limitations, so the goal of the new spinner was to avoid letting down users when they see that ugly one on top of their red background.

Also, apps and users can't theme a GIF...

**Comment by jancborchardt** [comment]
It’s more about proper collaboration and doing stuff in core. I wouldn’t call that just politics.

> Also, apps and users can't theme a GIF...

Yes they can, by replacing the file in their theme – which is done already. And actually the Gallery app implementing its own spinner creates a problem for these people because they need to recreate their custom spinner with spin.js.

**Comment by oparoz** [comment]
> Yes they can, by replacing the file in their theme – which is done already.

Too much work to just change the colour per example.

> And actually the Gallery app implementing its own spinner creates a problem for these people because they need to recreate their custom spinner with spin.js.

It's true that if someone has taken the time to design a killer CSS3 spinner in his theme, he may not like not seeing it in Gallery. **That** I find to be a valid reason, thanks.

**Comment by jancborchardt** [comment]
Thanks. Core and Gallery need to work hand-in-hand on stuff like this.
