### ISSUE TITLE
Restart GIF animations after a download on Firefox

### ISSUE THREAD

**Issue by oparoz** [owncloud/gallery#338]
On Firefox, GIF animations stop as soon as you download a file. They don't restart until you refresh the browser.
##

**Comment by virajparimi** [comment]
I would like to work on this one. Could we just reload the page when gif is downloaded? I know it's not a great idea so could you guide me further on it?

**Comment by oparoz** [comment]
> Could we just reload the page when gif is downloaded? 

No, that's not a good thing to do to users

> could you guide me further on it?

Unfortunately, I have no idea how to fix this as I haven't looked into it. Since it's specific to Firefox, try to look in the MozillaDN to see if there is a special JS method or some CSS we could use.
You can also search and ask on stackoverflow. It must not be the first time someone has encountered that issue.

**Comment by virajparimi** [comment]
@oparoz  Could  we use something of this sort [-->](http://stackoverflow.com/questions/14295244/animated-gif-wont-work-properly-in-chrome/21944730).
The 2nd answer.

**Comment by oparoz** [comment]
Sounds interesting. I'll let you test :)

**Comment by virajparimi** [comment]
@oparoz  How is the image's source in bigshotcontainer class created and where is it created. Could you help me out there as I am stuck.

**Comment by oparoz** [comment]
This should help:
https://github.com/owncloud/gallery/blob/master/js/slideshow.js#L101-L129

**Comment by oparoz** [comment]
This issue was moved to nextcloud/gallery#76
