### ISSUE TITLE
Add help button to slideshow with shortcuts description

### ISSUE THREAD

**Issue by oparoz** [owncloud/gallery#340]
People don't RTFM and rely on in-app help. We should provide a simple way for users to learn about shortcuts.
I'm thinking a help button which reveals the list of shortcuts.

@jancborchardt - We need an icon and a `core` GUI component for the dropdown. Thanks! ;)
##

**Comment by jancborchardt** [comment]
The standard shortcut to reveal other shortcuts is pressing `?`. Used by Github, Gmail, etc. Thanks to @Raydiation for pointing that out.

There should be no permanent UI element for this.

**Comment by oparoz** [comment]
Nobody knows that standard shortcut. People won't know they can zoom in per example unless they accidentally scroll the mouse, etc.

But the UI doesn't need to be permanent. We can apply the same technique used on 500px which rapidly shows that there are short-cuts available.

I also like the first run transparent overlays that some apps are using, but that wouldn't really work for public pages.

**Comment by jancborchardt** [comment]
@BernhardPosselt, not @raydiation

@oparoz ok, yeah, we could do it like for 500px. I thought you meant keyboard shortcuts.

**Comment by BernhardPosselt** [comment]
Check the news app's setting menu ;)

**Comment by oparoz** [comment]
@jancborchardt I'm talking about these shorcuts

![chocolate](https://cloud.githubusercontent.com/assets/323220/9919542/f8f2141c-5ccd-11e5-88ec-449e12ba5668.png)

**Comment by oparoz** [comment]
This issue was moved to nextcloud/gallery#77
