### ISSUE TITLE
Adapt authenticate template to match the one in `core`

### ISSUE THREAD

**Issue by oparoz** [owncloud/gallery#343]
The CSS in core has changed and so the authentication page now doesn't look great.

@jancborchardt Do you know which changes broke it?

**Comment by oparoz** [comment]
Never mind, found the subtle change :)

**Comment by oparoz** [comment]
Fix is in https://github.com/owncloud/gallery/pull/342 for now. It now looks exactly like the Files equivalent
@setnes @demattin

**Comment by jancborchardt** [comment]
@oparoz as soon as fixes are in master, you can close the issue btw. ;)

**Comment by oparoz** [comment]
Well, I'm forced to take a different approach with Gallery... There are not enough testers with the tools and the time to test the PRs, so we end up with dozens of out-of-sync PRs and it's a nightmare to maintain. So I went back to the way I did things on Gallery+. After I test them as much as I can and after a few days of waiting I merge them (if they're within my area of expertise) and label them so that people know it's something which still needs to be tested. That also has its cons, but I find it easier on everybody.

**Comment by oparoz** [comment]
So I'm re-opening until someone confirms the password asking page looks OK and will eventually close this if nobody complains before the launch date since it's a trivial, visual change.

**Comment by jancborchardt** [comment]
@rperezb make sure this also gets tested by QA please.

**Comment by oparoz** [comment]
> @rperezb make sure this also gets tested by QA please.

Yes, basically, all issues labelled QA can be reviewed at any time.

**Comment by oparoz** [comment]
1. Create a link to a share
2. Add a password to it
3. Modify the link so that instead of `index.php/s` you have `index.php/apps/gallery/s`
4. Visit the modified link

**Comment by Dianafg76** [comment]
I tested this issue with this options:

| Test case | Browser | Result |
| --- | --- | --- |
| Share from the Gallery a folder | Firefox, Chrome, Safary | OK |
| Share with password | Firefox, Chrome, Safary | OK |
| Share with expiration time | Firefox, Chrome, Safary | OK |
| Share with password and expiration time | Firefox, Chrome, Safary | OK |
| Force from admin to share with password | Firefox, Chrome | OK |
| Force from admin to share with password | Safary | NOK (https://github.com/owncloud/gallery/issues/399) |

Minor bug: 
- Expiration time date don't follow the same format as core https://github.com/owncloud/gallery/issues/398

**Comment by oparoz** [comment]
Thanks for the report, I'm going to close this, since this issue was about the button design. We will keep #399 open until this is resolved.
