### ISSUE TITLE
Malformed SVG breaks gallery

### ISSUE THREAD

**Issue by LukasReschke** [owncloud/gallery#346]
A SVG file with invalid SVG breaks a whole gallery album.

```
Uncaught TypeError: Cannot set property 'alt' of null(anonymous function) @ galleryimage.js?v=58e6c41db6cb9e4292f27caf8b86a008:87(anonymous function) @ jquery.min.js?v=58e6c41db6cb9e4292f27caf8b86a008:4x.Callbacks.c @ jquery.min.js?v=58e6c41db6cb9e4292f27caf8b86a008:4x.Callbacks.p.fireWith @ jquery.min.js?v=58e6c41db6cb9e4292f27caf8b86a008:4x.extend.Deferred.x.each.i.(anonymous function) @ jquery.min.js?v=58e6c41db6cb9e4292f27caf8b86a008:4Thumbnails.loadBatch.eventSource.listen.thumb.image.onerror @ thumbnail.js?v=58e6c41db6cb9e4292f27caf8b86a008:135
```

**Comment by oparoz** [comment]
Thanks :)

**Comment by oparoz** [comment]
So it's actually a general problem. When an image fails to load, it will not be usable later on, so I'm now showing the media type icon, letting the user download the file

**Comment by oparoz** [comment]
A broken SVG you can use to test:
https://oc8demo.interfacloud.com/index.php/apps/galleryplus/s/q6j106oXEF5bi2q/53739.svg

You need to enable native_svg first in your gallery.cnf

**Comment by oparoz** [comment]
This requires https://github.com/owncloud/gallery/pull/391 to work properly as SVGs containing an evil payload can still stop the rendering.

**Comment by ghost** [comment]
@rperezb @SergioBertolinSG @davitol can you please test?

**Comment by rperezb** [comment]
@Dianafg76 will take care of this one, I am currently working with her, thx

**Comment by rperezb** [comment]
Checked, it doesn't break the gallery

File used: https://s3.owncloud.com/owncloud/index.php/s/MD4hOi7Fqv9o4WL
(The suggested one doesn't work)

Server version: ownCloud 8.2 beta1 (daily) Build:2015-10-02T03:39:51+00:00 f891b91cf8475eee16ab1ca08869430bd2dbe51b

**Comment by oparoz** [comment]
> (The suggested one doesn't work)

Can't download it? What kind of error are you getting?

**Comment by rperezb** [comment]
Ummm, on Friday it didn't work, I got a connection error..

Today I have downloaded it, and it works fine, meaning this, the gallery is not broken

**Comment by oparoz** [comment]
Cool, thanks :)
