### ISSUE TITLE
extension_loaded('xdebug') -> error when c3.php file not present

### ISSUE THREAD

**Issue by mmattel** [owncloud/gallery#355]
On my test server (Ubuntu 14.04, mysql, nginx), where I did not change the settings for a long time.
I cloned owncloud to test, from git with `sudo ocdev setup base --dir xxx`

After enabling galley+

-- I got continuios error messages logged  = log pollution --

The error is triggered from `appinfo/application.php` https://github.com/owncloud/gallery/blob/master/appinfo/application.php#L19

I have looked if the file c3.php is present on my system but it is not.
The error did not raise before when I cloned from git.

Maybe it would be a good thing to check for file presence first before trying to load it.

```
Error   PHP include_once(): Failed opening '/xxx/apps/gallery/appinfo/../c3.php' for inclusion (include_path='/xxx/3rdparty/phpseclib/phpseclib/phpseclib:/xxx/3rdparty/pear/console_getopt:/xxx/3rdparty/pear/archive_tar:/xxx/3rdparty/pear/pear_exception:/xxx/3rdparty/pear/pear-core-minimal/src:/xxx/lib/private:/xxx/config:/xxx/3rdparty:/xxx/apps:/xxx/lib:.:/usr/share/php:/usr/share/pear:/xxx') at /xxx/apps/gallery/appinfo/application.php#20

Error   PHP include_once(/xxx/apps/gallery/appinfo/../c3.php): failed to open stream: No such file or directory at /xxx/apps/gallery/appinfo/application.php#20
```

I had xdebug installed, but it was not activated in any php.ini. After uninstalling xdebug, the error messeges disappeard

**Comment by oparoz** [comment]
> I had xdebug installed, but it was not activated in any php.ini. 

I doubt it. There are so many ini files in PHP, that it's possible that it was activated somewhere without you knowing it. 

> Maybe it would be a good thing to check for file presence first before trying to load it.

Indeed.
