### ISSUE TITLE
Buttons jump to second row in portrait mode

### ISSUE THREAD

**Issue by oparoz** [owncloud/gallery#357]
The breadcrumb takes half the screen and there is no room for the 5 buttons.

All action buttons should be behind 3 dots and we should only keep the info button.

@jancborchardt

**Comment by deMattin** [comment]
Yes, a good point.
But it should only be done, if complete browser width is benath a width of xxx px?!
(maybe also _info_ could go in the 3dot menu)

**Comment by oparoz** [comment]
> But it should only be done, if complete browser width is benath a width of xxx px?!
> Yes, just like the breadcrumb
> 
> (maybe also info could go in the 3dot menu)

We're all going to have an argument about which buttons to keep :D. I thought about users landing on a public gallery. They only care about sorting and info, but a files owner may only care about view switcher and sharing...

**Comment by deMattin** [comment]
Watching on small widths smartphones is no "normal" useage I think.
And with all buttons in 3dot menu, you see more of the breadcrump, which is mostly cropped.
So I suggest, NO button to keep - only 3dot menu fo _small screens_.

For wide screens as many buttons as possible should be shown and breadcrump rules, how much space is left.
Then it only is to discuss, which buttons should be hidden in menu first if space goes smaller ... ;)

**Comment by oparoz** [comment]
> And with all buttons in 3dot menu, you see more of the breadcrump, which is mostly cropped.

It's true that it isn't very useful if you have half the folder name

> Watching on small widths smartphones is no "normal" useage I think.

I have no idea which percentage of users open the link in their smartphone....

**Comment by jancborchardt** [comment]
As I said in another issue. ;) too many buttons, yes put them in a 3-dots-menu.

The info button should be inside there too, the only action outside should be sharing, as in Files.

**Comment by deMattin** [comment]
_Grmpf_ ... :/
`... sharing, as in files.`

There is no sharing button in files app. I see `gallery switch`, `new` and `upload` buttons in a row with breadcrump.
And in files app next to files and folders there is `download` and `share` and you get more actions with a long press on file/folder.

The cropping of path and sometimes completely not showing any path (because folder is longer than 2 handfull of characters) for more or less rarely used buttons isn't a good idea for _any_ app with breadcrump.
Navigation (going in parent folder) is nearly always impossible in files app because breadcrump is cropped! You have to either use home symbol and navigate from scratch or use the back button of smartphone.
Giving files app as reference isn't really a good idea for breadcrump design on small devices, because it also needs a rework to enable navigation there in portrait mode.
There's also too many waste of space between foldernames and `>`sign between them and it sometimes uses second row for buttons.
This is the reason why for me smartphone useage of files app isn't very important and I see me to be forced to use ownloud app, with a smoother navigation without breadcrump.

Two solutions might work (also for files app):
- always one single row with breadcrump and a second row with buttons
- if only one row, there should be only one 3dot button at all and the parent folder has always to be navigateable

So I vote for all buttons in a 3dot menu on small width - in files and gallery app!
_Anders ist es nichts Halbes und nichts Ganzes ..._ ;)

**Comment by jancborchardt** [comment]
@deMattin about the sharing button in breadcrumbs see https://github.com/owncloud/core/issues/4333
Navigation with the breadcrumbs on mobile is an entirely different topic. You are right that it’s difficult, but it’s also a difficult problem to solve. Help welcome.

**Comment by deMattin** [comment]
Ok, sorry for not knowing that.
I thought the topic has been the view on small devices like smartphones.
On PC or high res tablets I see no problem there with some buttons in the row as long as you see actual folder and one folder up and home symbol.

For smartphone navigation I like the approach from owncloud app only showing actual folder name and a small folder up button. And in this case, only one menu button should be shown with all actions in.
There's no space for a share or any other button next to a menu button if you want to see more than "..." of breadcrump or want to see more than a handful of letters of actual folder name.

But I don't know how to implement this, because it should be a smooth switch if you scale smaller from shortening breadcrump at first and than putting buttons one by the other in 3dot menu and at last only showing small folder up button, actual folder and 3dot menu.

BTW: because actual master of gallery is forcing to use oc 8.2 core I'm out of testing actual master because I have no test installation with master developer core. But I plan to set up such a test environment on server in some weeks.

**Comment by oparoz** [comment]
@deMattin - Use stable8.1 of Gallery+ it's up to date with the latest changes from here. Or if you want to experiment with 8.2, download the VM and replace 8.1.3 with a clone of master. It's pretty straight forward and portable :)

**Comment by deMattin** [comment]
I will go on holliday in some days for very long 3 weeks and after that, I will set up a VM with developer core. Thanks for your tipps.

**Comment by oparoz** [comment]
Regarding the issue at hand, I'll probably go for a ribbon interface scrolling down as a 2nd controls row. It's very convenient to use and could offer everything we don't need right away, leaving plenty of room for the breadcrumb.

**Comment by jancborchardt** [comment]
@oparoz can you illustrate what you mean? Best would be an action popover like for the file actions in Files, to be consistent.

**Comment by oparoz** [comment]
I'll do a mockup.
The problem with the vertical dropdown is that you need 2 clicks for every action whereas with the permanent 2nd row, the actions are there, if you want them, or you quickly hide them if you need the space.

BTW, I get horrible scrolling performance in the Files app because the controls keeps jumping all over the place. What's different in terms of CSS for that row in 8.2?

**Comment by jancborchardt** [comment]
@oparoz well, just try out 8.2 ;)

The point with the dropdown is that it needs to be consistent. Please don’t work on a homebrew solution for Gallery.

**Comment by deMattin** [comment]
What's the problem, if gallery leads to a new and innovative design and other apps follow ... ;)

**Comment by oparoz** [comment]
> @oparoz well, just try out 8.2 ;)

@jancborchardt - No, but I mean I get that horrible behaviour on 8.2, on a mobile device. I know there's been issues in the past with fixed elements, but I don't have the problem on the Gallery side, so I'm wondering what has changed.

**Comment by jancborchardt** [comment]
> What's the problem, if gallery leads to a new and innovative design and other apps follow ... ;)

@deMattin We can do that, but in a planned fashion, and as part of the feature development in the dev cycle (_not_ in the bugfixing phase before the release). Gallery is shipped by default and a pretty prominent app, so we need to make sure core and gallery are in line. ownCloud is used by millions of people, so we have to make sure it works and looks properly.

**Comment by deMattin** [comment]
@jancborchardt: Agree, not to be a topic for bugfixing phase!

Gallery can have many possible and useful features, and surely needs some possibilities for settings or switches. So it should be found a solution, that fits for other apps also, if there will be the need (later), too.

But one point: Clean and fitting GUI doesn't needfully be seen such hard, I think.
I use Rainloop integrated in owncloud for a long time now (longer than official owncloud integration by using "external app" feature) and it feels very well integrated and as a native part of owncloud.
A mailing app is something others than a files app or a gallery app and it doen't feel wrong, if there are some GUI elements, that are specific for that special app.
Only the corresponding features like download, share or something like that should look and being used the same way in all apps if possible or needed - and for sure the look or theme.
BTW: I hope rainloop will some time get "approved" state. It's a great enhancement, working very stable especially for more than 2 mail accounts, that actual developing owncloud mail app doesn't intend to be used for.

**Comment by oparoz** [comment]
@jancborchardt - Yes, this is definitely for 9.0. Ideally it would be a public UI element in core, but it might be given birth here if found to be of use.

**Comment by jancborchardt** [comment]
@deMattin well, you should try out ownCloud Mail: https://github.com/owncloud/mail/ – it has significantly more integration on both a functionality & look level. An embedded app will never feel as smooth and seamless.

**Comment by deMattin** [comment]
@jancborchardt You should have a look at rainloop. Comparing owncloud Mail with rainloop is like Comparing Outlook Express with Outlook... 
Rainloop is an owncloud app, uses addressbooks of oc and supports endless Accounts. I have installed both, but oc Mail is a Horror with more than 2 Accounts and rainloop hast much more features. 
But for sure it will be neuer get approved because of a well designed gui, that probably doesn't care of oc guidelines and never will.

**Comment by oparoz** [comment]
Well, Rainloop uses its own design and probably "only" has connectors to some of ownCloud' services. It could just as well be hosted on another server if I'm no mistaken. You definitely notice that the environment is different when switching between Files and Rainloop.
Mail is of alpha quality. It's a young project. We should give it some time.

I don't understand why people are obsessed with having a mail app on top of a sync and share solution which doesn't support push and can't sync over a single channel , but those apps are popular, so the demand is clearly there.
I'd be much more interested in being able to archive my emails on ownCloud or to be able to browse my owncloud from my mail client's compose window (that works if you think what you need to a local folder of course, but not from Horde per example).

**Comment by deMattin** [comment]
It's really offtopic ... ;)
Rainloop is a real owncloud app AND has the possibility to work as a standalone install (which is first and main branch but in code sync with oc install, if you install correct licence and with update possibility in admin panel of rainloop -> no git or oc app update neccessary!).
Admin settings are made in admin panel of oc and an enhanced admin panel with dozens of settings and nothing looks like "a foreign iframe".
For sure it looks other than files app - it's a mail app! But it doesn't feel or look wrong there.

Deepdiver posted, that his app is for 1-2 accounts. The GUI is set to this and is horrible (scrolling, overview) if you want to use more and so it will be a "mailer light" also in future.
And rainloop is years ahead in development and developer is fully active and very fast with (bug) fixes.

Rainloop is imap and for push notify I have my smartphone. Rainloop uses oc contacts database (perfect search!) and imap is actual state of mail usage.
A desktop mail client with pop download of mails is so much year 2000 and so my thundebird is also full imap and I have/see all my mails "in owncloud" and on phone and on desktop and ... ;)

Rainloop completes my mobile and hardware independent data environment. Owncloud is not (only) a sharing and sync app - it's more and with Rainloop even much more!
![image](https://cloud.githubusercontent.com/assets/5565503/10115052/d8163a3a-63fc-11e5-8c29-4ce0ee69e03a.png)

Sorry @jancborchardt, long posting again. But if I would have written all the things, I have in mind, then it would have been even MUCH longer. :D
I love owncloud AND Rainloop and have many arguments to use both of them (together).

**Comment by oparoz** [comment]
I'm going to rain on your parade ;)

> Rainloop is a real owncloud app

No, it's an external app with an ownCloud wrapper which loads it in an iframe.
Nothing wrong with that approach, but it's not an app built on the tools provided to build apps, unlike Mail.

> Admin settings are made in admin panel of oc and an enhanced admin panel with dozens of settings and nothing looks like "a foreign iframe".

Yes, that was clever of them, because that's one of the most confusing thing about wrapped apps.

> For sure it looks other than files app - it's a mail app! But it doesn't feel or look wrong there.

It will on 8.2 since the buttons are different, but right now, it's not shockingly different, no.

> Rainloop is imap and for push notify I have my smartphone.

Not Rainloop, your IMAP server does that. No advantage in having it in ownCloud

> Rainloop uses oc contacts database 

Yes, but there is nothing in the app. It could be installed in standalone mode and still access your contacts.

>  imap is actual state of mail usage

Thanks to your IMAP server

>  I have/see all my mails "in owncloud" and on phone and on desktop

With any standalone webmail, you would get the same thing. I still don't see any synergies between ownCloud and Rainloop. If you were forced to use a browser, you would use two tabs (one for files operations and one for the webmail) instead of one and that might be more efficient.

> Rainloop completes my mobile and hardware independent data environment.

No, your private IMAP server does ;). You would get even more value if you installed Horde as it supports ActiveSync. You would save bandwidth and battery life.

A Horde-ActiveSync ownCloud app would really help people wanting to use Mail, but the backend is not ready yet.

> Owncloud is not (only) a sharing and sync app - it's more

Actually, on the enterprise side, that's exactly what it is, according to their USP. They want to be the leaders in the Enterprise File Synchronization and Sharing sector. Their goal is to unify storage and allow users to easily sync data stored in various silos. 
On the community side, because WebDAV is used, we started to see apps using the other DAV components, but it's got nothing to do with files and each app seems to have been doing its own thing on top of SabreDAV and most are broken and undergoing rewrites.
When the AppFramework landed, along with some APIs, it really started to boost app development, but it's still not a fully fleshed framework, especially in the GUI department. The only reason why you would use it is to access files, just like the enterprise version, mainly because there is no JS API (like Dropbox, gdrive, etc.), but also because it's much faster to access data locally. All the other apps have no real reason to live within ownCloud, but they help discover issues with the APIs.
So, on the one hand, there is this new goal to grow the app store, but the tools and the store itself are not ready. To build an app from the ground up, there are plenty of alternatives and to try and cram as many iframes as possible on one ownCloud instance is not the safest way to do things, especially given how things break during upgrades.
The next big thing to solve will be the licensing issues. Compare the app selection we have to what's happening in the CMS sector where the most popular ones have thriving app stores...

**Comment by jancborchardt** [comment]
What kind of issue derail is this here? :D @deMattin if you have any issues or enhancements for ownCloud Mail, please open issues in the tracker: https://github.com/owncloud/mail/issues, thanks!

**Comment by oparoz** [comment]
> Best would be an action popover like for the file actions in Files, to be consistent.

@jancborchardt - Since that's gone, what do you think about this?

![double-controls](https://cloud.githubusercontent.com/assets/323220/12994814/7a6632fc-d123-11e5-8279-7136fe64a8e0.png)

_Note-to-self: grow #controls (or simply remove the height restriction), push #gallery down, force buttons down by adding enough margin to last crumb_

**Comment by jancborchardt** [comment]
@oparoz it’s not gone though – check out the 3-dot menu in Files, on every file.

**Comment by jancborchardt** [comment]
That could be put on the right in the controls bar. It would be much better and retain focus on the pictures, rather than growing the interface to make room for controls which are less important than content on an already small screen.

**Comment by oparoz** [comment]
The 3-dots menu is for actions, it's not a dialogue like the share dialogue was.
An action menu can't be used, because we have some entries which open their own dialogue (share) and others (sorting) which need to be other buttons.

What's missing from the screenshot above if the [...] button, which would be top right and reveal the 2nd row.

Also, with the upload button, there will need to be a 3rd row as there is no room for both the button and the progress bar. I could probably make it so that the progress bar fills the entire 3rd row and then disappears, but that requires detecting a new, very narrow width as it wouldn't look good if there is room between the buttons.

**Comment by oparoz** [comment]
Replaced by https://github.com/owncloud/gallery/issues/566
