### ISSUE TITLE
No pictures in owncloud stable

### ISSUE THREAD

**Issue by mmattel** [owncloud/gallery#358]
Ubuntu 14.04, mysql, nginx
Having production and test on the same machine.
Working with master (test), gallery shows me all pictures, while on stable 8.1.1-1 and even after the upgrade to 8.1.3-13.1 gallery does not show my any of my folders/pictures but the demo once only.

**Comment by oparoz** [comment]
Stable 8.1, 8 and 7 still get Pictures. Users have to use Gallery+ to have a working app, although I really need to push V14 asap.

**Comment by mmattel** [comment]
yes please! :+1:

**Comment by oparoz** [comment]
Hopefully this weekend
- Rainbow spinner
- Circular menu (Simon says)
- 3D cube transition between folders
- Snow flake comments

Everything 0.1% of users have been clamouring for!

**Comment by jancborchardt** [comment]
@oparoz LOL :D
