### ISSUE TITLE
Implement a search engine

### ISSUE THREAD

**Issue by oparoz** [owncloud/gallery#36]
oC8 comes with a more efficient search engine, but the app is not yet plugged into it.
### Thoughts on possible solutions

As soon as a search is started, the view and models should be cleared and thumbnails should be generated.
- If we keep the current way of building the view, then nothing might show up until a row is full.
- If we make it so that a search is authorised to ask the backend for one thumbnail as a time, then that backend may get flooded with requests (that's what the Files app is doing)
### Prerequisites
- [x] [Show thumbnails as soon as they're received](https://github.com/owncloud/galleryplus/issues/29)
##

**Comment by theCalcaholic** [comment]
What do you mean by "a row is full"? A row of search results or generated Thumbnails?

**Comment by oparoz** [comment]
This is the way it currently works
1. We get a list of all media files we need to show
2. We split the list in batches
3. We show a row of thumbnails once all thumbnails for that row have been received

This works kind of OK when we know in advance what we need to show in the view (via step 1)

The search app is sending back results as soon as we type a few letters, but we wouldn't be able to show anything until we get the thumbnails from the server whereas the Files app is first building the DOM and then asking for thumbnails.

**Comment by oparoz** [comment]
This issue was moved to nextcloud/gallery#16
