### ISSUE TITLE
Disable search field

### ISSUE THREAD

**Issue by oparoz** [owncloud/gallery#37]
The search field is not yet automatically disabled in `core` for apps which have not registered with the search system, see https://github.com/owncloud/core/issues/11635#issuecomment-71741834

We should hide that field for now since it does not work.

@jancborchardt - Feel free to voice your opinion

**Comment by oparoz** [comment]
Search field is now hidden.

**Comment by jancborchardt** [comment]
It’s actually a good question how we deal with that in core for apps in general. @oparoz can you open an issue in core for that?

cc @DeepDiver1975 @butonic for reference

**Comment by oparoz** [comment]
@jancborchardt - There is already something here, which is unresolved https://github.com/owncloud/core/issues/11635

**Comment by jancborchardt** [comment]
@oparoz no, that specific one is resolved (as I commented). Search in apps works in master. As I commented there, it would be cool if you can open a new more general issue in core. Thanks! :)
