### ISSUE TITLE
Old folder icons shown when folder is empty (or only has erroneous images and a subfolder in it)

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/gallery#370]
![capture du 2015-09-23 22-28-53](https://cloud.githubusercontent.com/assets/925062/10057838/9551fb96-6242-11e5-9383-b797f8f34029.png)

Please use the .icon-folder from core – directly reference `core/img/filetypes/folder.svg` instead of duplicating the icon.

**Comment by oparoz** [comment]
I was thinking we should use our own metaphor since this is a gallery and not a files management app.
An artist's presentation case maybe?

![da471300912](https://cloud.githubusercontent.com/assets/323220/10060509/9fe55620-6251-11e5-87a5-81767310fd56.jpg)

**Comment by jancborchardt** [comment]
Umm … no. That’s highly inconsistent and will look weird. People will then think it’s a different thing, maybe an image itself.

**Comment by oparoz** [comment]
Folders have a label, so they can't think it's an image. And when you have several of them, like on your screenshots, you really can't mistake them.
Maybe we should use the technique used for Contacts and Music. Large squares with the first letter?

**Comment by ghost** [comment]
This issue will fall off 8.2 if not resolved by 6 Oct

**Comment by oparoz** [comment]
Will use the folder from core and will open a new issue to get better folders in Gallery

**Comment by oparoz** [comment]
> People will then think it’s a different thing, maybe an image itself.

Of course it would need to be a vector representation, not a picture.

**Comment by jancborchardt** [comment]
@oparoz is the new core folder icon used for 8.2? That’s the important thing here.

**Comment by jancborchardt** [comment]
Otherwise this is a regression – it’s not in line with the Files app style. Keeping it in 8.2

**Comment by oparoz** [comment]
Lots of little design fixes have been moved to 8.2.1

**Comment by oparoz** [comment]
And I'm not sure this can be called a regression since this feature has never existed before. There was always a picture in Pictures.

**Comment by jancborchardt** [comment]
It’s a regression because before it was in line with the folder icon of Files. Now it’s not anymore. Just link to the core folder icon, don’t copy it into the app. :)

**Comment by oparoz** [comment]
Do you have a test case to make the folder icons appear?

**Comment by jancborchardt** [comment]
It happened to me when I had a folder with subfolders and images – with the images in that folder being broken. So Gallery thinks there are pictures, but can only load the preview of the folder.

In any case, look at `apps/gallery/img/folder.svg` – that’s the wrong old image.

**Comment by jancborchardt** [comment]
PR at https://github.com/owncloud/gallery/pull/426

**Comment by oparoz** [comment]
Yes, I know it's the wrong image, but that feature was never distributed with ownCloud, so it can't be a regression. At worse, it's an incomplete feature since the design is missing, which is still a problem for a core app.

But the problem is that using another icon is only part of the solution. In many cases, there is an empty image (just the label), that's why I need a way to reproduce it.

**Comment by oparoz** [comment]
You can use this in a PR if it works for you: https://github.com/owncloud/gallery/commit/d0aa2bb6fbdb6a09fde05468e600d98b3708c7b7

**Comment by jancborchardt** [comment]
@oparoz if that’s better than #426, can you please submit it as a PR so we can get this in for 8.2

**Comment by oparoz** [comment]
It's not better, it's more long term, since it may take some time to have a nice gallery album icon ;)
https://github.com/owncloud/gallery/pull/427
