### ISSUE TITLE
Uncaught TypeError when resizing browser window on empty Gallery app

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/gallery#371]
Just a detail @oparoz but when resizing the browser on a completely empty Gallery app, this error comes up in the console:

```
Uncaught TypeError: Cannot read property 'setMaxWidth' of null(anonymous function)
@ app.js line 63
```

**Comment by oparoz** [comment]
Thanks. The breadcrumb is not initialised at this stage. I need to move that call...
