### ISSUE TITLE
Use DOMPurify to parse SVGs [$15]

### ISSUE THREAD

**Issue by oparoz** [owncloud/gallery#373]
@LukasReschke - What do you think about using DOMPurify to parse SVGs before showing them in the browser?
- [x] Decode and parse base64 encoded SVG thumbnails
- [x] Parse large SVG previews
##

**Comment by LukasReschke** [comment]
This sounds like a potentially awesome idea!

**Comment by oparoz** [comment]
Cool. Crossing my fingers for it to not slow down operations too much :)

**Comment by LukasReschke** [comment]
Let's get you three beer for all the work… - THX!

**Comment by oparoz** [comment]
Hehe, thanks!
