### ISSUE TITLE
Message for empty galleries looks broken on the public side

### ISSUE THREAD

**Issue by oparoz** [owncloud/gallery#374]
Hopefully, this won't be too messy to fix...
Note that this was broken before the new design of the empty page. It probably happened when removing the permanent scrollbar.

![](https://cloud.githubusercontent.com/assets/323220/10073764/90cb151a-62cb-11e5-8b73-c01e4aac98d1.png)

@jancborchardt @raghunayyar

**Comment by oparoz** [comment]
Let's see what `core` come up with since it's broken there as well. They have a different problem though since the public page needs another fix for the scrollbar.

https://github.com/owncloud/core/issues/19364#issuecomment-143223436

**Comment by oparoz** [comment]
In case we want to go solo:

```
position: relative;
margin-top: 100px;
- top: 30%;
```

The only problem is that it would look different when switching side

**Comment by jancborchardt** [comment]
@oparoz in doubt we can also remove the footer for the emptycontent pages. Maybe @owncloud/designers @Henni @MorrisJobke can fix? (I’m on vacation now)

**Comment by oparoz** [comment]
If we modify the CSS, then I'd rather give the footer a fixed position in case there is nothing to see, but I'm waiting for `core`'s move first :)

**Comment by oparoz** [comment]
Targeting 8.2, like in `core`.

**Comment by cmonteroluque** [comment]
This issue will fall off 8.2 if not resolved by 6 Oct

**Comment by oparoz** [comment]
@cmonteroluque - There is a dependency on https://github.com/owncloud/core/issues/18968 which is targeting 9.0. 
Move to 9.0?

**Comment by ghost** [comment]
@oparoz it's a regression so I am hesitant to let it go. @PVince81 @MorrisJobke thoughts?

**Comment by DeepDiver1975** [comment]
@oparoz can you recheck this with latest master? Is this fixed with https://github.com/owncloud/core/issues/19364 - THX

**Comment by oparoz** [comment]
@DeepDiver1975 - The missing piece is https://github.com/owncloud/core/issues/18968 . Without it, the slideshow can't cover the whole content area and once you introduce that in Files, then the new landing page looks broken, like on the screenshot in the OP.

**Comment by MorrisJobke** [comment]
> @oparoz can you recheck this with latest master? Is this fixed with owncloud/core#19364 - THX

Just checked and it is still broken :(

**Comment by oparoz** [comment]
Yep. Ideally this should happen:
1. Fix https://github.com/owncloud/core/issues/18968
2. Fix the landing page in `core`
3. Port the fix to Gallery

The alternative is that I hack something for 8.2 in Gallery, but then the slideshow won't look great on public pages, in Files.

**Comment by MorrisJobke** [comment]
> @oparoz it's a regression so I am hesitant to let it go. @PVince81 @MorrisJobke thoughts?

Fix is here: https://github.com/owncloud/core/pull/19611

**Comment by ghost** [comment]
fix causes a new regression? https://github.com/owncloud/gallery/issues/418

**Comment by oparoz** [comment]
Yes :(
But I'm sure we'll find a solution. It's probably possible to apply a fix for the footer only.

**Comment by oparoz** [comment]
Closing this as this part as been fixed. The remaining issue concerns the a conflict between the public files list and the photowall in Gallery.
