### ISSUE TITLE
File - functions fail, if thumbnail has not been created

### ISSUE THREAD

**Issue by mmattel** [owncloud/gallery#38]
Ubuntu 14.04, Apache 2.4, PHP 5.5, OPcache enabled, MySQL, Browser W7/Opera
php.ini has set output_buffering = On
owncloud pre alpha 7 git, external storage support, pictures, music, 3 local mount points created, no encryption

### Problem:
having unsupported pictureformats like tiff in your folders, you get tons of filesystem related messages like filemtime, filesize ect failed filling up the owncloud log. 

filesize(): stat failed for .... /apps2/gallery/lib/thumbnail.php#104 (ect)

This happens because the thumbnail tried to be accessed has not been created. If you take a look into the database, you see that the picture-file is present with the right mimetype. When you look into the users folder in owncloud (at the server), you see under user/gallery the structure of the necessary folders and thumbs created, but on those where you expect a thumbnail (but unsupported) this is missing.

When you look at the code, thumbnail creation is skipped on currently unsupported formats (folders are created) but accessing the missing files is not prevented because it is only queried on all images (eg getimages.php $images = \OCP\Files::searchByMime('image');) and not on supported images.

Form the error message itself, it took a while to understand that this is a process error based on inproper handling of unsupported files and not a error based on a file function. Very confusing!

If you have a mount having tons of graphical data present where there are also files which can at the moment not be processed by owncloud, your error log gets quickly filled up AND logging happens as you enter the gappery app - from each user, for each folder accessed...

### Solution Suggestion
1.) either manage the supported graphical files more properly
2.) or add calls to the necessary routines if the file accessed is present or not

**Comment by oparoz** [comment]
Everything has been fixed in the next Gallery.
