### ISSUE TITLE
Docs in the wiki

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/gallery#383]
@oparoz I just noticed there’s https://owncloud.github.io/gallery for documentation. In an effort to not scatter stuff all over the place, we should only use the wiki for these things. (Or the https://github.com/owncloud/documentation, but not a third thing.)
##

**Comment by oparoz** [comment]
We can't. Those are websites, automatically generated after code analysis. They're exclusively for developers and there is not a similar repository in `core` storing that kind of information afaik.

**Comment by oparoz** [comment]
This issue was moved to nextcloud/gallery#84
