### ISSUE TITLE
The "switch-to-Gallery" button is hard to notice (on large monitors)

### ISSUE THREAD

**Issue by wilsonlmh** [owncloud/gallery#386]
The button can't be noticed in large monitor because it's top-right now. I personally "discovered" the button finally on my phone. Maybe this is my opinion. However my users has same suggestion on this. Is it better to move it back to left hand side(feeling just like a 'view' switcher in explorer or finder)? Or any reason/policy?

**Comment by oparoz** [comment]
@wilsonlmh - On which version did you test?

And I'll let @jancborchardt and @karlitschek explain why it moved to the right (and has been made discreet on 8.2)

**Comment by wilsonlmh** [comment]
14.0 and I saw 13.0 on the left. I just updated 14.1 and notice it become the view switcher I said! Great! But I am using iphone I don't how is it in computer. I will try tmr.

**Comment by oparoz** [comment]
OK, so the view switcher is exclusively available in Gallery+ for 8.1 and 8.0, but it will require some work to keep it on 8.2.
As for the location, it may be possible to move it back to the left on Gallery+, but I haven't decided yet.

**Comment by karlitschek** [comment]
Honestly. If you don't notice buttons on the interface then maybe you browser windows is just too big ;-) We can't just align everything to the left because you might go full screen on a big monitor and don't look on the right side of the interface. ;-)

**Comment by wilsonlmh** [comment]
![image](https://cloud.githubusercontent.com/assets/5100899/10142889/f5573e12-6647-11e5-82fc-fba2e177160e.png)d
You're right. However 1440x900 or 1920x1080 are very popular nowdays. I personally think it should have something to solve the problem on that kind of monitor. I mean more responsive. For example, change it's color?put it on center? or add some margin? We can have further discussion :)

**Comment by karlitschek** [comment]
Sorry but we will always have UI elements aligned to the left side and right side of the screen. We won't move everything to the left only because someone might use owncloud full screen on a huge monitor and  ignores what is going on on the right side of of the monitor.
