### ISSUE TITLE
Action menu for thumbnails

### ISSUE THREAD

**Issue by oparoz** [owncloud/gallery#39]
Each Album or thumbnail could feature a menu giving quick access to actions such as
- Regenerate thumbnail  #38 
- Edit meta data, requires https://github.com/owncloud/galleryplus/issues/101
- Share, requires https://github.com/owncloud/galleryplus/issues/68
- Edit name
- Delete image
- Select image (for drag and drop https://github.com/owncloud/gallery/issues/405)

There is a menu in Files. I don't think we can use it as is, but we could copy it if it's not too large. It would look something like this.

![](https://cloud.githubusercontent.com/assets/323220/13620216/62dbaaac-e58e-11e5-9662-58fa5356f5cc.png)
##

**Comment by oparoz** [comment]
All that's missing is a universal 3-dots menu in `core` or some duplication of code.
Refresh after delete works (was developed for drag and drop move)

**Comment by jancborchardt** [comment]
Nice, this would indeed be cool!

**Comment by oparoz** [comment]
This issue was moved to nextcloud/gallery#17
