### ISSUE TITLE
v14.1.0 - feof()/fread() errors should be replaced by readable message

### ISSUE THREAD

**Issue by j-ed** [owncloud/gallery#395]
## Expected behavior

The Gallery(Plus) app file scan process shouldn't throw out feof()/fread() errors if a file couldn't be found or the file access rights might haven't correctly be set. These messages are causing a rapid log file increase without valuable information. Instead the name of the file which couldn't be accessed should be shown so that an administrator is able to solve the problem.
## Current behavior

The following errors are logged if the app is accessed for the first time and the file scan was started and couldn't be stopped by disabling the app. My research on the Internet a pointing to a problem finding or accessing a file due to invalid file access rights but unfortunatly the file name and path is not shown so that the problem couldn't be solved.

https://stackoverflow.com/questions/16552484/warning-feof-expects-parameter-1-to-be-resource

```
...,"app":"PHP","message":"feof() expects parameter 1 to be resource, boolean given at \/var\/www\/htdocs\/owncloud\/apps2\/galleryplus\/service\/previewservice.php#216","level":0,"time":"2015-09-29 20:44:30+02:00","method":"GET","url":"\/owncloud\/index.php\/apps\/galleryplus\/thumbnails?ids=281396%3B281494%3B281595%3B281806%3B293225%3B293222%3B293229%3B293232&scale=1&square=1&requesttoken=XygAm9EDs3s5YxKEPQBpVUK8L5l5SV"}
...,"app":"PHP","message":"fread() expects parameter 1 to be resource, boolean given at \/var\/www\/htdocs\/owncloud\/apps2\/galleryplus\/service\/previewservice.php#217","level":0,"time":"2015-09-29 20:44:30+02:00","method":"GET","url":"\/owncloud\/index.php\/apps\/galleryplus\/thumbnails?ids=281396%3B281494%3B281595%3B281806%3B293225%3B293222%3B293229%3B293232&scale=1&square=1&requesttoken=XygAm9EDs3s5YxKEPQBpVUK8L5l5SV"}
```
## Steps to reproduce
1. Activate the Gallery(Plus) app
2. access the app
3. wait until the file scan starts and check the log file
#### Server Configuration

OS: Linux 3.2.67
Web server: Apache2 2.4.12
Database: MySQL 5.1.73
PHP version: 5.4.42
ownCloud version: 8.1.3
GalleryPlus app version: 14.1.0
My pictures are mostly stored on WebDAV shares
#### Client Configuration

Operating system: Windows 7
Firefox version: 41.0

**Comment by oparoz** [comment]
Thanks for the report and the link. This happens with GIF files exclusively.

We're already catching exceptions, but apparently this is not enough and I will update that method.

**Comment by oparoz** [comment]
@j-ed - Do you use encryption?

**Comment by j-ed** [comment]
@oparoz No, I don't use encryption.

**Comment by oparoz** [comment]
Thanks.

**Comment by rezeptpflichtig** [comment]
i search the logfile for the failing fopen to get the filename. Problem with my installation is that the whole owncloud installation locks up, have to restart php-fpm to make it work again, the log is spammed with the feof()/fread() errors and the logfile grows multiple GB in a few minutes.

i am running ownCloud 8.2.1 (stable) in a freebsd jail (freeNAS 9.3)
on nginx with mariadb
gallery app 14.2.0

**Comment by oparoz** [comment]
The fix should be simple. Something like

```
if ($fileHandle = $file->fopen('rb')) {
```

https://github.com/owncloud/gallery/blob/master/service/previewservice.php#L215

But the proper solution should include a else statement which logs the file for which this happens.

**Comment by oparoz** [comment]
Fix is in https://github.com/owncloud/gallery/pull/510
