### ISSUE TITLE
[SVG] Chrome it´s not showing the image file icon

### ISSUE THREAD

**Issue by rperezb** [owncloud/gallery#397]
STEPS: 
1.- Upload a malformed svg file, such as: https://s3.owncloud.com/owncloud/index.php/s/MD4hOi7Fqv9o4WL
2.- Access to the Gallery

EXPECTED BEHAVIOR
Image file icon is shown

CURRENT BEHAVIOR
See attached image:

![screen shot 2015-10-02 at 10 30 30](https://cloud.githubusercontent.com/assets/1846927/10242488/6f4596fa-68f1-11e5-8e82-f2cf56c1f505.png)

On ff:

![screen shot 2015-10-02 at 10 30 22](https://cloud.githubusercontent.com/assets/1846927/10242540/b8ea9eb8-68f1-11e5-9c4f-5d703bd2a7ca.png)

Server version: ownCloud 8.2 beta1 (daily) Build:2015-10-02T03:39:51+00:00 f891b91cf8475eee16ab1ca08869430bd2dbe51b

**Comment by oparoz** [comment]
Thanks for the report. I hope I'm going to be able to solve this. The icon appears after a refresh, so Chrome is not updating the image after it has downloaded it.

**Comment by oparoz** [comment]
Fix is in https://github.com/owncloud/gallery/pull/409

**Comment by ghost** [comment]
sent to @rperezb for QA test

**Comment by rperezb** [comment]
![screen shot 2015-10-13 at 14 24 07](https://cloud.githubusercontent.com/assets/1846927/10454607/1c62ec12-71b6-11e5-93f7-9f1f31e1b25a.png)

thx
