### ISSUE TITLE
On gallery plus if share a folder by expiration date and if you change the expiration date on Desktop Client, the date format has changed

### ISSUE THREAD

**Issue by Dianafg76** [owncloud/gallery#398]
### Steps to reproduce
1. Go to the Desktop
2. Create a new folder (e.g Sharing folder)
3. Upload same Photos
4. Go to the Server Client
5. Go to the Gallery option
6. Click on the Folder (call Sharing folder)
7. Share by link
8. Select the option "Set expiration date"
9. Introduce the date (e.g. 03-10-2015)
   ![screen shot 2015-10-02 at 12 36 25](https://cloud.githubusercontent.com/assets/12032058/10244806/441f109e-6902-11e5-831f-548cacf01cf3.png)
10. Go to the Desktop client
11. Go to the Folder (call Sharing folder)
12. Right click to the folder
13. Go to the Share with owClound option
14. Change the expiration date (e.g. 05/10/15)
15. Click on Close
16. Go to the Server Client
17. Go to Gallery option
18. Go to the Folder (Sharing folder)
19. Share by link
### Expected behaviour

The date format it shouldn't change
### Actual behaviour

The date format has changed
![screen shot 2015-10-02 at 12 42 30](https://cloud.githubusercontent.com/assets/12032058/10244917/15356bf6-6903-11e5-846b-91ea0356f4c5.png)
### Server configuration

Server v {"installed":true,"maintenance":false,"version":"8.2.0.7","versionstring":"8.2 beta1","edition":""}
Desktop v ownCloud-2.0.2.2760-nightly20151002.pkg

**Comment by oparoz** [comment]
Dianafg76 - There isn't a share dialogue in Files any more and I've tested with the new sidebar and it has the same problem, so I think this should be fixed in `core`.

![broken_expiration_in_files](https://cloud.githubusercontent.com/assets/323220/10246059/05a8c0c4-690e-11e5-9a1f-a4cfe93b7fef.png)

**Comment by oparoz** [comment]
Opened an issue in `core` https://github.com/owncloud/core/issues/19549

**Comment by oparoz** [comment]
Fix for Files is here: https://github.com/owncloud/core/pull/19553. Waiting on the backport.

**Comment by oparoz** [comment]
Backport is here: https://github.com/owncloud/core/pull/19598

**Comment by oparoz** [comment]
Fix is in: https://github.com/owncloud/gallery/pull/413

**Comment by ghost** [comment]
@Dianafg76 retest with fix please

**Comment by oparoz** [comment]
Fix has been merged, so use the master branch.

**Comment by oparoz** [comment]
Thanks @Dianafg76
