### ISSUE TITLE
Implement left sidebar, like in Files

### ISSUE THREAD

**Issue by oparoz** [owncloud/gallery#401]
- Make the burger permanent in the controls
- ~~Re-use the code from files~~
### Plan
- [ ] Try to use the navigation CSS to see if we can easily get a sidebar. https://doc.owncloud.org/server/9.0/developer_manual/app/css.html#navigation
- [ ] Auto-hide it via CSS
### Obstacles

The current official template design in `core` does not work on iOS.
#### Solutions
- Wait for `core`  to fix the problem https://github.com/owncloud/core/issues/22347
- Rewrite the templates, including modifying the controller in order to fetch all the needed variables
- Find a way to hack the template via JS and CSS to make it work by re-organising the structure

The best option would be to wait for `core`.
##

**Comment by oparoz** [comment]
Since we have to re-create the whole thing, we have to carefully evaluate the benefits of adding those filters.

**Comment by oparoz** [comment]
- [ ] Try to use the navigation CSS to see if we can easily get a sidebar. https://doc.owncloud.org/server/8.2/developer_manual/app/css.html#navigation
- [ ] Auto-hide it via CSS

**Comment by oparoz** [comment]
We can't use the navigation panel described in the documentation as-is since there is a design problem which hinders performance on iOS.

I've updated the OP.

**Comment by jancborchardt** [comment]
We should still use the same panel but try to fix the performance problem. Not adhering to the standards isn't cool either.

**Comment by jancborchardt** [comment]
cc @owncloud/designers

**Comment by oparoz** [comment]
> We should still use the same panel but try to fix the performance problem. Not adhering to the standards isn't cool either.

Yes, ideally, `core` will design a new side-panel which works with the new template structure which should be implemented in 9.1. If that doesn't happen, we could have a temporary solution in Gallery, but I found that there was a lot of black magic around that side panel.

**Comment by oparoz** [comment]
This issue was moved to nextcloud/gallery#90
