### ISSUE TITLE
Add the API to the capability manager

### ISSUE THREAD

**Issue by oparoz** [owncloud/gallery#403]
Use the new capability manager available in 8.2+:
https://github.com/owncloud/core/pull/15093
##

**Comment by ghost** [comment]
@oparoz 8.2.1?

**Comment by oparoz** [comment]
It's true that with the API in beta, we could wait for it to be production ready before adding it to the capabilities. I don't think there is anything else to add to the manager.

**Comment by oparoz** [comment]
This issue was moved to nextcloud/gallery#92
