### ISSUE TITLE
Drag and drop files and folders [$250]

### ISSUE THREAD

**Issue by oparoz** [owncloud/gallery#405]
As soon as the app supports [uploading files](https://github.com/owncloud/gallery/issues/25), there will be the need to re-organise them.
## Specifications

Files/folders should be draggable and folders/breadcrumbs should be drop targets. There is no support for multi-element select.
- [x] Make files draggable
- [x] Make folders draggable
- [x] Draggable elements must be resized and made semi-transparent so that users can easily drop them on the targets
- [x] Turn folders into drop zones
- [x] Turn breadcrumb elements into drop zones so that users can move files to parent folders
- [x] Add visual feedback to drop zones
- [ ] ~~Only turn albums with write permissions into drop targets~~ Requires #557
- [x] Move files and folders when dropped onto an album and refresh the view
### FAQ

**Q:** I get a permission denied after dropping files on an album. Why make it a drop target then?
**A:** It's actually not possible today to determine which albums can be real drop targets as we don't have any information about sub-albums beside their name. See #557 for details.
##

**Comment by oparoz** [comment]
I'll post a roadmap soon

**Comment by oparoz** [comment]
@jospoortvliet @jancborchardt @karlitschek @LukasReschke I've posted some specs. Let me know if this meets your requirements

**Comment by jancborchardt** [comment]
Looks good! cc @owncloud/designers for checking as well.

**Comment by jospoortvliet** [comment]
I think it's great!

**Comment by oparoz** [comment]
There is now a solution with https://github.com/owncloud/gallery/pull/519.

I wanted to visually indicate that some folders cannot be drop targets, but I don't think having a bix X across a folder is going to work, especially for the breadcrumb. The next solution would be a pop-up which would appear when the item hovers, but I'm worried that it might be unreadable.
Thoughts?

**Comment by oparoz** [comment]
Added a FAQ
