### ISSUE TITLE
Pause button is sometimes not clickable

### ISSUE THREAD

**Issue by Henni** [owncloud/gallery#407]
During a slideshow the pause button in the bottom right is sometimes not clickable.
I believe this happens for every image after it is displayed half of the time.
This issue occurs in Chrome and Firefox.

edit:
this happens because the progress indicator is not clickable.
`<div class="progress icon-view-pause" style="height: 23.72px; overflow: hidden;"></div>`
A simple fix would be to set `pointer-event: none` for this element, but this isn't supported in IE10 and below (http://caniuse.com/#feat=pointer-events).

**Comment by oparoz** [comment]
Fix is in https://github.com/owncloud/gallery/pull/410
