### ISSUE TITLE
Zooming doesn't work with larger next/previous touch areas

### ISSUE THREAD

**Issue by oparoz** [owncloud/gallery#411]
Introduced by https://github.com/owncloud/gallery/pull/369

Is it possible to keep both the scrollwheel events and the large touch areas?
Otherwise I'm going to have to revert #369.

@Henni @jancborchardt

**Comment by Henni** [comment]
Seems difficult to solve. But I'll take another look and experiment a bit.

**Comment by oparoz** [comment]
Thanks and so, I'm not against a replacement of bigshot for the zooming feature since it's quite a large lib and since we don't support its main feature which is to allow the use of multiple images when zoming, but we should pick a library instead of writing custom code :)

**Comment by Henni** [comment]
I'll take a look at this for 9.0

**Comment by oparoz** [comment]
OK, so I'll revert #369 for 8.2

**Comment by oparoz** [comment]
Revert PR: https://github.com/owncloud/gallery/pull/412

**Comment by oparoz** [comment]
Closing this as this is no longer relevant. Re-opened the original issue https://github.com/owncloud/gallery/issues/53
