### ISSUE TITLE
When navigating through albums, the starting position is not reset to the top of the album

### ISSUE THREAD

**Issue by oparoz** [owncloud/gallery#418]
### Steps to reproduce
1. Open an album with a lot of picture
2. Scroll down a little
3. Click on an album
### Expected result

The position is reset to exactly 45px from the top so that the photowall begins after the controls bar
### Actual result

The photowall starts from 0pc from the top of the container, partially hidden by the controls bar

**Comment by oparoz** [comment]
Caused by: https://github.com/owncloud/core/commit/e1286a4151c1ad2c2cbdbd16255a4eaa16254776

So with `position: relative` we get the proper scroll to top behaviour, but the footer overlaps the last row.

@henni is there another way of doing this?

**Comment by oparoz** [comment]
One day left for experts to find a solution. After that I give it a haircut with a chainsaw :) 

@jancborchardt

**Comment by jancborchardt** [comment]
What do you mean by »it doesn’t scroll back to the top anymore«? Is there overlap, or was there automatic scrolling?

**Comment by oparoz** [comment]
Yeah, sorry, it helps if there is an actual description of the problem... Updated the OP.

**Comment by jancborchardt** [comment]
@Henni can you check that out cause it relates to your change? Otherwise we might have to revert it because this issue is a tad more important I’d say.

**Comment by oparoz** [comment]
I'm pushing a fix

**Comment by oparoz** [comment]
Fix is in https://github.com/owncloud/gallery/pull/428
