### ISSUE TITLE
Remember last folder

### ISSUE THREAD

**Issue by MorrisJobke** [owncloud/gallery#42]
@zakoon wrote:

Hi, I have lots of folders with lots of pictures/graphics on my oc-instance. And I have one folder with photos.

Everytime I start the Pictures-App, all the folders, where pictures or graphics or photos are in, appear. I always have to navigate through some subfolders, to get to my photo-folder, which is the only folder I need in my Pictures-App.

Is it possible to add an option, so I can set the start-folder for the picture app?
like /SyncFolder/Private/Photos ?

Would be create!

Thanks!

------

@jancborchardt wrote:

It would be good if the last used folder would always be remembered. No need to have a setting for that.

@schiesbn @butonic @kabum who is the right person to ask about that? :)

-----

This was ported from https://github.com/owncloud/core/issues/6307

**Comment by oparoz** [comment]
The conversation can be continued here if need be: https://github.com/owncloud/galleryplus/issues/196
