### ISSUE TITLE
Rendering stops if first or only media file can't be read

### ISSUE THREAD

**Issue by oparoz** [owncloud/gallery#420]
It's particularly noticeable on albums containing a single broken file.
Hopefully this will be easy to fix and not a limitation of server-side events.

The client asks for thumbnails and instead of getting an event stream containing events with status linked to them (some of which can be 500), it receives an error 500, breaking the rendering.

**Comment by oparoz** [comment]
I don't think it's a regression. It's just new that GD recovers from processing some bad JPEGs and those warnings happen after we've processed the result received from the Preview class.

**Comment by oparoz** [comment]
Fix is here: https://github.com/owncloud/gallery/pull/422

**Comment by ghost** [comment]
https://github.com/owncloud/gallery/issues/420#issuecomment-147709206 The PR has a 9.0 milestone. Moving it? @oparoz please reply if we should bring it into 8.2.1
