### ISSUE TITLE
Preview API on shared folders

### ISSUE THREAD

**Issue by tobiasKaminsky** [owncloud/gallery#423]
Hi,

I am using these api calls to get a resized image https://www.server.de/owncloud/index.php/apps/galleryplus/api/preview/239638/768/1184

This works great for  the user who owns a folder.
But if this folder is shared within the same server the other user cannot get the preview; I get a 404.

A quick test yesterday showed me that it may help logging in via the website and browse with gallery+ to the specific folder.

Do you know what the problem could be?

Thank you

**Comment by oparoz** [comment]
You need to use the credentials of the sharees and they should have access, but it could be that the API is using the wrong internal user.

Just to be sure, could you write a step by step so that I can try to reproduce?

**Comment by tobiasKaminsky** [comment]
I tried to reproduce it on my 8.1 server where the problem is occurring within the android app.
But unfortunately I cannot reproduce it for now.

Basically it was:
User 1 creates folder and copies images into it
User 1 shares this with user2
user2 tries to access it via your preview api with the galleryplus app
A 404 error occurrs for user2 whereas the same url with user1 is working.

**Comment by oparoz** [comment]
Is it still happening from within your app?
If yes, it would be useful to collect some ownCloud logs.

**Comment by tobiasKaminsky** [comment]
As this happens on the device of my wife and I am currently not at home, I will have to wait for her reply.
In the meantime I have checked the logs and can see that galleryplus is creating previews via the api.
But I have to confirm with her that it works...

**Comment by oparoz** [comment]
OK, no worries.
