### ISSUE TITLE
Increase version for 9.0

### ISSUE THREAD

**Issue by nickvergessen** [owncloud/gallery#431]
Just a warning, when stable8.2 is branched off in core (most likely today), the info.xml needs to be adjusted to allow installing against 9.0:

``` xml
<owncloud min-version="8.2" max-version="8.2.99"/>
```

Also the app version should also be increased (first or second digit, to allow updates in stable8.2 later, in case it is needed):

``` xml
<version>14.3.0</version>
```

**Comment by oparoz** [comment]
Thanks for the heads up!

I need to have a think about versioning... The same functionalities are currently offered across 3 oC versions, but the code base is slightly different, so each need to be packaged individually.

**Comment by oparoz** [comment]
- 14.3 for all releases until something major lands
- Supports 8.2-9.0 until we need to use NBC code
