### ISSUE TITLE
Empty album representation when sub-folder contains bad image

### ISSUE THREAD

**Issue by oparoz** [owncloud/gallery#432]
When a folder contains a single bad image, it will be used for the album representation in the parent folder.
Currently, we get an empty image.

**Comment by oparoz** [comment]
Requires 2 fixes:
- https://github.com/owncloud/gallery/commit/a873e1792b26b0cd1f7e052911294cf86dab38d1
- https://github.com/owncloud/gallery/commit/3043b41f222dcc7d121f7fed7a6657ea263651cd

**Comment by ghost** [comment]
moving to 9.0 to match the PR

**Comment by PVince81** [comment]
PR here https://github.com/owncloud/gallery/pull/422

**Comment by oparoz** [comment]
Fixed via https://github.com/owncloud/gallery/pull/422
