### ISSUE TITLE
Calculate the available width for the breadcrumb based on shown buttons

### ISSUE THREAD

**Issue by oparoz** [owncloud/gallery#443]
The app is currently using the worst case scenario, the one where all buttons are shown, which means that there will be a large gap on public galleries per example if the only button shown is the switch to Files button.

The plan is to add 50px per button at view init time.
### In more details

We define `Gallery.buttonsWidth` at 350 pixels. that's the worst case scenario.

When the view is resized, we do this:
`Gallery.view.breadcrumb.setMaxWidth($(window).width() - Gallery.buttonsWidth);`

The 350 pixels area may not necessarily be filled with buttons, leaving some empty space.
### Plan
- [ ] List all buttons which can be shown on the controls bar
- [ ] List the minimum number of buttons which can be show on the interface
- [ ] Define the number of pixels a button takes
- [ ] Write a function which updates Gallery.buttonsWidth based on the number of buttons currently shown
##

**Comment by imjalpreet** [comment]
@oparoz I want to fix this issue. Can you please tell a little more about what needs to be done in this?
Secondly, can you also assign me some more tasks, so that I can get used to the code? 
Thanks!

**Comment by oparoz** [comment]
I've updated the OP with more details. That gives you a bit of investigating work to do to familiarise yourself with the GUI components.

Regarding tasks, do you want to stay with Javascript or do you want to start working on some PHP jobs? In general, any task with a label "Coder wanted" can be picked and I can clarify some of them or tell you if it's not the right time to look at it, etc.

**Comment by imjalpreet** [comment]
@oparoz I will have a look at the updated description.
Secondly, I am fine with both PHP and JS Jobs. Can you suggest me some jobs that can be looked at now? Thanks!

**Comment by oparoz** [comment]
Here is a selection: #4 https://github.com/owncloud/gallery/issues/193#issuecomment-133676344 #213 #565 
There is also a PR which could be finished, but you'll have to ask the person currently assigned: https://github.com/owncloud/gallery/pull/512

If none of them float your boat, let me know and I'll try to find bigger tasks.

**Comment by oparoz** [comment]
I've added another one: https://github.com/owncloud/gallery/issues/566

**Comment by imjalpreet** [comment]
@oparoz Cool! I will have a look at all of them along with this one and get back to you. :+1:

**Comment by oparoz** [comment]
OK and remember to sign the contributor agreement if you intend on delivering larger PRs. That way you can also manage labels and assign yourself to tasks.

**Comment by imjalpreet** [comment]
@oparoz Yeah Sure. Where can I find the contributor agreement?

**Comment by oparoz** [comment]
https://owncloud.org/contribute/agreement/

**Comment by imjalpreet** [comment]
Yeah! Thanks! Got it! :+1:

**Comment by oparoz** [comment]
I've also added some basic app ideas to the wiki

**Comment by imjalpreet** [comment]
@oparoz I am having a look at those basic app ideas that you have added. I will start developing one of those to have grip on the AppFramework. Thanks!

**Comment by imjalpreet** [comment]
@oparoz Secondly, Where can I communicate with you regarding GSoC projects? Is IRC fine?

**Comment by oparoz** [comment]
I'm rarely on IRC, unless I'm working on something as it's too distracting and unreliable. Emails works best, unless code needs to be discussed live, in which case we can meet on IRC.

**Comment by oparoz** [comment]
This issue was moved to nextcloud/gallery#98
