### ISSUE TITLE
API documentation wrong for "/api/preview/thumbnails"?

### ISSUE THREAD

**Issue by LukasReschke** [owncloud/gallery#446]
https://github.com/owncloud/gallery/wiki/RESTful-API#preview-api this should probably be `/api/thumbnails` instead of `/api/preview/thumbnails`? 

cc @oparoz

**Comment by oparoz** [comment]
You are [correct](https://github.com/owncloud/gallery/blob/master/appinfo/routes.php#L154). Fixed! Thanks!
