### ISSUE TITLE
Filter based on favorite photo's

### ISSUE THREAD

**Issue by youphyun** [owncloud/gallery#455]
Currently it is already possible in ownCloud to mark files and folder with a star (favorites). This also applies to photo's that are displayed in the gallery+ app. I would like to be able to filter these and show only favorites photo's in the gallery+ app. This would add some kind of album feature to the app based on a functionality that already exist in ownCloud. Can a dev estimate how much work this would be and I can see whether I can back this feature request in Bountysource.

I am not sure about the UI but it could look like this:
![capture_favorites](https://cloud.githubusercontent.com/assets/12627719/10767280/abfb693c-7cdb-11e5-87dd-694db12a9c5e.PNG)

**Comment by oparoz** [comment]
Thanks for the request and the screenshot :)
There is already an issue open about this: https://github.com/owncloud/gallery/issues/230, so let's continue the conversation there. I'll add your screenshot.
