### ISSUE TITLE
Browser bar always displays on mobile device during slideshow.

### ISSUE THREAD

**Issue by setnes** [owncloud/gallery#459]
I haven't had much time to track this project lately.  I had a chance to upgrade everything tonight though.  I'm now using OwnCloud 8.2.0 and the Gallery 14.2.0 that came with it.  I noticed that it is no longer possible to open up the slideshow on a mobile device without the browser bar showing.  I think this is somehow a side effect of the OwnCloud header being sticky at the top of gallery pages.  Is that new?

I used to be able to scroll down a little bit on a page of thumbnails to get the browser bar to disappear before opening a slideshow.  (Chrome on Android)  This doesn't work anymore.  It probably wasn't the best user experience anyway.  Perhaps a fullscreen button would help here.  There isn't an easy way for a mobile user to hit the F key.
##

**Comment by oparoz** [comment]
Please, try this PR https://github.com/owncloud/gallery/pull/454 and see if it helps.

**Comment by oparoz** [comment]
Yes, the fixed controls bar has killed the auto-hiding of the browser bar in some browsers.
It's more of a core issue since the slideshow needs to be displayed in Files as well.

But we can implement https://github.com/owncloud/gallery/issues/252 as a partial solution.

**Comment by oparoz** [comment]
I'm wondering if https://github.com/owncloud/gallery/pull/507 fixes the issue

**Comment by oparoz** [comment]
OK, it has zero effect. Looks going full screen is the way to go, if we can fix #454

**Comment by oparoz** [comment]
This issue was moved to nextcloud/gallery#101
