### ISSUE TITLE
Artifacts visible for previews and slideshow view

### ISSUE THREAD

**Issue by maddylliieeee** [owncloud/gallery#465]
### Steps to reproduce
1. Upload a bunch of photos to your OC
2. Open the Gallery app for these photos
3. Open a single photo (slideshow view)
### Expected behaviour

Assuming uploaded photos had proper resolution a sharp photo should appear.
### Actual behaviour

The resolution of the displayed photo fits (so this is not a duplicate to those issues pointing to resolution) but compression artifacts are visible.
Probably due to a low quality on JPEG compression?
### Server configuration

**Operating system**: 
Ubuntu 14.04 LTS
**Web server:**
 Apache/2.4.7 (Ubuntu) 
**Database:**
MySQL
**PHP version:**
PHP/5.5.9-1ubuntu4.14 OpenSSL/1.0.1f configured
**ownCloud version:** (see ownCloud admin page)
8.2.1
**Updated from an older ownCloud or fresh install:**
from 8.1.4, didn't test before 8.2.1 however

Question: Is there a way to set compression quality to 100% when you create the previews?

**Comment by oparoz** [comment]
This is a `core` issue. The default compression used is 75, which may indeed be too low for full screen previews.

Could you re-open the issue [here](https://github.com/owncloud/core/issues) and mention that the max previews should be using something like 90 instead of 75? I think 100 is too high and will lead to large files.

**Comment by georgehrke** [comment]
> The default compression used is 75

@oparoz Where do you get this 75 from?

**Comment by oparoz** [comment]
@georgehrke -> https://secure.php.net/manual/en/function.imagejpeg.php

**Comment by georgehrke** [comment]
thx :)
