### ISSUE TITLE
Clicking on folder label causes spinner to display without actually opening the folder.

### ISSUE THREAD

**Issue by setnes** [owncloud/gallery#466]
When I click on folders in my test instance (based on master), I sometimes will never be taken to the folder.  Instead, I will see the new spinner continue to spin.

I haven't figured out what is causing this yet.  Is it somehow related to the new spinner change?

**Comment by setnes** [comment]
I finally figured out how to reproduce this reliably.

If I click on the label (the shaded text area) for an album folder, I will get the spinner indefinitely.  If I click above the album label within the images for the album, the spinner will be displayed, very briefly, before the folder contents are displayed.

So... somehow clicking on the label is different from clicking above the label.  I noticed similar behavior for individual images.  Clicking the text does not open the image, but clicking above the text does.

**Comment by setnes** [comment]
It appears that moving... 

```
<span class="album-label">{{label}}</span>
```

...to be within the hyperlink "a" tag of the TEMPLATE variable defined at the top of galleryalbum.js resolves this problem.  I imagine a similar change might be wanted in galleryimage.js if you also want the image labels to be clickable.

```
        var TEMPLATE =
                '<div class="item-container album-container" ' +
                'style="width: {{targetWidth}}px; height: {{targetHeight}}px;" ' +
                'data-width="{{targetWidth}}" data-height="{{targetHeight}}">' +
                '       <div class="album-loader loading"></div>' +
                '       <a class="album" href="{{targetPath}}">' +
                '               <span class="album-label">{{label}}</span>' + 
                '       </a>' +
                '</div>';

```

@oparoz, let me know what you think of this and I'll see if I can find some time this week to put together a pull request.  I made the mistake of making the last one on my master branch, so I imagine I might need to do some renaming to have two in flight at the same time.  (still git challenged)

**Comment by oparoz** [comment]
Thanks for debugging this issue :)
The way forward is to drop the anchor (a tag) and use a new onClick behaviour for the top container. It should fix both this problem and allow for [better looking labels](https://github.com/owncloud/gallery/pull/456).

You can have a go at that change if you want to, should be straight forward. There are similar examples in the code already.

**Comment by setnes** [comment]
That's a curve ball challenge.  :)

There is already a click tied to _showLoader.  Do you want two click functions... one to call _showLoader and one to call something new like _openAlbum?  I think that would work.

I think we can reference encodeURIComponent(this.path) within an _openAlbum function.  What's the best way to open the page?

Also... it looks like there is some tricky logic that appends thumbnail divisions as children to the anchor tag.  All that logic would need to be reworked if we drop the "a".  This might be a little more complicated than you are thinking.  It looks like the "a" gets passed around a bit as well to make that happen.

**Comment by oparoz** [comment]
> There is already a click tied to _showLoader. Do you want two click functions... one to call _showLoader and one to call something new like _openAlbum? I think that would work.

I think one would suffice. we just want to show the loader and open the album. That function can be renamed to openAlbum.

> What's the best way to open the page?

https://github.com/owncloud/gallery/blob/5628f45fd2a4bd5371923e9ba82a178275514035/js/gallery.js#L359-L365

> All that logic would need to be reworked if we drop the "a"

span or div replacement?

>  This might be a little more complicated than you are thinking

The implementation is a bit more complex for albums than it is for images, but I think it's the right way forward :)

**Comment by setnes** [comment]
I might take a stab at this.  It might take me a little time to get it right though.

I think styles.css will also need to change for a.album and a.image.

**Comment by oparoz** [comment]
Cool, keep me posted and I'll help if needed.
