### ISSUE TITLE
Breadcrumb for current album goes to #.

### ISSUE THREAD

**Issue by setnes** [owncloud/gallery#469]
The href for the current album's breadcrumb is set to "#".  This takes you to the base path when clicked.  The old behavior was to not have the current album's breadcrumb be a link.

**Comment by oparoz** [comment]
I don't understand, the current album is `#currentAlbum`. Home is `#`.

**Comment by setnes** [comment]
I think a screenshot will explain this better than words.

![selection_2015-12-05-09 48 42](https://cloud.githubusercontent.com/assets/12475102/11608675/d6fd20f8-9b35-11e5-8095-44db7cf845f7.jpg)

**Comment by oparoz** [comment]
You're right:
https://github.com/owncloud/gallery/blob/master/js/breadcrumb.js#L147

There needs to be an extra condition in that method which only adds the hash if there is a link.
