### ISSUE TITLE
gallery (i.e. folder) name not shown in sharing email

### ISSUE THREAD

**Issue by svenXY** [owncloud/gallery#47]
Hi,

thanks for making sharing galleries possible in oC6!

One little thing left:

In the mail subject for instance, it just says 

```
'<name> shared << >> with you,
```

That means that the variable for the folder/gallery in 'en_GB/core.po': 'msgid "%s shared »%s« with you"'name does not seem to get filled.

Can this please get fixed?

Thanks a lot,
Sven

**Comment by oparoz** [comment]
That's a core issue. Closing
