### ISSUE TITLE
Single photo view confusing download icon position.

### ISSUE THREAD

**Issue by LeonFedotov** [owncloud/gallery#474]
Hi the download icon is confusing and makes me think i'm preforming a gesture when its in the top center  like that, perhaps the bottom left corner is a better fit.

**Comment by jancborchardt** [comment]
@oparoz ;) I said it’s confusing at the top. Would be cool if we can finally bring it next to the image name for 9.0

cc @owncloud/designers

**Comment by oparoz** [comment]
One thing after the other ;) . The first thing to do is to move them back to the right. I didn't like them there because the style of those icons is different, but it doesn't work in the centre.
After that we'll have to see some ~~landscape~~ portrait mock ups in the relevant issue to be able to make a decision.

**Comment by LeonFedotov** [comment]
Here you go: 
![mockup](https://cloud.githubusercontent.com/assets/130342/11641395/c713ca04-9d40-11e5-92d1-e162dd415f66.jpg)
also file extension looks kinda funny in the preview context (mobile use) :dancer:

**Comment by raghunayyar** [comment]
can we have that as a button at the bottom right of the image instead of just an image along with the file name?

**Comment by oparoz** [comment]
@raghunayyar - There is already the autoplay button at the bottom right. As I said earlier, we'll first move the action buttons back to the right and then decide if those need to move to the bottom based on a solid business case including both desktop and mobile mockups of various button placements to see what works best. The goal is to find the combination which offers the least problems. See https://github.com/owncloud/gallery/issues/351

**Comment by jancborchardt** [comment]
@oparoz how did you end up fixing this? :)

**Comment by oparoz** [comment]
It's not what you think it is... I just sort of reverted the move to the centre. So the 2 extra icons are back to the top right and the next steps will be taken in #351
