### ISSUE TITLE
Add per-album option to enable Gallery View by default

### ISSUE THREAD

**Issue by kulve** [owncloud/gallery#476]
When sharing album links to others, they see the list view with small thumbnails and the file name. It seems that a typical user doesn't know that they need to click the file name to see the image and not click the thumbnail of the image which only allows them to select images for downloading.

This isn't a problem in the Gallery View as there the user sees only thumbnails/previews.

If the album owner would be able to choose the Gallery View as the default view for the shared albums (e.g. by using the gallery.cnf), the users watching the albums without Owncloud experience wouldn't be so lost.

**Comment by oparoz** [comment]
You can currently create a gallery link using the [ShareLinks](https://apps.owncloud.com/content/show.php/ShareLinks?content=170527) app. Isn't it enough?

**Comment by kulve** [comment]
ShareLinks doesn't seem to support Owncloud 8.2. And based on the description it doesn't allow me to enable different views but I couldn't verify that as I have 8.2 installed.

**Comment by oparoz** [comment]
> ShareLinks doesn't seem to support Owncloud 8.2

Not yet. That's due to the new side-bar

> And based on the description it doesn't allow me to enable different views 

You pick the view you want to share and it generates a link for that view. You then share that link and they will get the proper view.

**Comment by kulve** [comment]
Why was this closed without any comment? The plugin suggested earlier doesn't support the latest version of Owncloud nor does it seem to be under development.

**Comment by oparoz** [comment]
It was closed due to inactivity. The solution is to use ShareLinks or any clone which offers the same functionality since the `core` team doesn't want to add views to the sharing dialogue. The alternative is to share using the Gallery view since it shows the proper link already.

Gallery can't hijack the Files app to redirect it to the Gallery view when a user lands there.

**Comment by kulve** [comment]
"Share using the gallery view" is actually what I was after here. I just didn't realise that different views to same folder give different kinds of URLs.

Thanks!

**Comment by oparoz** [comment]
:)
