### ISSUE TITLE
App name not transtlated when gallery is active.

### ISSUE THREAD

**Issue by matiasdelellis** [owncloud/gallery#479]
My owncloud is configured in Spanish..  
To understand the bug please see these images:

On the files view, the gallery app is showed translated into Spanish.. (Gallery > Galería)
![captura de pantalla_2015-12-17_22-00-46](https://cloud.githubusercontent.com/assets/733715/11886544/eb3bf96c-a509-11e5-9a65-e13a01784903.png)

When use the gallery application, it is shown in English..  :disappointed: 
![captura de pantalla_2015-12-17_22-07-22](https://cloud.githubusercontent.com/assets/733715/11886601/9b6a38c6-a50a-11e5-8437-f12f5630db94.png)

**Comment by oparoz** [comment]
Thanks for the report. It could be that this has not been translated yet.

**Comment by oparoz** [comment]
No missing string. Are you sure this is only happening with Gallery?

**Comment by matiasdelellis** [comment]
Hi,
Assuming that the string inside or outside of the application is the same, it is impossible that just was a missing translation..At least I understand this. :confused: 

In the same pictures you can see that inside the gallery application, translation of mail also is wrong.

**Comment by oparoz** [comment]
I mean, if you go to "calendario", does the icon say "Calendar"?

**Comment by matiasdelellis** [comment]
Hi,
- Within Files all translated (First image of this issue)
- Within Activity: "Actividad" translated but Gallery and Mail are not tranlated. (Simil Second image)
- Within Mail:  Neiter Gallery and Mail are not tranlated. (Simil Second image)
- Within Gallery: Neiter Gallery and Mail are not tranlated. (The Second image)
- Within calendar: "Calendario" and rest of strings are tranlated but Gallery and Mail not. (Simil Second image)
- Within Contacts the same: "Contactos" and rest strings ok but Gallery and Mail are not tranlated. (Simil The Second image)

**Comment by matiasdelellis** [comment]
Hi oparoz,
I discovered something curious, and perhaps is relevant..
I entered to my owncloud from my Android phone and everything works correctly...The rest of the tests were always in Firefox on diferents Linux.

Regards,

**Comment by oparoz** [comment]
Thank you very much for your investigative work.

Since the string is made available for translation and has been translated,
https://github.com/owncloud/gallery/blob/master/appinfo/app.php#L49
there may be a bug in `OCP\INavigationManager` or `OCP\IL10N`

@nickvergessen @MorrisJobke Any pointers?

**Comment by nickvergessen** [comment]
Bug in ownCloud fixed in the 8.2.2 release for this week

**Comment by oparoz** [comment]
Thank you @nickvergessen
