### ISSUE TITLE
random order?

### ISSUE THREAD

**Issue by ak1n** [owncloud/gallery#480]
Is there a way to display images in a random order rather than the date/name options listed on the wiki page in the sort section?

If the answer is presently no, could anyone perchance reference the area of code dealing with sorting? Would handling this simply involve randomizing a received file array (initially and then upon each completion of the full rotation)?

Thanks for any recommendations/thoughts in this regard!
##

**Comment by oparoz** [comment]
> Is there a way to display images in a random order rather than the date/name options listed on the wiki page in the sort section?

Nope... Didn't think there was a need :)

> Would handling this simply involve randomizing a received file array (initially and then upon each completion of the full rotation)?

That's correct.

This returns the list of files:
https://github.com/owncloud/gallery/blob/5628f45fd2a4bd5371923e9ba82a178275514035/js/gallery.js#L67

For a quick hack, you could add your own sorting order at the end of the function by calling `Gallery.config.updateAlbumSorting`

But you will need to create a new "random" sorting type in here: https://github.com/owncloud/gallery/blob/5628f45fd2a4bd5371923e9ba82a178275514035/js/galleryutility.js#L185

**Comment by oparoz** [comment]
This issue was moved to nextcloud/gallery#104
