### ISSUE TITLE
Wrong GalleryImage arguments in Album._showFolder

### ISSUE THREAD

**Issue by oparoz** [owncloud/gallery#483]
https://github.com/owncloud/gallery/blob/d982e0e976ab91ecbf52d5917bbdebad79351035/js/galleryalbum.js#L296

```
var image = new GalleryImage('Generic folder', 'Generic folder', -1, 'image/svg+xml',
                Gallery.token); 
```

but  in https://github.com/owncloud/gallery/blob/d982e0e976ab91ecbf52d5917bbdebad79351035/js/galleryimage.js#L25

```
var GalleryImage = function (src, path, fileId, mimeType, mTime, etag) {
```

**Comment by virajparimi** [comment]
According to my understanding only the modification time parameter is missing. So do we just just need to add that argument.

**Comment by oparoz** [comment]
Almost correct, `etag` is also missing. I've updated the OP to make it clearer.

So just send `null` for these arguments. 

Make sure you understand how to test this. It's important for the functionality to still work without throwing any errors.

**Comment by virajparimi** [comment]
The function declaration has 6 parameters and the call has 5 already, so I thought only 1 parameter was missing. If 2 are missing then wont the declaration and the call still have different parameters.

**Comment by oparoz** [comment]
> The function declaration has 6 parameters and the call has 5 already

Exactly, so the call needs to be modified to match the declaration

**Comment by virajparimi** [comment]
I was saying that ONLY mTime is missing but you later told that even etag is missing. If I were to send null for these arguments then total parameters to call would become 7. Are we supposed to delete a parameter that is already being passed?

**Comment by oparoz** [comment]
> Are we supposed to delete a parameter that is already being passed?

Yes, because the token currently sent is not being used. It's a leftover.

**Comment by virajparimi** [comment]
I am stuck on how to go about testing the fix. As of now I know that I need to make [`_getFourImages` ](https://github.com/owncloud/gallery/blob/master/js/galleryalbum.js#L210)function to fail so that the fail variable becomes true. Could you guide me further on how to go about it.

**Comment by oparoz** [comment]
Sure :)
1. Create an empty folder
2. Put a corrupt JPG in it. Just delete a few hundred bytes and make sure you can't get a preview in ownCloud.
3. Load the folder above in Gallery

You should get a folder thumbnail instead of an image.

**Comment by virajparimi** [comment]
Thanks. Just wanted to inform that the change does not affect the working at all. It still shows the folder thumbail which it used to show initially as well.
