### ISSUE TITLE
Switch from Math.floor() to Math.ceil() when sending the dimension to Preview

### ISSUE THREAD

**Issue by oparoz** [owncloud/gallery#484]
We're still using Math.floor() when we want to round one of the dimensions of an image after applying window.devicePixelRatio, but I think what we really want is Math.ceil(), as otherwise pictures can still end up being a bit blurry since they will be smaller than the expected size.

See https://github.com/owncloud/core/commit/46475b81147633060cd24f026d54eee77aa559d2

**Comment by AbdealiLoKo** [comment]
HI, could someone assign this to me ?
I wanted to begin contributing at owncloud and saw this "Junior job" issue which I wanted to begin with.

**Comment by oparoz** [comment]
Thanks for taking an interest :)
In order to be able to assign you to tasks, you need to become an ownCloud contributor by signing the agreement:
https://owncloud.org/contribute/agreement/

It's not necessary to become one for MIT contributions though.

**Comment by AbdealiLoKo** [comment]
Ah, I thought that was only for `core` - sure, will do it soon

**Comment by oparoz** [comment]
Gallery is a bit different because it's shipped as part of the enterprise product.
