### ISSUE TITLE
Make images and albums selectable in the photowall

### ISSUE THREAD

**Issue by arkascha** [owncloud/gallery#487]
The file list view of a folder offers a checkbox per file to select multiple files and use actions on a set of selected files. 

The same would be very useful in the galleries photowall, since it offers a much better preview of the individual files. For albums this would clearly the preferred way to make a selection. Possible actions for sets of selected pictures would be: 
- download of set as an archive
- preview of set in slideshow
- deletion of elements in set
- moving of elements in set
- ...

The actions are already implemented, this enhancement is just a duplication of an existing feature inside the front end. 
##

**Comment by oparoz** [comment]
Yes, it's on my roadmap, but after [drag and drop](https://github.com/owncloud/gallery/issues/405) has been implemented (and after that, there may be other priorities as well)

**Comment by oparoz** [comment]
This issue was moved to nextcloud/gallery#105
