### ISSUE TITLE
"No pictures found"

### ISSUE THREAD

**Issue by Biopticon** [owncloud/gallery#489]
Hello,

I enabled Gallery+ application. I opened the Gallery+ page. After a long hour glass activity, it said "No pictures found. Upload new pictures in the files..." So I tried to create picture thumbnails manually by issuing the following command:

sudo -u www-data ./occ gallery:create-thumbnails --path=/media/OwnCloud/data/user/files/documents/Music

But I get the following error:

[InvalidArgumentException]
There are no commands defined in the "gallery" namespace.

What's wrong? How can I make Gallery+ app to index the pictures in the "/media/OwnCloud/data/user/files/documents/Music" directory (at an external drive)?

**Comment by oparoz** [comment]
Hello, thanks for the report.

In order to be able to tell what's wrong with your ownCloud and why you have to wait for so long, we need more information, especially the logs. Please use this form: https://raw.githubusercontent.com/owncloud/core/master/issue_template.md

Regarding the command, I should mention in the wiki that this feature hasn't been released yet. It's only available if you get these files: https://github.com/owncloud/gallery/pull/387

**Comment by Biopticon** [comment]
Hello Oparoz,

Here are the answers to issue_template. I did not attach the OC and Apache logs yet. They are too big. I do not know how to incorporate files #387 to my OC installation. I appreciate simple instructions.

Thank you.

### Steps to reproduce
1. cd /var/www/owncloud
2. sudo -u www-data ./occ gallery:create-thumbnails --path=/media/OwnCloud/data/user/files/documents/Music

### Expected behaviour

The necessary thumbnails are created for the Gallery+ app.

### Actual behaviour

I get the following error

 [InvalidArgumentException]
  There are no commands defined in the "gallery" namespace.

### Server configuration

**Server:**Debian 7

**Web server:**Apache 2.2.22

**Database:**mySQL 5.5.46

**PHP:****PHP 5.4.45

**OwnCloud:**OwnCLoud 8.1.5-12.1

OC updated from version 7

**OC apps:**
- activity: 2.0.2
- calendar: 0.7.3
- contacts: 0.4.0.1
- files: 1.1.10
- files_external: 0.2.3
- files_pdfviewer: 0.7
- files_sharing: 0.6.3
- files_texteditor: 0.4
- files_trashbin: 0.6.3
- files_versions: 1.0.6
- files_videoviewer: 0.1.3
- firstrunwizard: 1.1
- galleryplus: 14.3.0
- music: 0.3.8
- templateeditor: 0.1

**The content of config/config.php:**

<?php
$CONFIG = array (
  'instanceid' => 'adsd',
  'passwordsalt' => 'sds',
  'secret' => 'sdds$
  'trusted_domains' =>
  array (
    0 => 'mydomain.com',
  ),
  'datadirectory' => '/media/OwnCloud/data',
  'overwrite.cli.url' => 'https://mydomain',
  'dbtype' => 'mysql',
  'version' => '8.1.5.2',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'oc_girit',
  'dbpassword' => 'dsdasd',
  'installed' => true,
  'mail_smtpmode' => 'smtp',
  'mail_smtpsecure' => 'tls',
  'mail_from_address' => 'user',
  'mail_domain' => 'isp.net',
  'mail_smtpauthtype' => 'LOGIN',
  'mail_smtpauth' => 1,
  'mail_smtphost' => 'smtp.sip.net',
  'mail_smtpport' => '587',
  'mail_smtpname' => 'user',
  'mail_smtppassword' => 'pswd',
  'forcessl' => true,
  'debug' => true,
  'loglevel' => 0,
  'theme' => '',
  'maintenance' => false,
  'forceSSLforSubdomains' => true,
  'memcache.local' => '\OC\Memcache\APC',
  'enable_previews' => false,
  'preview_max_scale_factor' => 1,
  'enabledPreviewProviders' =>
  array (
    0 => 'OC\Preview\PNG',
    1 => 'OC\Preview\JPEG',
    2 => 'OC\Preview\GIF',
    11 => 'OC\Preview\Illustrator',
    12 => 'OC\Preview\Postscript',
    13 => 'OC\Preview\Photoshop',
    14 => 'OC\Preview\TIFF',
  ),
);

```

**Are you using external storage, if yes which one:** local/smb/sftp/...** Yes. /media/owncloud

**Are you using encryption:** yes

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/.. No

#### LDAP configuration (delete this part if not used) No

```

### Client configuration

**Browser:** Firefox

**Operating system:** Win 7

### Logs

#### Web server error log

```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)

```
Insert your ownCloud log here
```

#### Browser log

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by oparoz** [comment]
I think you misunderstood me. I need the report for the problem where you can't see anything in Gallery (spinning wheel). The browser logs should be enough to begin with. You need to hit F12 to see if any errors are reported.

I don't need a report on the thumbnail generating command since that feature is not available in Gallery yet. I've updated the wiki earlier to mention that.

If you want the feature now, you need to download all the files of the PR and try to see if it works. It's completely unsupported at the moment.

**Comment by Biopticon** [comment]
Hello Olivier,

Thank you. Sorry about my naivety. I did not know you could find out errors on a webpage like that! I attached a picture showing the errors I got after spinning wheel come back and displayed the message that "there are no pictures".

 I just need to view the pictures in the Gallery+ app. I thought, enabling the app would be sufficient to view them. I could not find any document to learn if there are steps to direct the app to the pictures folder under Files.  If there are actions to implement in Gallery + in order index them I do not need to use the command line program to do it.  So basically the question is what to do in Gallery + or in OC admin to be able to view my pictures in the /media/OwnCloud/data/user/files/documents/Pictures folder in an external drive?

![capture](https://cloud.githubusercontent.com/assets/6756426/12148067/620d405e-b46a-11e5-87af-344844343602.JPG)

**Comment by oparoz** [comment]
You are correct, Gallery(+) is plug and play, unless you have some special requirements (like adding external storage) or if ownCloud encounters a bug when reading files or generating previews.

How did you add the external drive in ownCloud? If it's via the ~~`external_shares`~~ `files_external` app, you need to make sure previews are enabled for that location and you need to add [this config file](https://github.com/owncloud/gallery/wiki/Gallery-configuration#load-images-from-external-clouds) in your root folder.

If not, do this.
In debug mode in Firefox.
1. go to the network tab
2. hit refresh (F5)
3. click on the entry which starts with `list?location`
4. click on params
5. paste content here
6. click on the response tab
7. paste content here (remove private info)

**Comment by Biopticon** [comment]
Hello Olivier,

The external drive is defined in the OC config.php (see the previous post):

'datadirectory' => '/media/Biopticon/OwnCloud/data',

Although I am using the file_external app (not external_shares though), I did not do anything to make sure that previews were enabled. Then, based on your suggestion I added a gallery.cnf file in the /media/OwnCloud/data/user/files/documents/  folder (Pictures folder is a sub folder of the documents). But when I went to the Gallery page, the spinning wheel reported no picture files!

I followed your instruction and opened the Gallery + page of my OC site with Chrome. I found the 'list?location' entry but could not locate 'parms' to report its contents, and the contents of the "response" tab is empty. See the attached picture.
![capture](https://cloud.githubusercontent.com/assets/6756426/12152714/02c28d88-b484-11e5-8825-d6796a076d13.JPG)

**Comment by oparoz** [comment]
Hello @Biopticon. Thanks for the information.

`files_external` is the app I was talking about. If you can see thumbnails in the Files app, it means that previews are working and that it's a problem with Gallery.

You need to place the `gallery.cnf` file in `/media/OwnCloud/data/user/files/` folder. That's your root folder.

I apologies, the instructions I gave you were for Firefox, since I noticed at the last minute that that's what you were using in your screenshot. I forgot to remove the half written sentence above the steps.

But the fact that you get an empty response is not a good sign and that's the reason I want to look at the params.

In the network tab, you should see a line which starts with `config`. Could you please paste the response you get?

**Comment by Biopticon** [comment]
Hello Olivier,

 I am sorry not being responsive for a long time. I placed the gallery.cnf file into the root directory. But still I do not get any images in the Gallery+ page. But there is an orange background with large font blue letter on the left corner.

Here is my gallery.cnf file:

```
#Gallery configuration file
features:
  external_shares: yes
  native_svg: yes
  background_colour_toggle: yes
design:
  background: "#ff9f00"
  inherit: yes
information:
  description: My Album
  description_link: readme.md
  copyright: Copyright 2003-2015 [interfaSys sàrl](http://www.interfasys.ch), $
  copyright_link: copyright.md
  inherit: yes
sorting:
  type: date
  order: des
  inherit: yes
```

Here are the results of the diagnostics on Firefox as you suggested:
1.  Response tab gives nothing (empty).
2.  Params tab:
   ![params](https://cloud.githubusercontent.com/assets/6756426/12691546/ce0b1616-c6ba-11e5-873d-fbaae6a6eaec.jpg)
3.  Headers tab
   ![headers](https://cloud.githubusercontent.com/assets/6756426/12691604/78876a4a-c6bb-11e5-9637-b272eabecce7.jpg)
4.  Timings is empty.

Any ideas? Thank you.

**Comment by oparoz** [comment]
OK, so the problem is that you only have SVG enabled (because it's defined in gallery.cnf).
Maybe you have disabled previews?

**Comment by oparoz** [comment]
Yep, it's in your config, in the OP: `'enable_previews' => false,`

So enable previews and it should work.

**Comment by Biopticon** [comment]
Hello Olivier,

It worked! Thank you. How can I make the pictures folder selected rather than top level "documents" folder?

**Comment by oparoz** [comment]
You can't. Gallery works the other way around. You can ignore folders, but of course, that won't work for the top folder...
