### ISSUE TITLE
 GDrive-like grid view

### ISSUE THREAD

**Issue by RoxasShadow** [owncloud/gallery#492]
For me would be great having the possibility to have a grid view similar to the Google Drive one with nice cropped image that share the same size.
I think it's an elegant and efficient way to look at the image thumbnails.

_Gallery+_
<img width="341" alt="screen shot 2016-01-07 at 12 28 50" src="https://cloud.githubusercontent.com/assets/805144/12169644/4ed1950a-b53a-11e5-805d-df245cab9fd9.png">

_Google Drive_
<img width="1167" alt="screen shot 2016-01-07 at 12 27 45" src="https://cloud.githubusercontent.com/assets/805144/12169715/d1431d9c-b53a-11e5-92d5-0d1ade39b6f6.png">
##

**Comment by oparoz** [comment]
My position is that this grid view belongs to the Files app: https://github.com/owncloud/core/issues/17357

Other layouts can also be implemented in Gallery, but this has a low priority for me.

**Comment by oparoz** [comment]
This issue was moved to nextcloud/gallery#107
