### ISSUE TITLE
Is there a way or an API to rotate images?

### ISSUE THREAD

**Issue by elpraga** [owncloud/gallery#494]
Can images be rotated in the Gallery app or is there an app that the android app can use to rotate the images and regenerate the thumbnails?

**Comment by oparoz** [comment]
If an Android app can rotate a picture and modify it's metadata, then once it's uploaded to ownCloud again it should show up with the correct rotation in ownCloud.

It should be possible in the future to rotate images from within Gallery. See https://github.com/owncloud/gallery/issues/236
