### ISSUE TITLE
Improved screen resolution detection on scaled screens

### ISSUE THREAD

**Issue by oparoz** [owncloud/gallery#495]
Gallery uses `screen.width` to detect the screen's width and apparently it doesn't work for everybody when the screen is scaled, so we need to see if we can improve the detection of the user's screen resolution.
### Example
- The original image is 1200x849
- The screen resolution of the device is 2880x1800,
- The resolution is scaled down in the OS to 1280x800

The image should nearly fill the viewport, but instead it looks like it should look like if the screen resolution was 2880x1800.
The problem is that neither Javascript, nor CSS, are reporting correct values for the screen.

I'll put this down to a bug in the OS or the browser. If something modifies the resolution, it should advertise the change to all applications needing it.

This is the request made by Gallery

``` html
<img src="/index.php/apps/galleryplus/preview/59594?c=fc01f2275f4c1ebdc962202b35307850&amp;width=2900&amp;height=2900&amp;requesttoken=..." alt="51284906_p0_master1200.jpg" style="position: absolute; background-color: rgb(0, 0, 0); background-size: 660px 466.95px; top: 46px; left: 462px; background-position: 0px 0px; height: 466.95px; width: 660px;">
```

And this is the result
<img width="1440" alt="screen shot 2016-01-07 at 11 49 25" src="https://cloud.githubusercontent.com/assets/805144/12168781/c6d2536a-b534-11e5-8b80-feaee318ba08.png">
##

**Comment by oparoz** [comment]
@RoxasShadow, could you post a screenshot of the info on http://www.mydevice.io/ ? I'd like to see which resolution is reported via CSS and JS, as well as the pixel ratio, etc.
Thanks.

**Comment by oparoz** [comment]
Pinging @jancborchardt as this can also affect `core` and is an accessibility issue.

**Comment by oparoz** [comment]
And maybe @henni has a solution :)

**Comment by Henni** [comment]
As your linked page http://www.mydevice.io/ suggests, `body.clientWidth` probably solves this issue.

**Comment by oparoz** [comment]
Unfortunately `body.clientWidth` works like `window.innerWidth` and we can't use it because if you go full screen you'll have a small preview, the size of the original window

**Comment by RoxasShadow** [comment]
@oparoz sure, [here](https://cloud.githubusercontent.com/assets/805144/12275656/8b59e1c2-b971-11e5-9917-af4234510ae6.png) it is.

**Comment by oparoz** [comment]
![](https://cloud.githubusercontent.com/assets/805144/12275656/8b59e1c2-b971-11e5-9917-af4234510ae6.png)

Thanks. All the variables are returning the natural screen resolution, so I don't know how to solve this, but anybody is welcome to give it a try.

**Comment by derfritsch** [comment]
I'd like to mention an additional use case, in which a scaling of the image would be desired:

In case the 'preview_max_x' and 'preview_max_y' are set in config.php (which might be chosen if bandwidth is limited), only size-limited previews will be shown for all images. Personally, I would prefer to look at those previews being blown up to fill the full viewport, rather than being scaled to the size specified by 'preview_max_x' and 'preview_max_y'.

**Comment by oparoz** [comment]
Once we have user settings, the scaling ratio would be an ideal candidate. Doesn't solve the initial problem though.

**Comment by oparoz** [comment]
This issue was moved to nextcloud/gallery#108
