### ISSUE TITLE
Add missing options to the share dialogue

### ISSUE THREAD

**Issue by elacour** [owncloud/gallery#498]
Dear OC developpers,
I'm using OC 8.2.2 with gallery+ 14.3.0.

When viewing an album I can share it to other using the top right icon, by user name or using link.

But there is three issues:
- using public link, I cannot send email. It works on file app
- ~~using a named target user, I cannot change the permissions~~
- using a named target user, I cannot send him an email

See gallery+ screenshot:

![galleryplus-app](https://cloud.githubusercontent.com/assets/101576/12377849/7e6c1e04-bd2b-11e5-9f89-85d3923475c6.png)

and files app screenshot:

 ![files-app](https://cloud.githubusercontent.com/assets/101576/12377848/7ad771f8-bd2b-11e5-803a-f1d85d256930.png)
##

**Comment by oparoz** [comment]
Thanks for the detailed report :+1: 
It's a known issue and may be fixed by itself if and when we switch to using a sidebar or if someone wraps the sharing content from Files into a dialogue.

**Comment by oparoz** [comment]
The permissions now work properly. Fix will be available in 8.2.3 and Gallery+ 15.0

**Comment by oparoz** [comment]
Send via email is tracked in https://github.com/owncloud/gallery/issues/213
Allow uploading is tracked in https://github.com/owncloud/gallery/issues/565

**Comment by oparoz** [comment]
This issue was moved to nextcloud/gallery#109

**Comment by Milo-W** [comment]
It still doesn't work, does it? I can't see the "share" button or something.
