### ISSUE TITLE
Gallery only finds new pictures on external storage (files_external) after logging off/on

### ISSUE THREAD

**Issue by mmattel** [owncloud/gallery#499]
- I have created a test instance via `ocdev setup base --dir=xxxx`
- Then I added a external smb share (with 19k pictures)
- Manually started `./occ -uwww-data files:scan --all`
- After finishing, Gallery told me that there are no pictures found.
- After logging off and relogging on, Gallery finds the pictures and presents them.
##

**Comment by oparoz** [comment]
Probably because of https://github.com/owncloud/core/blob/master/config/config.sample.php#L1104

**Comment by mmattel** [comment]
nope, is set to `'filesystem_check_changes' => 1,`

**Comment by oparoz** [comment]
On 8.2 you may have to set it to 2: https://github.com/owncloud/core/blob/stable8.2/config/config.sample.php#L1057

But there isn't much Gallery can do. It asks for a list of files which have a supported media type and the cache says there is nothing.

You can try to open a report in `core` to see if there is a different process you can use.

**Comment by oparoz** [comment]
Also, check your logs, there may be 503s or something similar.

**Comment by oparoz** [comment]
Now that https://github.com/owncloud/core/pull/23561 has been merged, do you still have the issue?

**Comment by oparoz** [comment]
This issue was moved to nextcloud/gallery#110
