### ISSUE TITLE
Add REST API

### ISSUE THREAD

**Issue by oparoz** [owncloud/gallery#5]
## General
- Versioning will happen using headers
- Authentication happens via HTTP auth
## Config API

Gives information about the supported features as well as the list of supported media types
- [x] `/api/config`
## Files API

Gives the list of files found in the folder given as argument and lets you download a file
- [x] `/api/files/list`
- [x] `/api/files/download/{fileId}`
## Preview API

Gives you a list of base64 encoded thumbnails when you connect to the thumbnails endpoint using EventSource and gives you a resized preview when you use the preview endpoint
- [x] `/api/preview/thumbnails`
- [x] `/api/preview/{fileId}/{width}/{height}`

**Comment by oparoz** [comment]
The API can be tested using Codeception.
You need to install Codeception via composer as we need a local web server to run during the test. See this doc for details: https://github.com/owncloud/gallery/blob/master/tests/README.MD#install-via-composer

Then you simply do:

```
# cd apps/gallery
# vendor/bin/codecept run api
```

If you need a more verbose output to check the scenarios, use:
`# vendor/bin/codecept run api -vvv`

**Comment by ghost** [comment]
@rperezb can someone have a look?

**Comment by rperezb** [comment]
@SergioBertolinSG may check this one, once he finishes with the encryption one

**Comment by oparoz** [comment]
@SergioBertolinSG - There is now some documentation for the API: https://github.com/owncloud/gallery/wiki/RESTful-API

**Comment by SergioBertolinSG** [comment]
@oparoz Awesome, thanks.

**Comment by oparoz** [comment]
I'm going to close this since the tests are used in CI.
We'll have a better idea of if it meets the needs of developers when they start using it.
Any missing, interesting test case, just add them directly to the tests or post new scenarios.
