### ISSUE TITLE
Try to fix the horrible scrolling performance on mobile introduced by core on 8.2

### ISSUE THREAD

**Issue by oparoz** [owncloud/gallery#500]
I don't remember all the details, but I think that from 8.2 the controls are in a fixed div which kills all hardware acceleration on mobile.
- [x] Find out why this was introduced exactly
- [x] Fix it if we don't have a reason to use the same CSS
### Desktop
- Chromium/win10: no visible change
- Firefox/win10: no visible change
- Edge/win10: no visible change
- IE11/win10: no visible change
### Mobile
- Chrome/ios9: huge performance gains. Activates smooth kinetic scrolling
- Safari/ios9: huge performance gains. Activates smooth kinetic scrolling with bouncing edges
- Browser/BB10: improves scrolling performance
- Chrome/Android 4.x: huge performance gains. Activates smooth kinetic scrolling
- Firefox/Android 4.x: no visible change. Seems like hardware acceleration is not available on 4.x
- Chrome/Android 5.x
- Firefox/Android 5.x
- Chrome/Android 6.x
- Firefox/Android 6.x

**Comment by oparoz** [comment]
I think there is hope :). It involves reorganising the templates. Hopefully this won't lead to to much code re-writing.

**Comment by oparoz** [comment]
Re-opening this to give a chance to people to voice their opinion if something doesn't seem right on Android 5+

**Comment by davivel** [comment]
I'll have a look.

**Comment by ghost** [comment]
@davivel any update?

**Comment by davivel** [comment]
Sorry, @cmonteroluque , I forgot this one :$. I'll have look today.

**Comment by davivel** [comment]
@oparoz , I'd need some more details about how did you compare peformance. 

I tried this:
- Server 1: OC server master + gallery app v9.0 installed via git, folder with over 200 pictures from Nexus camera
- Server 2: OC server 8.2 + gallery app v8.2 installed via git, folder with same pictures from Nexus camera
- client: Nexus 5 with Android 6, Chrome 49.0.2623.105 ; I use two devices with same configuration to access at the same time to server 1 and server 2 in each of them and compare visually.
- Steps: Access to folder in Chrome, enable 'grid mode', scroll up & down several times.

I don't find performance problems with none of them, what makes me suspect that my environment or my test is not appropriate. Please, tell me what you think about it.

I can see that accessing to server 1 (newest), when scrolling fast the pictures that get out of the view are not there immediately when scrolling back to the same position, such as they are not kept in memory all the time. Accessing server 2, when scrolling fast pictures are always there. There is also a visual effect (animation) when a picture is loaded for the first time (picture is slightly too big and then is scaled down to fit the screen) in server 1 not existing in server 2. I can't find any other difference.

**Comment by oparoz** [comment]
@davivel - You did everything right. The visual effects are due to changes to the way rows are loaded and are unrelated.

The fact that you don't see any difference means that this has been addressed by Chrome on Android on version 5+, which is a good thing. It still affects iOS though and the reason I had to introduce the fix.

Could you test with Firefox mobile?

**Comment by davivel** [comment]
Of course. On Monday, my first task. :)

**Comment by oparoz** [comment]
Thanks :)

**Comment by ghost** [comment]
thank you both!

**Comment by davivel** [comment]
Tested in Firefox 45.0.2 + Android 6.0.1 ; same as in your tests with Android 4, @oparoz , no visible change between both versions, visibly worse than Chrome. Probably you are right, no hardware acceleration available.

**Comment by oparoz** [comment]
Thanks @davivel . I'm closing this as there are no side-effects with the changes, only benefits on some Webkit implementations.

**Comment by davivel** [comment]
Happy to help :)
