### ISSUE TITLE
Thumbnails, libjpeg: recoverable error: Invalid SOS parameters for sequential JPEG

### ISSUE THREAD

**Issue by rajil** [owncloud/gallery#502]
Hello,

I have some photos taken from a phone which render fine in gwenview and gimp, but give an error in owncloud. The errors I get in the owncloud.log file is
"imagecreatefromjpeg(): gd-jpeg, libjpeg: recoverable error: Invalid SOS parameters for sequential JPEG"

The web UI is unable to show the thumbnail.
The relevant packages i have installed are php56-gd-5.6.17 and jpeg-turbo-1.4.2

Google returned this
https://github.com/golang/go/issues/3916
https://code.google.com/p/go/issues/detail?id=3916

**Comment by oparoz** [comment]
Hello,
Although it might not seem logical, please open the same report here:
https://github.com/owncloud/core/issues

Gallery does not generate previews, it just uses them.
