### ISSUE TITLE
OC 8.2.2, public share does not longer scroll

### ISSUE THREAD

**Issue by elacour** [owncloud/gallery#503]
Since upgrade of my OC from 8.2.1 to 8.2.2, public links of gallery do not longer scroll to next pictures. See attached screenshot. Tested on firefox (iceweasel) 43.0.4. Console does not report error, network console does not report failures. It just stops loading leaving half (or part) of the last row.

![capture d ecran de 2016-01-26 21-26-05](https://cloud.githubusercontent.com/assets/101576/12593852/75bd31e0-c473-11e5-81c6-4e0145d322b6.png)

**Comment by elacour** [comment]
Same problem with 41.0.2272.118. Seems server side problem, thought no php errors in logs.

**Comment by artemanufrij** [comment]
Same here... FF, Chrome, Midori, Browser (Samsung Tablet, Ubuntu Phone BQ4.5).

**Comment by khlschrnk** [comment]
Same here. Running kubuntu 15.10 on my server. I just updated from 8.2.1 to 8.2.2 (I think it included gallery-14.2) and can see now the same behaviour:
The gallery thumbnail view shows the first THREE rows as expected. The FOURTH row is only visible till 50%. Any other pictures in the rows further down are missing completely.

I can state firefox-44, chrome-7, firefow-ios-1.4, safari-9.0.3, safari-ios to be affected in the same way. It's always the pictures in line four that are not visible any more.

So I am also pretty sure it must be a server side problem. I can also not find any usefull information in my logs. Also trying to update via git to gallery-14.3 did not solve the problem.

**Comment by oparoz** [comment]
Please refer to https://github.com/owncloud/gallery/issues/490. It's a bug in pdf_viewer.

**Comment by khlschrnk** [comment]
Yes, I can confirm that updating pdf_viewer fixes this issue.

**Comment by elacour** [comment]
I confirm too, sorry for this duplicate bug.

**Comment by oparoz** [comment]
> sorry for this duplicate bug.

No worries, I also forget to check closed issues sometimes :)
