### ISSUE TITLE
Make Gallery compatible with shorter URLs from 9.0

### ISSUE THREAD

**Issue by oparoz** [owncloud/gallery#515]
It seems shorter URLs have been introduced in 9.0, but Gallery doesn't support them.
- [x] Fix page detecting JS in app.php
- [x] Fix Gallery button

**Comment by oparoz** [comment]
@LukasReschke - Is this a standard feature in 9.0 or is this optional?

**Comment by LukasReschke** [comment]
> @LukasReschke - Is this a standard feature in 9.0 or is this optional?

Enabled if the web server supports it, it should also not really require any work on your side if you have `mod_env` and `mod_rewrite` enabled. It should use short URLs then if you use the default IURLGenerator plus the ownCloud core JS functions.

**Comment by oparoz** [comment]
Thanks! Unfortunately, work is required because we check the URL to only load our JS on the `files` and `files_sharing` apps and the regexp contains `index.php`. I'll remove that and hope URLs don't contain `/s/` until `files_sharing` supports `loadAdditionalScripts`

**Comment by LukasReschke** [comment]
Your welcome. Thanks for fixing @oparoz :rocket:
