### ISSUE TITLE
Remove the footer when the user is logged in

### ISSUE THREAD

**Issue by oparoz** [owncloud/gallery#518]
The footer makes sense in the public template, promoting ownCloud, but I don't think there is any value in keeping it when the user is logged in.

@jancborchardt @karlitschek

**Comment by karlitschek** [comment]
hmm. what do you think @jancborchardt

**Comment by jancborchardt** [comment]
It’s a good point, but there’s also value in keeping it as close to what the person you send it to will see.

**Comment by oparoz** [comment]
> It’s a good point, but there’s also value in keeping it as close to what the person you send it to will see.

I don't understand. If you share a link, then the footer is displayed as you land on the public page. If you share with another user, then that user is already familiar with the system and doesn't see that footer when browsing using the Files app per example. Same with mail I imagine.

**Comment by oparoz** [comment]
It's in fact a regression introduced when changing the layout. The footer was copied over from the public template...

**Comment by oparoz** [comment]
Fixed via #524

**Comment by jancborchardt** [comment]
Ah, ok, now I understand. :D Yeah, of course for normal users the footer does not make sense.
