### ISSUE TITLE
Only activate uploading if we can write to the current folder

### ISSUE THREAD

**Issue by oparoz** [owncloud/gallery#521]
Users will get an error message if they try to upload files where they're not allowed to, but it could be better to just block/disable the feature. The reason I'm not sure is that they would have no way of knowing if it's not available because of a permission problem or because of a bug.

_Note: The upload functionalitiy is only available from 9.1, after merging ~~#520~~ #574_
##

**Comment by mbtamuli** [comment]
@oparoz How do I work on this? I mean the VCS part. Can you help me with that? I want to work on this one.

**Comment by oparoz** [comment]
If I understand your request correctly, you should fork the branch used in #520 in order to have all the uploading mechanism in your repository. After you've committed your solution, create a PR against that same branch and only your commits will show. Depending on when #520 is merged, we'll then either cherry pick your work or create a new, rebased branch.
There might be better ways, but that's how I do it. It does involve more work as both master and that branch might introduce small breaking changes.

**Comment by oparoz** [comment]
And #574 superseded #520, so use that :)

**Comment by oparoz** [comment]
This can now be worked on.

**Comment by mbtamuli** [comment]
I would like to work on this, if nobody else is already working on this.

**Comment by oparoz** [comment]
OK, but I'm working on sending permissions to the client differently. It will be trivial to rebase if you read permissions with GalleryConfig, but I just wanted to let you know.

**Comment by mbtamuli** [comment]
Okay. Thanks for letting me know.

Also, are you not there on the irc channel?

**Comment by oparoz** [comment]
The best way to get me on IRC is to ping me via email :)

**Comment by oparoz** [comment]
This issue was moved to nextcloud/gallery#113
