### ISSUE TITLE
Add exif description to the slideshow

### ISSUE THREAD

**Issue by oparoz** [owncloud/gallery#525]
@0xb0ba has opened [a PR](https://github.com/owncloud/gallery/issues/453) which adds the EXIF description to an image shown in the slideshow, if it exists. There are still quite a few opened questions regarding the design.

Should the description : 
- Be centred? 
- Be spread over 3 lines?
- Include a scroller or rollover? Rollover would fill the screen with that description since we have to keep it narrow. A scroller requires 2 additional touch areas instead of an ugly scrollbar
- Be enabled/disabled via a button? Because it can mask the view and would not disappear when interacting with the slideshow, so, the default would be to hide the description
- Be shown in a sliding sidebar?
### Picasa

![](https://cloud.githubusercontent.com/assets/15338877/10887154/68d4952c-81a7-11e5-8c14-0d18702ca0ca.png)

![](https://cloud.githubusercontent.com/assets/15338877/10890163/47747648-81b8-11e5-97d1-993247f50a98.png)
##

**Comment by 0xb0ba** [comment]
> Be centred?

yes

> Include a scroller or rollover?

nothing

> Be enabled/disabled via a button?

no. autohide in 3 sec

> Be shown in a sliding sidebar?

yes. all tags (all photo tags) from exif. but php exif lib is poor. exiftool?

**Comment by Bugsbane** [comment]
> Be centered?

Yes

> Spread over 3 lines?

Personally I would make a div with a minimum height of around 1em (ie a single line high) and a max height of a few percentage points of the screen height (I'd need to judge this visually on my desktop, and I'm on my phone now, but I can do a mock-up for precise numbers), center it horizontally and align it to the bottom of the screen with a margin of say .5 em.

I'd make the text color white with a black css dropdown shadow (this tends towards decent readability against a wide variety of backgrounds as long as the shadow outlines the text at least a little in all directions, maybe blur 3px, with no x offset and a y offset of 2px).

 I'd set overflow to cut off, ideally with an opacity gradient fading the text out at the end, and an ellipses to signify more text being available, but have a tooltip display with a system standard font size with the full text on hover or click.

As Jan suggests, I'd go with fading after 3 seconds, but I'd reverse the fade-out if the text is hovered over or clicked on. Onmouseout restart the 3 second countdown.

No to buttons, scrollers, roll overs and scroll bars.

Yes to showing in the sidebar.

**Comment by oparoz** [comment]
Thanks for the feedback. It's interesting that both of you think the description should fade away with the rest. I can think of at least one use-case where I would want the description to show permanently: In slideshow mode in a real gallery if I wanted to add a caption to each image. So maybe there should be 2 modes, one with tooltip + fade and a permanent description one

I'd greatly appreciate some mockups.

Things to look for:
- There should be a max width to keep the description readable. A paragraph is better than a long line
- Both the filename and the description have to be shown
- Some mockups should include the other buttons in the UI to be able to see how it all fits together

**Comment by 0xb0ba** [comment]
serious doubts that the file name should be in full screen.

**Comment by Bugsbane** [comment]
Yes, I agree on the max-width.

I question whether it's best to show both the description and the filename at
all time, especially in slideshow mode. Generally, if an actual description
has been given then it's more meaningful to the user in a slideshow mode
(which is more about casual viewing than hunting down technical details).
Personally I would suggest showing the description where one has been set, the
filename where one has not, and making the filename available in the sidebar
info for anyone looking for more than is shown in the sileshow view.

**Comment by Bugsbane** [comment]
I'm happy to run up a mockup though as soon as we have a general agreement on
what should be in it, or at least that people have polarised around a couple
of options.

Yes, I agree on the max-width.

> I question whether it's best to show both the description and the filename
> at all time, especially in slideshow mode. Generally, if an actual description
> has been given then it's more meaningful to the user in a slideshow mode
> (which is more about casual viewing than hunting down technical details).
> Personally I would suggest showing the description where one has been set, the
> filename where one has not, and making the filename available in the sidebar
> info for anyone looking for more than is shown in the sileshow view.

**Comment by oparoz** [comment]
> I'm happy to run up a mockup though as soon as we have a general agreement on
> what should be in it, or at least that people have polarised around a couple
> of options.

Makes sense

**Comment by turb** [comment]
Hello, what options still need to be agreed on, in order to merge this PR?

If the only one is "should both description and filename be displayed, or only the description", my own preference goes to only the description (filename makes little sense when the description has been filled).

**Comment by oparoz** [comment]
This issue was moved to nextcloud/gallery#114
