### ISSUE TITLE
Improve the touch area of some buttons

### ISSUE THREAD

**Issue by oparoz** [owncloud/gallery#53]
I think _next_ and _previous_ should have larger click/tap areas.
Buttons at the top (download, toggle, etc.) should also have a larger tap area and should be spaced accordingly. 
##

**Comment by jancborchardt** [comment]
To review at https://github.com/owncloud/gallery/pull/369

**Comment by ghost** [comment]
This bug will fall off 8.2 if not resolved by 6 Oct

**Comment by oparoz** [comment]
So #369 solved the issues mentioned in the OP, but there was a conflict with the zooming feature, so we were unable to keep it.

I'm not against a replacement of bigshot for the zooming feature since it's quite a large lib and since we don't support its main feature which is to allow the use of multiple images when zoming, but we should pick a library instead of writing custom code :)

**Comment by jancborchardt** [comment]
To fix https://github.com/owncloud/gallery/issues/411 as well, we need to show the image above the actions. And a tap on the image itself should also switch to the next image.

**Comment by oparoz** [comment]
> To fix #411 as well, we need to show the image above the actions. And a tap on the image itself should also switch to the next image.

I don't understand. The image will mask the controls

**Comment by jancborchardt** [comment]
@oparoz right, I guess adding another empty transparent ghost container of the size of the image to handle the zooming is too much?

But in any case, tap on the image itself should switch to the next one, as Facebook and others do.

**Comment by oparoz** [comment]
What needs to happen is either capturing the scroll events and sending them to Bigshot or having Bigshot capture the send events.
I think there is always going to be a decision to be made regarding what clicking on the screen does. If we remove bigshot, the pointer will probably turn into a lens which will let the user zoom in/out, not go to the next picture.

**Comment by PVince81** [comment]
@jancborchardt any update on this ?

**Comment by oparoz** [comment]
There is a PR which needs to be tested: https://github.com/owncloud/gallery/pull/457 and possibly slightly altered if we prefer large click zones as opposed to buttons.

**Comment by oparoz** [comment]
#457 has been merged and now needs to be backported to ~~8.2.2~~ 8.2.3

**Comment by jancborchardt** [comment]
@oparoz did the backport happen? Then we could close this. (Even if not I guess this is closable.)

**Comment by oparoz** [comment]
Didn't happen, no. The problem is that we don't have enough testers, so not sure if people will properly test the backport.

**Comment by ghost** [comment]
https://github.com/owncloud/gallery/issues/53#issuecomment-171954472 if we don't then we'll have to just accept it for 9.0 and move on

**Comment by oparoz** [comment]
OK, closing then.
