### ISSUE TITLE
Panning stops working when reaching the large touch zones in the slideshow

### ISSUE THREAD

**Issue by oparoz** [owncloud/gallery#535]
### Steps to reproduce
1. Open the slideshow
2. Zoom in all the way
3. Try to pan left or right by dragging from the centre to the edge
### Expected behaviour

The image should pan during the whole dragging action
### Actual behaviour

Panning stops as soon as the touch zone (25% of the width on each side) is reached

**Comment by oparoz** [comment]
@0xb0ba - Any idea on how to solve this? The dragging action should turn off the touch zone.

**Comment by 0xb0ba** [comment]
@oparoz 
change
`this.container.children('.previous, .next, .menu, .name').on('mousewheel DOMMouseScroll',function (evn){
 this.container.children('.bigshotContainer')[0].dispatchEvent(new WheelEvent(evn.originalEvent.type,evn.originalEvent));
}.bind(this));`
to
`this.container.children('.previous, .next, .menu, .name').on('mousewheel DOMMouseScroll mousemove',function (evn){
 this.container.children('.bigshotContainer')[0].dispatchEvent(new WheelEvent(evn.originalEvent.type,evn.origina
}.bind(this));`

**Comment by oparoz** [comment]
Exactly what I was looking for, thanks!

PR is in #537
