### ISSUE TITLE
Sharing permissions can't be modified because checkboxes are not shown

### ISSUE THREAD

**Issue by oparoz** [owncloud/gallery#538]
### Steps to reproduce
1. Open an album
2. Click on the share button
3. Share with a user
### Expected behaviour

In the area where the user which the folder is shared with is shown, there should be checkboxes next to _can share_,  _can edit_, _create_, _change_ and _delete_
### Actual behaviour

Checkboxes are not shown which means permissions cannot be modified.

This was introduced when all the checkboxes where changed, starting from 8.2.

By playing with the CSS, we can see that the checkboxes exist; they're just masked.

The checkboxes for the public link section were modified. I'm guessing a similar fix needs to be applied here.

**Comment by oparoz** [comment]
I'll take care of it

**Comment by Henni** [comment]
short hint:
The HTML has to look like `<input type="checkbox"><label>[...]</label>`.
Only if it is ordered this way the checkbox will be rendered.

**Comment by oparoz** [comment]
Yeah, I've figured it out by comparing with Files, but thanks for confirming :). There is also a problem with the classes, each input has 2 declarations and the second one is ignored.
The fix will be released as part of the rewrite of the share class.

**Comment by rullzer** [comment]
Fixed with #541 as far as I can tell. Please reopen if not.

**Comment by oparoz** [comment]
I'm re-opening it because this is for 8.2.x. Even though nobody seems to have noticed, it would be nice if it worked as expected.

**Comment by oparoz** [comment]
Fixed via #546
