### ISSUE TITLE
OC 8.2.2: Last row of shared gallery not visible

### ISSUE THREAD

**Issue by astroleo** [owncloud/gallery#539]
In a shared gallery the last row of the image miniatures is cut off and cannot be reached by scrolling down. I have looked at all issue and have not found one that describes this (but #240 might be related). However, since the bug is pretty obvious, I wouldn't be surprised if it has been reported. If so, apologies for duplication.
### Steps to reproduce
1. Copy images into a folder (using Mac OS X sync client), let owncloud synchronize
2. Log in to your OC installation and share this folder via link
3. Visit that link with Firefox 44.0.2 (Mac OS X) or Safari 9.0.3 (Mac OS X). I don't think it depends on browser/OS though as I have heard from others about this as well.

(Update: I have removed the web shares since the issue is closed.)

I'm using OC 8.2.2 (fresh install) server with MySQL database and PHP 5.6.17-0+deb8u1

**List of activated apps:**

 Enabled:
- activity: 2.1.3
- files: 1.2.0
- files_pdfviewer: 0.7
- files_sharing: 0.7.0
- files_texteditor: 2.0
- files_trashbin: 0.7.0
- files_versions: 1.1.0
- files_videoviewer: 0.1.3
- firstrunwizard: 1.1
- gallery: 14.2.0
- logreader: 1.1.2
- notifications: 0.1.0
- provisioning_api: 0.3.0
- templateeditor: 0.1
  Disabled:
- encryption
- external
- files_external
- piwik
- user_external
- user_ldap

**The content of config/config.php:**

{
    "system": {
        "instanceid": "ocwko0t9earj",
        "passwordsalt": "**_REMOVED SENSITIVE VALUE**_",
        "secret": "**_REMOVED SENSITIVE VALUE**_",
        "trusted_domains": [
            "192.168.1.11",
            "ileo.no-ip.biz"
        ],
        "datadirectory": "\/var\/www\/owncloud\/data",
        "overwrite.cli.url": "http:\/\/192.168.1.11\/owncloud",
        "dbtype": "mysql",
        "version": "8.2.2.2",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "**_REMOVED SENSITIVE VALUE**_",
        "dbpassword": "**_REMOVED SENSITIVE VALUE**_",
        "logtimezone": "UTC",
        "installed": true,
        "loglevel": 2
    }
}

**Are you using encryption:** yes

**Are you using custom gallery.cnf config files:** no

**Comment by oparoz** [comment]
Thank you for providing all this information. Unfortunately, this is a duplicate, please refer to https://github.com/owncloud/gallery/issues/490 for the solution

**Comment by astroleo** [comment]
Thank you for your fast feedback. Happy to see this is solved. Just to clarify: Will the patch mentioned in #490 go into the next OC release (8.2.3)?

**Comment by oparoz** [comment]
Yep: https://github.com/owncloud/files_pdfviewer/pull/92

**Comment by astroleo** [comment]
Merci bien! Looking forward to updating soon, then. :-)
