### ISSUE TITLE
Screenshot in readme is broken

### ISSUE THREAD

**Issue by AbdealiLoKo** [owncloud/gallery#542]
## Bug report
1. Open https://github.com/owncloud/gallery and check the readme rendered by github 
   OR
2. Open [link to screenshot](https://camo.githubusercontent.com/be0ace97cde3cb74f06c2eaf47dd5e88bfbe0247/68747470733a2f2f6f633864656d6f2e696e7465726661636c6f75642e636f6d2f696e6465782e7068702f732f7076657476345261496246684452622f646f776e6c6f6164) - it gives 503 backend read error.

**Comment by oparoz** [comment]
Thanks for noticing. I thought it was a temporary issue, but it seems Github can no longer retrieve images stores on ownCloud.

I'll create a screenshot folder and link from there.
