### ISSUE TITLE
Close the share dialogue when performing another action

### ISSUE THREAD

**Issue by oparoz** [owncloud/gallery#545]
### Steps to reproduce
1. Open the share dialogue
2. Click on an album

or
1. Open the share dialogue
2. Click on the info button
### Expected behaviour

The share dialogue should close
### Actual behaviour

The share dialogue stay open

**Comment by virajparimi** [comment]
I would like to work on this one. Could you guide me as to in which file changes are to be made.

**Comment by oparoz** [comment]
Well, the first step is to determine what is wrong.

Basically, when [`_openAlbum`](https://github.com/owncloud/gallery/blob/master/js/galleryalbum.js#L156-L160) is called, all the dialogues, including the share dialogue should be closed and it's not the case.

So should this method be modified or is there another way?

**Comment by virajparimi** [comment]
Should we use [hideDropDown](https://github.com/owncloud/gallery/blob/master/js/vendor/owncloud/share.js#L497) function when _openAlbum is called.

**Comment by oparoz** [comment]
I think that's the method to call, yes. 
There is another problem though, the share dialogue also stays open when clicking on the info button (enabled when there is a description. See https://github.com/owncloud/gallery/wiki/Gallery-configuration#album-presentation).

So maybe we should use this instead:
https://github.com/owncloud/gallery/blob/master/js/app.js#L41-L43

**Comment by virajparimi** [comment]
I have figured out the solution and it is working fine. Shall i send a pull request.

**Comment by oparoz** [comment]
Please do. That way we I and other can test the solution :).
_Note: Always create the PR against master._

**Comment by oparoz** [comment]
@viraj96 - There is a regression.

That's not available in the Files app:
https://github.com/owncloud/gallery/blob/master/js/slideshow.js#L95-L96

So the call should be made in the method which calls `show()`

**Comment by virajparimi** [comment]
So, can I add it here [-->](https://github.com/owncloud/gallery/blob/master/js/gallery.js#L252).

**Comment by oparoz** [comment]
Yes, right at the end should work.
