### ISSUE TITLE
Create .nomedia file from the album itself

### ISSUE THREAD

**Issue by oparoz** [owncloud/gallery#547]
## Feature request

**User type**: All

**User level**: All
### Description

Add an entry to the [+] menu allowing users to quickly blacklist an album from Gallery. The menu entry will create the `.nomedia` file

_Note: The [+] menu is only available from 9.1, after merging ~~#520~~ #574_
### Benefit / value

It just avoids having to do a round trip via Files just for that.
### Risk / caveats

None
##

**Comment by prastut** [comment]
How can I blacklist an album from the files menu? When I click the [+] menu all I got is the feature to upload and create a new folder.

OC version:  9.1.0 pre alpha (git)

**Comment by oparoz** [comment]
This has to happen from the Gallery side and can only be implemented once this is merged:
~~#520~~ #574.
That PR needs a fix to make it work with a last minute change in `core`. You're welcome to try and fix that, but that requires learning about how the uploading mechanism works in Files and what the equivalent variables might be in Gallery.

**Comment by tahaalibra** [comment]
i want to try this fix....i guess now that #574 replaces #520...and it in the test it works great..i can now get at this issue

**Comment by oparoz** [comment]
:+1:, but make sure you fork #574 as your base as it hasn't been merged yet.

**Comment by oparoz** [comment]
This can now be worked on

**Comment by oparoz** [comment]
Implemented in #625
