### ISSUE TITLE
Create custom detailsview for the slideshow

### ISSUE THREAD

**Issue by oparoz** [owncloud/gallery#549]
## Feature request

**User type**: All

**User level**: All
### Description

We can't re-use the sidebar designed for Files as it only works in Files, especially since plugins used in tabs target the Files app (#548), so we'll have to design our own.
We can probably re-use the tabs logic to be able to easily show additional information and in order to not interfere with the slideshow itself, the information should be kept in a separate container, next to the slideshow.

Like this:

![detailsview_slideshow](https://cloud.githubusercontent.com/assets/323220/13540068/a45eb22c-e254-11e5-8da9-97c816db8f84.jpg)
#### Basic info
- filename
- favourite star
- File info
- Read-only tags
#### Additional info
- [ ] Meta data (GPS, decription, etc.)
- [ ] Sharing
- [ ] Read-only comments
### Benefit / value

- Users will appreciate being able to get to see everything there is to know about a particular image right next to it
- Users will be able to share individual media files
### Risk / caveats

- It will look different than the Files sidebar
- It will definitely offer less features than the Files sidebar, namely tags and comments management will never happen.
### Sponsorship

None

**Comment by oparoz** [comment]
@bugsbane @jancborchardt @blizzz If you have ideas on what this should look like.

**Comment by oparoz** [comment]
I've added a screenshot.
Also @setnes @demattin

**Comment by jancborchardt** [comment]
Is there absolutely no way we can just use exactly the same? The sidebar should be a component, and especially since pictures are all files it should be the same.

cc @PVince81 @Deepdiver1975

**Comment by oparoz** [comment]
No way in its current state. It's a component in Files and sidebar plugins target Files. It's the same problem with the upload class (https://github.com/owncloud/core/issues/19563) and the current position of `core` is to let apps rewrite everything. That would require an additional Gallery maintainer focusing exclusively on keeping everything in sync with changes in core.

**Comment by jancborchardt** [comment]
Would really be cool if we can find a way to have the core one reusable. Otherwise it will result in a really strange UX. @karlitschek @PVince81 @DeepDiver1975

**Comment by oparoz** [comment]
> Otherwise it will result in a really strange UX.

Or complaints by users because of the lack of core features in apps. One cool alternative is being discussed in the grid view issue where apps would directly render their content in the Files app.

**Comment by PVince81** [comment]
I'm not sure whether it's a good idea to make that class public. But maybe there could be another mechanism to let apps inject a sidebar into their apps, for example a method `var detailsView = OC.Apps.enableDetailsView();`. Then they can register their own panels there.

However, note that the details view is a more complicated topic. It's not just a panel, we also need to figure out whether the panel should automatically display all default tabs (sharing, comments, etc) if a file is given as input. And it becomes even more complicated when people are using the details view for non-files, in which case they'd have to implement their own sharing, comments, etc views.

A ticket was raised here to discuss this: https://github.com/owncloud/core/issues/18170.

Or is this only about having an empty panel on the right that has the same styling as in core ?

**Comment by oparoz** [comment]
> Or is this only about having an empty panel on the right that has the same styling as in core ?

The business case for using the Files sidebar was opened here: https://github.com/owncloud/gallery/issues/548
The idea is to be able to use any tabs available in Files, although we might remove some of the tabs, and to add our own.

The issue here was created to discuss about an alternative way of doing things where we would probably offer non-interactive views for things like comment and re-use the sharingview component in order to get rid of the dropdown.

I'll share my views on possible implementations on owncloud/core#18170

Thanks @PVince81

**Comment by oparoz** [comment]
While we wait we could have a very simple sidebar implementation:
1. User clicks on action button
2. Sidebar slides out containing only the information relevant to the pressed button i.e.  comments, sharing panel, meta data

If the user presses on a different button while the sidebar is open, the proper content can slide-out covering the previous one, which would be removed/hidden afterwards.

In the end, I don't think that it would be too much of a problem to have a different sidebar in the slideshow as that's another component all together, presenting a detailed view of an image or video.
The header would be different anyway, since there wouldn't be any thumbnail, the star for favourite doesn't need to be repeated there if it's already in the slideshow UI, etc.

**Comment by oparoz** [comment]
This issue was moved to nextcloud/gallery#119
