### ISSUE TITLE
Sort by "face" using meta data

### ISSUE THREAD

**Issue by oparoz** [owncloud/gallery#551]
## Feature request

**User type**: All

**User level**: All
### Description

It's possible to store and retrieve information in image headers which can be used for face detection.
It would then be possible to create virtual albums to quickly find specific images.
### Benefit / value

@rhatguy
If a user has spent the significant amount of time it takes to tag all of their photos, being able to take advantage of those tags is huge.
### Sponsorship

None
### Exploration

@rhatguy
exiftool is able to read the data from the image as shown below via command line.  I'm not terribly familiar with how to pull this type of data from within php's EXIF library.  There are some guidelines for storing face detection data put together by the metadataworking group specifically in section 5.9 in the linked pdf below.  Google Picasa has conformed to this standard and is able to search for faces and add the tags directly into the files metadata.

http://www.metadataworkinggroup.com/pdf/mwg_guidance.pdf

```
# exiftool IMG_6420.JPG  | egrep -i region
Region Applied To Dimensions W  : 3456
Region Applied To Dimensions H  : 5184
Region Applied To Dimensions Unit: pixel
Region Name                     : Travis Kelley
Region Type                     : Face
Region Area X                   : 0.531829
Region Area Y                   : 0.371238
Region Area W                   : 0.0983796
Region Area H                   : 0.0788966
Region Area Unit                : normalized
```
##

**Comment by oparoz** [comment]
This issue was moved to nextcloud/gallery#121

**Comment by kidalabama** [comment]
yes face recognition and tagging very important. and the other recognition. for example building, nature, document and others. google photos using this system.

**Comment by kidalabama** [comment]
openface https://cmusatyalab.github.io/openface/ may be integrate to owncloud app.
