### ISSUE TITLE
Cannot download shared albums that were shared via link

### ISSUE THREAD

**Issue by davitol** [owncloud/gallery#554]
### Steps to reproduce
1. Go to Gallery and browse into an album
2. Share it via link
3. Copy the link a nd paste it
4. Try to download the album
### Expected behaviour

It should be possible to download the album. 
### Actual behaviour

An error is shown. File not found... (see screenshot below)
### Server configuration

**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** mysql

**PHP version:** 5.5.9

**ownCloud version: ownCloud Enterprise Edition 9.0.0 RC1 (testing)
### Logs

No logs in owncloud.log or in web console

**Updated from an older ownCloud or fresh install:** Fresh install

**Are you using external storage, if yes which one:** no.
**Are you using encryption:** no
**Are you using an external user-backend, if yes which one:** no
### Client configuration

**Browser:** Firefox for Mac OSX

![screen shot 2016-03-03 at 15 50 11](https://cloud.githubusercontent.com/assets/10596560/13498078/b2930638-e158-11e5-9e9f-d7a835bab577.png)

![screen shot 2016-03-03 at 15 50 01](https://cloud.githubusercontent.com/assets/10596560/13498101/d2137dd0-e158-11e5-9622-29524cc608c5.png)

@rullzer @oparoz

**Comment by oparoz** [comment]
Confirmed. We have to remove the folder name from the path or get `core` to fix the download endpoint to use the path to generate the name of the archive.

**Comment by oparoz** [comment]
https://github.com/owncloud/core/issues/22836, if accepted is probably going to be for 9.1, so the best thing to do is to just remove the top folder from the path or use another variable which gives us the correct path.

**Comment by oparoz** [comment]
Re-opening as only 9.1 has been merged so far.

**Comment by oparoz** [comment]
Fix has been added to stable9
