### ISSUE TITLE
Sort by date button should work with albums too

### ISSUE THREAD

**Issue by davitol** [owncloud/gallery#555]
### Steps to reproduce
1. Go to Gallery with more than one album
2. Click on order by date button
### Expected behaviour

The albums should be sort by date
### Actual behaviour

Albums are not sort, only the images.
### Server configuration

**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** mysql

**PHP version:** 5.5.9

**ownCloud version: ownCloud Enterprise Edition 9.0.0 RC1 (testing)

**Updated from an older ownCloud or fresh install:** Fresh install

**Are you using external storage, if yes which one:** no.
**Are you using encryption:** no
**Are you using an external user-backend, if yes which one:** no
### Client configuration

**Browser:** Firefox for Mac OSX
##

**Comment by oparoz** [comment]
It's a known issue that we have to keep in mind if we ever redesign the photowall's caching mechanism.
We download a list of files and use the path to identify albums and thus don't have any information on the album themselves...

**Comment by oparoz** [comment]
I'm also open to suggestions regarding letting users known... because it will look like a bug to them...

**Comment by oparoz** [comment]
Could be solved via https://github.com/owncloud/gallery/issues/557

**Comment by oparoz** [comment]
This issue was moved to nextcloud/gallery#122
