### ISSUE TITLE
Do not allow empty urls to be submitted in "add to your owncloud"

### ISSUE THREAD

**Issue by oparoz** [owncloud/gallery#556]
Originally reported by @jancborchardt 
### Steps to reproduce
1. Go to a public Gallery
2. Click on "Add to ownCloud"
3. Press "Enter" or the confirm button **without entering any url**
### Actual behaviour

![federated-sharing-no-url-put](https://cloud.githubusercontent.com/assets/925062/10111548/ef16a342-6428-11e5-8bbc-261a37ddabbf.png)
### Expected behaviour

When no URL is put in, nothing should happen (the button should be disabled).

The fix is here and needs to be ported to Gallery:
https://github.com/owncloud/core/commit/08fd4b38f895a5e9a91cdc476103c26be68dda80

**Comment by virajparimi** [comment]
I would like to work on this one. But I am not able to reproduce the error. Where do we enter the url, do we do it while sharing the file when share dialog opens?

**Comment by kavishdahekar** [comment]
@viraj96 I think it is already fixed. 

> The fix is here and needs to be ported to Gallery:
> owncloud/core@08fd4b3

**Comment by prastut** [comment]
@oparoz This seems to be fixed.

**Comment by oparoz** [comment]
In order to understand the problem, you need to read this:
https://doc.owncloud.org/server/9.0/admin_manual/configuration_files/federated_cloud_sharing_configuration.html#creating-federation-shares-via-public-link-share

and then try to apply what's described in the OP **from the Gallery side**. You'll experience the same bug and will need to port the fix from `core` to Gallery.
In order to fix the problem, you need to have access to 2 different owncloud instances, to make sure that the connection is successfully established when entering a valid URL.

**Comment by oparoz** [comment]
I've updated the original report to make it clearer, since on the `core` side, people are more experienced with these kind of issues and can usually read between the line. That's probably not the case for people new to the project.

**Comment by tahaalibra** [comment]
i added patch using 08fd4b3.
by the way just wanted to know..can it also be done by adding  attribute 'required' to the 'input' tag.

**Comment by oparoz** [comment]
@tahaalibra - I don't know if you're familiar with Github, but on the right, you can see that the task was already assigned. I can only do it with registered ownCloud members, so it's also a good idea to also check the list of PRs before submitting a new one. That way there is no duplication of effort :)

**Comment by tahaalibra** [comment]
@oparoz i see..somehow i missed to see if it was assigned...i will surely check carefully next time..
No harm Done..i ended learning more about the code...which was my original intention

**Comment by oparoz** [comment]
:+1:
