### ISSUE TITLE
Add detailsview to the photowall

### ISSUE THREAD

**Issue by oparoz** [owncloud/gallery#559]
## Feature request

**User type**: All

**User level**: All
### Description

We can't re-use the sidebar designed for Files as it only works in Files, especially since plugins used in tabs target the Files app (#548), so we'll have to design our own.
We can probably re-use the tabs logic to be able to easily show additional information, but we don't even need to use a sidebar.

I find this design interesting

![detailsview_example](https://cloud.githubusercontent.com/assets/323220/13539858/4f5e1ef8-e253-11e5-8391-93e9fcf7ed0e.jpg)
#### Basic info
- filename
- favourite star
- File info
- Read-only tags
#### Additional info
- [ ] Meta data (GPS, decription, etc.)
- [ ] Sharing
- [ ] Read-only comments
### Benefit / value

- Users will appreciate being able to get to see everything there is to know about a particular image right next to it
- Users will be able to share individual media files
### Risk / caveats

- It will look different than the Files sidebar
- It will definitely offer less features than the Files sidebar, namely tags and comments management will never happen.
### Sponsorship

None
##

**Comment by oparoz** [comment]
@bugsbane @jancborchardt @blizzz  @setnes @demattin - What do you think?

**Comment by deMattin** [comment]
I would prefer it, like it is in files sidebar.
1. same look in files and gallery view
2. picture previews remain scrollable to search next picture of interest
3. you can switch to another picture and the new infos are at the same place as the old ones before.

**Comment by jancborchardt** [comment]
Yeah, I agree with @deMattin here. Even if we absolutely need to design our own detail view, we should model it as closely as possible to the one in Files. Otherwise people need to learn 2 different things for such elementary tasks, which is not acceptable.

**Comment by oparoz** [comment]
And thinking about the mobile experience, users would end up with half a vertical sidebar which would offer a pretty bad ux.

I guess we'll have to fog out all the other pictures to make it clear which one is currently selected

**Comment by deMattin** [comment]
I have no idea, how to get this on mobile except in portrait mode of smartphone with only a single picture on the top (should be possible to switch to next one) and the informations at the bottom on the other half of screen.
Even in this case you will need to scroll the informations.

**Comment by oparoz** [comment]
We'll have to have a different layout based on orientation.

**Comment by prastut** [comment]
I propose the following:
- On Picture hover:
  - Picture details come on hover. The tags could come below the said picture as well as the share icon link.  
- As far as the sharing part, I agree with @oparoz solution of creating a dropdown tooltip.

This will work well on mobile as well as normal displays, since the idea of creating a half vertical sidebar will give no use.

**Comment by oparoz** [comment]
> Picture details come on hover. The tags could come below the said picture as well as the share icon link.

I don't think it will work, because there is already a slight problem with labels on hover when you're scrolling. As labels are quite discreet, it doesn't matter much, but it would be bad if there were popups coming up when scrolling

The simple solution will be to show the star and the 3 dots menu as an overlay, probably top right, so that there is enough space for the filename at the bottom.

Then the details view would show up like on the slideshow (https://github.com/owncloud/gallery/issues/549). On mobile, it would fill all the space in portrait mode and half the space in landscape mode, like in Files.

**Comment by oparoz** [comment]
What I was saying about the "half a vertical sidebar" is that with the drop down, the top of the screen in portrait mode would have a couple of images and the bottom something like half of the sharing dialogue and that's not very useful.

**Comment by jancborchardt** [comment]
I would really advise that we don’t waste time on thinking about our own implementation here. It’s important that we standardize across apps, and that means we need to find a way (work together with core devs such as @PVince81) to get the sidebar standardized and usable across apps.

**Comment by oparoz** [comment]
Sure, but the issue in core is in the backlog and requires changing a lot of core internals, so we're probably a year away (10.0) from a solution (idea->politics->architecture->resources->implementation).
The fact that we don't have a sidebar is blocking a lot of features, so maybe having something simple which allows presenting some information is better than nothing for 2016, but that will also depend on available resources for this project.

**Comment by oparoz** [comment]
This issue was moved to nextcloud/gallery#124
