### ISSUE TITLE
Add the checkbox in the share dialogue to allow uploading from the public side

### ISSUE THREAD

**Issue by oparoz** [owncloud/gallery#565]
## Feature request

**User type**: All

**User level**: All
### Description

Users who want to let people they share a link with upload new files can't do it from the Gallery side
### Benefit / value

Feature parity with the share dialogue in Files
### Risk / caveats

The share dialogue will be rewritten this year, so not too much time should be spent on this as this would be a temporary solution.
### Sponsorship

None

**Comment by imjalpreet** [comment]
@oparoz I have started to work on this as well as #213. Will get back to you with some progress soon.

**Comment by imjalpreet** [comment]
@oparoz Can you please give a little pointer on how can I proceed with this? I have been trying to fix this but I haven't been successful till now. A small pointer from your side would be really helpful. Thanks!
Sorry, I haven't been able to contribute much from yesterday due to my university commitments.

**Comment by oparoz** [comment]
Let's see if that helps :)
- https://github.com/owncloud/gallery/blob/master/js/vendor/owncloud/share.js#L172-L189
- https://github.com/owncloud/core/blob/master/apps/files/templates/list.php#L43
- https://github.com/owncloud/core/blob/c5a200c4198de951dabdd3f783ade655b8ea6434/apps/files/list.php#L28

**Comment by imjalpreet** [comment]
@oparoz I have already headed in this direction. I was also referring to these files only. I am trying to figure out how to do the same in gallery app. Thanks!

**Comment by oparoz** [comment]
- https://github.com/owncloud/gallery/blob/master/templates/part.content.php#L100
- https://github.com/owncloud/gallery/blob/master/controller/pagecontroller.php#L84

**Comment by oparoz** [comment]
Fix is in #587
