### ISSUE TITLE
Buttons jump below the controls bar in portrait mode on small screens

### ISSUE THREAD

**Issue by oparoz** [owncloud/gallery#566]
### Steps to reproduce
1. Use the app with a very narrow window. That's typically the portrait mode on a mobile device
### Expected behaviour

The GUI should adapt and it should still be possible to use all the features of the app
### Actual behaviour

The breadcrumb takes half the screen and there is no room for the buttons which jump on a 2nd, invisible row.
### Solution

![](https://cloud.githubusercontent.com/assets/323220/12994814/7a6632fc-d123-11e5-8279-7136fe64a8e0.png)
- On small screen in portrait mode, the buttons should be replaced by the 3-dots button.
- Pressing on that button will reveal a 2nd row containing all the usual buttons
- Pressing on buttons on that row should not make the 2nd row disappear since they often open other dialogues.

Note that one that screenshot, the [+] button for upload and the settings buttons are missing, but there should be enough room for them.
##

**Comment by gauravmittal1995** [comment]
@oparoz Hi, I want to work on this. Can you please give me more detail on this?

**Comment by oparoz** [comment]
Hi, it would be easier if you had specific questions. That way I can update the OP.

**Comment by gauravmittal1995** [comment]
@oparoz  Hi, i just wanted some clarifications. i.e Right now, the buttons are all in the same row (Sort, Share, FileView) ... what we want is that it should have a 3 dot button after the path which when clicked slides down a second row which will contain the sort, share and fileview button? Is this correct?

**Comment by oparoz** [comment]
That's correct, yes.
When there isn't enough room in the controls bar, all buttons should be replaced by the 3-dots button. In reality, they will be placed on a hidden div which scrolls down when the 3-dots button is scrolled.

That's my vision of how things would work best, but I welcome suggestions if anybody thinks they can do better :)

**Comment by oparoz** [comment]
@gauravmittal1995 Any update?

**Comment by shubhrajodiya** [comment]
@oparoz 
The probable solution to this issue may be
Current Style
#breadcrumbs {
    float: left;
}
#content-wrapper {
    position: absolute;
    height: 100%;
    width: 100%;
    overflow-x: hidden;
    padding-top: 45px;
    box-sizing: border-box;
}
Changes Required
#breadcrumbs {
   width:100%; //this style rule
    float: left;
}
#content-wrapper {
    position: absolute;
    height: 100%;
    width: 100%;
    overflow-x: hidden;
    padding-top: 95px; //this style rule
    box-sizing: border-box;
}

**Comment by oparoz** [comment]
Thanks @shubhrajodiya. I did try a CSS solution (to create the screenshot above), but I had some issue with the alignment of buttons and it automatically wastes a full row for something users don't always use, so the best solution would be to put all the buttons in a drawer which can be hidden and replaced by a button under certain circumstances

**Comment by jancborchardt** [comment]
@oparoz as also said in the preceding issue, I disagree with the wrapping solution for this. There should be a 3-dots-menu richt in the breadcrumbs bar instead.

Otherwise like now, there are three bars covering the top. That's about a third of the viewport which is always used up by UI instead of content. This is an absolute no-go, especially for an image gallery where you want your pictures front and center.

cc @owncloud/designers

**Comment by skjnldsv** [comment]
I can't reproduce with the last update (9.0.1). The breadcrumbs doesn't show anything.
![screen](https://cloud.githubusercontent.com/assets/14975046/14378141/df8e1be6-fd73-11e5-8dd9-39d98de024c4.png)

**Comment by oparoz** [comment]
@skjnldsv - It happens if you add more buttons. There is now an upload button and it's progress bar and an info button can show up sometimes. It's just getting too crowded, thus the need to only show the essential ones.

**Comment by shubhrajodiya** [comment]
@oparoz 
I have implemented this please check it out

1.Full Screen
![1 full screen](https://cloud.githubusercontent.com/assets/10657930/14399463/98f98dd6-fe0a-11e5-94ae-827820976bbf.png)

2.Just before the change take place
![2 critical screen](https://cloud.githubusercontent.com/assets/10657930/14399466/990bad68-fe0a-11e5-81bc-72052c42b3db.png)

3.Just after the change take place
![3 button active](https://cloud.githubusercontent.com/assets/10657930/14399464/98fdaeb6-fe0a-11e5-87a9-83426a223891.png)

4.Final Screen
![4 active screen 2](https://cloud.githubusercontent.com/assets/10657930/14399465/98fe578a-fe0a-11e5-8805-0f406d2d38be.png)

am i on the right path ?

**Comment by oparoz** [comment]
Yes, that's how it should work.

#### TODO
- Use a 3 dots icon
- Make modifications to the width checks so that we can have a breadcrumb which fills the entire width
- Introduce a drawer for the hidden buttons
- Make the drawer adaptable, so that it can auto-resize over 2 rows when the screen is super tiny

**Comment by oparoz** [comment]
Also, `core` uses snap.js in case you didn't know and want to re-use a lib.

**Comment by shubhrajodiya** [comment]
@oparoz 
is it good to use another js library 
i am thinking to use classie js

**Comment by oparoz** [comment]
I don't think classie is required as we already have jQuery or am I missing something?

**Comment by jancborchardt** [comment]
Yep, nice job @shubhrajodiya! :)

The correct icon you can use can be loaded by giving the button a class `icon-more`. Also, can you show a screenshot of the menu being open?

**Comment by shubhrajodiya** [comment]
@jancborchardt @oparoz 
Actually i am having a couple of doubts regarding the functioning of the ellipsis a whole div can be inserted upon the click event on the ellipsis or a pop may be generated which one is suggested can you please tell me

**Comment by oparoz** [comment]
From my pov, the div should be pre-existing, but hidden underneath the controls and would be revealed via a slide out mechanism. We can't have a menu there because having 2-3 sorting buttons on one line of the menu doesn't look right.

#### Normal

All buttons are shown

#### Reduced
- 3-dots are shown
- Buttons are moved to the hidden div (This might break a few actions because of change in CSS paths)
- Clicking on the 3-dots reveals the buttons

**Comment by shubhrajodiya** [comment]
@oparoz @jancborchardt 
I have implemented the 3-dot(icon-more) and written the js also but have trouble in integrating it can you please guide me

**Comment by oparoz** [comment]
Can you be more specific regarding the problem you're running into?

**Comment by shubhrajodiya** [comment]
@oparoz 
I want to trigger the click event handler on the ellipsis and show the hidden div which contains all the buttons but my script is not running i dont know why it's happening ??

**Comment by jancborchardt** [comment]
cc @owncloud/javascript for help on the 3-dot-menu.

**Comment by oparoz** [comment]
@shubhrajodiya - May you're not targeting the right element? Do you get any error in the console? It's difficult to tell without being able to look at the code.

**Comment by skjnldsv** [comment]
Is there an associated pr? Where can we see your code to help you @shubhrajodiya ? :)

**Comment by shubhrajodiya** [comment]
@skjnldsv 
No as i am working on it there is no pr 
I am able to make changes in css and manipulate the scenario in the gallery app but when i am trying to trigger an event handler on the ellipsis(3-dot button) using the script its not working. can you please guide me how to add new script which will work as expected because i tried creating a new js file in the js folder and also embedded the script but its not working.

**Comment by skjnldsv** [comment]
We're going to need more information, what did you changed for now, only css?

**Comment by oparoz** [comment]
This issue was moved to nextcloud/gallery#125
