### ISSUE TITLE
The empty page message is still too low

### ISSUE THREAD

**Issue by oparoz** [owncloud/gallery#569]
### Steps to reproduce
1. Login with an account which contains no files
2. Resize your window to make it really short
3. Open Gallery
### Expected behaviour

It should look like on Files
![empty_files](https://cloud.githubusercontent.com/assets/323220/13644316/6f3305ec-e625-11e5-87fb-327e4df89b8f.png)
### Actual behaviour

The content is too low.
![empty_gallery](https://cloud.githubusercontent.com/assets/323220/13644303/5467338c-e625-11e5-9f42-567683b67b1b.png)
### TODO
- [x] Test on 8.2 to see if it is also affected
- [x] See if @oparoz broke it when fixing mobile scrolling and try to revert the damage

**Comment by virajparimi** [comment]
@oparoz I have checked in 8.2.3. The problem is also there in it. Any further suggestions?

**Comment by oparoz** [comment]
Thanks

**Comment by oparoz** [comment]
That should be fixable via CSS. There was a lot of discussion around that before launching 8.2. I thought it had been fixed, but maybe the compromise was that there needed to be a minimum height. Hopefully we can do better.

**Comment by tahaalibra** [comment]
yea..i checked and padding-bottom : 100px which is causing this...i am trying to correct this problem from css

**Comment by oparoz** [comment]
Good luck! :)

**Comment by harshjv** [comment]
Yes, this is because of `#gallery.hascontrols` in `css/styles.css` (https://github.com/owncloud/gallery/blob/master/css/styles.css#L85)

**Comment by oparoz** [comment]
Fixed via #572
