### ISSUE TITLE
Cleanup the Javascript

### ISSUE THREAD

**Issue by oparoz** [owncloud/gallery#57]
I didn't want to touch too much of it before so that ownCloud staff could compare it to the original version of Gallery in order to validate the changes. Those changes were mainly brought through the PRs in that repository, so they were easy to track.
I did get rid of some dead code, but there is more and now is the time to clean it up.
- [x] Remove tokens from all objects. There is now a Gallery.token which stores that value and a Gallery.buildUrl() which builds URLs with everything needed to make a valid request
- [x] Remove code which always returns the same value. Albums and album thumbnails are always 200x200 (before resizing). No need to even ask for it.
- [x] Split long classes. See the complexity scores for [slideshow.js](https://codeclimate.com/github/interfasys/galleryplus/js/slideshow.js) and [gallery.js](https://codeclimate.com/github/interfasys/galleryplus/js/gallery.js)
- [x] Document all methods
- [x] Clearly mark private methods. It's pointless to have real private methods in Javascript, but it should be easy to identify them.

**Comment by ghost** [comment]
Where is the discussion of yesterday?
All my posts have been deleted.

And what is this for a code slideshow.js and gallery.js?

Am I still in the ownCloud-discussion ?!

**Comment by oparoz** [comment]
Apps have been renamed, the issue you're referring to is now available here:
https://github.com/owncloud/gallery-old/issues/57

**Comment by oparoz** [comment]
Done
