### ISSUE TITLE
Federated shares shared via public link are not considered external any more

### ISSUE THREAD

**Issue by oparoz** [owncloud/gallery#571]
### Steps to reproduce
1. Add a federated share
2. Make sure gallery.cnf does not allow external shares
3. Go inside the folder
4. Open Gallery

At this stage, you should get an empty Gallery
1. Go back to Files
2. Share the folder via public link
3. Open the link in another browser
4. Switch to Gallery
### Expected behaviour

You should get the same empty Gallery you saw when logged in
### Actual behaviour

The Gallery is happy to show you all the images.

I'm not sure if it's a problem with Gallery or `core`.
The default behaviour is to not show content stored on external storage, so the content should not be shown, but somehow our tests are saying that the folder is not external any more.
### Plan
- [ ] Recheck once this is fixed in core
##

**Comment by oparoz** [comment]
@rullzer @PVince81 Does a reshare of a federated share change status and is not considered external any more because it was shared by an internal user?

**Comment by rullzer** [comment]
reshares of federated shares are indeed for the receiving user internal. This is indeed an issue in core.

**Comment by oparoz** [comment]
Ah, thanks @rullzer! :)

**Comment by oparoz** [comment]
This issue was moved to nextcloud/gallery#128
