### ISSUE TITLE
Remove duplication in configvalidator

### ISSUE THREAD

**Issue by oparoz** [owncloud/gallery#578]
That's what we have

```
    /**
     * Determines if the sorting type found in the config file is safe for web use
     *
     * @param array $parsedConfigItem the sorting configuration to analyse
     * @param bool $safe whether the current config has been deemed safe to use so far
     *
     * @return bool
     */
    private function isSortingTypeSafe($parsedConfigItem, $safe) {
        if ($safe && array_key_exists('type', $parsedConfigItem)) {
            $safe = $safe && $this->sortingValidator('type', $parsedConfigItem['type']);
        }

        return $safe;
    }

    /**
     * Determines if the sorting order found in the config file is safe for web use
     *
     * @param array $parsedConfigItem the sorting configuration to analyse
     * @param bool $safe whether the current config has been deemed safe to use so far
     *
     * @return bool
     */
    private function isSortingOrderSafe($parsedConfigItem, $safe) {
        if ($safe && array_key_exists('order', $parsedConfigItem)) {
            $safe = $safe && $this->sortingValidator('order', $parsedConfigItem['order']);
        }

        return $safe;
    }
```

Seems to me like this can be simplified in one method

@mbtamuli @imjalpreet you were looking for something a bit different. This is pure PHP and will involve updating the unit tests.

**Comment by imjalpreet** [comment]
@oparoz Yeah, I would like to take this up. I will get back to you if I have any doubts. Thanks!

**Comment by oparoz** [comment]
Cool, just assign yourself. The fix should be pretty straightforward, but you may run into some issues when running Codeception to test. There is a guide on here, but I'm sure it can be improved.

**Comment by rahulgoyal030** [comment]
@oparoz   hello , i  am gsoc aspirant . I want to work on it  for better understanding of the owncloud codebase .

**Comment by oparoz** [comment]
Hi @rahulgoyal030. You have to make sure a task hasn't been assigned to somebody else before working on it and if someone has not had the time to work on it for a while, it's best to ask before doing the work. This task was picked up 6 hours ago, that's not that much time ;)

Since the change was trivial. I'm going to keep your PR, but keep that in mind for next time.

**Comment by rahulgoyal030** [comment]
@oparoz  , sorry man . i  am new here and  and i was't aware about this. It is  my first PR  in OSS so i get  little excited .  next i will always keep this in mind .

**Comment by oparoz** [comment]
Cool :)

**Comment by oparoz** [comment]
Closed via https://github.com/owncloud/gallery/issues/578
