### ISSUE TITLE
Use the new shareManager to get a share based on a token

### ISSUE THREAD

**Issue by oparoz** [owncloud/gallery#579]
`OCA\Gallery\Environment::setTokenBasedEnv` is based on `OCA\Files_Sharing\Controllers\ShareController::showShare` and that class has now been moved to Share 2.0, which makes it easier to retrieve information about a share without having to mess with the filesystem.

This commit was the first one in a series
https://github.com/owncloud/core/commit/0ebc92c44ab6332e74e88fb3a32e860139417677

It would be great to move to that new model in order to have cleaner code and to be able to get rid of less testable static methods.

`OCA\Gallery\Middleware::getLinkItem` will also need to be updated
##

**Comment by oparoz** [comment]
@mbtamuli @imjalpreet this is a bit more advanced but a good opportunity to get to know how the PHP side of sharing works in ownCloud.

**Comment by rullzer** [comment]
If you have any questions or remarks regarding the shareManager feel free to ping me on IRC. I'm interested what the API consumers think. Or what could be done better :)

**Comment by oparoz** [comment]
Thanks @rullzer :)

**Comment by oparoz** [comment]
Fixed via #668
