### ISSUE TITLE
Some files have not passed the integrity check.

### ISSUE THREAD

**Issue by pierreozoux** [owncloud/gallery#580]
On version 9, I just re-installed latest version of gallery.

Right after installation, I started to get:
`Some files have not passed the integrity check.`

Here is the RAW output:

```
Raw output
==========
Array
(
    [core] => Array
        (
            [INVALID_HASH] => Array
                (
                    [.htaccess] => Array
                        (
                            [expected] => f40e7ca19cd76ff922ccd164e38f4d73806f66170cafa202fb470be225c813b4b242f4321da8a01bef1329e300acf3d137dbcbff058c501f166a2619031fc651
                            [current] => 7bae810b6f5ca98d062ac9985cac7fb2dc8e22d981ec41e8327e53a5ee7f33017b128bbb4ceefbe665dbd35f7a1ee3a0926c4278aeeeb6d7b4325197be1ed9a9
                        )

                )

        )

)
```

I can send you the complete htaccess if you want.
(I use nginx, so I actually don't use htaccess)

**Comment by oparoz** [comment]
Actually, I don't think it's related to Gallery at all as the app doesn't touch `.htaccess`.
Could be a cron job which has altered the file. See if someone has reported a similar issue in `core`

**Comment by ghormoon** [comment]
I have this (with the same "current" hash) after upgrading 8.2.2 -> 9.0.0
Activated plugins: Activity, Collaborative tags, Comments, Default encryption module, Deleted files, External storage support, Federation, First run wizard, Gallery, Mail template editorX, Notifications, PDF Viewer, Provisioning API, Share files, Text editor, Update notifications, Video playerX, CalendarX, ContactsX, DocumentsX, TasksX
I'm pretty sure that plugins marked with X were turned on after I've noticed the warning for first time, so those are not the ones that changed it.

**Comment by oparoz** [comment]
I  still think that it's either core or the modification of an admin setting which is responsible. The best thing to do is to report this in `core` if it hasn't been already.
It's debatable whether `.htaccess` should be included in the integrity check or not. If you move its content to a virtualhost per example, you'll fail the check.

**Comment by ghormoon** [comment]
I've just checked the differences, it's unlikely to be related to gallery

diff:

```
82,105d81
< #### DO NOT CHANGE ANYTHING ABOVE THIS LINE ####
< 
< ErrorDocument 403 /core/templates/403.php
< ErrorDocument 404 /core/templates/404.php
< <IfModule mod_rewrite.c>
<   RewriteBase /
<   <IfModule mod_env.c>
<     SetEnv front_controller_active true
<     <IfModule mod_dir.c>
<       DirectorySlash off
<     </IfModule>
<   </IfModule>
< </IfModule>
< #### DO NOT CHANGE ANYTHING ABOVE THIS LINE ####
< 
< <IfModule mod_rewrite.c>
<   RewriteBase /
<   <IfModule mod_env.c>
<     SetEnv front_controller_active true
<     <IfModule mod_dir.c>
<       DirectorySlash off
<     </IfModule>
<   </IfModule>
< </IfModule>
```

I'll check if I find this in core

edit: fixed formatting

**Comment by oparoz** [comment]
I saw that the appstore was trying to make modifications to the .htaccess file
