### ISSUE TITLE
"Download" button broken

### ISSUE THREAD

**Issue by gjedeer** [owncloud/gallery#583]
### Steps to reproduce
1. Upgrade to ownCloud 9.0 and Gallery 14.5.0
2. Share some album using "Share Link"
3. Open the link in Private Browsing mode
4. Click "Download"
### Expected behaviour

A zip file downloads, like it used to in 14.4
### Actual behaviour

File not found

The specified document has not been found on the server.

You can click here to return to ownCloud.
### Server configuration

**Operating system**:
Ubuntu 14.04

**Web server:**
lighttpd

**Database:**
Sqlite

**PHP version:**
5.5.9

**ownCloud version:** (see ownCloud admin page or version.php)
9.0

**Updated from an older ownCloud or fresh install:**
Updated from 8.2

**List of activated apps:**

Enabled:
- activity: 2.2.1
- calendar: 1.0
- comments: 0.2
- contacts: 1.0.0.0
- dav: 0.1.5
- external: 1.2
- federatedfilesharing: 0.1.0
- federation: 0.0.4
- files: 1.4.4
- files_pdfviewer: 0.8
- files_sharing: 0.9.1
- files_texteditor: 2.1
- files_trashbin: 0.8.0
- files_videoplayer: 0.9.8
- firstrunwizard: 1.1
- gallery: 14.5.0
- notifications: 0.2.3
- provisioning_api: 0.4.1
- systemtags: 0.2
- templateeditor: 0.1
- updatenotification: 0.1.0
  Disabled:
- encryption
- files_external
- files_versions
- galleryplus
- user_external
- user_ldap

**The content of config/config.php:**

```
{
    "system": {
        "datadirectory": "***********************",
        "dbtype": "sqlite3",
        "version": "9.0.0.19",
        "installedat": "1328029564.0652",
        "lastupdatedat": "1342961822.3781",
        "installed": true,
        "instanceid": "51c89bd926532",
        "maintenance": false,
        "forcessl": true,
        "defaultapp": "calendar",
        "remote_core.css": "\/core\/minimizer.php",
        "remote_core.js": "\/core\/minimizer.php",
        "theme": "",
        "trusted_domains": [
            "***************",
            "***************"
        ],
        "share_folder": "\/Shared",
        "mail_smtpmode": "smtp",
        "mail_smtphost": "127.0.0.1",
        "mail_smtpport": "25",
        "mail_smtptimeout": 10,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "loglevel": "2",
        "check_for_working_webdav": false,
        "mail_smtpdebug": true,
        "mail_from_address": "owncloud",
        "mail_domain": "*****************",
        "enable_previews": true,
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***"
    }
}
```

**Are you using external storage, if yes which one:** local folder, smb share, sftp, etc.
no

**Are you using encryption:** yes/no
no

**Are you using custom gallery.cnf config files:** yes/no
no
#### Web server error log

(nothing related)
#### ownCloud log (data/owncloud.log)

(empty)
### Client configuration

**Browser:**
Firefox 44

**Operating system:**
Ubuntu 14.04
#### Browser log

URL:
https://(owncloud_domain)/index.php/s/(key)/download?path=Shared%2F(folder_name)&files=

**Comment by oparoz** [comment]
Thanks for the report. It's already been fixed and will be part of 9.0.1
See #554

**Comment by oparoz** [comment]
Btw, the fix is really small, so you can patch it yourself for the time being: https://github.com/interfasys/galleryplus/commit/9ea9b63367eec0e6a353cc4efd7575a62f6b6230

**Comment by gjedeer** [comment]
Thanks!

On March 10, 2016 11:47:41 PM CET, Olivier Paroz notifications@github.com wrote:

> Btw, the fix is really small, so you can patch it yourself for the time
> being:
> https://github.com/interfasys/galleryplus/commit/9ea9b63367eec0e6a353cc4efd7575a62f6b6230
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/owncloud/gallery/issues/583#issuecomment-195084855

## 

Sent from my Android device with K-9 Mail. Please excuse my brevity.
