### ISSUE TITLE
Create albums straight from Gallery

### ISSUE THREAD

**Issue by oparoz** [owncloud/gallery#584]
With drag and drop, you start to feel the need for it as it would make it easer to organise images quickly
### Exploration

We could allow for empty albums which have been created during the session to show up in Gallery, but they would not be saved to the filesystem until something has been moved inside them.

---

@jancborchardt @setnes @demattin 
##

**Comment by jancborchardt** [comment]
Yeah, sounds good. Or creating folders is just straight up the same.

**Comment by oparoz** [comment]
> Or creating folders is just straight up the same

That can't be. They'll disappear right away because they're empty

**Comment by oparoz** [comment]
This issue was moved to nextcloud/gallery#130
