### ISSUE TITLE
Show useful information about the current album

### ISSUE THREAD

**Issue by oparoz** [owncloud/gallery#585]
## Feature request

**User type**: All

**User level**: intermediate
### Description

Sometimes you'd like to quickly have the answers to these questions
- Can I upload new images to the current album?
- Do I have free space in the current album?
- Am I inside a shared album?

Sharing information is available in the share dialogue, but not the rest.

Maybe we could add that at the top of the infoPanel, shown when clicking on the infoButton?
- Lock icon to let users know they don't have write permission
- Share icon to let them know that the current album is shared
- Album size
- Free space
- Modification time
### Benefit / value

Avoids having to switch to the files side to have access to the information
### Risk / caveats

It would make the infoButton permanent
### Sponsorship

None
##

**Comment by imjalpreet** [comment]
@oparoz What all needs to be implemented in this? I was thinking of implementing this. Thanks!

**Comment by oparoz** [comment]
The first step is to decide where we want to show that information. I've made a suggestion in the OP, but you need to check with @jancborchardt and his team.
Files has some information at the bottom and on each row, but we can't use that.

What I would find useful:
- Lock icon to let users know they don't have write permission
- Share icon to let them know that the current album is shared
- Album size
- Free space
- Modification time

**Comment by oparoz** [comment]
This issue was moved to nextcloud/gallery#131
