### ISSUE TITLE
Enhancement: Rotate pictures directly in the slideshow and save.

### ISSUE THREAD

**Issue by enoch85** [owncloud/gallery#6]
Instead of having to download every single picture and rotate it into the position you want, it would be much better and easier to rotate them directly in the slideshow.

This could be handled by just adding a "rotate left" & "rotate right" button. After the rotation is done, the picture would be saved automatically.

Would it be possible to "rotate --> save automatically" like i.e. when you rotate pics in Windows? In that way the pictuers would turn out the right way in every instance, like WebDAV and also the sync client.

Opened this issue a while ago here: https://github.com/owncloud/apps/issues/1362 but was recommended by @PVince81 to move it here.

**Comment by oparoz** [comment]
Moved to https://github.com/owncloud/galleryplus/issues/236
