### ISSUE TITLE
Make it possible to use different slideshow engines in Gallery 

### ISSUE THREAD

**Issue by oparoz** [owncloud/gallery#600]
## Feature request

**User type**: All

**User level**: All
### Description

There is currently one slideshow engine in Gallery: Bigshot
We're only using a fraction of what this library is capable of doing (VR, tiling) while not offering more standard features, especially on mobile. On top of that it's huge and not maintained any more.

While investigating the use of alternatives, I thought that we could maybe modify [the slideshow launcher](https://github.com/owncloud/gallery/blob/master/js/gallery.js#L261-L324) to make it engine agnostic so that different types of ownCloud installations could use different types of engines.

This only works if most engines expect the same kind of data:
- A div on which content will be shown
- An image array
- A configuration object
- Maybe some callbacks for buttons?

A good engine can
- be customised via CSS
- accept new buttons
- be configured via a configuration object

and the current and future list of features for the slideshow can be found here:
https://github.com/owncloud/gallery/wiki/Slideshow

The first engine to implement which would become the new default is Photoswipe. See #158 for details.

We cannot load all engines at the same time, so users have to be able to pick the one they need from the preferences menu, the default would probably not be Bigshot
### Benefit / value

- Space agencies can still use ownCloud to drill down their super high resolution images using the Bigshot engine
- Non-technical users can swipe and zoom on their tablet
- Geeks can decide to implement their own solution
### Risk / caveats

It's important not to spend too much time trying to write a connector. It could very well be that each engine is very different and requires some specific JS and PHP code to work properly on the ownCloud platform. In that case we would focus on replacing Bigshot with Photoswipe.
### Sponsorship

Without a sponsor, Gallery will probably just remove Bigshot
##

**Comment by shubhrajodiya** [comment]
@oparoz  
now i am getting the taste of the task can you please give me some resources through which i can manage to get owncloud on my windows platform or i have to change my OS

**Comment by oparoz** [comment]
@shubhrajodiya Windows is fine. You can download a VM from there: https://www.techandme.se/pre-configured-owncloud-installaton/

A word of warning, that VM is not designed to be a dev VM, but it can be turned into one in a few steps.
Ping me if you get stuck and we'll try to document the process to make it easier for everybody to get on board.
You still need a basic understanding of how Linux works in order to be able to do ownCloud development though.

**Comment by shubhrajodiya** [comment]
@oparoz 

Is it possible to any how implement owncloud using wamp or any other such software stack on windows because the problem is that i am using a 2GB ram laptop and running VM will be really hectic for me.

**Comment by oparoz** [comment]
@shubhrajodiya - Unfortunately, it isn't... But try to see if you can pick up a Raspberry Pi2 or something similar. This slideshow project doesn't require a powerful server.

**Comment by Viva10** [comment]
Hi, I'm an engineering student of the University of Buea and I am interested in the project idea of the flexible slideshow egines. So I wish to how I can get the my environment setup and get to familiarize with the code.

**Comment by oparoz** [comment]
@Viva10 - Everything you need should be in [this wiki article](https://github.com/owncloud/gallery/wiki/GSoC-2016) or the official documentation

**Comment by oparoz** [comment]
This issue was moved to nextcloud/gallery#134
