### ISSUE TITLE
no way in public download view to go back to file view

### ISSUE THREAD

**Issue by jospoortvliet** [owncloud/gallery#605]
### Steps to reproduce
1. Share a folder link without images from the Files app with a public link
2. Visit the public link in an anonymous browser window
3. Switch to the Gallery app
4. Try to switch back - there is no button!

Note that the button IS there if you share a folder and there are images. It just doesn't show without.
### Expected behaviour

It should always show the header with button to switch back to the Files view.
### Actual behaviour

It shows no files view button on the top-right.
### Server configuration

**Operating system**:
openSUSE 13.2

**Web server:**
Apache 2

**Database:**
MySQL

**PHP version:**
7.0.3

**ownCloud version:** (see ownCloud admin page or version.php)
9.0.0

**Updated from an older ownCloud or fresh install:**
Updated since 6.0

**List of activated apps:**
Enabled:
- activity: 2.2.1
- calendar: 1.0
- comments: 0.2
- contacts: 1.0.0.0
- dav: 0.1.5
- documents: 0.12.0
- federatedfilesharing: 0.1.0
- federation: 0.0.4
- files: 1.4.4
- files_external: 0.5.2
- files_markdown: 0.1
- files_pdfviewer: 0.8
- files_sharing: 0.9.1
- files_texteditor: 2.1
- files_trashbin: 0.8.0
- files_versions: 1.2.0
- files_videoplayer: 0.9.8
- firstrunwizard: 1.1
- gallery: 14.5.0
- notifications: 0.2.3
- provisioning_api: 0.4.1
- systemtags: 0.2
- templateeditor: 0.1
- updatenotification: 0.1.0

**The content of config/config.php:**
        "datadirectory": "\/media\/bigbtrfs\/owncloud\/",
        "dbtype": "mysql",
        "version": "9.0.0.19",
        "dbname": "ownCloudDB",
        "dbhost": "127.0.0.1",
        "dbtableprefix": "oc_",
        "installed": true,
        "loglevel": 2,
        "forcessl": true,
        "theme": "",
        "maintenance": false,
        "preview_libreoffice_path": "\/usr\/lib64\/libreoffice\/program\/soffice",
        "overwritewebroot": "",
        "log_rotate_size": "100000000",
        "overwrite.cli.url": "https:\/\/cloud.josandcamila.com",
        "asset-pipeline.enabled": true,
        "forceSSLforSubdomains": true,
        "enable_previews": true,
        "preview_max_x": 2048,
        "preview_max_y": 2048,
        "preview_max_scale_factor": 10,
        "preview_max_filesize_image": 50,
        "enabledPreviewProviders": [
            "OC\Preview\PNG",
            "OC\Preview\JPEG",
            "OC\Preview\GIF",
            "OC\Preview\BMP",
            "OC\Preview\XBitmap",
            "OC\Preview\PDF",
            "OC\Preview\MP3",
            "OC\Preview\TXT",
            "OC\Preview\MarkDown",
            "OC\Preview\Postscript",
            "OC\Preview\SVG",
            "OC\Preview\TIFF",
            "OC\Preview\Font",
            "OC\Preview\Movie",
            "OC\Preview\Illustrator",
            "OC\Preview\Image",
            "OC\Preview\Photoshop"
        ],
        "appstore.experimental.enabled": true,
        "trashbin_retention_obligation": "auto",
        "memcache.locking": "\OC\Memcache\Redis",
        "redis": {
            "host": "localhost",
            "port": 6379,
            "timeout": 0,
            "password": "",
            "dbindex": 0
        },
        "updatechecker": false

**Are you using external storage, if yes which one:**
 local folders, Dropbox, G-drive.

**Are you using encryption:**
Nope

**Are you using custom gallery.cnf config files:**
Nope
### Logs

No relevant logs
### Client configuration

**Browser:**
Firefox and Chromium

**Operating system:**
Linux

**Comment by oparoz** [comment]
Thanks for the report!
This has already been fixed for 9.1 because I did notice it as well when testing the uploading feature.
https://github.com/owncloud/gallery/commit/0e89aab141d46458cb714ad5467754fdbb418924

**Comment by jospoortvliet** [comment]
Cool, thanks!
