### ISSUE TITLE
Panorama pics don't look very good

### ISSUE THREAD

**Issue by jospoortvliet** [owncloud/gallery#61]
Hi,

Panorama images don't look good in GalleryPlus, neither as thumbnail nor when clicked. They seem to be rendered in very low quality. Not sure if this is on my side, but I do see it for all wide pics. They are shown really cool: width shows up nicely in the thumbnail view, the image view can zoom and scroll very well. Just rendered at a low resolution...

![eight1](https://cloud.githubusercontent.com/assets/551757/6505938/3a125ca2-c347-11e4-8633-1d51ef5f9c8c.png)

Otherwise, awesome work on GalleryPlus - just updated to oC 8.0.1 and a git checkout of the performance fixes branch. Haven't applied the performance patches to ownCloud, just using it this way - not a big problem as long as I don't go to the root. I have to navigate to a sub folder with images in the Files app and then switch to Gallery and all is well ;-)

Let's get this app merged back in core! That would really rock.
##

**Comment by oparoz** [comment]
Thanks for the report... and the kind words :). I can confirm the bug, it's clearly visible on the demo as well.
`Preview` in `core` can't handle wide pictures, it sends back messed up previews. I fix them for the square previews (albums containing wide pics should look normal), but didn't want to have to fix all of them as it doubles the processing time. Maybe I should...
And even though it's been mentioned several times in various tickets, I don't think it's even in the `core` tracker.

(I've just pushed the latest changes from master to performance-fixes, so that you can benefit from them as well)

**Comment by oparoz** [comment]
OK, filed in `core` https://github.com/owncloud/core/issues/14712

**Comment by oparoz** [comment]
A big problem we'll be facing when this is fixed is that all these "bad" pictures will be stored in the cache as `400-200-with-aspect.png` and there is currently no way to fix only select thumbnails without manually removing them.

**Comment by oparoz** [comment]
So, I've had a look and for large previews, I've applied a quick fix which should help with most previews

**Comment by oparoz** [comment]
For thumbnails, it's a bit more complicated.
We always ask for 400x200 pictures, so it's either
- we stretch them to maybe 800x400 and crop them to 800x200, leading to blurry thumbnails or
- we crop them to 400x200, but there is no way of telling they're panoramic.

The 3rd option is to ask for the image size in advance, but that's going to slow down operations as each image has to be tested even before we start showing anything.

**Comment by jospoortvliet** [comment]
Hmm, the crop is probably the best one. That is already wide, and it's less bad than blurry I think...

**Comment by oparoz** [comment]
Let's see if other people want to chime in. It should be possible to fix wide images, but the Preview class doesn't make it easy as there isn't a way to invalidate a preview, so we have to generate a new one.

**Comment by oparoz** [comment]
I've filed this in core to try and make it easier to alter previews quickly if we see that a preview could be problematic: https://github.com/owncloud/core/issues/14739

**Comment by jospoortvliet** [comment]
@oparoz note that in my opinion - this isn't a huge issue. The crop is quite OK. Yes, yes, showing them fully is prettier, but it isn't worth a HUGE amount of work unless you feel like taking on the challenge :D

**Comment by oparoz** [comment]
The problem is that it doesn't only affect panoramic pictures. Any picture with a height smaller than 200 will be stretched, so cropping works for pictures, but wouldn't look great for logos per example.

**Comment by jospoortvliet** [comment]
Ok, I understand. So no easy fix for this one...

**Comment by oparoz** [comment]
Having this would help greatly https://github.com/owncloud/core/issues/7881

**Comment by oparoz** [comment]
Moved to https://github.com/nextcloud/gallery/issues/19
