### ISSUE TITLE
Many problems after upgrade to new gallery app

### ISSUE THREAD

**Issue by rahliak** [owncloud/gallery#624]
### Steps to reproduce
1. Upgrade from OC 8.1 to OC 8.2
2. Open the Gallery app
3. Nothing happens. No images are displayed.
### Expected behaviour

The gallery app shows a gallery of my uploaded pictures.
### Actual behaviour

After starting the gallery app, nothing happens. The "waiting wheel" rotates and rotates, but nothing happens.
### Server configuration

**Operating system**:
Debian 8.3

**Web server:**
apache2 2.4.10-10+deb8u4

**Database:**
mysql-server 5.5.47-0+deb8u1

**PHP version:**
php5 5.6.17+dfsg-0+deb8u1

**ownCloud version:** (see ownCloud admin page or version.php)
owncloud 8.2.3-2.1

**Updated from an older ownCloud or fresh install:**
Update from owncloud 8.1.6-13.1

**List of activated apps:**
Enabled:
- activity: 2.1.4
- files: 1.2.1
- files_pdfviewer: 0.7
- files_sharing: 0.7.0
- files_texteditor: 2.0
- files_trashbin: 0.7.0
- files_versions: 1.1.0
- files_videoviewer: 0.1.3
- firstrunwizard: 1.1
- gallery: 14.2.0
- provisioning_api: 0.3.0
- templateeditor: 0.1
  Disabled:
- encryption
- external
- files_external
- notifications
- user_external
- user_ldap

config.php
<?php
$CONFIG = array (
  'instanceid' => 'oc8dokjp3iuk',
  'passwordsalt' => 'xxx',
  'secret' => 'xxx',
  'trusted_domains' =>
  array (
    0 => '10.0.40.8',
  ),
  'datadirectory' => '/var/www/owncloud/data',
  'overwrite.cli.url' => 'https://10.0.40.8/owncloud',
  'dbtype' => 'mysql',
  'version' => '8.2.3.2',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'owncloud_admin',
  'dbpassword' => 'xxx',
  'installed' => true,
  'mail_from_address' => 'owncloud',
  'mail_smtpmode' => 'smtp',
  'mail_domain' => 'testdom',
  'mail_smtphost' => '10.0.40.40',
  'mail_smtpsecure' => 'tls',
  'forcessl' => true,
  'forceSSLforSubdomains' => true,
  'default_language' => 'de',
  'loglevel' => 0,
  'maintenance' => false,
  'theme' => '',
  'memcache.local' => '\OC\Memcache\APCu',
  'trashbin_retention_obligation' => 'auto',
);

**Are you using external storage, if yes which one:** local folder, smb share, sftp, etc.
no

**Are you using encryption:** yes/no
no

**Are you using custom gallery.cnf config files:** yes/no
no
#### Web server error log

[Fri Mar 25 06:51:43.891686 2016] [ssl:info] [pid 5136] [client 192.168.0.27:48763] AH01964: Connection to child 7 established (server www.kuegler.org:443)
[Fri Mar 25 06:51:48.924139 2016] [ssl:info] [pid 5136](70007)The timeout specified has expired: [client 192.168.0.27:48763] AH01991: SSL input filter read failed.
[Fri Mar 25 06:51:54.448879 2016] [ssl:info] [pid 6254](70007)The timeout specified has expired: [client 192.168.0.27:48758] AH01991: SSL input filter read failed.
#### ownCloud log (data/owncloud.log)

{"reqId":"1k\/gMRNwTtAHY7e041qp","remoteAddr":"","app":"cron","message":"Run job with ID 3","level":0,"time":"2016-03-25T05:45:05+00:00","method":"--","url":"--"}
{"reqId":"1k\/gMRNwTtAHY7e041qp","remoteAddr":"","app":"cron","message":"Finished job with ID 3","level":0,"time":"2016-03-25T05:45:05+00:00","method":"--","url":"--"}
{"reqId":"1k\/gMRNwTtAHY7e041qp","remoteAddr":"","app":"cron","message":"Run job with ID 4","level":0,"time":"2016-03-25T05:45:05+00:00","method":"--","url":"--"}
{"reqId":"1k\/gMRNwTtAHY7e041qp","remoteAddr":"","app":"DeleteOrphanedSharesJob","message":"0 orphaned share(s) deleted","level":0,"time":"2016-03-25T05:45:05+00:00","method":"--","url":"--"}
{"reqId":"1k\/gMRNwTtAHY7e041qp","remoteAddr":"","app":"cron","message":"Finished job with ID 4","level":0,"time":"2016-03-25T05:45:05+00:00","method":"--","url":"--"}
{"reqId":"1k\/gMRNwTtAHY7e041qp","remoteAddr":"","app":"cron","message":"Run job with ID 5","level":0,"time":"2016-03-25T05:45:05+00:00","method":"--","url":"--"}
{"reqId":"1k\/gMRNwTtAHY7e041qp","remoteAddr":"","app":"cron","message":"Finished job with ID 5","level":0,"time":"2016-03-25T05:45:06+00:00","method":"--","url":"--"}
{"reqId":"1k\/gMRNwTtAHY7e041qp","remoteAddr":"","app":"cron","message":"Run job with ID 6","level":0,"time":"2016-03-25T05:45:06+00:00","method":"--","url":"--"}
{"reqId":"1k\/gMRNwTtAHY7e041qp","remoteAddr":"","app":"cron","message":"Finished job with ID 6","level":0,"time":"2016-03-25T05:45:06+00:00","method":"--","url":"--"}
{"reqId":"1k\/gMRNwTtAHY7e041qp","remoteAddr":"","app":"cron","message":"Run job with ID 7","level":0,"time":"2016-03-25T05:45:06+00:00","method":"--","url":"--"}
{"reqId":"1k\/gMRNwTtAHY7e041qp","remoteAddr":"","app":"cron","message":"Finished job with ID 7","level":0,"time":"2016-03-25T05:45:06+00:00","method":"--","url":"--"}
{"reqId":"1k\/gMRNwTtAHY7e041qp","remoteAddr":"","app":"cron","message":"Run job with ID 2","level":0,"time":"2016-03-25T05:45:06+00:00","method":"--","url":"--"}
{"reqId":"1k\/gMRNwTtAHY7e041qp","remoteAddr":"","app":"cron","message":"Finished job with ID 2","level":0,"time":"2016-03-25T05:45:06+00:00","method":"--","url":"--"}
### Client configuration

**Browser:**
Firefox/Iceweasel 38.6.0 (Debian)
and
Firefox 45.0.1 (Windows)

**Operating system:**
Debian 8.3 
and
Windows 7
#### Browser log

no Browser log available

**Comment by oparoz** [comment]
Please enable debugging in your config.php and try to look at the browser (F12) and owncloud log again.

**Comment by rahliak** [comment]
I found the solution for myself. It was the following Redirect-Rule in my apache-config:
RedirectMatch 404 /config(/|$)

After disabling this RedirectMatch, everything works fine.

**Comment by oparoz** [comment]
Ah, good :)
