### ISSUE TITLE
Images on ext. stor.: image rotation corrupt

### ISSUE THREAD

**Issue by snoopyf** [owncloud/gallery#637]
## Bug report

Hi everyone,

stumbled across this issue:
When images resides in external storage (SMB/CIFS for example) the image rotation based on EXIF information doesn't work anywhere... neither in the preview of the files app, nor in the gallery-apps thumbnails.
When the same images resides in the "normal" storage (oc - data dir) rotation works as expected everywhere...
### Steps to reproduce
1. Upload a rotated image to an external storage
2. Open path in files or gallery app
3. Notice the image is not rotated automatically
4. Upload the same image to the "normal" OC Storage (users root folder for example)
5. Open path in files or gallery app
6. Image is rotated automatically as it should be
### Expected behaviour

The images should be rotated based on the EXIF information regardless where they r stored
### Actual behaviour

The image rotation depends on the store
### Server configuration

**Operating system**:
Ubuntu 15.04 LTS
**Web server:**
 Apache 2.4.10
**Database:**
MySQL 5.6.28
**PHP version:**
PHP 5.6.4
**ownCloud version:** (see ownCloud admin page or version.php)
9.0.0
**Updated from an older ownCloud or fresh install:**
Updated (8.2.x)
**List of activated apps:**
- comments: 0.2
- dav: 0.1.5
- federatedfilesharing: 0.1.0
- federation: 0.0.4
- files: 1.4.4
- files_external: 0.5.2
- files_pdfviewer: 0.8
- files_sharing: 0.9.1
- files_texteditor: 2.1
- files_trashbin: 0.8.0
- files_versions: 1.2.0
- files_videoplayer: 0.9.8
- firstrunwizard: 1.1
- gallery: 14.5.0
- gpxpod: 0.9.16
- html5_videoplayer: 1.0
- logreader: 1.1.2
- news: 7.1.2
- notifications: 0.2.3
- ownnote: 1.07
- provisioning_api: 0.4.1
- systemtags: 0.2
- templateeditor: 0.1
- updatenotification: 0.1.0
- user_ldap: 0.8.0

**The content of config/config.php:**
{
    "system": {
        "instanceid": "***_",
        "passwordsalt": "**_REMOVED SENSITIVE VALUE**_",
        "secret": "**_REMOVED SENSITIVE VALUE**_",
        "trusted_domains": [
somedomains
        ],
        "datadirectory": "**__",
        "overwrite.cli.url": "_**_",
        "overwritewebroot": "**__",
        "dbtype": "mysql",
        "version": "9.0.0.19",
        "dbname": "_**",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "**_REMOVED SENSITIVE VALUE_**",
        "dbpassword": "**_REMOVED SENSITIVE VALUE_**",
        "logtimezone": "UTC",
        "installed": true,
        "ldapIgnoreNamingRules": false,
        "appstore.experimental.enabled": true,
        "theme": "",
        "loglevel": 0,
        "memcache.local": "\OC\Memcache\APC",
        "filesystem_check_changes": 1,
        "mail_from_address": "**_",
        "mail_smtpmode": "smtp",
        "mail_domain": "_**",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "**_",
        "mail_smtpport": "25",
        "mail_smtpname": "_**REMOVED SENSITIVE VALUE**_",
        "mail_smtppassword": "_**REMOVED SENSITIVE VALUE***",
        "updatechecker": false,
        "maintenance": false
    }
}

**Are you using external storage, if yes which one:** local folder, smb share, sftp, etc.
Yes: SMB/CIFS

**Are you using encryption:** yes/no
no

**Are you using custom gallery.cnf config files:** yes/no
no
#### Web server error log

Nothing of interest here
#### ownCloud log (data/owncloud.log)

Nothing of interest here
### Client configuration

**Browser:**
Firefox 45.0

**Operating system:**
KUbuntu 15.10

**Comment by oparoz** [comment]
Thanks for the report!

Because it also affects Files and because I heard it before, there must already be an issue about it in `core`. Could you see if you find it? I think it affects all storage locations which are not "local", so encrypted files are affected as well.

**Comment by snoopyf** [comment]
In core I found this issue:
https://github.com/owncloud/core/issues/21485

At a first glance it seems not exactly the same than I described... in this issue nothing about "non"-local storage can be read.. just the very last post mentions sth about. encryption (as u assumed). I will post a comment there too linking to this issue here...

**Comment by oparoz** [comment]
Closing as this is a `core` issue

**Comment by snoopyf** [comment]
In the mentioned thread in core here seems to be the solution:
https://github.com/owncloud/core/issues/21485#issuecomment-203863754
