### ISSUE TITLE
Disable spinner on current breadcrumb

### ISSUE THREAD

**Issue by oparoz** [owncloud/gallery#638]
When on "home" or in an album with no parent represented by an ellipsis in the breadcrumbs, the click action should be disabled, with the nice side-effect that the spinner wouldn't show up.
##

**Comment by shubhrajodiya** [comment]
@oparoz can you please upload some screenshots because its not much clear

**Comment by oparoz** [comment]
It's easy to reproduce.
1. Open Gallery
2. Click on "home"

You'll see a spinner on top of the icon. It should happen because we're already on "home.

Clearer?

**Comment by shubhrajodiya** [comment]
@oparoz 
i think its working fine no spinner is shown when i click on home in gallery

**Comment by sourabhjagtap95** [comment]
Yes I see a spinner on top of the home icon @oparoz 
First of all, is there any need for displaying a spinner on the label because switching to another folder through breadcrumb makes the spinner barely visible.

**Comment by oparoz** [comment]
> Yes I see a spinner on top of the home icon @oparoz 

Good :)

> First of all, is there any need for displaying a spinner on the label because switching to another folder through breadcrumb makes the spinner barely visible.

There is a need for some form of visual feedback because loading the new folder can take a few seconds on some platforms.
I chose to place a spinner in the breadcrumb (which is far from perfect), but it can be something else if you have some ideas?
