### ISSUE TITLE
Saving individual images in original quality is not possible

### ISSUE THREAD

**Issue by arjanvlek** [owncloud/gallery#642]
Hi,
For some reason, it is impossible to save an individual image file in full quality.
The Download button works, but downloads a .zip archive containing all pictures in the folder.

If you right click -> save image as on the gallery itself, it saves a very low-res picture, probably only the thumbnail file.
If you open an image and right click on it, you'll only get the option to download the page as Webpage, complete (.mht):
![2016-04-03 3](https://cloud.githubusercontent.com/assets/10106652/14231522/e8d1789c-f986-11e5-8d18-d79a35be88d6.png)
![2016-04-03 4](https://cloud.githubusercontent.com/assets/10106652/14231523/ecaf4980-f986-11e5-815b-aef5bde9f906.png)

After inspecting the image, I see the following code:

```
<img src="**SOME IMAGE SOURCE**" alt="** ORIGINAL FILE NAME OF IMAGE FILE **" style="position: absolute; top: 0.602667px; height: 502px; left: 626.603px; width: 669.333px; background-color: rgb(0, 0, 0); background-size: 669.333px 502px; background-position: 0px 0px;">
<div style="position: absolute; overflow: hidden; width: 1920px; height: 502px;"></div>
```

The bottom <div> element seems to be blocking the download of the image file.
If I remove this div delemnt in Chrome DevTools, I can save the image fine. Also see the screenshots:
![2016-04-03 1](https://cloud.githubusercontent.com/assets/10106652/14231511/7ab1284e-f986-11e5-9034-93424bfc33e2.png)

![2016-04-03 5](https://cloud.githubusercontent.com/assets/10106652/14231529/177ba92e-f987-11e5-8b41-5969a3b6cf26.png)
![2016-04-03 6](https://cloud.githubusercontent.com/assets/10106652/14231530/19a5c680-f987-11e5-9e19-cf8f8d32fb69.png)
### Steps to reproduce
1. Open a folder in the gallery app
2. Open any image by clicking on it.
3. Right click on the image, and find out that only the webpage can be saved, not just the image file
### Expected behaviour

I think it should be possible to save just one image file, rather than having to download the entire folder in zipped format.

### Actual behaviour

Only option is to download the zipped folder, or save the crappy quality thumbnail image. Right clicking on the image allows the web page to be saved in .mht format, but is useless for e.g. Facebook sharing.

### Server configuration

**Operating system**: Debian Jessie 8.3 (i386)

**Web server:** Apache 2.4.10

**Database:** MySQL Server 5.5.47

**PHP version:** 5.6.17

**ownCloud version:** (see ownCloud admin page or version.php) ownCloud 8.2.3 (stable)

**Updated from an older ownCloud or fresh install:** Updated 8.2.0 -> 8.2.1 -> 8.2.2 -> 8.2.3

**List of activated apps:**

- activity: 2.1.4
- files: 1.2.1
- files_pdfviewer: 0.7
- files_sharing: 0.7.0
- files_texteditor: 2.0
- files_trashbin: 0.7.0
- files_versions: 1.1.0
- files_videoviewer: 0.1.3
- firstrunwizard: 1.1
- gallery: 14.2.0
- notifications: 0.1.0
- provisioning_api: 0.3.0
- templateeditor: 0.1

Disabled:
- audios
- documents
- encryption
- external
- files_external
- user_external
- user_ldap

**The content of config/config.php:**

{
    "system": {
        "instanceid": "ocmhq499vyue",
        "passwordsalt": "**_REMOVED SENSITIVE VALUE**_",
        "secret": "**_REMOVED SENSITIVE VALUE**_",
        "trusted_domains": [
            "drive.familievlek.nl"
        ],
        "datadirectory": "\/media\/hdd\/owncloud",
        "overwrite.cli.url": "https:\/\/drive.familievlek.nl",
        "dbtype": "mysql",
        "version": "8.2.3.2",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "**_REMOVED SENSITIVE VALUE**_",
        "dbpassword": "**_REMOVED SENSITIVE VALUE**_",
        "logtimezone": "UTC",
        "installed": true,
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "ssl",
        "mail_from_address": "arjan1995",
        "mail_domain": "gmail.com",
        "mail_smtphost": "smtp.gmail.com",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtpname": "**_REMOVED SENSITIVE VALUE**_",
        "mail_smtppassword": "**_REMOVED SENSITIVE VALUE**_",
        "mail_smtpport": "465",
        "maintenance": false,
        "loglevel": 2,
        "trashbin_retention_obligation": "auto",
        "appstore.experimental.enabled": true,
        "theme": ""
    }
}

**Are you using external storage, if yes which one:** local folder, smb share, sftp, etc.
Yes, local folder on external USB Hard Drive
**Are you using encryption:** yes/no
yes, HTTPS is being enforced on all OwnCloud requests. File encryption is turned off.
**Are you using custom gallery.cnf config files:** yes/no
no
#### Web server error log

This issue doesn't cause errors to be logged (this is my log from today):
Sun Apr 03 07:58:43.993717 2016] [ssl:warn] [pid 23207] AH01909: familievlek.nl:443:0 server certificate does NOT include an ID which matches the server name
[Sun Apr 03 07:58:44.020116 2016] [ssl:warn] [pid 23207] AH01909: familievlek.nl:443:0 server certificate does NOT include an ID which matches the server name
[Sun Apr 03 07:58:44.020898 2016] [mpm_prefork:notice] [pid 23207] AH00163: Apache/2.4.10 (Debian) OpenSSL/1.0.1k configured -- resuming normal operations
[Sun Apr 03 07:58:44.020914 2016] [core:notice] [pid 23207] AH00094: Command line: '/usr/sbin/apache2'
[Sun Apr 03 10:17:03.088097 2016] [authz_core:error] [pid 10306] [client 84.104.12.137:60318] AH01630: client denied by server configuration: /var/www/owncloud/data/htaccesstest.txt
#### ownCloud log (data/owncloud.log)

{"reqId":"99fkxr5kJ+NHa5nDci9E","remoteAddr":"84.104.12.137","app":"PHP","message":"Undefined offset: 0 at \/var\/www\/owncloud\/lib\/private\/appframework\/http\/request.php#685","level":3,"time":"2015-10-03T15:41:15+00:00"}
{"reqId":"99fkxr5kJ+NHa5nDci9E","remoteAddr":"84.104.12.137","app":"PHP","message":"fopen(\/var\/www\/owncloud\/config\/config.php): failed to open stream: No such file or directory at \/var\/www\/owncloud\/lib\/private\/config.php#191","level":3,"time":"2015-10-03T15:41:16+00:00"}
{"reqId":"C8zbtEKwroZ9z1W+gxw2","remoteAddr":"84.104.12.137","app":"PHP","message":"Undefined offset: 0 at \/var\/www\/owncloud\/lib\/private\/appframework\/http\/request.php#685","level":3,"time":"2015-10-03T15:43:06+00:00"}
{"reqId":"0gJ8Tp+uX+0XS\/aR1JIW","remoteAddr":"84.104.12.137","app":"PHP","message":"Undefined offset: 0 at \/var\/www\/owncloud\/lib\/private\/appframework\/http\/request.php#685","level":3,"time":"2015-10-03T15:50:26+00:00"}
{"reqId":"Js3zi2aPGmyU\/SDhvSim","remoteAddr":"84.104.12.137","app":"PHP","message":"Undefined offset: 0 at \/var\/www\/owncloud\/lib\/private\/appframework\/http\/request.php#685","level":3,"time":"2015-10-03T16:00:39+00:00"}
{"reqId":"VZN\/39Lp+dVC5kr2D69O","remoteAddr":"84.104.12.137","app":"PHP","message":"Undefined offset: 0 at \/var\/www\/owncloud\/lib\/private\/appframework\/http\/request.php#685","level":3,"time":"2015-10-03T17:19:28+00:00"}
{"reqId":"Pngf9\/rRQdpCpnk1IaQt","remoteAddr":"84.104.12.137","app":"PHP","message":"Undefined offset: 0 at \/var\/www\/owncloud\/lib\/private\/appframework\/http\/request.php#685","level":3,"time":"2015-10-03T17:19:36+00:00"}
{"reqId":"\/g+uzXbfkEQ64qNFtUy9","remoteAddr":"84.104.12.137","app":"PHP","message":"Undefined offset: 0 at \/var\/www\/owncloud\/lib\/private\/appframework\/http\/request.php#685","level":3,"time":"2015-10-05T20:40:22+00:00"}
{"reqId":"EXTgAEyKNrXyHvZGb0vg","remoteAddr":"84.104.12.137","app":"PHP","message":"Undefined offset: 0 at \/var\/www\/owncloud\/lib\/private\/appframework\/http\/request.php#685","level":3,"time":"2015-10-05T21:16:15+00:00"}
{"reqId":"+xz+AytNTRXLuZeZRXnS","remoteAddr":"84.104.12.137","app":"PHP","message":"Undefined offset: 0 at \/var\/www\/owncloud\/lib\/private\/appframework\/http\/request.php#685","level":3,"time":"2015-10-07T21:05:54+00:00"}
{"reqId":"f8VnwBHYVhCJXox7Z4ff","remoteAddr":"84.104.12.137","app":"PHP","message":"Undefined offset: 0 at \/var\/www\/owncloud\/lib\/private\/appframework\/http\/request.php#685","level":3,"time":"2015-10-07T21:06:29+00:00"}
{"reqId":"f8VnwBHYVhCJXox7Z4ff","remoteAddr":"84.104.12.137","app":"PHP","message":"mkdir(): Permission denied at \/var\/www\/owncloud\/lib\/private\/setup.php#264","level":3,"time":"2015-10-07T21:06:29+00:00"}
{"reqId":"rt+1pkk5IliZPEwo5g3L","remoteAddr":"84.104.12.137","app":"PHP","message":"Undefined offset: 0 at \/var\/www\/owncloud\/lib\/private\/appframework\/http\/request.php#685","level":3,"time":"2015-10-07T21:07:54+00:00"}
{"reqId":"rt+1pkk5IliZPEwo5g3L","remoteAddr":"84.104.12.137","app":"PHP","message":"mkdir(): Permission denied at \/var\/www\/owncloud\/lib\/private\/setup.php#264","level":3,"time":"2015-10-07T21:07:54+00:00"}
{"reqId":"1ZMekxc\/qKpu27cyOx5c","remoteAddr":"84.104.12.137","app":"PHP","message":"Undefined offset: 0 at \/var\/www\/owncloud\/lib\/private\/appframework\/http\/request.php#685","level":3,"time":"2015-10-07T21:08:19+00:00"}
{"reqId":"1ZMekxc\/qKpu27cyOx5c","remoteAddr":"84.104.12.137","app":"PHP","message":"mkdir(): Permission denied at \/var\/www\/owncloud\/lib\/private\/setup.php#264","level":3,"time":"2015-10-07T21:08:19+00:00"}
{"reqId":"hEBLMi7CNgTdeRHxKEkm","remoteAddr":"84.104.12.137","app":"PHP","message":"Undefined offset: 0 at \/var\/www\/owncloud\/lib\/private\/appframework\/http\/request.php#685","level":3,"time":"2015-10-07T21:11:32+00:00"}
{"reqId":"hEBLMi7CNgTdeRHxKEkm","remoteAddr":"84.104.12.137","app":"PHP","message":"mkdir(): Permission denied at \/var\/www\/owncloud\/lib\/private\/setup.php#264","level":3,"time":"2015-10-07T21:11:32+00:00"}
{"reqId":"7sFDodAqs+lZ0NIXPhoR","remoteAddr":"84.104.12.137","app":"PHP","message":"Undefined offset: 0 at \/var\/www\/owncloud\/lib\/private\/appframework\/http\/request.php#685","level":3,"time":"2015-10-07T21:11:49+00:00"}
{"reqId":"7sFDodAqs+lZ0NIXPhoR","remoteAddr":"84.104.12.137","app":"PHP","message":"mkdir(): Permission denied at \/var\/www\/owncloud\/lib\/private\/setup.php#264","level":3,"time":"2015-10-07T21:11:49+00:00"}
{"reqId":"ipWJoM2yMqKlx55c184i","remoteAddr":"84.104.12.137","app":"PHP","message":"Undefined offset: 0 at \/var\/www\/owncloud\/lib\/private\/appframework\/http\/request.php#685","level":3,"time":"2015-10-07T21:12:42+00:00"}
{"reqId":"xL\/jpEO\/4u818LnnZA\/O","remoteAddr":"84.104.12.137","app":"PHP","message":"Undefined offset: 0 at \/var\/www\/owncloud\/lib\/private\/appframework\/http\/request.php#685","level":3,"time":"2015-10-07T21:13:08+00:00"}
{"reqId":"xL\/jpEO\/4u818LnnZA\/O","remoteAddr":"84.104.12.137","app":"PHP","message":"mkdir(): Permission denied at \/var\/www\/owncloud\/lib\/private\/setup.php#264","level":3,"time":"2015-10-07T21:13:08+00:00"}
{"reqId":"3um8zUlvbtqlgQKk0XrG","remoteAddr":"84.104.12.137","app":"PHP","message":"Undefined offset: 0 at \/var\/www\/owncloud\/lib\/private\/appframework\/http\/request.php#685","level":3,"time":"2015-10-07T21:13:44+00:00"}
{"reqId":"3um8zUlvbtqlgQKk0XrG","remoteAddr":"84.104.12.137","app":"PHP","message":"mkdir(): Permission denied at \/var\/www\/owncloud\/lib\/private\/setup.php#264","level":3,"time":"2015-10-07T21:13:44+00:00"}
{"reqId":"Hmcc60s7fToLp1AqzGy8","remoteAddr":"84.104.12.137","app":"PHP","message":"Undefined offset: 0 at \/var\/www\/owncloud\/lib\/private\/appframework\/http\/request.php#685","level":3,"time":"2015-10-07T21:13:48+00:00"}
{"reqId":"Hmcc60s7fToLp1AqzGy8","remoteAddr":"84.104.12.137","app":"PHP","message":"mkdir(): Permission denied at \/var\/www\/owncloud\/lib\/private\/setup.php#264","level":3,"time":"2015-10-07T21:13:48+00:00"}
{"reqId":"32ggSbq77B9JCZQXDOhe","remoteAddr":"84.104.12.137","app":"PHP","message":"Undefined offset: 0 at \/var\/www\/owncloud\/lib\/private\/appframework\/http\/request.php#685","level":3,"time":"2015-10-07T21:15:05+00:00"}
{"reqId":"32ggSbq77B9JCZQXDOhe","remoteAddr":"84.104.12.137","app":"PHP","message":"mkdir(): Permission denied at \/var\/www\/owncloud\/lib\/private\/setup.php#264","level":3,"time":"2015-10-07T21:15:05+00:00"}
{"reqId":"6g7nazAkNTb9N8W9yDKx","remoteAddr":"84.104.12.137","app":"PHP","message":"Undefined offset: 0 at \/var\/www\/owncloud\/lib\/private\/appframework\/http\/request.php#685","level":3,"time":"2015-10-07T21:15:16+00:00"}
{"reqId":"6g7nazAkNTb9N8W9yDKx","remoteAddr":"84.104.12.137","app":"PHP","message":"mkdir(): Permission denied at \/var\/www\/owncloud\/lib\/private\/setup.php#264","level":3,"time":"2015-10-07T21:15:16+00:00"}
{"reqId":"z8M\/qknkAO2Gw8tuV0dL","remoteAddr":"84.104.12.137","app":"PHP","message":"Undefined offset: 0 at \/var\/www\/owncloud\/lib\/private\/appframework\/http\/request.php#685","level":3,"time":"2015-10-07T21:16:44+00:00"}
{"reqId":"GaIB9ANaOab0oguBQ092","remoteAddr":"84.104.12.137","app":"PHP","message":"fopen(\/var\/www\/owncloud\/config\/config.php): failed to open stream: No such file or directory at \/var\/www\/owncloud\/lib\/private\/config.php#191","level":3,"time":"2015-10-18T19:09:22+00:00"}
{"reqId":"3m0PEyXB9oXBErDJecG+","remoteAddr":"84.104.12.137","app":"PHP","message":"Undefined offset: 0 at \/var\/www\/owncloud\/lib\/private\/appframework\/http\/request.php#685","level":3,"time":"2015-10-18T19:09:25+00:00"}
{"reqId":"zFem3nMddYAtKINxz5Rk","remoteAddr":"84.104.12.137","app":"PHP","message":"Undefined offset: 0 at \/var\/www\/owncloud\/lib\/private\/appframework\/http\/request.php#685","level":3,"time":"2015-10-18T19:09:44+00:00"}
{"reqId":"qC3XVg7+BqiELTjUTHyU","remoteAddr":"84.104.12.137","app":"PHP","message":"Undefined offset: 0 at \/var\/www\/owncloud\/lib\/private\/appframework\/http\/request.php#685","level":3,"time":"2015-10-18T19:11:44+00:00"}
{"reqId":"qC3XVg7+BqiELTjUTHyU","remoteAddr":"84.104.12.137","app":"PHP","message":"fopen(\/var\/www\/owncloud\/config\/config.php): failed to open stream: No such file or directory at \/var\/www\/owncloud\/lib\/private\/config.php#191","level":3,"time":"2015-10-18T19:11:44+00:00"}
{"reqId":"f+oRSdJ5ibHOa4NJkPJ0","remoteAddr":"84.104.12.137","app":"PHP","message":"Undefined offset: 0 at \/var\/www\/owncloud\/lib\/private\/appframework\/http\/request.php#685","level":3,"time":"2015-10-18T19:12:31+00:00"}
### Client configuration

**Browser:** Chrome 49.0.2623.110

**Operating system:** Windows 10
#### Browser log

a) The javascript console log: No errors are logged
b) The network log:
![2016-04-03 2](https://cloud.githubusercontent.com/assets/10106652/14231508/6a97d584-f986-11e5-9b22-5684ce3f4fa9.png)

**Comment by oparoz** [comment]
Hello @arjanvlek. Thanks for the report. It should be possible to download images from the slideshow when you're in Gallery, but there seems to be a bug because the download button doesn't show up in your interface. I'll try to reproduce.

**Comment by oparoz** [comment]
I can't reproduce the problem.
When you're inspecting the elements, look in the `menu` div in the `slideshow` div.
There should be an button for downloads. If it's not there, then there must be something wrong with your setup.
If it's there, but you don't see it, it could be because of another app like the pdf or video viewers.

**Comment by arjanvlek** [comment]
EDIT: I have opened the Gallery app on my server and see the download button now. The issue is that the picture I showed has such a bright sky rendering the button completely invisible. The button is located in the middle at the top. I installed a local copy of OwnCloud 9.x and I saw that the button has moved to the right corner. That is at least a lot better for 4:3 photos (which most are), but still is insufficient for 16:9 images as they cover almost the whole screen.

My remaining questions are:
- Is there anyway I can make the download button a bit more gray-ish, such as by altering a css file? 
- Why is my server not running on 9.0.0 even though `apt-get update`/ `apt-get (dist-)upgrade` show everything is up to date? I did change the repository back in the days to get the 8.2.x files so that is not the issue, or do I have to change it again?

**Comment by oparoz** [comment]
> The issue is that the picture I showed has such a bright sky rendering the button completely invisible.

Yes, I realised that it wouldn't work located there and we have more to add.

> Is there anyway I can make the download button a bit more gray-ish, such as by altering a css file?

Yes, create a new class in slideshow.css

> Why is my server not running on 9.0.0 even though apt-get update/ apt-get (dist-)upgrade show everything is up to date?

It might be related to all the drama which recently took place between Debian maintainers and ownCloud developers.
You may not have new packages and should update from within ownCloud.
It's a much better solution from my pov.

**Comment by arjanvlek** [comment]
Okay, I got it updated as I found out my owncloud.list (/etc/apt/sources.d) was stuck on 8.2. Changing it to stable immediately started the update. All is fine now, thanks for helping me!
