### ISSUE TITLE
Show a warning if the PHP memory limit is set too low

### ISSUE THREAD

**Issue by oparoz** [owncloud/gallery#645]
One of the last remaining way to make Gallery crash is to try to open an album containing large JPEGs while having a PHP memory limit set lower than 256MB.

Despite my belief that PHP 7 had removed all these internal errors which made PHP stop in its tracks, that one still kills PHP and leaves Gallery hanging.

One way to solve the problem is to stop parallel processing thumbnails. I don't think it's a good idea as most CPUs today have multiple cores.
Another way could be to wait for all thumbnails to be ready before closing the line, but that means there would be less PHP workers available to do other things and not all thumbnails would be sent back, leading to randomly missing content.

So, since this seems difficult to solve via code, maybe we could show a warning somewhere, letting admins know that there will be issues with image preview rendering if they keep the current limit that low.

@jancborchardt 
##

**Comment by jancborchardt** [comment]
Maybe something for the Setup & security warnings in the admin page? Or the tips & tricks, if it’s not too breaking.

cc @LukasReschke @karlitschek

**Comment by karlitschek** [comment]
Hmm. so the memory limit is per process. So shouldn't affect parallel requests.
Are there really single jpegs that are so big that they trigger a memory limit problem on their own?
Wow.

**Comment by LukasReschke** [comment]
> Are there really single jpegs that are so big that they trigger a memory limit problem on their own?
> Wow.

That's actually not that unlikely to have. Checkout http://www.dotsamazing.com/en/labs/phpmemorylimit

For example to resize a 8.6 Megabyte image with 3'000x3'000 pixels you need already 50MB. 256MB are like 7k*7k :see_no_evil: 
(or just a panorama photo, etc…)

**Comment by oparoz** [comment]
@karlitschek - You're right regarding parallel processing, I was thinking about batch processing and I've fixed the OP.
Regarding the size of JPEGs, I've updated [the wiki page](https://github.com/owncloud/gallery/wiki/Defining-the-PHP-memory_limit) with examples.
With any pic above 10MP you're taking your chances with 128MB of memory

**Comment by oparoz** [comment]
A workaround could be implemented in `core` to only process images we think we can process.
1. Get dimension and bit depth
2. Calculate memory requirements
3. Compare to `getMB(ini_get('memory_limit')) - 70

The problem is that this will be attempted every time a preview is requested since we can't blacklist a preview.

**Comment by karlitschek** [comment]
Hmm. Tricky.
Not processing an image if there is not enough memory sounds like the best option from a pure user point of view. Maybe better then a warning on the admin page that user ignore.
@jancborchardt What do you think?

**Comment by jancborchardt** [comment]
We should show something like »Preview can not be generated« if that’s the case. As feedback that the image exists, otherwise people might think their data is gone.

**Comment by jancborchardt** [comment]
But a warning on the admin page to optimize this should definitely be there as well.

**Comment by oparoz** [comment]
> We should show something like »Preview can not be generated« if that’s the case. As feedback that the image exists, otherwise people might think their data is gone.

We would rarely be able to show that message because the problem happens in files or photowall mode, where dozens of images are shown at once. The user would have no way of knowing of which images we're talking about, unless we start listing all the ones which failed, which could be the whole album/folder.

What will happen if we don't process large images is that the media type icon is going to be shown instead of a preview. We could show a single notification letting the user know that a problem was encountered, but that means adding a new kind of exception which needs to be forwarded to the client. I'm not sure we want to go this full-on.

I would expect users who see many default icons instead of previews to complain to their admin, who would know about the problem if we list it in the admin zone.

My only concern is the waste of resources, especially on devices with very little RAM. I expect the scanning of large images to slightly alter the fluidity of the rendering of the photowall, but it might be totally acceptable, except in case images are located on external storage (images will be downloaded over and over again).

**Comment by oparoz** [comment]
Added issues to core: 
- Don't process images if PHP can't handle it https://github.com/owncloud/core/issues/24045
- Add warning to admin section https://github.com/owncloud/core/issues/24046

**Comment by oparoz** [comment]
This issue was moved to nextcloud/gallery#140
