### ISSUE TITLE
[Slideshow/ImagePreview] The spinner(loading) never stops

### ISSUE THREAD

**Issue by imjalpreet** [owncloud/gallery#647]
### Steps to reproduce
1. Open Gallery App
2. Click on an image
### Expected behaviour

The Spinner should hide after the image is loaded
### Actual behaviour

The spinner never stops, even after the image is loaded.
### Server configuration

**Operating system**: Ubuntu 14.04

**Web server:** Apache/2.4.7

**Database:** mysql Ver 14.14 Distrib 5.6.28, for debian-linux-gnu (x86_64)

**PHP version:** PHP 5.5.9-1ubuntu4.14

**ownCloud version:** 9.1.0 pre alpha

**List of activated apps:**

```
Enabled:
  - comments: 0.3.0
  - dav: 0.2.4
  - federatedfilesharing: 0.2.0
  - federation: 0.1.0
  - files: 1.5.1
  - files_sharing: 0.10.0
  - files_versions: 1.3.0
  - gallery: 15.0.0
  - provisioning_api: 0.5.0
  - systemtags: 0.3.0
  - updatenotification: 0.2.0
Disabled:
  - encryption
  - files_external
  - files_trashbin
  - testing
  - user_ldap
```

**The content of config/config.php:**

```
{
    "system": {
        "instanceid": "oc4z46udfiog",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost:8080"
        ],
        "datadirectory": "\/var\/www\/GSoC\/data",
        "overwrite.cli.url": "http:\/\/localhost:8080",
        "dbtype": "mysql",
        "version": "9.1.0.1",
        "dbname": "ownCloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "mail_from_address": "jalpreet.cse",
        "mail_smtpmode": "smtp",
        "mail_domain": "gmail.com",
        "mail_smtpsecure": "ssl",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "smtp.gmail.com",
        "mail_smtpport": "465",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "loglevel": 0,
        "enabledPreviewProviders": [
            "OC\\Preview\\JPEG",
            "OC\\Preview\\PNG",
            "OC\\Preview\\GIF",
            "OC\\Preview\\Postscript",
            "OC\\Preview\\Font"
        ],
        "theme": "",
        "maintenance": false
    }
}
```

**Are you using external storage, if yes which one:** No

**Are you using encryption:** No

**Are you using custom gallery.cnf config files:** No
### Client configuration

**Browser:** Chrome 49.0.2623.75 (64-bit)

**Operating system:** Ubuntu 14.04

![issuespinner](https://cloud.githubusercontent.com/assets/6432146/15217640/1674eea2-187a-11e6-9f59-d5ec36f4950b.png)

**Comment by oparoz** [comment]
Thanks. That's an interesting side-effect of the new spinner. 
I did notice the problem before with tiny images, but classified it as minor since I wanted to update the sideshow engine anyway. 
We'll have to fix this for 9.1 since there won't be a new engine in that release.
