### ISSUE TITLE
Image removing straight from the slideshow or the gallery (delete button).

### ISSUE THREAD

**Issue by tempico** [owncloud/gallery#649]
## Feature request

**User type**: Logged-in user
### Description

Image removing straight from the slideshow or the gallery (delete button).
### Benefit / value

In case of 1000 party pics in one folder it will save time to remove unneeded stuff from gallery without switching to "files" view. In future "remove" functionality can be upgraded to "removing with multiple file selection" functionality.
### Risk / caveats

If pictures will be (re)moved to trash folder I do not expect any risk here.
### Sponsorship

I can donate $20-50, but this depends.

**Comment by oparoz** [comment]
It's a bit more complicated than I initially thought because we need to refresh the photowall as well...

## Design
- Add bin icon

## Code

On delete:
- move to bin
- load next slide
- remove image from slideshow array
- remove image from photowall cache
- set a flag which tells the photowall to refresh when slideshow ends

**Comment by tempico** [comment]
Maybe it is possible to take "files" functionality and just use bigger preview pictures? "Files" have selection/removing/sharing/moving/"file_wall_update_on_file_remove" functionality already.

**Comment by oparoz** [comment]
Unfortunately, it's not that simple, the photowall is built differently and has a different use case. I think at some point I'll add a select mode to the photowall allowing for easy selection for move and delete, but the first step will be to have a big bin onto which thumbnails can be dropped.
There is also a request to add the 3-dots menu on each thumbnail which should help.

**Comment by tempico** [comment]
> move and delete

and maybe "download as zip/tar" too? I saw good implementation of this function in AirDroid gallery.

**Comment by manishbisht** [comment]
I would like to work on this issue.
So when the delete function is called the following things will be done :
-Image will be moved to bin (to move image in the same bin which is used in the files)
-Load next slide
-Remove image from slideshow array
-Remove image from photowall cache

About the another addition "download as zip/tar"
When the multiple images are selected in the gallery a button showing "download as zip" can be shown near the sorting buttons.

**Comment by oparoz** [comment]
You can go ahead @manishbisht . Just focus on the delete button since multi-select is not available yet.

**Comment by tempico** [comment]
@manishbisht good, thank you!
What about single picture download button (like in gallery+)? Is it possible to implement this functionality too?

**Comment by oparoz** [comment]
> What about single picture download button (like in gallery+)? Is it possible to implement this functionality too?

That's already implemented.

**Comment by tempico** [comment]
@oparoz ,
Yes, you are right. I was confused a bit with "files slideshow" and "gallery slideshow". Sorry.

**Comment by manishbisht** [comment]
@oparoz I have just started working on this issue. About deleting the image I have found 2 ways.
1. Call the do_delete() function present in the file app to delete the image. But i am unable to call this function through gallery.
2. Next one is to get the node of the image using the get() function and passing the image path as its arguments. And at the end we can just call the node.delete() to delete the image.

But I am unable to call do_delete() function and get() function. How can I call those functions in Gallery Can you please help me out here.

**Comment by oparoz** [comment]
@manishbisht - You shouldn't call any method in the Files app if possible. Simply use the dav endpoint. You should already have everything you need to identify the image in the slideshow. If not, add it to the array for each slide.

**Comment by oparoz** [comment]
@tempico - If you agree with my proposal in https://github.com/owncloud/gallery/issues/649#issuecomment-218867622 and still intend on sponsoring the issue, please add a bounty via bountysource:

https://www.bountysource.com/issues/34174605-image-removing-straight-from-the-slideshow-or-the-gallery-delete-button

**Comment by manishbisht** [comment]
@oparoz  I am about to complete this issue.
- Image will be moved to bin (to move image in the same bin which is used in the files) [Completed]
- Load next slide [Completed]
- Remove image from slideshow array [Completed]
- Remove image from photowall cache (Gallery.imageMap array) [Completed]
- If the images in slideshow array is zero then exit the slideshow [Completed]

Now at the last I am unable to remove/hide the deleted images from the Gallery view without refresh.

**Comment by manishbisht** [comment]
@oparoz  I am about to complete this issue.

- Image will be moved to bin (to move image in the same bin which is used in the files) [Completed]
- Load next slide [Completed]
- Remove image from slideshow array [Completed]
- Remove image from photowall cache (Gallery.imageMap array) [Completed]
- If the images in slideshow array is zero then exit the slideshow [Completed]

Now at the last I am unable to remove/hide the deleted images from the Gallery view without refresh.

**Comment by oparoz** [comment]
> Now at the last I am unable to remove/hide the deleted images from the Gallery view without refresh.

@manishbisht - If I understand you correctly, there is no way around it. If you remove an image from the photowall, you will need to refresh the view in order to rebuild it.

Make sure you build a comprehensive test suite we can use, because we need to make sure that things don't break if users upload/move or switch album after having deleted images.

**Comment by manishbisht** [comment]
@oparoz How can I refresh the view without clicking on the reload button of the browser. Does Gallery.view.init() will work in this case.

**Comment by oparoz** [comment]
> How can I refresh the view without clicking on the reload button of the browser. Does Gallery.view.init() will work in this case.

@manishbisht - Yes, I think that's the way to do it. Also, make sure you've removed the thumbnail from `Thumbnails.map`.

**Comment by tempico** [comment]
@oparoz,
👍

**Comment by manishbisht** [comment]
@oparoz I have removed the thumbnail from thumbnail.map and then called the function Gallery
view.init(Gallery.current Album) but still unable to remove the deleted images from the gallery view. When I checked the init function then I get to know that I have to remove the image from the Gallery.albumMap Object also. Is this true ?

**Comment by oparoz** [comment]
Thanks for the bounty @tempico :)

**Comment by oparoz** [comment]
Current PR is at #676

**Comment by oparoz** [comment]
@tempico - Everything in #676 has been included in the latest version of Gallery+ which has just been released. That should make it easy for you to test. The icon still needs fixing.

**Comment by tempico** [comment]
@oparoz,
Yep, spinner is now working fine. Thanks!

**Comment by oparoz** [comment]
Thank you guys for making this happen. It's really useful after having dumped images from a mobile client.
