### ISSUE TITLE
Allowed memory size of 134217728 bytes exhausted

### ISSUE THREAD

**Issue by martin-hermann** [owncloud/gallery#65]
Gallery not working after uploading ~35GB of picture-files.
Not working means:
--> message: No pictures found! If you upload pictures in the files app, they will be displayed here.

owncloud version: 7.RC1
.htaccess-changes:
php_value upload_max_filesize 512M
php_value post_max_size 512M
php_value memory_limit 512M

php.ini changes:
memory_limit = 1024M

error-log:
Error 	PHP 	Allowed memory size of 134217728 bytes exhausted (tried to allocate 2182174 bytes) at ..../public_html/owncloud/apps/gallery/ajax/getimages.php#79 

Gallery is working with less than ~ 20GB of data.

**Comment by oparoz** [comment]
Should not be a problem any more with Gallery.
