### ISSUE TITLE
Sorting icons messed up

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/gallery#650]
This is what I see in 9.0.2:
![capture du 2016-05-14 08-12-47](https://cloud.githubusercontent.com/assets/925062/15266614/b96bf83a-19ab-11e6-9d1a-8f186b81d3ac.png)

cc @oparoz @owncloud/designers any idea here? Compression maybe … seems like they are layered over a second time, but upside down.

**Comment by jancborchardt** [comment]
Aaah I guess cause of the CSS/JS effect of the sorting icon switching up/down when changing? Not sure though. Only the arrow should change directions.

**Comment by oparoz** [comment]
I can't reproduce. Does it happen a 100% of the time?
It's probably due to a JS error which stops the execution of the script, so check the browser log.

**Comment by skjnldsv** [comment]
Can't reproduce either! What browser? i supposed you tried an ignore cache reload?

**Comment by tempico** [comment]
adblock?

**Comment by oparoz** [comment]
Closing since nobody can reproduce. Could be a problem with a specific browser version.
