### ISSUE TITLE
thumbnail+gallery not working on fresh install

### ISSUE THREAD

**Issue by sksbir** [owncloud/gallery#651]
Hi. 
Has I'm sure the only one to have this problem, I think it's a configuration problem.  apache and PHP are installed on defaults path too (coming with fedora23 distribution ) but not configured nor enabled.
My first aim is to get more info about the problem. httpd.conf in debug mode didn't gave me any clue.
### Steps to reproduce
1. Fresh manual installation of owncloud 8.2.4, has described here : https://doc.owncloud.org/server/8.2/admin_manual/installation/source_installation.html ( tried again with owncloud 9.0.2 : same )
2. Lauch installation wizard, and successfully access to my admin home page
3. take a look in newly installed "Photos" folder ( the one with 3 jpg inside : Paris, San Francisco, Squirrel )
### Expected behaviour

images should be shown has thumbnail in the file list and also be shown in the gallery view.
### Actual behaviour

thumbnail isn't shown (just the mimetype image icon) in the file list and the gallery view simply states error creating preview, removing it from preview
NO "thumbnail" folder created in Photo folder, even after browsing from explorer.
### Server configuration
- Fedora 23 X64
- Apache 2.4.20 , compiled on custom path ( /envperso/Apache_run )
- MariaDB : manual installation ( from mariadb-10.1.13-linux-glibc_214-x86_64.tar.gz ) on custom path ( /envperso/Mariadb/mysql )
- PHP 7.0.6, compiled on custom path ( /envperso/Php_run )
- owncloud : Tested with 8.2.4 and 9.0.2 , fresh install on /envperso/OC_docroot, /envperso/OC_data specified has data path in installation wizard.
- Activated app : the ones from fresh install.

**The content of config/config.php:**
{
    "system": {
        "instanceid": "ocl9a3aulmd2",
        "passwordsalt": "**_REMOVED SENSITIVE VALUE**_",
        "secret": "**_REMOVED SENSITIVE VALUE**_",
        "trusted_domains": [
            "192.168.22.31:8443"
        ],
        "datadirectory": "\/envperso\/OC_data",
        "overwrite.cli.url": "https:\/\/192.168.22.31:8443",
        "dbtype": "mysql",
        "version": "9.0.2.2",
        "dbname": "ownclouddb",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "**_REMOVED SENSITIVE VALUE**_",
        "dbpassword": "**_REMOVED SENSITIVE VALUE**_",
        "logtimezone": "UTC",
        "installed": true,
        "loglevel": 0
    }
}

**Are you using encryption:** no
**Are you using custom gallery.cnf config files:** no
#### ownCloud log (data/owncloud.log)

Debug   core    OC_Image->fixOrientation() Orientation: -1  2016-05-14T07:32:45+00:00
Debug   core    OC_Image->fixOrientation() Image is not a JPEG.     2016-05-14T07:32:45+00:00
Debug   core    OC_Image->loadFromFile, JPG images not supported: /envperso/OC_data/gips-admin/files/Photos/Paris.jpg   2016-05-14T07:32:45+00:00
Debug   core    Generating preview for "Photos/Paris.jpg" with "OC\Preview\JPEG"    2016-05-14T07:32:45+00:00
Debug   core    OC_Image->fixOrientation() Orientation: -1  2016-05-14T07:32:43+00:00
Debug   core    OC_Image->fixOrientation() Image is not a JPEG. 2016-05-14T07:32:43+00:00
Debug   core    OC_Image->loadFromFile, JPG images not supported: /envperso/OC_data/gips-admin/files/Photos/Squirrel.jpg    2016-05-14T07:32:43+00:00
Debug   core    Generating preview for "/Photos/Squirrel.jpg" with "OC\Preview\JPEG"    2016-05-14T07:32:43+00:00
Debug   core    OC_Image->fixOrientation() Orientation: -1  2016-05-14T07:32:42+00:00
Debug   core    OC_Image->fixOrientation() Image is not a JPEG. 2016-05-14T07:32:42+00:00
Debug   core    OC_Image->loadFromFile, JPG images not supported: /envperso/OC_data/gips-admin/files/Photos/Paris.jpg   2016-05-14T07:32:42+00:00
Debug   core    Generating preview for "/Photos/Paris.jpg" with "OC\Preview\JPEG"   2016-05-14T07:32:42+00:00
Debug   core    OC_Image->fixOrientation() Orientation: -1  2016-05-14T07:32:42+00:00
Debug   core    OC_Image->fixOrientation() Image is not a JPEG. 2016-05-14T07:32:42+00:00
Debug   core    OC_Image->loadFromFile, JPG images not supported: /envperso/OC_data/gips-admin/files/Photos/San Francisco.jpg   2016-05-14T07:32:42+00:00
Debug   core    Generating preview for "/Photos/San Francisco.jpg" with "OC\Preview\JPEG"   2016-05-14T07:32:42+00:00
### Client configuration
- Firefox 45.0.2 / window 7
- Native browser / android 5.1
### Apache modules from phpinfo:

core
mod_so
http_core
event
mod_authn_file
mod_authn_core
mod_authz_host
mod_authz_groupfile
mod_authz_user
mod_authz_core
mod_access_compat
mod_auth_basic
mod_reqtimeout
mod_filter
mod_mime
mod_log_config
mod_env
mod_headers
mod_setenvif
mod_version
mod_unixd
mod_status
mod_autoindex
mod_dir
mod_alias
mod_rewrite
mod_php7
mod_ssl
### PHP enabled modules from phpinfo:

ctype
curl
date
dom
fileinfo
filter
gd
hash
iconv
imagick ( v3.4.1 )
intl
json
libxml
mbstring
mcrypt
mysqlnd
openssl
pcre (v8.38 )
PDO
pdo_mysql
pdo_sqlite
Phar
posix
Reflection
session
SimpleXML
SPL
sqlite3
standard
tokenizer
xml
xmlreader
xmlwriter
zip
### httpd.conf :

```
ServerRoot "/envperso/Apache_run"
Listen 8000
LoadModule authn_file_module modules/mod_authn_file.so
LoadModule authn_core_module modules/mod_authn_core.so
LoadModule authz_host_module modules/mod_authz_host.so
LoadModule authz_groupfile_module modules/mod_authz_groupfile.so
LoadModule authz_user_module modules/mod_authz_user.so
LoadModule authz_core_module modules/mod_authz_core.so
LoadModule access_compat_module modules/mod_access_compat.so
LoadModule auth_basic_module modules/mod_auth_basic.so
LoadModule reqtimeout_module modules/mod_reqtimeout.so
LoadModule filter_module modules/mod_filter.so
LoadModule mime_module modules/mod_mime.so
LoadModule log_config_module modules/mod_log_config.so
LoadModule env_module modules/mod_env.so
LoadModule headers_module modules/mod_headers.so
LoadModule setenvif_module modules/mod_setenvif.so
LoadModule version_module modules/mod_version.so
LoadModule unixd_module modules/mod_unixd.so
LoadModule status_module modules/mod_status.so
LoadModule autoindex_module modules/mod_autoindex.so
LoadModule dir_module modules/mod_dir.so
LoadModule alias_module modules/mod_alias.so
LoadModule rewrite_module modules/mod_rewrite.so
LoadModule php7_module        modules/libphp7.so
<IfModule unixd_module>
User daemon
Group daemon
</IfModule>
ServerAdmin no@no.com
ServerName 192.168.22.31
<Directory />
    AllowOverride none
    Require all denied
</Directory>
DocumentRoot "/envperso/Apache_run/htdocs"
<Directory "/envperso/Apache_run/htdocs">
    Options Indexes FollowSymLinks
    AllowOverride None
    Require all granted
</Directory>
<IfModule dir_module>
    DirectoryIndex index.html
</IfModule>
<Files ".ht*">
    Require all denied
</Files>
ErrorLog "logs/error_log"
LogLevel warn
<IfModule log_config_module>
    LogFormat "%h %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-Agent}i\"" combined
    LogFormat "%h %l %u %t \"%r\" %>s %b" common
    <IfModule logio_module>
      # You need to enable mod_logio.c to use %I and %O
      LogFormat "%h %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-Agent}i\" %I %O" combinedio
    </IfModule>
    CustomLog "logs/access_log" common
</IfModule>
<IfModule alias_module>
    ScriptAlias /cgi-bin/ "/envperso/Apache_run//cgi-bin/"
</IfModule>
<IfModule cgid_module>
</IfModule>
<Directory "/envperso/Apache_run/cgi-bin">
    AllowOverride None
    Options None
    Require all granted
</Directory>
<IfModule mime_module>
    TypesConfig conf/mime.types
    AddType application/x-compress .Z
    AddType application/x-gzip .gz .tgz
</IfModule>
<IfModule proxy_html_module>
Include conf/extra/proxy-html.conf
</IfModule>
Include conf/owncloud/owncloud.conf
<IfModule ssl_module>
SSLRandomSeed startup builtin
SSLRandomSeed connect builtin
</IfModule>
<FilesMatch \.php$>
    SetHandler application/x-httpd-php
</FilesMatch>
```
### owncloud.conf

```
LoadModule ssl_module modules/mod_ssl.so
Listen 8443 https
Alias /owncloud "/envperso/OC_docroot/"
# Hote virtuel qui ecoute sur le port HTTPS 8443
<VirtualHost *:8443>
DocumentRoot "/envperso/OC_docroot"
# Activation du mode SSL
SSLEngine On
SSLOptions +FakeBasicAuth +ExportCertData +StrictRequire
# On indique ou est le certificat
SSLCertificateFile /envperso/Apache_run/conf/owncloud/owncloud.crt
SSLCertificateKeyFile /envperso/Apache_run/conf/owncloud/owncloud.key
Header always set Strict-Transport-Security "max-age=15768000; includeSubDomains; preload"
<Directory "/envperso/OC_docroot">
    Options +FollowSymLinks
    AllowOverride All
        <IfModule mod_dav.c>
          Dav off
         </IfModule>
setenv HOME /envperso/OC_docroot
setenv HTTP_HOME /envperso/OC_docroot
    Require all granted
    Satisfy Any
</Directory>
</VirtualHost>

```

**Comment by oparoz** [comment]
Sounds like a problem with missing libraries. Check the result of `phpinfo()` under GD. It should list JPEG as a supported format.

**Comment by sksbir** [comment]
@oparoz : You point it out !  Problem is now solved for thumbnails : 
- added '--with-jpeg-dir=/usr/lib64' \ to my config.nice from php installation folder
- compiled php again ( with mandatory "make clean")
- restarted apache

Usefull link : http://stackoverflow.com/questions/7167860/compiling-php-with-gd-and-libjpeg-support

A little suggestion : has png thumbnail works without libjpeg (tested before recompiling), what about insert a png file in "Photo" folder ( I mean .. in default owncloud distribution and installation ) ? People would have a more obvious clue when problem like mine occurs...

Out of that, gallery ( I mean the full page slideshow, not the photo collection ) still not works, it still  shows simply states error creating preview, removing it from preview.
No log in owncloud.log, even in "full" mode....

Should I create an other issue ? ( has we can state now that source of the problem is not the same... )

**Comment by sksbir** [comment]
Everything is working well now. Slideshow was just blocked by uBlock Origin on my browser.
The first thumbnail error let me though there was also a server error here.
Thanks again for your reply.

**Comment by oparoz** [comment]
Ah, good news :)
