### ISSUE TITLE
Cannot browse into the images of the skeleton files

### ISSUE THREAD

**Issue by davitol** [owncloud/gallery#659]
### Steps to reproduce
1. Go to Gallery Menu
2. Click on the collage of the skeleton files images
### Expected behaviour

It should be possible to browse into the pictures
### Actual behaviour

Clicking on the photos nothing is shown

Note: If we upload another photo to the server. It is possible to browse into every image.
### Server configuration

**Operating system**:
Ubuntu 14.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:"9.1.0.3","versionstring":"9.1.0 pre alpha","edition":"Enterprise"

**Updated from an older ownCloud or fresh install:**
Fresh

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** 
No

**Logs**

No logs are shown in owncloud.log file
### Client configuration

**browser**

 Firefox

![galleryblank](https://cloud.githubusercontent.com/assets/10596560/15577960/dc05eace-235e-11e6-8a60-83044cb64975.gif)

@oparoz

**Comment by oparoz** [comment]
Thanks. There must be an error reported in the browser, no? Also, what does the message say at the top?

**Comment by davitol** [comment]
@oparoz No error reported in the browser console.
The message at the top is not related to this issue. It is a warning message related to code integrity check

**Comment by hitam4450** [comment]
I do have a similar problem: browsing e.g. SofortUpload no images are shown, only placeholder!
(see attached screen shot)

![gallery1](https://cloud.githubusercontent.com/assets/9738727/15738586/529aae8e-28ac-11e6-8217-fc1f3c1fab51.png)
Regrads, hitam4450

**Comment by oparoz** [comment]
@hitam4450 - That's using 9.1 and JPG images?

**Comment by hitam4450** [comment]
I use 9.0.2 and jpg........ the same happens in files...view ......
Gallery 14.5.0

**Comment by hitam4450** [comment]
If I click on an image file the following error message pops up:

![gallery2](https://cloud.githubusercontent.com/assets/9738727/15744741/1a8d09ca-28ce-11e6-9b4d-44757cc059d7.png)

**Comment by oparoz** [comment]
@hitam4450 - OK, so please open your own issue as it's likely to be unrelated to this issue. The logs should tell you what's wrong.

**Comment by hitam4450** [comment]
OK, thanks for info!

**Comment by oparoz** [comment]
@davitol - Which package did you install for your "ownCloud version 9.1.0.3"? I'm asking because master only contains a txt file.

**Comment by oparoz** [comment]
Never mind, I was able to reproduce. The server sends back information about the image, but the frontend doesn't process it.

**Comment by oparoz** [comment]
Not a Gallery bug, see: https://github.com/owncloud/core/issues/25152

**Comment by oparoz** [comment]
I'm going to implement a change anyway since things may change in the future and etags may stop being unique.
