### ISSUE TITLE
Can't view image file (jpg) in files view and in gallery

### ISSUE THREAD

**Issue by hitam4450** [owncloud/gallery#661]
### Steps to reproduce
1. Upload Image files to OC 
2. View image files in gallery
   1.
### Expected behaviour

Should see the image
### Actual behaviour

Only see placeholder (see enclosed screen shot)
### Server configuration

**Operating system**:
Debian 8.3 Jessie
**Web server:**
lighttpd 1.4.35
**Database:**

**PHP version:**
5.6
**ownCloud version:** (see ownCloud admin page or version.php)
9.0.2
**Updated from an older ownCloud or fresh install:**
new install
**List of activated apps:**

**The content of config/config.php:**

**Are you using external storage, if yes which one:** local folder, smb share, sftp, etc.

**Are you using encryption:** yes/no

**Are you using custom gallery.cnf config files:** yes/no
### Client configuration

**Browser:**

**Operating system:**
## Feature request

**User type**: Logged-in or public user

**User level**: Beginners, intermediate or advanced
### Sponsorship

**Are you a developer willing to implement this feature?**: yes/no

**Can you sponsor the development of this feature or do you know somewone who can?**: yes

The enclosed screen-shot gives sample view

![gallery1](https://cloud.githubusercontent.com/assets/9738727/15749496/ef493c24-28e2-11e6-9762-81cd5bb9cf11.png)

Clicking on image file in files view results in the following error message:
![gallery2](https://cloud.githubusercontent.com/assets/9738727/15749495/ef480390-28e2-11e6-82fe-65309f4cae14.png)

**Comment by oparoz** [comment]
Please paste your logs, your images are not found and it's probably not related to Gallery.

**Comment by hitam4450** [comment]
What kind of logs should I post ???

**Comment by oparoz** [comment]
The end of your owncloud.log after you get the error.

**Comment by hitam4450** [comment]
tail owncloud.log results:
{"reqId":"SoGtCPngDO2EEQVpS8ez","remoteAddr":"192.168.175.60","app":"core","message":"OC_Image->fixOrientation() Orientation: -1","level":0,"time":"2016-06-06T13:29:26+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/gallery\/thumbnails?ids=713%3B716%3B720%3B724%3B728%3B732&scale=0.800000011920929&square=0&requesttoken=Ly4JVl8lBh0mNCQ%2FGTxyVjdZQmUkOFl%2BcCw4Lz0EBDE%3D%3AgVxb1iShAYOHQYD3drw0NZnKCzbZYl7g8ggwRk2ewxo%3D","user":"dirk"}
{"reqId":"SoGtCPngDO2EEQVpS8ez","remoteAddr":"192.168.175.60","app":"core","message":"Generating preview for \"SofortUpload\/20151114_003918.jpg\" with \"OC\Preview\JPEG\"","level":0,"time":"2016-06-06T13:29:26+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/gallery\/thumbnails?ids=713%3B716%3B720%3B724%3B728%3B732&scale=0.800000011920929&square=0&requesttoken=Ly4JVl8lBh0mNCQ%2FGTxyVjdZQmUkOFl%2BcCw4Lz0EBDE%3D%3AgVxb1iShAYOHQYD3drw0NZnKCzbZYl7g8ggwRk2ewxo%3D","user":"dirk"}
{"reqId":"SoGtCPngDO2EEQVpS8ez","remoteAddr":"192.168.175.60","app":"core","message":"OC_Image->fixOrientation() Image is not a JPEG.","level":0,"time":"2016-06-06T13:29:26+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/gallery\/thumbnails?ids=713%3B716%3B720%3B724%3B728%3B732&scale=0.800000011920929&square=0&requesttoken=Ly4JVl8lBh0mNCQ%2FGTxyVjdZQmUkOFl%2BcCw4Lz0EBDE%3D%3AgVxb1iShAYOHQYD3drw0NZnKCzbZYl7g8ggwRk2ewxo%3D","user":"dirk"}
{"reqId":"SoGtCPngDO2EEQVpS8ez","remoteAddr":"192.168.175.60","app":"core","message":"OC_Image->fixOrientation() Orientation: -1","level":0,"time":"2016-06-06T13:29:26+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/gallery\/thumbnails?ids=713%3B716%3B720%3B724%3B728%3B732&scale=0.800000011920929&square=0&requesttoken=Ly4JVl8lBh0mNCQ%2FGTxyVjdZQmUkOFl%2BcCw4Lz0EBDE%3D%3AgVxb1iShAYOHQYD3drw0NZnKCzbZYl7g8ggwRk2ewxo%3D","user":"dirk"}
{"reqId":"SoGtCPngDO2EEQVpS8ez","remoteAddr":"192.168.175.60","app":"core","message":"Generating preview for \"SofortUpload\/20151114_003918(0).jpg\" with \"OC\Preview\JPEG\"","level":0,"time":"2016-06-06T13:29:26+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/gallery\/thumbnails?ids=713%3B716%3B720%3B724%3B728%3B732&scale=0.800000011920929&square=0&requesttoken=Ly4JVl8lBh0mNCQ%2FGTxyVjdZQmUkOFl%2BcCw4Lz0EBDE%3D%3AgVxb1iShAYOHQYD3drw0NZnKCzbZYl7g8ggwRk2ewxo%3D","user":"dirk"}
{"reqId":"SoGtCPngDO2EEQVpS8ez","remoteAddr":"192.168.175.60","app":"core","message":"OC_Image->fixOrientation() Image is not a JPEG.","level":0,"time":"2016-06-06T13:29:26+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/gallery\/thumbnails?ids=713%3B716%3B720%3B724%3B728%3B732&scale=0.800000011920929&square=0&requesttoken=Ly4JVl8lBh0mNCQ%2FGTxyVjdZQmUkOFl%2BcCw4Lz0EBDE%3D%3AgVxb1iShAYOHQYD3drw0NZnKCzbZYl7g8ggwRk2ewxo%3D","user":"dirk"}
{"reqId":"SoGtCPngDO2EEQVpS8ez","remoteAddr":"192.168.175.60","app":"core","message":"OC_Image->fixOrientation() Orientation: -1","level":0,"time":"2016-06-06T13:29:26+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/gallery\/thumbnails?ids=713%3B716%3B720%3B724%3B728%3B732&scale=0.800000011920929&square=0&requesttoken=Ly4JVl8lBh0mNCQ%2FGTxyVjdZQmUkOFl%2BcCw4Lz0EBDE%3D%3AgVxb1iShAYOHQYD3drw0NZnKCzbZYl7g8ggwRk2ewxo%3D","user":"dirk"}
{"reqId":"SoGtCPngDO2EEQVpS8ez","remoteAddr":"192.168.175.60","app":"core","message":"Generating preview for \"SofortUpload\/20151114_003919.jpg\" with \"OC\Preview\JPEG\"","level":0,"time":"2016-06-06T13:29:26+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/gallery\/thumbnails?ids=713%3B716%3B720%3B724%3B728%3B732&scale=0.800000011920929&square=0&requesttoken=Ly4JVl8lBh0mNCQ%2FGTxyVjdZQmUkOFl%2BcCw4Lz0EBDE%3D%3AgVxb1iShAYOHQYD3drw0NZnKCzbZYl7g8ggwRk2ewxo%3D","user":"dirk"}
{"reqId":"SoGtCPngDO2EEQVpS8ez","remoteAddr":"192.168.175.60","app":"core","message":"OC_Image->fixOrientation() Image is not a JPEG.","level":0,"time":"2016-06-06T13:29:26+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/gallery\/thumbnails?ids=713%3B716%3B720%3B724%3B728%3B732&scale=0.800000011920929&square=0&requesttoken=Ly4JVl8lBh0mNCQ%2FGTxyVjdZQmUkOFl%2BcCw4Lz0EBDE%3D%3AgVxb1iShAYOHQYD3drw0NZnKCzbZYl7g8ggwRk2ewxo%3D","user":"dirk"}
{"reqId":"SoGtCPngDO2EEQVpS8ez","remoteAddr":"192.168.175.60","app":"core","message":"OC_Image->fixOrientation() Orientation: -1","level":0,"time":"2016-06-06T13:29:26+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/gallery\/thumbnails?ids=713%3B716%3B720%3B724%3B728%3B732&scale=0.800000011920929&square=0&requesttoken=Ly4JVl8lBh0mNCQ%2FGTxyVjdZQmUkOFl%2BcCw4Lz0EBDE%3D%3AgVxb1iShAYOHQYD3drw0NZnKCzbZYl7g8ggwRk2ewxo%3D","user":"dirk"}

**Comment by oparoz** [comment]
Thank you. This is a problem in core which may have been fixed on 9.0.3. I'll wait for you to update to confirm.

**Comment by hitam4450** [comment]
What kind of problem it is in core ?? When 9.0.3 will be available ? Hotfix available??

**Comment by oparoz** [comment]
The fix I was thinking about was merged in 9.0.2, but there is an issue in core which is probably describing the problem you're having:

https://github.com/owncloud/core/issues/20762

Your problem could simply be that PHP is running out of memory.
