### ISSUE TITLE
Not able to switch to gallery+ in (sub)folder with no pictures

### ISSUE THREAD

**Issue by deMattin** [owncloud/gallery#67]
It's a great feature to switch to gallery+ from file view in subfolders and start preview there.
I have noticed, that if you are in a folder where no pictures are in but subfolders with pictures, the switching button is disabled.

I think, it would be better, not to disable this switchbutton.
So you will be able to use every subfolder as a startpoint for gallery+.

**Comment by oparoz** [comment]
Yes, I did notice that behaviour when having a root folder with no pictures per example, but thought it was OK as the menu item "Gallery+" would let the user go there anyway, but that doesn't work for your case.

I don't think there is a way to know what's in the sub-folders without looking, so there are 2 solutions :
1. Always keep the Gallery view button in the UI, but that means that in some cases, you will end up in an empty gallery, if there are no pictures in sub-folders. Maybe @jancborchardt and his team knows what's best here. Maybe having a consistent UI is best and users wouldn't be surprised by the behaviour I've just described. _Very light development work_
2. Query the server to see if there are pictures in the sub-folders. That's an extra request at every folder change. Does it matter? Are there too many already? _Medium development work_

**Comment by deMattin** [comment]
I think,  it would really be the best, to **never** remove the switch and I see no disadvantages:
1. it is consistent
2. if you switch and there are no pictures in this or subfolders, you get a clear message
3. if pictures are in subfolders you get gallery+ working from this point in folder structure
4. no performance issues or performance disadvantages at all

**Comment by oparoz** [comment]
I agree, but the contextual button is an old feature from the original Gallery project, so I'd love to get some feedback from people who've been involved with the project from the start.

**Comment by deMattin** [comment]
I think, the old gallery didn't have this issue.
Isn't there the folder preview saved as a separate file?
But it's also possible, I mix it with the gallery enhancement of libasys (OC 7) which was on a good way but he doesn't continue to work on as it seams to me.

**Comment by oparoz** [comment]
It's right here: https://github.com/owncloud/gallery/blob/master/js/public.js#L9 :)

I hope libasys hasn't given up and that' he'll contribute some of his frontend enhancements

**Comment by oparoz** [comment]
I'm going to always enable it and see if people complain ;)

**Comment by oparoz** [comment]
It's in

**Comment by deMattin** [comment]
I like it very much!
The possibility to start gallery in any folder without pictures (but possibly with pictures in subfolders) is very helpfull.
And I see no bugs or disadvantages.

And with a "backlink" #76 in empty pages it would be perfect ... :wink:
