### ISSUE TITLE
Picture browser double-advance in 7.0.0

### ISSUE THREAD

**Issue by alerque** [owncloud/gallery#67]
Using the picture browser in 7.0.0 in Chrome appears to cause some sort of double event trigger. Since clicking on the picture causes it to advance and the "next" arrow is overlayed on the picture, clicking the next arrow causes the picture to flash by the next one and advance 2 instead of just 1.

(Previously mistakenly [submitted to core issue tracker](https://github.com/owncloud/core/issues/9795)).

**Comment by oparoz** [comment]
Not reproducible on the next Gallery, so closing.
