### ISSUE TITLE
Add a share button (and other actions like delete, rename) to the large preview [$5]

### ISSUE THREAD

**Issue by oparoz** [owncloud/gallery#68]
We already have download, maybe it would be useful to have a "share" button there as well?
Clicking on it would reveal the usual dropdown and let people share that one picture via the usual means.

It's something I've seen on other slideshows, but I have no idea if this is really needed or if people would rather share the entire folder like it is now.
### Next steps
- [ ] Share button
- [ ] A sidebar ~~https://github.com/owncloud/gallery/issues/548~~ #549 
- [ ] Import sharing view from `core`

There is a [share API](https://doc.owncloud.org/server/8.0/developer_manual/core/ocs-share-api.html), but using it in this app just means re-inventing the wheel, so we should use whatever is used in `core` and theme it
##

**Comment by deMattin** [comment]
It could be usefull in some (rare) situations - but normally I share single files from file app.
You tagged for user experience? I don't need this!
But it won't annoy me, if it would be there.

**Comment by oparoz** [comment]
It's all about making the life of users easier. You're in full screen mode and you see something you want to share, you don't want to have to quit the slideshow, go to Files, find the file and click share.

**Comment by jancborchardt** [comment]
Yes – all actions which are available in the files list should also be available in the detail view. However (as I think I said in another issue as well) instead of bulky buttons up top, as nice grey text+icons on the bottom center. :)

**Comment by jancborchardt** [comment]
Moving the actions from up top to a proper place is prerequisite for this: https://github.com/owncloud/gallery/issues/349

Also to fix the confusion: https://github.com/owncloud/gallery/issues/474

**Comment by jospoortvliet** [comment]
Add commenting! for 9.0 ;-)

**Comment by jancborchardt** [comment]
@jospoortvliet different issue ;) https://github.com/owncloud/gallery/issues/176

**Comment by oparoz** [comment]
Once we have a sidebar, we should be able to use the `core` share dialogue
https://github.com/owncloud/core/blob/master/core/js/sharedialogview.js

and get rid of our old share.js

**Comment by oparoz** [comment]
This issue was moved to nextcloud/gallery#20
