### ISSUE TITLE
Galley apps can't be accessed from "link share" page

### ISSUE THREAD

**Issue by schiessle** [owncloud/gallery#683]
originally reported here https://github.com/nextcloud/server/issues/256 by @Sesivany
If you come to the conclusion that this is a Nextcloud server bug, feel free to re-open the server issue
### Steps to reproduce
1. Share a folder with pictures via link
2. Open the link in another browser
3. Click the gallery view icon
### Expected behaviour

Users I share the folder with via link should be able to view is as a picture gallery and view individual pictures without having to download them.
### Actual behaviour

If the share link is created from within Gallery or Gallery+ apps it doesn't load at all and goes to "internal server error" page. If the link is created from Files the user I shared it with can open the link and see the folder, but if they want to switch to the gallery view, it goes to the "internal server error" page, too. Individual pictures need to be downloaded to view them.
### Server configuration

**Operating system**:
Fedora 24, 64 bit

**Web server:**
Apache 2.4.18

**Database:**
MariaDB 10.1.14

**PHP version:**
php-5.6.22

**Nextcloud version:** (see Nextcloud admin page)
9.0.51

**Updated from an older Nextcloud/ownCloud or fresh install:**
Fresh install

**Where did you install Nextcloud from:**
Zip file from nextcloud.com

**Signing status (Nextcloud 9.0 and above):**
No errors have been found.

**List of activated apps:**
Enabled:
- activity: 2.2.1
- admin_audit: 1.0.0
- comments: 0.2
- contacts: 1.3.1.0
- dav: 0.1.6
- documents: 0.12.0
- federatedfilesharing: 0.1.0
- federation: 0.0.4
- files: 1.4.4
- files_pdfviewer: 0.8.1
- files_sharing: 0.9.1
- files_texteditor: 2.1
- files_trashbin: 0.8.0
- files_versions: 1.2.0
- files_videoplayer: 0.9.8
- firstrunwizard: 1.1
- gallery: 14.5.0
- news: 8.8.0
- notifications: 0.2.3
- provisioning_api: 0.4.1
- systemtags: 0.2
- templateeditor: 0.1
- updatenotification: 0.1.0

**The content of config/config.php:**
{
    "system": {
        "instanceid": "oc8dql9cs9ex",
        "passwordsalt": "**_REMOVED SENSITIVE VALUE**_",
        "secret": "**_REMOVED SENSITIVE VALUE**_",
        "trusted_domains": [
            "**_REMOVEDIP**_",
            "**_REMOVEDDOMAIN**_"
        ],
        "datadirectory": "\/var\/www\/html\/nextcloud\/data",
        "overwrite.cli.url": "http:\/\/**_REMOVEDIP**_\/nextcloud",
        "dbtype": "mysql",
        "version": "9.0.51.0",
        "dbname": "nextcloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "**_REMOVED SENSITIVE VALUE**_",
        "dbpassword": "**_REMOVED SENSITIVE VALUE**_",
        "logtimezone": "UTC",
        "installed": true,
        "mail_from_address": "admin",
        "mail_smtpmode": "php",
        "mail_domain": "**_REMOVEDDOMAIN**_",
        "memcache.local": "\OC\Memcache\APCu",
        "loglevel": 0,
        "enable_previews": "true",
        "asset-pipeline.enabled": true
    }
}

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** yes/no
No

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No
### Client configuration

**Browser:**
Any browser (Firefox, Chrome, Epiphany)

**Operating system:**
Tested on Fedora and Android
#### Web server error log

For Gallery+ app:
Exception: {"Exception":"OCP\AppFramework\QueryException","Message":"Could not resolve UserId! Class UserId does not exist","Code":0,"Trace":"#0 \/var\/www\/html\/nextcloud\/lib\/private\/appframework\/utility\/simplecontainer.php(104): OC\AppFramework\Utility\SimpleContainer->resolve('UserId')\n#1 \/var\/www\/html\/nextcloud\/lib\/private\/appframework\/utility\/simplecontainer.php(150): OC\AppFramework\Utility\SimpleContainer->query('UserId')\n#2 [internal function]: OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility{closure}(Object(OC\AppFramework\DependencyInjection\DIContainer))\n#3 \/var\/www\/html\/nextcloud\/lib\/private\/appframework\/utility\/simplecontainer.php(102): Pimple\Container->offsetGet('userId')\n#4 \/var\/www\/html\/nextcloud\/lib\/private\/appframework\/utility\/simplecontainer.php(64): OC\AppFramework\Utility\SimpleContainer->query('userId')\n#5 \/var\/www\/html\/nextcloud\/lib\/private\/appframework\/utility\/simplecontainer.php(83): OC\AppFramework\Utility\SimpleContainer->buildClass(Object(ReflectionClass))\n#6 \/var\/www\/html\/nextcloud\/lib\/private\/appframework\/utility\/simplecontainer.php(104): OC\AppFramework\Utility\SimpleContainer->resolve('OCA\GalleryPlus...')\n#7 \/var\/www\/html\/nextcloud\/lib\/private\/appframework\/utility\/simplecontainer.php(64): OC\AppFramework\Utility\SimpleContainer->query('OCA\GalleryPlus...')\n#8 \/var\/www\/html\/nextcloud\/lib\/private\/appframework\/utility\/simplecontainer.php(83): OC\AppFramework\Utility\SimpleContainer->buildClass(Object(ReflectionClass))\n#9 \/var\/www\/html\/nextcloud\/lib\/private\/appframework\/utility\/simplecontainer.php(104): OC\AppFramework\Utility\SimpleContainer->resolve('OCA\GalleryPlus...')\n#10 \/var\/www\/html\/nextcloud\/lib\/private\/appframework\/app.php(97): OC\AppFramework\Utility\SimpleContainer->query('OCA\GalleryPlus...')\n#11 \/var\/www\/html\/nextcloud\/lib\/private\/appframework\/routing\/routeactionhandler.php(45): OC\AppFramework\App::main('PageController', 'publicIndex', Object(OC\AppFramework\DependencyInjection\DIContainer), Array)\n#12 [internal function]: OC\AppFramework\routing\RouteActionHandler->_invoke(Array)\n#13 \/var\/www\/html\/nextcloud\/lib\/private\/route\/router.php(276): calluser_func(Object(OC\AppFramework\routing\RouteActionHandler), Array)\n#14 \/var\/www\/html\/nextcloud\/lib\/base.php(950): OC\Route\Router->match('\/apps\/gallerypl...')\n#15 \/var\/www\/html\/nextcloud\/index.php(39): OC::handleRequest()\n#16 {main}","File":"\/var\/www\/html\/nextcloud\/lib\/private\/appframework\/utility\/simplecontainer.php","Line":89}

For Gallery app:
Exception:
{"Exception":"OCP\AppFramework\QueryException","Message":"Could not
resolve UserId! Class UserId does not exist","Code":0,"Trace":"#0
\/var\/www\/html\/nextcloud\/lib\/private\/appframework\/utility\/simplecontainer.php(104):
OC\AppFramework\Utility\SimpleContainer->resolve('UserId')\n#1
\/var\/www\/html\/nextcloud\/lib\/private\/appframework\/utility\/simplecontainer.php(150):
OC\AppFramework\Utility\SimpleContainer->query('UserId')\n#2
[internal function]:
OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility{closure}(Object(OC\AppFramework\DependencyInjection\DIContainer))\n#3

\/var\/www\/html\/nextcloud\/lib\/private\/appframework\/utility\/simplecontainer.php(102):
Pimple\Container->offsetGet('userId')\n#4
\/var\/www\/html\/nextcloud\/lib\/private\/appframework\/utility\/simplecontainer.php(64):
OC\AppFramework\Utility\SimpleContainer->query('userId')\n#5
\/var\/www\/html\/nextcloud\/lib\/private\/appframework\/utility\/simplecontainer.php(83):

OC\AppFramework\Utility\SimpleContainer->buildClass(Object(ReflectionClass))\n#6

\/var\/www\/html\/nextcloud\/lib\/private\/appframework\/utility\/simplecontainer.php(104):

OC\AppFramework\Utility\SimpleContainer->resolve('OCA\Gallery\Env...')\n#7

\/var\/www\/html\/nextcloud\/lib\/private\/appframework\/utility\/simplecontainer.php(64):

OC\AppFramework\Utility\SimpleContainer->query('OCA\Gallery\Env...')\n#8

\/var\/www\/html\/nextcloud\/lib\/private\/appframework\/utility\/simplecontainer.php(83):

OC\AppFramework\Utility\SimpleContainer->buildClass(Object(ReflectionClass))\n#9

\/var\/www\/html\/nextcloud\/lib\/private\/appframework\/utility\/simplecontainer.php(104):

OC\AppFramework\Utility\SimpleContainer->resolve('OCA\Gallery\Con...')\n#10
\/var\/www\/html\/nextcloud\/lib\/private\/appframework\/app.php(97):
OC\AppFramework\Utility\SimpleContainer->query('OCA\Gallery\Con...')\n#11

\/var\/www\/html\/nextcloud\/lib\/private\/appframework\/routing\/routeactionhandler.php(45):
OC\AppFramework\App::main('PageController', 'publicIndex',
Object(OC\AppFramework\DependencyInjection\DIContainer), Array)\n#12
[internal function]:
OC\AppFramework\routing\RouteActionHandler->__invoke(Array)\n#13
\/var\/www\/html\/nextcloud\/lib\/private\/route\/router.php(276):
call_user_func(Object(OC\AppFramework\routing\RouteActionHandler),
Array)\n#14 \/var\/www\/html\/nextcloud\/lib\/base.php(950):
OC\Route\Router->match('\/apps\/gallery\/s...')\n#15
\/var\/www\/html\/nextcloud\/index.php(39): OC::handleRequest()\n#16
{main}","File":"\/var\/www\/html\/nextcloud\/lib\/private\/appframework\/utility\/simplecontainer.php","Line":89}
#### Nextcloud log (data/owncloud.log)

Same error messages as in server error log.
#### Browser log

This is probably relevant:
Content Security Policy: Page settings blocked loading source on self ("script-src https://**_REMOVEDDOMAIN**_ 'unsafe-eval'").

**Comment by oparoz** [comment]
Thanks for the report. I can't reproduce on ownCloud and since it's been experienced by several people on Nextcloud only, I really suspect this is due to a change in the server.

I'll keep this open until we can figure out the root of the problem.

**Comment by oparoz** [comment]
Could not reproduce.

**Comment by alexstocker** [comment]
Hi @oparoz 
Well I think I can reproduce this Isssue and it's exactly like described above.

### Steps to reproduce
1. Share a folder with pictures via link
2. Open the link in another browser
3. Click the gallery view icon
.... ec.

### Debug Log
{"reqId":"xxxxxxxxx","level":0,"time":"2018-04-13T19:52:46+00:00","remoteAddr":"xxx.xxx.xxx.xxx","user":"--","app":"no app in context","method":"GET","url":"\/index.php\/apps\/gallery\/s\/Nr***************oq","message":"App is not enabled"}

OC Version: 10.0.4.4
Gallery Version: 16.0.2
Files Version: 1.5.1
Files Sharing Version: 0.10.1

I'm oberserving this problem sind OC Version 9.x. I did a lot of research on this issue but I could not solve it, so I decided that it's not bothering me longer - untill now.

Any ideas where to go for further investigation appreciated

Thanx
Alex
