### ISSUE TITLE
Add download button to slideshow preview

### ISSUE THREAD

**Issue by PVince81** [owncloud/gallery#686]
From https://github.com/owncloud/core/issues/25333

@jonesints

**Comment by jonesints** [comment]
Summarizing the above: 

The 'download' option in fullscreen preview only appears when navigating inside the Gallery. For photos being previewed outside the Gallery there isn't an option to download the current previewed file.

**Comment by oparoz** [comment]
Yes, this was intentional, but in the end, I think people prefer to be able to download straight from the slideshow.

**Comment by oparoz** [comment]
This issue was moved to nextcloud/gallery#143
