### ISSUE TITLE
Remove IE<11 support

### ISSUE THREAD

**Issue by manishbisht** [owncloud/gallery#693]
### Description

As OC9+ doesn's support IE<11 anymore. So now we can also remove support for IE<11 from the gallery.
https://github.com/owncloud/core/pull/25240

**Are you a developer willing to implement this feature?**: yes

**Comment by oparoz** [comment]
You can go ahead and remove all the PNGs, thank you :)

**Comment by manishbisht** [comment]
@oparoz The test function `public function getPreviewOfPng()` in getPreviewCest.php is of no use after removing PNG files.
Also the if condition should be removed from the `_getMimeIcon()` function in thumbnail.js

I think these are the only 2 changes we have to do apart from removing the PNG images.

**Comment by oparoz** [comment]
> The test function public function getPreviewOfPng() in getPreviewCest.php is of no use after removing PNG files

That's incorrect. Gallery still displays previews of PNG files even though it doesn't use PNG icons.

> Also the if condition should be removed from the _getMimeIcon() function in thumbnail.js

That's correct

> I think these are the only 2 changes we have to do apart from removing the PNG images.

There is more, per example:
https://github.com/owncloud/gallery/blob/5a33e86e568d267239d1982f38e7d113717f595f/js/slideshow.js#L56

Have another look to see if there aren't any other exceptions.

**Comment by manishbisht** [comment]
Then there are three things which I able to find.
1. if condition should be removed from the _getMimeIcon() function in thumbnail.js to remove png option in gallery view
2. https://github.com/owncloud/gallery/blob/5a33e86e568d267239d1982f38e7d113717f595f/js/slideshow.js#L56 if condition should be removed to remove png support from slideshow.
3.  Remove getPreviewOfPng() in getPreviewCest.php to remove the PNG test case.

**Comment by oparoz** [comment]
I don't understand the difference between 1) and 3)

**Comment by manishbisht** [comment]
Sorry updated the third point.
The test that I have mentioned in third point is used for icons or it is used for png images. I have no experience in testing.

**Comment by oparoz** [comment]
OK, but I've just said that getPreviewOfPng() should **not** be removed ;)

**Comment by manishbisht** [comment]
Ok I will be implementing 1) and 2) and submitted the PR in next half an hour.

**Comment by oparoz** [comment]
Thank you :)

**Comment by oparoz** [comment]
This issue was moved to nextcloud/gallery#144
