### ISSUE TITLE
Timeline view

### ISSUE THREAD

**Issue by spoorun** [owncloud/gallery#697]
A timeline view to be available alongside the existing view types.
In time line view, photos are ordered by EXIF metadata (#221), if that is missing they are sorted by created date, and then modified date.
The User see photos in chronological order, most recent at the top.
There is a slider bar which the user can move slowly to move between days, more quickly to move between months, and on continued moving can move between years.
As is available in most modern photo gallery viewing applications.

**Comment by oparoz** [comment]
Could you add the content of this post as a comment to https://github.com/owncloud/gallery/issues/95 ? This is the same request, just more detailed.

**Comment by oparoz** [comment]
This issue was moved to nextcloud/gallery#56
