### ISSUE TITLE
Location filter

### ISSUE THREAD

**Issue by spoorun** [owncloud/gallery#698]
In the lefthand panel, user can choose to filter by location (from EXIF data #221 ).

Upon clicking that, the left-hand panel opens up, and User can see a list of applicable Countries to filter photos upon. 
Upon clicking a country name, User can see applicable regions. 
Upon clicking a region name, User can see applicable districts.
The view will work in tandem with other view modes such as Tags, Folders, and Timeline views.

**Comment by oparoz** [comment]
Thanks for the user story :)

**Comment by oparoz** [comment]
Added to https://github.com/owncloud/gallery/issues/531

**Comment by oparoz** [comment]
This issue was moved to nextcloud/gallery#55
