### ISSUE TITLE
Gallery not longer working after upgrade to OC 9.1 when application files_move is enabled

### ISSUE THREAD

**Issue by TDannhauer** [owncloud/gallery#699]
### Steps to reproduce
1. Install OC 9.0.4
2. Upgrae to 9.1
3. Activate files_move app  <-- Important, since this is the showstopper
4. Log into OC
5. Activate Gallery app.
### Expected behaviour

Gallery should show up, load the thumbnails and display them.
Clicking on the "file view" icon in the upper right corner switches back to file view.
### Actual behaviour

Browser Title changes to Gallery.
No photos are shown. T
In the upper right corner the icon for switching back to file view appears, but is dead (No function on clicking on it.)
Switching back to file view is only possible via the main app selector in the upper left corner.

Firebug reveals an error in the console:

In OCA.Files.fileActions.register() it throws "TypeError: OCA.Files.fileActions is undefined"
### Server configuration

Debian Jessie 64 Bit

Apache 2.4.10

PostgresSQL 9.4

PHP-FPM 5.6.23 via mod_proxy_fcgi

Owncloud 9.1.15, Upgraded from 9.0.4

**List of activated apps:**
Enabled:
- activity: 2.3.2
- comments: 0.3.0
- dav: 0.2.5
- federatedfilesharing: 0.3.0
- federation: 0.1.0
- files: 1.5.1
- files_external: 0.6.0
- files_mv: 0.8.2
- files_pdfviewer: 0.8.1
- files_sharing: 0.10.0
- files_texteditor: 2.1
- files_trashbin: 0.9.0
- files_versions: 1.3.0
- files_videoplayer: 0.9.8
- firstrunwizard: 1.1
- gallery: 15.0.0
- notifications: 0.3.0
- systemtags: 0.3.0
- templateeditor: 0.1
- updatenotification: 0.2.1
  Disabled:
- encryption
- external
- files_antivirus
- provisioning_api
- user_external
- user_ldap

**The content of config/config.php:**
 php occ config:list system
{
    "system": {
        "instanceid": "oc87896c1670",
        "passwordsalt": "**_REMOVED SENSITIVE VALUE**_",
        "trusted_domains": {
            "1": "owncloud.dannhauer.de",
            "2": "owncloud.dannhauer.info"
        },
        "datadirectory": "\/extradata\/owncloud",
        "dbtype": "pgsql",
        "version": "9.1.0.15",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "**_REMOVED SENSITIVE VALUE**_",
        "dbpassword": "**_REMOVED SENSITIVE VALUE**_",
        "installed": true,
        "forcessl": true,
        "loglevel": 3,
        "mail_smtpmode": "smtp",
        "mail_from_address": "owncloud",
        "mail_domain": "dannhauer.de",
        "mail_smtphost": "smtp.dannhauer.de",
        "mail_smtpport": "587",
        "mail_smtpname": "**_REMOVED SENSITIVE VALUE**_",
        "mail_smtppassword": "**_REMOVED SENSITIVE VALUE**_",
        "mail_smtpauth": 1,
        "mail_smtpauthtype": "PLAIN",
        "theme": "",
        "maintenance": false,
        "secret": "**_REMOVED SENSITIVE VALUE**_",
        "redis": {
            "host": "localhost",
            "port": 6379,
            "timeout": 0,
            "dbindex": 0
        },
        "memcache.local": "\OC\Memcache\Redis",
        "overwritehost": "owncloud.dannhauer.de",
        "overwriteprotocol": "https",
        "overwritewebroot": "\/",
        "mail_smtpsecure": "tls",
        "trashbin_retention_obligation": "auto",
        "appstore.experimental.enabled": true
    }
}

**Are you using external storage, if yes which one:** local folder, smb share, sftp, etc.
No

**Are you using encryption:** yes/no
No

**Are you using custom gallery.cnf config files:** yes/no
No
#### Web server error log

throws no logs.
#### ownCloud log (data/owncloud.log)

{"reqId":"eyerNEvLLeCKI40+xfXD","remoteAddr":"193.171.63.202","app":"PHP","message":"Zend OPcache can't be temporary enabled (it may be only disabled till the end of request) at Unknown#0","level":3,"time":"2016-07-25T09:00:46+00:00","method":"PROPFIND","url":"\/remote.php\/webdav\/","user":"torben"}
### Client configuration

**Browser:**
Up to Date firefox

**Operating system:**
Win8.1 64bit
#### Browser log

TypeError: OCA.Files.fileActions is undefined
https://owncloud.dannhauer.de/apps/files_mv/js/move.js?v=cc39ea15799207dbdb5b9c99402eadbf
Line 29

**Comment by oparoz** [comment]
That app is unmaintained and pollutes all apps by loading its scripts everywhere.
I have provided a patch there:
https://github.com/eotryx/oc_files_mv/pull/29
