### ISSUE TITLE
show filenames in slideshow and gallery

### ISSUE THREAD

**Issue by walross01** [owncloud/gallery#70]
Browsing the gallery or slideshow my visitors and I would like to know the filenames of the shown pictures. Maybe it could be solved in the same way as the foldernames are displayed.

**Comment by oparoz** [comment]
Gallery+ shows the filename when you roll over a thumbnail.

Sharing is a [feature request](https://github.com/interfasys/galleryplus/issues/68)

**Comment by jospoortvliet** [comment]
So, let's close this then as 'fixed in gallery successor' and 'duplicate' ;-)
