### ISSUE TITLE
not work on ownCloud 9.1.0.15

### ISSUE THREAD

**Issue by hansen0730** [owncloud/gallery#701]
### Steps to reproduce

1.
1.
1.
### Server configuration

**Operating system**:

**Web server:**

**Database:**

**PHP version:**

**cloud server:** Nextcloud or ownCloud

**cloud version:** (see admin page or version.php)

**Updated from an older installation or fresh install:**

**List of activated apps:**

<details>
<summary>

App list</summary>

```
Paste the list of applications here
```

</details>

**The content of config/config.php:**

<details>
<summary>

Config report</summary>

```
Paste the config here
```

</details>

**Are you using external storage, if yes which one:** local folder, smb share, sftp, etc.

**Are you using encryption:** yes/no

**Are you using custom gallery.cnf config files:** yes/no
#### Web server error log

<details>
<summary>

Web server error log</summary>

```
Insert your webserver log here
```

</details>
#### Cloud log

<details>
<summary>

Cloud log</summary>

```
Insert your cloud log here
```

</details>
### Client configuration

**Browser:**

**Operating system:**
#### Browser log

<details>
<summary>

Browser log</summary>

```
Insert your browser log here
```

</details>
## Feature request

**User type**: Logged-in or public user

**User level**: Beginners, intermediate or advanced
### Sponsorship

**Are you a developer willing to implement this feature?**: yes/no

**Can you sponsor the development of this feature or do you know someone who can?**: yes/no

**Comment by gildebrand-** [comment]
I have the same problem was. After the application Files Move (0.8.2) is shut down  - Gallery is worked .

**Comment by LuffyyyffuL** [comment]
The same, thank you gildebrand.
