### ISSUE TITLE
Isn't this app still maintained here? :)

### ISSUE THREAD

**Issue by benjaoming** [owncloud/gallery#710]
There are newer releases in this repo than the nextcloud -- if it's the case that it's still maintained here, there's a statement at the top of the README that should be removed.

**Comment by DeepDiver1975** [comment]
this app is unmaintained as stated in the readme - in case you are interested to help out - feel free 😉

**Comment by benjaoming** [comment]
This app had several new releases on Oct 25, while the one that's referred to had a release on Sep 21.

So once again, is the comment in the README not precise or what's the deal?

**Comment by oparoz** [comment]
Apps are packaged at different times on different distributions. It's not that important. What matters are the commits. And for now they're roughly the same.

**Comment by benjaoming** [comment]
So the state of things: Two repos with "_roughly_" the same commits, where the one with the most recent changes claims you shouldn't use it with giant letters on the cover page. I think it sounds like a decision is needed but I'm new here, just voicing my confusion :)

Thanks for the app, nonetheless!
