### ISSUE TITLE
Share Folder on version 10

### ISSUE THREAD

**Issue by alahwany** [owncloud/gallery#731]
Hello,

i am a new user with owncloud version 10

i have installed it on shared hosting and everything working fine but when share folder to public with or without password not working the link and still asked for authentication !!!!

my server using cpanel and softaculous and i have installed it from softaculous
my server using CENTOS 7.4 with last version for cpanel 

is there any solution to make share folders ?

thank you very much

**Comment by alahwany** [comment]
![capture](https://user-images.githubusercontent.com/14204438/32023281-0adf3c62-b9d9-11e7-9016-4570170b1caf.JPG)

**Comment by PVince81** [comment]
@alahwany I suggest you ask on http://central.owncloud.org/.

The problem is likely an environment problem. Make sure to specify the exact ownCloud version (10.0.2, 10.0.3, ...)

**Comment by alahwany** [comment]
version 10.0.3

if there php function must be enabled can you tell me the name of it and i will request for open

**Comment by PVince81** [comment]
@alahwany I can't help you here as I don't know the answer. This is a bug tracker, not a support platform. Please ask on platform where people can help with environment setup.

**Comment by alahwany** [comment]
@PVince81  thank you for your reply and i will try to ask on http://central.owncloud.org/.
