### ISSUE TITLE
Pictures show up all on one line or cut off

### ISSUE THREAD

**Issue by escservices** [owncloud/gallery#74]
My problem is when someone views the shared gallery. And when they view the gallery and click on a picture before all the pictures have loaded then close the slideshow/lightbox all the pictures are gone from the page you then would have to refresh and they would reload. Sometimes when you close the slideshow they don't all disappear they all show up on one line but cut off. Screenshot below there should be an img after the one on the end.

![image](https://cloud.githubusercontent.com/assets/1287511/3775176/f6ad3378-193d-11e4-8744-fb7031df049a.png)

Should be like this 

![image](https://cloud.githubusercontent.com/assets/1287511/3775180/0b1e0472-193e-11e4-9e7e-cf300976dacc.png)

When I first open a large shared gallery
![image](https://cloud.githubusercontent.com/assets/1287511/3775215/5a48e214-193f-11e4-8fe3-e72b12553030.png)

After closing slideshow
![image](https://cloud.githubusercontent.com/assets/1287511/3775213/417de360-193f-11e4-95ea-af20704eee9f.png)

```
Undefined index: itemSourceName at /misc/34/339/800/330/2/user/web/theescservice.com/core/ajax/share.php#44
```
I'm on OC version 7.0.0 stable
PHP ver 5.4
MySQL

I'm also using a remote hosing service.

My Config File

```
<?php
$CONFIG = array (
  'instanceid' => 'oc25578b2e93',
  'passwordsalt' => '******************',
  'trusted_domains' => 
  array (
    0 => 'theescservice.com',
  ),
  'datadirectory' => '/misc/34/339/800/330/2/user/web/theescservice.com/data',
  'dbtype' => 'mysql',
  'version' => '7.0.0.8',
  'installed' => true,
  'mail_from_address' => 'mike',
  'mail_smtpmode' => 'php',
  'mail_domain' => 'escservices.net',
  'mail_smtpname' => 'escservices',
  'mail_smtppassword' => '************',
  'loglevel' => '2',
  'dbname' => '****************',
  'dbhost' => 'sql3.bravehost.com',
  'dbtableprefix' => 'oc_',
  'dbuser' => '***************',
  'dbpassword' => '**************',
);
```

The dev console only showed one thing for the most part.
` The code on this page disabled back and forward caching.`

**Comment by oparoz** [comment]
The OP's problem is not reproducible on the next Gallery, so closing.
