### ISSUE TITLE
On the Gallery page, uploading the same file with a completely different prompt box, choosing to keep the new and old files, the Continue button is not available.

### ISSUE THREAD

**Issue by supermanlinux** [owncloud/gallery#740]
### Steps to reproduce
1.Open the Gallery application and upload an image.
2.Upload the same image file again, a dialog box will pop up for file differences.
3.Choose to keep new files and old files, click the Continue button below does not reflect.
![12](https://user-images.githubusercontent.com/34739130/36142811-1f4a12c8-10e4-11e8-8162-aa8a41ada728.png)

### Expected behaviour
Click the continue button upload same files, as the list of files upload difference file.
### Actual behaviour
The continue button can't click, can't upload the same files.
### Server configuration

**Database:**10.0.31-MariaDB-0ubuntu0.16.04.2 Ubuntu 16.04
**PHP version:**PHP 7.0.22
**ownCloud version:10.0.6.1
**Where did you install ownCloud from:owncloud-10.0.6.tar.bz2

**Comment by supermanlinux** [comment]
@SergioBertolinSG  I have no ideas,what happened,the log is noting help me.Thanks.

**Comment by PVince81** [comment]
need to verify the JS code that wires up the gallery upload code with the conflict dialog

@supermanlinux did you check the browser console for Javascript errors ?

**Comment by supermanlinux** [comment]
Yes,I check the browser console for Javascript errors.The error is:file-upload.js? Uncaught TypeError: this.fileList.inList is not a function,then I replace the fileList  with findFile,then it can upload conflict pictures,but other problem is occuered.First,the progress bar is always blinking.Second，when I upload two pictures,one is not conflict picture,it can upload,but you must refresh the page first,then you can see the two pictures.You can have a try.I have no ideas to solve this problem.Ohhhh...
![13](https://user-images.githubusercontent.com/34739130/36143627-960781d2-10e6-11e8-8ec1-866e3c3c2bc1.png)

**Comment by supermanlinux** [comment]
@PVince81 Can you give me some ideas?Thanks.

**Comment by PVince81** [comment]
after your change to `findFile` do you see new errors in the console ?

**Comment by superstoraged** [comment]
@PVince81 No errors in the console after I change to findFile,but when I upload many pictures include conflict pictures,some problems occured,one is the progress bar is always blinking,the other is you must refresh the page,then you can see the conflict picture you upload...

**Comment by windoyblank** [comment]
@PVince81 I have a same question.

**Comment by PVince81** [comment]
This will likely need more extensive JS code debugging but I don't have time to this myself right now

**Comment by supermanlinux** [comment]
@oparoz @phil-davis Can you give me some ideas to solve this problem?Thanks.

**Comment by oparoz** [comment]
@supermanlinux - I no longer maintain this version of gallery.

**Comment by supermanlinux** [comment]
@PVince81 Any chance this will get fixed? I think it's a big bug  for users to used.Thanks.

**Comment by phil-davis** [comment]
When I try a Gallery upload that would overwrite an existing file, having current core stable10, and gallery either from latest master or gallery stable10, I get no conflict dialog at all. Just a 412 on the server:
```
[Tue Mar 27 18:24:45 2018] 127.0.0.1:45996 [412]: /remote.php/webdav/a.jpg
```
and nothing in owncloud.log
The upload progess bar flashes for a second, so it does try :)
The existing file stays in place on the server. The upload overwrite "silently fails".

**Comment by jvillafanez** [comment]
https://github.com/owncloud/gallery/pull/753 should fix the problem. Checked with OC 10.0.7 and firefox. It might need more testing.

**Comment by jvillafanez** [comment]
> but when I upload many pictures include conflict pictures,some problems occured,one is the progress bar is always blinking,the other is you must refresh the page,then you can see the conflict picture you upload...

Progress bar blinks are caused by multiple uploads attempts for the duplicated files trying to upload the file with an available name. This is a problem related to core (or so it seems), so nothing to do here.

The need for the refresh is caused by a buggy behaviour in the gallery, because it assumes that the refresh is needed when a specific file is uploaded (the last one), but due to conflicts, the file that was supposed to be the last upload isn't the last upload, but one of the files with conflicts is. As a consequence, the refresh is done before all the files are effectively uploaded to the server.
This is something to be fixed in the gallery app.

**Comment by phil-davis** [comment]
I quickly tried uploading a png file over the top of a existing png file, using core stable10 and this gallery branch. A popup comes saying "Error loading file exists template".

So something is amiss here. I don't have priority right now to play more...
