### ISSUE TITLE
Make all thumbnails quadratical

### ISSUE THREAD

**Issue by stefan-niedermann** [owncloud/gallery#75]
Hey Guys, what do you think about this:

Some time ago i extracted the algorithm, that is used by wordpress to generate thumbnails.

We could make all thumbnails quadratical, so the design would be much more streamlined. we would have everytime a perfect grid, doesn't metter which dimensions the pictures have. clicking on it could still show the original photos with original dimensions.

This also would simplify #52 imho, because the folders for itself could be quadratical just like the pictures in it. Look at the screenshot of the gnome tool, too. the thumbnails in the folder are quadratical.

**Comment by oparoz** [comment]
Closing since this has been implemented.
