### ISSUE TITLE
Folder navigation missing, if message "no picture" is shown [$5]

### ISSUE THREAD

**Issue by deMattin** [owncloud/gallery#76]
The fix #73 shows an issue with navigation in case, the "No picture" message is shown.
The path navigation of OC isn't shown any more and you are only able to go back with browser navigation or switch the app in OC app menu.

File view (only filled with mp3):
![image](https://cloud.githubusercontent.com/assets/5565503/6547421/d304516c-c5d7-11e4-9a3f-0b8a99ba57a6.png)

Folder switched to gallery+ (only filled with mp3)::
![image](https://cloud.githubusercontent.com/assets/5565503/6547419/b51fb740-c5d7-11e4-83ad-11a313511400.png)

This is, how it should look like:
![image](https://cloud.githubusercontent.com/assets/5565503/6547701/0e6ee1ba-c5e0-11e4-8704-6cad75cd6182.png)
##

**Comment by oparoz** [comment]
I was also surprised the first time I saw that, but decided to keep it like this, because there can be many reasons for this message to show up and the easiest way out of here is to just reload the app.

I'm using the original showEmpty() function when the initial request fails and I think that was designed for the root folder since the gallery button on the files view was supposed to only be available when there where pictures in that folder.

I'm happy to make modifications, as long as we can cover all use cases.
Per example, if we show the breadcrumb but it isn't working and we can't easily detect that case, then it will be less confusing to just let the user start from the beginning.
It might also not be easy to do it before other changes are put in place.

Here is an example of things which are difficult to detect: Is the folder empty or did the user paste a link with a typo in it or even a path which doesn't exist?

**Comment by deMattin** [comment]
hmm - I understand.

You are right - in case of root folder it makes sense to show this message as it is without path. Because in this case no path exists - there's only the "virtual" picture folder or lets say "mountpoint" for picture view.

The showEmpty function has to be enhanced for this to detect, if the message is caused by switching in a valid and existing folder.
The actual path remains in browser so OC "knows" where it actually is and that it isn't a call in app root.
Wouldn't a simple file app call on the path be sufficent to validate the existence of the path and to decide to show the path?

**Comment by oparoz** [comment]
The backend tries to open the given path, but it doesn't know what it is. Is it a folder? Is it a file? If it doesn't work, should we check the parent? What is the parent? etc.
I plan on implementing that later https://github.com/interfasys/galleryplus/issues/44
Once that's in place, we should be able to be more flexible.
The path in the browser means nothing as we can't assume it's valid and when switching app the whole page is reloaded, so there is no persistence. I could introduce an extra parameter to indicate a switch and the breadcrumb could trust that I guess

**Comment by oparoz** [comment]
I've played with it a bit and it's not going to be an easy fix because the breadcrumb function gets confused and would need to be rewritten.

I can get the Files button to show, but it looks ugly, so best to maybe add a large button after the message to go back to the start of the gallery and maybe the files button next to it, to go back...

**Comment by deMattin** [comment]
Not a button to go back to start of gallery but a back button to "browse back" (browser history) to the previous page would make sense, I think.
Wherever you came from to this page, it has to be avalid page.

The issue, that there is no previous page if you typed the link in browser directly, can be unattended.

How do you feel about this?

**Comment by oparoz** [comment]
I've tested with the browser navigation and it works, so it might be possible to implement if someone designs the page.

**Comment by deMattin** [comment]
Later I will have a look at it and try to find a look, that integrates well and uses themeable css-style.
Are you looking for html or php code to inject in the "no picture found" page or a separate page?

**Comment by oparoz** [comment]
HTML and CSS and a few screenshots on here so that designers can voice their opinion

**Comment by deMattin** [comment]
As I have to "hardcode", I have a simple solution with inserting following code behind the message:

``` javascript
<br/>
<br/>
<a href="javascript:history.back()">
    <img src="../../../core/img/actions/history.svg" width="60" height="60" alt="history back">
</a>
```

It looks like this:
![image](https://cloud.githubusercontent.com/assets/5565503/6582817/2f7fcb4a-c760-11e4-9908-7688c7d92bfa.png)

The advantage of this solution would be, that the symbol should be known by everybody as the "back" or "revert" symbol and you don't need to read something or to add a translation.

As an enhancement, it would be nice, if the "history"-symbol would get the color style (here: light grey) of the message text. But I don't know how to achieve that.

**Edit:**
History back has another advantage I actually see in context with #67:
If you have switched from file navigation to gallery+ and get "no message", you go back with the backbutton to file view.
NICE!! :smile:

**Comment by oparoz** [comment]
OK, so to me, that doesn't look like a "back" button, but more like a refresh button... That's why I want to get designers involved.
I'd also use real buttons, with borders and maybe have 2. One to go back to where you came from and one to go to the root of the gallery.
@jancborchardt, we need some help :)

Regarding colour, we can play with opacity. No problem there.

**Comment by deMattin** [comment]
Refresh or redo is nearly the same button but other way round.
But I'm surely no designer or GUI expert. So, a more unmistakeable symbol is needed... HELP! ;)
(though this is the "history" named button in owncloud core ;))

And "real" buttons are not only a matter of taste.
It should be clear, that this buttons are not previews of gallery and that these buttons are not pictures in this folder.

As long as starting gallery root lasts very long if you have many folders in account, I generally don't recommend a gallery root button at all.

But even if gallery root folder starts loading in 1-2 seconds independend of the account size (what  should be the far goal), I don't await a gallery root button here.
This "no pictures" page only appears in more or less rare cases:
1. most common: You have switched from file navigator to check there or in deeper folders for pictures. In my opinion you certainly don't want to go to gallery root afterwards if this "fails". Or better to say: it gives you the information, that there is not picture in this or subfolder (I like this new feature very much!)
2. possible but not likely: You have followed a deep link or typed it manually. Then you probably would like to check a folder above in gallery or go to file navigator in the called folder, which both is not so easy to implement as you said. This case the file navigator (root) even could be a better link than the gallery root if you only could start a link to a root folder. But user knows where these buttons are to be found ... ;)
3. If there is a use case I don't figure, the menu button is 1 click away with user decision, wether gallery or file navigation from root folder is more appropiate.
4. If you get this message on a shared link there has to be no button at all - only the message should appear..
5. With "normal" gallery navigation this message window should or could never appear and I couldn't imagine another use case or workflow to wish to go to gallery root if the message appears.

Have I missed something?

**Comment by oparoz** [comment]
Yeh, so let's wait for some designs, because I'm sure we'll get many more comments if we break things than if we leaver them as is ;)

Regarding the speed of loading the root of the gallery, going there after the app has loaded is going to be faster than opening the app by clicking on the icon. That's because the app is already loaded. It's even faster if you enable asset-pipelining.
And then, let's say you have a 1920x1080 desktop and the view is filled with albums. That's 50 albums. Let's say that there is an average of 3 pictures per album, that's a total of 150 200x200 thumbnails to download. This is going to take time, no matter how crazy fast people can make Gallery+ go. You can give a feeling of speed by showing an empty gallery which is populated as thumbnails are received. That way users can starts navigating within seconds, but you won't see a nice photowall until all thumbnails are received.

Regarding your use cases, the best thing to do is to conduct some usability surveys by observing people. You can be surprised sometimes :D.
It's quite common to be able to go back to the start of the app. It's like on a website. You can always go back to "home".
Having an extra Files icon there could also improve the user experience, but there needs to be something on the interface. That makes it look less broken than having nothing and leaving the user scrambling about what to do next.

**Comment by deMattin** [comment]
Ok - everybody might have another workflow. I tried to catch the "usual" procedures.
To me any solution would be ok, as long as there is a big "back" Button anyhow ... :wink: 

Comment on speed:
That loading the preview icons lasts a while is no problem as you can see a progress.
But in gallery root it lasts long til the gallery+ root path arises. And this is every time you start with gallery+ icon in menu. I see a caching of previews but no speedup of this step, if you visit this page again.
I think of the step from this:
![image](https://cloud.githubusercontent.com/assets/5565503/6623464/7c75c60a-c8e3-11e4-9639-2edb34ae45d6.png)
to that:
![image](https://cloud.githubusercontent.com/assets/5565503/6623474/84d48124-c8e3-11e4-91f8-600462bb6dd0.png)
If I remember right, this is the step, where gallery+ scans all folders (in memory?).
But it's now again much faster as before - it speeded up from 20 seconds to 6 seconds now - I don't know, which patch it has been. A time ago it even lasted 60 seconds. I don't think, this has something to do with already generated previews.

**Comment by oparoz** [comment]
I'm glad you've detailed the use cases. That will give useful information to UX designers.
In my head, I see 3 large buttons with an icon and some text in each. I'm sure there are good examples of 404 out there which could be used as inspiration.

As for the loading, check your browser debugger. I'm sure you'll find it takes the same time to load the Files and Gallery app: 5s, then 1s to build the map and a few seconds to download the thumbnails (from your browser's cache)
So, if you want to reduce that initial 5s, use asset pipelining, if that works on your setup.

**Comment by deMattin** [comment]
"asset pipelining" ... ?!?!
Have to look, what that is and where I'm able to "activate" this.

The following call (root gallery) lasts the longest - nearly all the time of the complete task:

> https://domain/owncloud/index.php/apps/galleryplus/images?currentfolder=

It consists of much js-calls and this call is much faster (1-2 s) in any subfolder in my account but also there this is the most time consuming call
But I have to say, I don't understand very much of the timings in browser debug/timing.

My Server isn't the fastest one (HP N54L with a AMD Turion(tm) II Neo N54L Dual-Core Processor with 2.2 GHz).
My personal boundary value for "usability" of root gallery call has been at max 10 seconds to wait for something to appear - but the faster, the better! :smile:

**Comment by oparoz** [comment]
All the js calls you're seeing is ownCloud getting ready. I've added a little note about asset pipelining in the readme. It should always be used on production servers, once apps have been verified to be compatible.

**Comment by deMattin** [comment]
Hmm - there's a link to a short description in manual  - sounds easy:
https://doc.owncloud.org/server/8.0/admin_manual/configuration_server/js_css_asset_management_configuration.html

I crated a folder "assets" in webservers root owned by webserver.
And then I tried to activate it.
But how to really enable it in config/config.php?

This (as described in manual) doesn't work - only a blank screen if you call owncloud:

``` php
<?php
  'asset-pipeline.enabled' => true,
$CONFIG = array (
  ...
```

This works - but I don't recognize speed improvement and no files created by owncloud:

``` php
<?php

$CONFIG = array (
  'asset-pipeline.enabled' => true,
  ...
```

**EDIT:**
What a faulty description!!!
Would be better to describe the following in readme and not the link to the wrong description in manual:

The folder has to be created in owncloud folder (/owncloud/assets) and not in root of webserver!
And this is the correct config.php setting:

``` php
<?php

$CONFIG = array (
  'asset-pipeline.enabled' => true,
  ...
```

One last question to this "off topic":
Does this packed css and js actualize on it's own or do you have to delete them to be newly generated if you changed something?
(BTW: I see no great speedup in LAN, maybe it's faster, if you visit over Internet...)

**Comment by oparoz** [comment]
:S I gave a link to the official doc because I thought it would be safer than trying to explain it myself... Need to fix the doc...

**Comment by deMattin** [comment]
The link to the doc should stay there but with a remark, that this is actually faulty!

**Edit:**
I opened an issue on github to correct this.

**Edit2:**
Got the answer about updating the assets on changes:

> It will detect changes automatically.

**Comment by oparoz** [comment]
The official doc will be updated tonight, so it should make things easier when I release 2.0.6

**Comment by deMattin** [comment]
I see - now anything with installation of asset-pipelining should be clear.
But to make it perfect, there should or could be also the hint, that the cached assets actualize automatically if css or js changes. I missed to mention this in your last pull request.

**Comment by oparoz** [comment]
It's there, look closely ;)
https://github.com/owncloud/documentation/blob/master/admin_manual/configuration_server/js_css_asset_management_configuration.rst

**Comment by deMattin** [comment]
Sorry ... :sunglasses: .

**Comment by deMattin** [comment]
Again off topic: ...
I have a question regarding asset-pipelining cache.
I updated gallery+ and I don't get the asset cache automatically updated.
Clearing browser cache doesn't help..
I have to clear the corresponding assets or clear them all on server to get actual version of js and css code.

Am I missing something?

**Comment by oparoz** [comment]
If it's not working as expected, then you should open an issue in `core`. It could be that it only updates when an app changes version, but then it would mean that the feature is incomplete as people can track apps via git.
Try to change the version number in Gallery+ and do a refresh to see if you get the new code.
I forgot to update the number in 2.0.6, but I'll release 2.0.7 soon.

**Comment by deMattin** [comment]
Looks like it only uses (relative) pathes and version of the app.

> https://github.com/owncloud/core/blob/master/lib/private/templatelayout.php

It also should use file (css/js) modification date to hash and check the asset.
I will have a closer look at this this evening ...

**Comment by deMattin** [comment]
I opened an issue in OC core: https://github.com/owncloud/core/issues/14937
It should be an easy task, I think and I hope, someone does it ... :wink:

**Comment by oparoz** [comment]
Thanks. I guess one could argue that pipeling should only be enabled on productions servers and on those you would only install releases as opposed to tracking a git branch.

**Comment by oparoz** [comment]
So now there is a breadcrumb. All we're missing is some large buttons by @jancborchardt and his team to help redirect the user.

![empty_folder](https://cloud.githubusercontent.com/assets/323220/8522938/a0867714-23f2-11e5-8012-b3d6d4dc9090.png)

**Comment by oparoz** [comment]
Can be tested by using `ultimate8` on core `stable8`

@setnes @demattin @jancborchardt 

If we can't get a design in quickly, I'll split the task in 2. We have the navigation, as asked in the OP and a better landing page can be designed later.

**Comment by oparoz** [comment]
Now available on `ultimatedev` for core `stable8.1`

**Comment by deMattin** [comment]
I tested it on ultimate8 by switching from files to gallery view in a folder without pictures and it works like expected:
Browser history back goes back to file view, file app switch is there and working and you have the possibility to use breadcromp to go on navigating in gallery.

All in all I'm not missing a back button in the middle of the screen!
The explicit back button won't bother me, but I don't think, it's really needed.
Now it behaves like the files app, where also is no back button in an empty folder and I think, it's ok and consistent like it is with only showing the message.

**Comment by oparoz** [comment]
Thanks. I agree that if it behaves like the Files app, then it's good enough. Both apps can be modified in parallel  if users ever complain that they're lost when reaching an empty folder.
