### ISSUE TITLE
Improvement of getimages.php

### ISSUE THREAD

**Issue by mmattel** [owncloud/gallery#76]
@icewind1991 @karlitschek 

This is a suggestion to improve getimages.php (or whatever is necessary to make the overall process better)

Right now, when a new storage is added, a list of files is added in the database and a mimetype to each file is assigned. Based on the mimetype 'image', thumbnails are created, but only for those image files owncloud can support right now. eg a thumbnail for .tiff files (even from mimetype image) is not supported and therefore not created.

Right now, getimmages.php queries for mimes=image and gets a list of all files from mime type image independent if a thumbnail was created or not. But this ends up, when trying to display unsupported images = non present thumbs, that errors are trown and logged (please see #43 Path 'thumbnails/xxxxx' is not readable). As this can end up an many unnecessary and confusing log entries, I please for improvement of the handling.

I took a look into the code, but my php knowledge is by for not where it must be to do the necessary changes.

Just brainstorming around,
the best would be to have the reference list of processable thumbs stored in the database, eg as a additional tag to the filelist queried right now. This would btw open new opportunities for other mimes too eg:
give me all files from mimetype xxxx
give me all files from mimetype xxxx where flag owncloud_processable=true
Thinking of music files, video, office, whatever...

This would be from the query side a extension of searchByMime and of course a small change in the database including a update of the corresponding routines which need to maintain this new database flag. But if "maintaining" routines will not be changed, nothing changes and will not disturb current functionality, means soft transition to new functionalities...

**Comment by oparoz** [comment]
Implemented in Gallery+
