### ISSUE TITLE
release contains tests

### ISSUE THREAD

**Issue by butonic** [owncloud/gallery#778]
double check if the build script properly kill the tests, eg `owncloud/apps/gallery/vendor/symfony/yaml/Tests/DumperTest.php` seems to be in

**Comment by patrickjahns** [comment]
This is in the vendor folder and we shall not touch the vendor folder in that regard - upstream bug

**Comment by patrickjahns** [comment]
@butonic 
checking https://github.com/owncloud/gallery/blob/master/composer.json - there shouldn't be even a vendor folder included in any release. Fixed with 16.1.0
