### ISSUE TITLE
Move CI from Travis to drone

### ISSUE THREAD

**Issue by phil-davis** [owncloud/gallery#790]

**Comment by DeepDiver1975** [comment]
No idea if we shall invest time in here. There will soon be a new gallery ....

**Comment by phil-davis** [comment]
This is not being scheduled in current QA sprint. So we can decide on care factor after other CI moves are done first. CC: @patrickjahns

**Comment by patrickjahns** [comment]
We shall bootstrap drone only on the new app as soon as development starts

**Comment by paurakhsharma** [comment]
@phil-davis , We should close this?

**Comment by phil-davis** [comment]
"soon" is a flexible deadline for a new gallery app.
IMO switching from Travis to Drone should be easy - we should "just do it" to remove the pain of having "old" Travis CI apps "hanging around".

Other opinions welcome.

**Comment by PVince81** [comment]
if it doesn't take too long (max 1 day) then let's just do it

**Comment by phil-davis** [comment]
I bumped it to the coming sprint.
