### ISSUE TITLE
Error! Could not generate a preview of this file

### ISSUE THREAD

**Issue by Farbauti** [owncloud/gallery#791]
## Bug report
The viewing of images as well as thumbnail creation does not work after upgrade OwnCloud from 10.0.8.5 to 10.0.9.

### Steps to reproduce
When clicking on an image I get:
![grafik](https://user-images.githubusercontent.com/31306453/44626478-5e894400-a91d-11e8-9d94-7f5e00e86017.png)

While the images are actually there:
![grafik](https://user-images.githubusercontent.com/31306453/44626499-b9bb3680-a91d-11e8-9a32-0f4e3115817d.png)

And the thumbnails in folderview are stuck on the loading circles.
![grafik](https://user-images.githubusercontent.com/31306453/44626508-ed965c00-a91d-11e8-9ae7-da655a19f439.png)

I also uninstalled and redeployed Gallery app, but to no avail.

### Expected behaviour
Gallery should work as expected.

### Actual behaviour
Images cannot be watched in large.
There are no folder tumbnails available.

### Server configuration
**Gallery version**
gallery-16.0.2

**Operating system**:
Linux

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
7.0

**cloud server:**
ownCloud

**cloud version:**
10.0.9.5

**Updated from an older installation or fresh install:**
updated from 10.0.8.5

**List of activated apps:**
no other custom apps
 
**The content of config/config.php:**
<?php
$CONFIG = array (
  'instanceid' => 'ocln0j11zf8h',
  'passwordsalt' => 'TG8wUAzlEwQjYQhQ8VbxyrDnkAKuNC',
  'secret' => 'EtzrQCi06PmM3HqoE1HO8NoDcAe8EOC082rNuAMqfZ38wjm2',
  'trusted_domains' => 
  array (
    0 => 'docs.herzog-wege.de',
  ),
  'datadirectory' => '/www/htdocs/**************/data',
  'overwrite.cli.url' => 'http://docs.herzog-wege.de',
  'dbtype' => 'mysql',
  'version' => '10.0.9.5',
  'dbname' => '****************',
  'dbhost' => 'localhost',
  'dbtableprefix' => '************',
  'mysql.utf8mb4' => false,
  'dbuser' => '******************',
  'dbpassword' => '*********************',
  'logtimezone' => 'Europe/Berlin',
  'installed' => true,
  'tempdirectory' => '/www/htdocs************/tmp/',
  'integrity.check.disabled' => true,
  'mail_domain' => 'herzog-wege.de',
  'mail_smtpmode' => 'php',
  'mail_from_address' => 'docs',
  'updater.secret' => '**********',
  'loglevel' => 2,
  'maintenance' => false,
  'theme' => '',
);

**Are you using custom gallery.cnf config files:**
no

#### Web server error log
n.a.

#### Cloud log
<details>
{"reqId":"W4JyiFUNhFkAAAgoV8wAAAAI","level":3,"time":"2018-08-26T11:27:36+02:00","remoteAddr":"********","user":"********","app":"index","method":"GET","url":"\/index.php\/apps\/gallery\/thumbnails?ids=548%3B1002%3B1003%3B1004%3B1000&scale=1&square=1&requesttoken=JRhQQDcnU08zLg4VHw5VCG0sHDQHNGJleWsCTQgRFyY%3D%3Asl6xuLg8xhvPvVeK5vefOc%2B08XI8xeaRoKKoQYt2ZIE%3D","message":"Exception: {\"Exception\":\"TypeError\",\"Message\":\"Argument 3 passed to OC\\\\Preview::__construct() must implement interface OCP\\\\Files\\\\Node, string given, called in \\\/www\\\/htdocs\\\/v137501\\\/oc\\\/apps\\\/gallery\\\/preview\\\/preview.php on line 100\",\"Code\":0,\"Trace\":\"#0 \\\/www\\\/htdocs\\\/v137501\\\/oc\\\/apps\\\/gallery\\\/preview\\\/preview.php(100): OC\\\\Preview->__construct('********', 'files', 'allg. Vereins-I...')\\n#1 \\\/www\\\/htdocs\\\/v137501\\\/oc\\\/apps\\\/gallery\\\/service\\\/previewservice.php(107): OCA\\\\Gallery\\\\Preview\\\\Preview->setupView('********', Object(OC\\\\Files\\\\Node\\\\File), 'allg. Vereins-I...')\\n#2 \\\/www\\\/htdocs\\\/v137501\\\/oc\\\/apps\\\/gallery\\\/controller\\\/preview.php(167): OCA\\\\Gallery\\\\Service\\\\PreviewService->createPreview(Object(OC\\\\Files\\\\Node\\\\File), 200, 200, false, true)\\n#3 \\\/www\\\/htdocs\\\/v137501\\\/oc\\\/apps\\\/gallery\\\/controller\\\/preview.php(117): OCA\\\\Gallery\\\\Controller\\\\PreviewController->getPreviewData(Object(OC\\\\Files\\\\Node\\\\File), false, 200, 200, false, true)\\n#4 \\\/www\\\/htdocs\\\/v137501\\\/oc\\\/apps\\\/gallery\\\/controller\\\/preview.php(86): OCA\\\\Gallery\\\\Controller\\\\PreviewController->getData(548, 200, 200, false, false, true)\\n#5 \\\/www\\\/htdocs\\\/v137501\\\/oc\\\/apps\\\/gallery\\\/controller\\\/previewcontroller.php(103): OCA\\\\Gallery\\\\Controller\\\\PreviewController->getThumbnail(548, true, '1')\\n#6 [internal function]: OCA\\\\Gallery\\\\Controller\\\\PreviewController->getThumbnails('548;1002;1003;1...', true, '1')\\n#7 \\\/www\\\/htdocs\\\/v137501\\\/oc\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(159): call_user_func_array(Array, Array)\\n#8 \\\/www\\\/htdocs\\\/v137501\\\/oc\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(89): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OCA\\\\Gallery\\\\Controller\\\\PreviewController), 'getThumbnails')\\n#9 \\\/www\\\/htdocs\\\/v137501\\\/oc\\\/lib\\\/private\\\/AppFramework\\\/App.php(103): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\Gallery\\\\Controller\\\\PreviewController), 'getThumbnails')\\n#10 \\\/www\\\/htdocs\\\/v137501\\\/oc\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(46): OC\\\\AppFramework\\\\App::main('PreviewControll...', 'getThumbnails', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#11 [internal function]: OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke(Array)\\n#12 \\\/www\\\/htdocs\\\/v137501\\\/oc\\\/lib\\\/private\\\/Route\\\/Router.php(342): call_user_func(Object(OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler), Array)\\n#13 \\\/www\\\/htdocs\\\/v137501\\\/oc\\\/lib\\\/base.php(919): OC\\\\Route\\\\Router->match('\\\/apps\\\/gallery\\\/t...')\\n#14 \\\/www\\\/htdocs\\\/v137501\\\/oc\\\/index.php(55): OC::handleRequest()\\n#15 {main}\",\"File\":\"\\\/www\\\/htdocs\\\/v137501\\\/oc\\\/lib\\\/private\\\/Preview.php\",\"Line\":112}"}
{"reqId":"W4J14lUNhFkAACkEMUYAAAAH","level":3,"time":"2018-08-26T11:41:54+02:00","remoteAddr":"********","user":"********","app":"index","method":"GET","url":"\/index.php\/apps\/gallery\/thumbnails?ids=1002%3B1003%3B1004%3B1000%3B1001%3B3547&scale=1&square=0&requesttoken=ZQAUT3MeBh4tEx4KOm9ydRNiKmcQAXlmBQYOWjhAPQQ%3D%3A3trw1u2ifUfOS7B6K8S5XV03D5E%2FH4KpOLopv%2BEzZ5I%3D","message":"Exception: {\"Exception\":\"TypeError\",\"Message\":\"Argument 3 passed to OC\\\\Preview::__construct() must implement interface OCP\\\\Files\\\\Node, string given, called in \\\/www\\\/htdocs\\\/v137501\\\/oc\\\/apps\\\/gallery\\\/preview\\\/preview.php on line 100\",\"Code\":0,\"Trace\":\"#0 \\\/www\\\/htdocs\\\/v137501\\\/oc\\\/apps\\\/gallery\\\/preview\\\/preview.php(100): OC\\\\Preview->__construct('********', 'files', 'Vorstands-Inter...')\\n#1 \\\/www\\\/htdocs\\\/v137501\\\/oc\\\/apps\\\/gallery\\\/service\\\/previewservice.php(107): OCA\\\\Gallery\\\\Preview\\\\Preview->setupView('********', Object(OC\\\\Files\\\\Node\\\\File), 'Vorstands-Inter...')\\n#2 \\\/www\\\/htdocs\\\/v137501\\\/oc\\\/apps\\\/gallery\\\/controller\\\/preview.php(167): OCA\\\\Gallery\\\\Service\\\\PreviewService->createPreview(Object(OC\\\\Files\\\\Node\\\\File), 400, 200, true, true)\\n#3 \\\/www\\\/htdocs\\\/v137501\\\/oc\\\/apps\\\/gallery\\\/controller\\\/preview.php(117): OCA\\\\Gallery\\\\Controller\\\\PreviewController->getPreviewData(Object(OC\\\\Files\\\\Node\\\\File), false, 400, 200, true, true)\\n#4 \\\/www\\\/htdocs\\\/v137501\\\/oc\\\/apps\\\/gallery\\\/controller\\\/preview.php(86): OCA\\\\Gallery\\\\Controller\\\\PreviewController->getData(1002, 400, 200, true, false, true)\\n#5 \\\/www\\\/htdocs\\\/v137501\\\/oc\\\/apps\\\/gallery\\\/controller\\\/previewcontroller.php(103): OCA\\\\Gallery\\\\Controller\\\\PreviewController->getThumbnail(1002, false, '1')\\n#6 [internal function]: OCA\\\\Gallery\\\\Controller\\\\PreviewController->getThumbnails('1002;1003;1004;...', false, '1')\\n#7 \\\/www\\\/htdocs\\\/v137501\\\/oc\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(159): call_user_func_array(Array, Array)\\n#8 \\\/www\\\/htdocs\\\/v137501\\\/oc\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(89): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OCA\\\\Gallery\\\\Controller\\\\PreviewController), 'getThumbnails')\\n#9 \\\/www\\\/htdocs\\\/v137501\\\/oc\\\/lib\\\/private\\\/AppFramework\\\/App.php(103): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\Gallery\\\\Controller\\\\PreviewController), 'getThumbnails')\\n#10 \\\/www\\\/htdocs\\\/v137501\\\/oc\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(46): OC\\\\AppFramework\\\\App::main('PreviewControll...', 'getThumbnails', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#11 [internal function]: OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke(Array)\\n#12 \\\/www\\\/htdocs\\\/v137501\\\/oc\\\/lib\\\/private\\\/Route\\\/Router.php(342): call_user_func(Object(OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler), Array)\\n#13 \\\/www\\\/htdocs\\\/v137501\\\/oc\\\/lib\\\/base.php(919): OC\\\\Route\\\\Router->match('\\\/apps\\\/gallery\\\/t...')\\n#14 \\\/www\\\/htdocs\\\/v137501\\\/oc\\\/index.php(55): OC::handleRequest()\\n#15 {main}\",\"File\":\"\\\/www\\\/htdocs\\\/v137501\\\/oc\\\/lib\\\/private\\\/Preview.php\",\"Line\":112}"}
{"reqId":"W4J161UNhFkAADPtTYMAAAAC","level":3,"time":"2018-08-26T11:42:03+02:00","remoteAddr":"********","user":"********","app":"index","method":"GET","url":"\/index.php\/apps\/gallery\/preview\/1002?width=2600&height=2600&c=d9847941239c296fd1176b30a814c2db&requesttoken=BjpSUAYzbA4JICpuBTBhdxdpHiYiZz85eGY%2BDDMWOEQ%3D%3APN4hDXXyBfR%2BlhQ4O3gtj0vl9UuyCbN0EYLsa2FnVoY%3D","message":"Exception: {\"Exception\":\"TypeError\",\"Message\":\"Argument 3 passed to OC\\\\Preview::__construct() must implement interface OCP\\\\Files\\\\Node, string given, called in \\\/www\\\/htdocs\\\/v137501\\\/oc\\\/apps\\\/gallery\\\/preview\\\/preview.php on line 100\",\"Code\":0,\"Trace\":\"#0 \\\/www\\\/htdocs\\\/v137501\\\/oc\\\/apps\\\/gallery\\\/preview\\\/preview.php(100): OC\\\\Preview->__construct('********', 'files', 'Vorstands-Inter...')\\n#1 \\\/www\\\/htdocs\\\/v137501\\\/oc\\\/apps\\\/gallery\\\/service\\\/previewservice.php(107): OCA\\\\Gallery\\\\Preview\\\\Preview->setupView('********', Object(OC\\\\Files\\\\Node\\\\File), 'Vorstands-Inter...')\\n#2 \\\/www\\\/htdocs\\\/v137501\\\/oc\\\/apps\\\/gallery\\\/controller\\\/preview.php(167): OCA\\\\Gallery\\\\Service\\\\PreviewService->createPreview(Object(OC\\\\Files\\\\Node\\\\File), 2600, 2600, true, false)\\n#3 \\\/www\\\/htdocs\\\/v137501\\\/oc\\\/apps\\\/gallery\\\/controller\\\/preview.php(117): OCA\\\\Gallery\\\\Controller\\\\PreviewController->getPreviewData(Object(OC\\\\Files\\\\Node\\\\File), true, 2600, 2600, true, false)\\n#4 \\\/www\\\/htdocs\\\/v137501\\\/oc\\\/apps\\\/gallery\\\/controller\\\/previewcontroller.php(128): OCA\\\\Gallery\\\\Controller\\\\PreviewController->getData(1002, 2600, 2600)\\n#5 [internal function]: OCA\\\\Gallery\\\\Controller\\\\PreviewController->getPreview(1002, 2600, 2600)\\n#6 \\\/www\\\/htdocs\\\/v137501\\\/oc\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(159): call_user_func_array(Array, Array)\\n#7 \\\/www\\\/htdocs\\\/v137501\\\/oc\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(89): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OCA\\\\Gallery\\\\Controller\\\\PreviewController), 'getPreview')\\n#8 \\\/www\\\/htdocs\\\/v137501\\\/oc\\\/lib\\\/private\\\/AppFramework\\\/App.php(103): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\Gallery\\\\Controller\\\\PreviewController), 'getPreview')\\n#9 \\\/www\\\/htdocs\\\/v137501\\\/oc\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(46): OC\\\\AppFramework\\\\App::main('PreviewControll...', 'getPreview', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#10 [internal function]: OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke(Array)\\n#11 \\\/www\\\/htdocs\\\/v137501\\\/oc\\\/lib\\\/private\\\/Route\\\/Router.php(342): call_user_func(Object(OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler), Array)\\n#12 \\\/www\\\/htdocs\\\/v137501\\\/oc\\\/lib\\\/base.php(919): OC\\\\Route\\\\Router->match('\\\/apps\\\/gallery\\\/p...')\\n#13 \\\/www\\\/htdocs\\\/v137501\\\/oc\\\/index.php(55): OC::handleRequest()\\n#14 {main}\",\"File\":\"\\\/www\\\/htdocs\\\/v137501\\\/oc\\\/lib\\\/private\\\/Preview.php\",\"Line\":112}"}
</details>

### Client configuration

**Browser:**
Firefox

**Operating system:**
Win10

**Comment by Farbauti** [comment]
Am I the only one with this problem?

**Comment by PVince81** [comment]
@Farbauti please update the gallery app. I have gallery 16.1.0 and thumbnails work fine
