### ISSUE TITLE
Unable to update from 16.1.0 to 16.1.1

### ISSUE THREAD

**Issue by wolkenschieber** [owncloud/gallery#817]
## Bug report

I'm unable to update the Gallery App from 16.1.0 to 16.1.1. The process fails due to failed code check.

### Steps to reproduce

1. Open Market App
1. Install Gallery Update

### Code-Check

Verifying the app using `occ` produces following output:
```
$ ./occ app:check-code gallery
ownCloud is in maintenance mode - no app have been loaded

Analysing /var/www/owncloud/apps/gallery/middleware/envcheckmiddleware.php
 1 errors
    line  155: OC_User - Static method of private class must not be called
App is not compliant
```

**Comment by DeepDiver1975** [comment]
Please disable the code-checker in config.php - THX

**Comment by wolkenschieber** [comment]
Disabling the code checker allowed me to update the app. Thanks!
