### ISSUE TITLE
Display image title/description/metadata

### ISSUE THREAD

**Issue by simon04** [owncloud/gallery#83]
It would be great if the gallery app displayed image metadata. Most interesting would be title/description/author which would be obtained from XMP files stored in the same directory. Furthermore, image taking conditions from EXIF could be displayed. This idea/request is based on the display of images on Flickr …

This could be implemented as a separate API call `metadata.php` which given an image path returns the XMP/IPTC/EXIF metadata.

**Comment by oparoz** [comment]
Moved here: https://github.com/owncloud/galleryplus/issues/101
