### ISSUE TITLE
[QA] 16.1.2 Testplan

### ISSUE THREAD

**Issue by jnweiger** [owncloud/gallery#847]
404: Not Found
## 'Gallery' Test Plan

TBD: Nothing useful found in https://github.com/owncloud/QA/tree/master/Server
TBD: Here is a dummy testplan template. Please edit!
TBD: Please also doublecheck https://github.com/owncloud/qa-enterprise/tree/master/Core

## Setup
<details><summary>Setup details (click to view)</summary>

  `oc_release.sh app:get gallery`
</details>

## Testing functionality

Test Case | Expected Result | Result | Related Comment
------------- | -------------- | ----- | ------
Improve testplan | More tests | :construction: | TBD

----

**Comment by jnweiger** [comment]
## Changelog Testing
* [ ] Fix: Show proper name in file menu https://github.com/owncloud/gallery/pull/836
* [ ] Fix: Don't return files when accessing a share files drop https://github.com/owncloud/gallery/pull/839
* [ ] Fix: Unbreak gallery with gallery.cnf https://github.com/owncloud/gallery/pull/840
* [ ] Fix: Align password public protected link, with new Login-UI https://github.com/owncloud/gallery/pull/846

**Comment by jnweiger** [comment]
No regression testing. 
Smoke testing with folders of a few hundred images....
Exercise gallery featues from its menues...

**Comment by cdamken** [comment]
I think this could be closed

@GeraldLeiklam @jnweiger
