### ISSUE TITLE
Check that gallery is working OK after Guzzle7 core update for core 10.11

### ISSUE THREAD

**Issue by phil-davis** [owncloud/gallery#859]
Check the gallery app with core 10.10 and make sure that any existing problems have issues.

Try again with current core master (to be 10.11 release), and raise issues for any new problems.

Related to issue https://github.com/owncloud/core/issues/39387

**Comment by phil-davis** [comment]
@kiranadh1452 I just merged PR #860 - please pull the latest master of gallery and then do a quick check that it looks OK.

**Comment by kiranadh1452** [comment]
## V10.10:
## Local Folder's gallery view
- Gallery View: works
- Sort by Name: works
- Sort by date: works
- Deletion from gallery: works
- Next Image Button: works
- Previous Image Button: works
- Change Orientation Button: works but does not actually change the orientation
- Download Button: works
- Close Button: works
- Slide Show: works
  
## Shared Folder’s gallery view (Shared by someone else to me)
> Shared Folder does not appear in gallery view. Messgae displayed: `Album cannot be shown` - The owner has placed a restriction or the storage location is unavailable (403)
> However, the images inside the shared folder can be opened inside the gallery manually. (Click on `...` and select open with gallery)

- Gallery View: works
- Sort by Name: works
- Sort by date: works
- Deletion from gallery: works
- Next Image Button: works
- Previous Image Button: works
- Change Orientation Button: works but does not actually change the orientation
- Download Button: not displayed (by default, delete permission is not given to the shared folder)
- Close Button: works
- Slide Show: works

### Issue: Can not set every permission from gallery view

## V10.11
## Local Folder's gallery view
- Gallery View: works
- Sort by Name: works
- Sort by date: works
- Deletion from gallery: works 
- Next Image Button: works
- Previous Image Button: works
- Change Orientation Button: works but does not actually change the orientation
- Download Button: works
- Close Button: works
- Slide Show: works

## Shared Folder’s gallery view (Shared by someone else to me)
> Shared Folder does not appear in gallery view. Messgae displayed: `Album cannot be shown` - The owner has placed a restriction or the storage location is unavailable (403)
> However, the images inside the shared folder can be opened inside the gallery manually. (Click on `...` and select open with gallery)

- Gallery View: works
- Sort by Name: works
- Sort by date: works
- Deletion from gallery: works
- Next Image Button: works
- Previous Image Button: works
- Change Orientation Button: works but does not actually change the orientation
- Download Button: not displayed (by default, delete permission is not given to the shared folder)
- Close Button: works
- Slide Show: works

**Comment by kiranadh1452** [comment]
Looks like no new issue in 10.11.
Most of the existing issues were reported already.

**Comment by phil-davis** [comment]
works as good as before - closing
