### ISSUE TITLE
Gallery+ not working with IE11

### ISSUE THREAD

**Issue by deMattin** [owncloud/gallery#87]
I tested gallery+ 2.0.5 with some browsers:
Working with:
- Firefox 36.0.1
- Chrome 41.0

Not working:
- IE 11.0.17

Wheel keeps spinning - no matter if you start in mainfolder or subfolder
I see no errors in IE console but the weird thing:
The iframe with the preview call is shown in DOM Explorer but it isn't shown in browser page - it stays on "spinning wheel". A css incompatibility with IE11?
For me it seems, that the IE11 is ready with loading but always refreshes and shows "wheel screen"
And there's also a message:

> DOM7011: Der Code auf dieser Seite hat die Zwischenspeicherung für das Vor- und Zurücknavigieren deaktiviert. Weitere Informationen dazu finden Sie unter: http://go.microsoft.com/fwlink/?LinkID=291337
> (Code on this page has deactivated caching for navigating forwards and backwards...)

**Edit:**
Sorry, dub of #21 

**Edit 2:**

If you switch to Gallery+ in a folder without pics, the message "no picture" is shown.
So I think, it's possibly the code to **show** the previews that causes the problem.

**Comment by oparoz** [comment]
Let's continue on #21
