### ISSUE TITLE
Show spinner while loading an album

### ISSUE THREAD

**Issue by spamverdacht** [owncloud/gallery#90]
It would be great, if a spinner would be displayed while loading of the album is not finished. On my slow system it takes 30s for each row of pictures/subalbums.

**Comment by oparoz** [comment]
The first step would be to show albums and images as they're rendered. Currently, a row is only made visible once it's full.

**Comment by oparoz** [comment]
Moved to https://github.com/owncloud/galleryplus/issues/130
