### ISSUE TITLE
Warn users of Internet Explorer 

### ISSUE THREAD

**Issue by oparoz** [owncloud/gallery#92]
The only versions of Internet Explorer we may be able to support are 11+ and even that is a nightmare.

We need to let users know though, instead of just showing them a broken app and we can recommend they upgrade their browser.

**Comment by deMattin** [comment]
Do you think, this message is needed in IE11 with gallery+ 2.0.7?
With 2.0.7 there seems to be no restrictions that require to show this message.

**Edit:**
Ok, I see, big galleries still have a problem with gallery+ ...
So the message should remain.

**Comment by oparoz** [comment]
I'm not sure the problem big galleries are having are IE11 related. Do you have a link to that info?

**Comment by deMattin** [comment]
Not a link, but I testet it with my same big account, that didn't work but smaller test account works. 
In Firefox and Chrome both are ok. 
I'm on the road and not able to check and confirm before friday.
