### ISSUE TITLE
Share single picture(s) instead of whole folder

### ISSUE THREAD

**Issue by Siedlerchr** [owncloud/gallery#93]
Hi,

it would be nice to share single picture(s) in the gallery, that would be consistent to the file sharing.
Currently it's only possible to share a whole folder with images in the gallery app.

If I only want to share a single pic, I have to go the files app and share it then.
So it would be nice to have the option to share all pics, a single pic or a selection of pics.

Regards
siedlerchr

**Comment by oparoz** [comment]
It's being considered: https://github.com/owncloud/galleryplus/issues/68
