### ISSUE TITLE
Sorting pictures on metadata i.e "date taken" 

### ISSUE THREAD

**Issue by FredrikLindseth** [owncloud/gallery#94]
A way to sort pictures after fields like "date taken" would be a very nice feature :-)

**Comment by seuf** [comment]
+1 on sorting by name, in desc order ! i want to see newer pictures first !

**Comment by Riechao** [comment]
Name descending is very easily fixed, reverse the comparator in the gallery.js:
change
return a.path.toLowerCase().localeCompare(b.path.toLowerCase());
to
return b.path.toLowerCase().localeCompare(a.path.toLowerCase());

**Comment by oparoz** [comment]
You can keep the conversation going here: https://github.com/owncloud/galleryplus/issues/221
