### ISSUE TITLE
Make gallery app more tablet friendly

### ISSUE THREAD

**Issue by Aesculapius** [owncloud/gallery#95]
There are a few things that are annoying while viewing a gallery on a tablet;

- one cannot swipe the photo to go to the next one
- one cannot pinch-zoom to zoom-in on the photo and see details
- the pre-loading of images as of OC7 is nice, but appears to be initiated only when reaching the end of the page. When fast scrolling down on a tablet, you've reached that point quickly...and then have to wait for the next ones to load. Better prefetching could solve this.

**Comment by oparoz** [comment]
Most of these requests are now tracked in https://github.com/owncloud/galleryplus/issues
