### ISSUE TITLE
Don't jump to start after closing image

### ISSUE THREAD

**Issue by Aesculapius** [owncloud/gallery#96]
When you've scrolled down in the gallery (with or without loading a new set of images), and you click an image to look at it, it opens with an overlay-like window which looks nice. In the background, you see the place to where you've scrolled.

But when you close the image with the X, the gallery jumps back to the top of the page. This is annoying, since with large collections, you got to scroll back again all the way down - including fetching all the new batches... This makes working with the gallery annoying. It should just keep its current position and close the overlay...

**Comment by oparoz** [comment]
This doesn't seem to be happening on oC8, correct?

**Comment by SailorOrion** [comment]
After upgrading to OC8, this issue is no longer present

**Comment by oparoz** [comment]
Still happening on public galleries- Re-opening.
