### ISSUE TITLE
Gallery+ 2.0.7 requires ownCloud 8.0.2

### ISSUE THREAD

**Issue by deMattin** [owncloud/gallery#98]
I made a git pull and got gallery+ in Version 2.0.7.
As it requires OC 8.0.2 it doesn't work with actual suse owncloud repository which is still at 8.0.1.
(As allways readme is read afterwards...)

Could you please provide the last 2.0.6 as a separate branch?
For now I switched to the performance branch which doesn't depend on 8.0.2.

**Comment by oparoz** [comment]
It's true that I didn't think about distributions which may be slow to update... but there are important changes in 8.0.2, so I'll stick with the version number.
You can change the version number yourself, but then results may be unpredictable. 2.0.6 already requires 8.0.2 and in the coming days, so will the performance-fixes branch.
TBH, oC won't be reliable before 8.0.3 at least.

**Comment by deMattin** [comment]
I don't know, why this time it takes so long with the suse repo.
Before this the repo mostly was even faster than the official announcements.
The problem will solve itself as time goes by ... ;)

**Comment by deMattin** [comment]
I changed the recommended min version in info.xml to 8.0.1 (actual suse repo) and everything seems to work.
Maybe something is faster with 8.0.2 but 8.0.1 is at least working without any obvious errors.
~~And IE11 is working without any errors, too!~~

Which dependencies do require 8.0.2? I see no issue.

**Comment by oparoz** [comment]
Less broken things and on top of that some people were on the illegal 8.0.1 ;)
