### ISSUE TITLE
Make picture galleries embeddable

### ISSUE THREAD

**Issue by FredrikLindseth** [owncloud/gallery#98]
It would be nice to have the an easy way to embed picture galleries on my own webpages. Not sure if this is possible now via some php-magic or not.

**Comment by oparoz** [comment]
It's possible using Gallery and the ShareLinks app
https://apps.owncloud.com/content/show.php/ShareLinks?content=170527

**Comment by oparoz** [comment]
Actually, Share Links will only share a single pic. Will create a new request in the new repository.

**Comment by oparoz** [comment]
Request has been created here: https://github.com/owncloud/galleryplus/issues/235
