### ISSUE TITLE
No big preview with slideshow

### ISSUE THREAD

**Issue by kolumbus120** [owncloud/gallery#99]
When I click on the picture it turn in to grey but no big preview with slideshow.
browser Chrome 41.0.2272.89 m
error in browser console 
https://x.x.x.x/apps/galleryplus/js/vendor/bigshot/bigshot.js?v=e643dc64dfce69129aef074e95e9c179 Failed to load resource: the server responded with a status of 403 (OK)
slideshow.js?v=e643dc64dfce69129aef074e95e9c179:84 Uncaught ReferenceError: bigshot is not defined

browser firefox 36.0.1
ReferenceError: bigshot is not defined
var browser = new bigshot.Browser();

**Comment by oparoz** [comment]
Thanks for the report.
The problem seems to come from your server which seems to be refusing to serve the bigshot script for some reason.
Maybe some file permission errors? Or a misbehaving proxy?

See this for more information: https://en.wikipedia.org/wiki/HTTP_403

**Comment by kolumbus120** [comment]
Thnak you very much. it`s funny. I did not do anything with permission. Now just run scritp to setup strong secure permison for owncloud, restart nginx and its work.
